### ISSUE TITLE
Crash with trash can

### ISSUE THREAD

**Issue by KellyLynch** [AllTheMods/ATM-8#1]
Three in a row I've had a crash when clicking on trash can ..  crash logs for both attached.  once had an rfbuilder clearing quarry running, 2nd & 3rd time i stopped the quarry before trying the trash can.  this is for the Trash Can adjacent to the ftbchunk map icon in inventory screen.

[crash-2022-08-16_19.33.05-client.txt](https://github.com/AllTheMods/ATM-8/files/9355653/crash-2022-08-16_19.33.05-client.txt)
[crash-2022-08-16_19.36.48-client.txt](https://github.com/AllTheMods/ATM-8/files/9355654/crash-2022-08-16_19.36.48-client.txt)
[crash-2022-08-16_19.42.57-client.txt](https://github.com/AllTheMods/ATM-8/files/9355673/crash-2022-08-16_19.42.57-client.txt)
.

**Comment by whatthedrunk** [comment]
Thanks this is fixed on our new builds.
