### ISSUE TITLE
Bugs : Corail Tombstone & Inventory

### ISSUE THREAD

**Issue by Skolteix** [AllTheMods/ATM-8#10]
Hi,

1/ The chat shortcut of Corail Tombstone don't work

![2022-09-03_19 02 28](https://user-images.githubusercontent.com/112773598/188281154-dfdd22f2-6613-4f05-af36-c79c8c86eabb.png)

2/ The stuff on the floor don't go on hotbar

https://youtu.be/zc5nKd6_qHs

**Comment by Mitchell5200** [comment]
1/ according to the tombstone mod page, that command might not exist anymore, https://www.curseforge.com/minecraft/mc-mods/corail-tombstone

2/ that's a setting in `Inventory Profiles Next`, called Pickup to inventory, press R+C to open the config in game and find the locked slots heading.

**Comment by Skolteix** [comment]
> Yes, but when we run the command with access to the commands it works
I didn't know for that, thanks :)
