### ISSUE TITLE
Compact Machines Crash Server

### ISSUE THREAD

**Issue by DougWz** [AllTheMods/ATM-8#1000]
when I right click on the compact machine with the shrink I enter the dimension of the compact machine but I stay in void for a while, the server kika crashes all players and restarts, staying a while with ghost "players" logged in, it appears that there are players online but there is no one and the server restarts, atm8 version 1.0.13, forge version 43.2.6

**Comment by AlexHailstone** [comment]
I'm getting this as well.

I'm running a hosted server (albeit hosted for myself only), and running decent specs on the server, but as soon as I click on the compact machines, the server loads me into the abyss (no inventory loaded yet and mana bar showing with no reason for it yet); I end up just falling forever until the server restarts and kicks me out.

Here's a quick video of what I'm seeing: https://youtu.be/b_joVt4mmsU
