### ISSUE TITLE
Crash when using Pipez

### ISSUE THREAD

**Issue by Cewball** [AllTheMods/ATM-8#1006]
I was using Pipez item pipe to input Fe (Iron) and Al (aluminum) from alchemistry into a fusion reactor. Upon relaunching the world, I received another crash report. 
[crash-2023-03-03_23.11.55-server.txt](https://github.com/AllTheMods/ATM-8/files/10887458/crash-2023-03-03_23.11.55-server.txt)
[crash-2023-03-03_23.18.26-server.txt](https://github.com/AllTheMods/ATM-8/files/10887460/crash-2023-03-03_23.18.26-server.txt)

**Comment by Mitchell5200** [comment]
Related to https://github.com/SmashingMods/Alchemistry/issues/291

**Comment by Dark-Arcana** [comment]
This should have been resolved in a previous update. Just going through old issues now. Can someone confirm if this has been fixed?
