### ISSUE TITLE
ATM8 (1.0.13) Crashes when I join world

### ISSUE THREAD

**Issue by jzells09** [AllTheMods/ATM-8#1012]
I recently updated my pack from 1.0.11 to 1.0.13 and my world crashes when I join it. Does anyone have a fix?

https://gist.github.com/jzells09/5d947b1d7a62020763803669941228a2

**Comment by tunse80** [comment]
This looks like the same issue I had. I'm not skilled enough to tell if it's the same issue but our error logs look very similar. I made a post about it here too.

**Comment by Mitchell5200** [comment]
okay, that's the particle render crash others have reported before, i have a list of fixes that are reported by others to work
```
1, Update GPU drivers
2, disable particles
3, enable shaders (some on github report this as a fix)
