### ISSUE TITLE
Quarry Plus or Chunk destroyer dont work in nether mining dimension 

### ISSUE THREAD

**Issue by Blackspack** [AllTheMods/ATM-8#1016]
I tried to use them and it build his cage but after its done nothing happens anymore (Chunk destroyer), 
on Quarry Plus after he build his cage the arm will move but nothing happen to the blocks.

**Comment by Mitchell5200** [comment]
"nether mining dimension"??, Do you mean the other, if so, that's by design in the allthemodium mod, it's a feature not a bug

**Comment by Blackspack** [comment]
ok that mean i cant mine with Quarry in other ? this is quite useless.
