### ISSUE TITLE
Comb Quests are broken.

### ISSUE THREAD

**Issue by yariplus** [AllTheMods/ATM-8#1018]
You can't complete any of the ATM comb quests.

Maybe related
https://github.com/AllTheMods/ATM-7/issues/1336

**Comment by alfredggttv** [comment]
Tested this and could not replicate it. Could you share your quest progress in a screenshot?

**Comment by yariplus** [comment]
Looks like it was fixed in the 1.0.12 update, I couldn't find the exact commit, but it's working now! Thanks.
