### ISSUE TITLE
[1.0.13] crashing and high memory usage

### ISSUE THREAD

**Issue by tunse80** [AllTheMods/ATM-8#1019]
Just started a new world but after a few minutes the game started using all of the ram and then crashed.
I have not done much and I haven't built anything. I have previously played some earlier versions for many hours and even though that save also broke, it lasted longer than this (i.e., 5-10 minutes). I've attached the crashlog here. Thank you in advance.

[hs_err_pid6596.log](https://github.com/AllTheMods/ATM-8/files/10897265/hs_err_pid6596.log)

**Comment by Mitchell5200** [comment]
okay, that's the particle render crash others have reported before, i have a list of fixes that are reported by others to work
```
1, Update GPU drivers
2, disable particles
3, enable shaders (some on github report this as a fix)

**Comment by tunse80** [comment]
Hey, thanks for the reply, much appreciated. :) My drivers were up to date but I tried the other solutions and setting particles to minimal solved it for me. Thanks!
