### ISSUE TITLE
ATM8 crashes each time I enter nether

### ISSUE THREAD

**Issue by Cyanicus** [AllTheMods/ATM-8#1021]
So basically the game freezes then returns to the launcher

"OpenJDK Platform binary is not responding" is displayed when I close the game from the icon on the bar at the bottom of the screen

From the launcher: " Exit Code: -805306369"

**Comment by Mitchell5200** [comment]
Crashlogs, a seed, and the cordinates of your nether portal please

**Comment by Cyanicus** [comment]
How do I find the first two?

**Comment by Mitchell5200** [comment]
the crash reports folder, and then the command /seed

**Comment by Cyanicus** [comment]
seed: 3983874626132317607
cordinates: x-18 y 119 z 6

do I find the crash reports folder by pressing windows + R then typing %appdata%\.minecraft\ ?

**Comment by Mitchell5200** [comment]
right click on the pack in the curseforge app, and click "Open folder"

**Comment by Cyanicus** [comment]
is it called "crashlogs"? cant seem to find it?

**Comment by tunse80** [comment]
For me, they're in the folder "install path" ... \Instances\All the Mods 8 - ATM8 and called hs_err_pid followed by a number.

**Comment by Cyanicus** [comment]
OK. It seems to have resolved itself. The portal spawned right next to a magma cube spawner.
