### ISSUE TITLE
join my friend server and keeps crashing

### ISSUE THREAD

**Issue by Garbagewonder** [AllTheMods/ATM-8#1025]
i do everything right and i don't get in

[hs_err_pid48028.log](https://github.com/AllTheMods/ATM-8/files/10905286/hs_err_pid48028.log)

**Comment by Natomik** [comment]
I think either you don't have enough RAM or your firewall is blocking the connection. I had quite the same error and I jumped in solo mode, create a new world (if it's lagging already try adding more RAM), open LAN and here you will have a message from your firewall accept private and public and normally it should be ok.

**Comment by Garbagewonder** [comment]
so i put 10g of RAM and 15g of RAM and check my firewall, everything is running smoothly on single player so i go and join my friends server and still i just crash, so whats going on. what do i do.

**Comment by Natomik** [comment]
Close all the other programs, try to update java and your graphic card

**Comment by Garbagewonder** [comment]
tried it all and still crashes, and the mod is no longer giving me a crash log, there's crash code or close, the crash log button is gone. also find some stuff, if i turn off all particles and clouds. though i still crash sometimes and still can't get the crash log. i am able to play and do stuff, though it gets boring and i want to use the mod to the fullest but i can't. it really sucks

**Comment by wakkytabbaky** [comment]
if singleplayer is working fine andits only stuffing up when you are joining your friend it could be your friends specs / internet is the problem. have them try to join you and see if it fixes the issue

**Comment by Garbagewonder** [comment]
so i got him to join me and hasn't crash at all, so i trying joining his server again i crash right away. also my brother who live in the same house as me has no problem at all. doesn't crash and can run it to the fullest it can. so i guess i have to play it with everything turned off and have an uneventful time playing this mod. like there is 9 of us playing and i'm the only one who is having this problem, like my pc every new and everything is up to date and i am putting lots of RAM into. like it really sucks.
