### ISSUE TITLE
Refined Storage power consumption 

### ISSUE THREAD

**Issue by ballaman300** [AllTheMods/ATM-8#1026]
If your refined storage network consumes more then 16.000rf/t (often happens if you use a dimension card which takes 8k rf/t on its own) it will crash trough a too high power consumption even with a sufficient power supply. 

This seems to be a problem that also occurs in ATM7 (https://github.com/AllTheMods/ATM-7/issues/1093) where the workaround was to use "creative crafters" which reduce the power consumption drastically , there are currently no creative crafters in atm8 so this workaround doesnt work.

Problem occured in ATM 8 1.0.11

Short Example with screenshots:

Mekanism Creative Energy Cube -> Ultimate Energy Cable (mekanism) -> Controller (so enough energy to power a 16k Network)

Over 16krf/t consumption: 
![2023-03-07_17 16 47](https://user-images.githubusercontent.com/127225066/223483469-e2141de3-c043-440d-bca7-dcccafc3fe65.png)

System down (as you can see the displays and everything is shut off)

Under 16krf/t consumption:
![2023-03-07_17 18 01](https://user-images.githubusercontent.com/127225066/223482972-27440fd3-5737-4976-b40e-6f8017e0a3d1.png)

Edit: Added some screenshots.

**Comment by hokomili** [comment]
Another walkaround is to change the config.
https://github.com/refinedmods/refinedstorage/issues/3350

**Comment by ballaman300** [comment]
@hokomili so probably a good "workaround" would be to change the default config for atm8? or do we just wait until it is fixed from rs?

**Comment by hokomili** [comment]
They(devs from rs) probably won't fix it. Or I should say not at this version, as they are developing refined storage 2.
So changing the config might be the way to go. Or else you can wait until creative crafter to be added in ATM8, which is more likely to happen in the near future.
But if you're as impatient as me, I suggest the former one.
