### ISSUE TITLE
Craftingspeed of ExtraStorage Craftern drastically limited when combined with ATM-Furnaces

### ISSUE THREAD

**Issue by ballaman300** [AllTheMods/ATM-8#1027]
The Craftingspeed of ExtraStorage Crafters (iron crafter, diamond crafter, netherite crafter) is drastically limited when aimed on a ATM-Furnace (allthemodium, vibranium, unobtainium furnace) . The Craftingspeed is always limited to 2x even with speed upgrades.  Compared to the refined Storage Crafter.

This seems to be a bug.

Some screenshots:
Every Crafter has 4 Speed Upgrades.
Refined Storage Crafter:
![grafik](https://user-images.githubusercontent.com/127225066/223478322-c37a6433-df08-40f4-aa2d-c5bab1432f87.png)
Extra Storage Crafters
![grafik](https://user-images.githubusercontent.com/127225066/223478409-b225a644-3d37-40f9-a306-51d1895ff0f5.png)

**Comment by James103** [comment]
The crafter speed is limited by the number of slots in the inventory its pointing to. To allow the crafter to work faster,
1. Point the crafter at a chest or barrel and use pipes to send items from the chest to the machines in use.
2. Convert the furnaces to factories by crafting Factory Upgrades from the Iron Furnaces mod and using them on the furnaces. Make sure to power the furnaces with RF if you are doing this.
