### ISSUE TITLE
Radon mod causes black particles when picking up blocks

### ISSUE THREAD

**Issue by transbiod** [AllTheMods/ATM-8#1028]
As i wrote in the title. Was bothering me quite heavy, because you can also see all the particles around you in black and with higher tiers of pickaxes screen just turnes into black square's festival.

ATM8 1.0.13

**Comment by transbiod** [comment]
Issue was in other mod that i can not locate. Removing Radon helped for one session only

**Comment by typecasto** [comment]
Did you ever figure out what caused this? I'm running into the same issue.
