### ISSUE TITLE
ATM8 crashing on world join

### ISSUE THREAD

**Issue by officerwacky** [AllTheMods/ATM-8#1034]
I have put quite a few hours into this world, and it has not crashed prior to this occasion. Nothing is different as far as I'm aware, the modpack is just crashing upon joining the world in question. Attached below is my crash log.

Update: upon further inspection, loading into, or creating other worlds works fine. It appears to be just the one world.

[hs_err_pid14056.log](https://github.com/AllTheMods/ATM-8/files/10917479/hs_err_pid14056.log)

**Comment by wakkytabbaky** [comment]
cant say for sure but i was getting this issue for awhile, i updated my geforce drivers and then restored the geforce control panels settings to default. after restoring the settings to default i have not got this crash once. might help you fix it as it or might not

**Comment by osirus31** [comment]
I am able to fix this by "re-installing" ATM8 via Curseforge (switch versions to the same version you are already on) and repairing the profile.
