### ISSUE TITLE
Dynamic Handheld Light Visual Conflict 

### ISSUE THREAD

**Issue by FoundryCove** [AllTheMods/ATM-8#1035]
The Dynamic lights mod's handheld lighting is rather jarring compared to the implementation in the shader packs, but there is no config option to disable it when shaders are on. If possible, a toggle option for the mod's lighting would be nice.

**Comment by Mitchell5200** [comment]
the current Dynamic lighting mod we have does not have an option for enabling or disabling that setting

**Comment by ariosos** [comment]
Is there another mod that also adds dynamic lighting? I disabled the dynamiclights-1.19.2.1.jar file, and reloaded from the launcher. Torches still give off dynamic lighting. The thing I don't like about this is that it interferes with the F7 Torch Lighting. I still want to see where the light level is spawnable without having to constantly switch out from holding a torch, or other light block.
