### ISSUE TITLE
My game keeps crashing after playing for a few min up to an hour or two.

### ISSUE THREAD

**Issue by Torv95** [AllTheMods/ATM-8#1036]
I have looked at this github and tried multiple tricks people have posted here but non seem to work. 

Crash log:
[hs_err_pid13320.log](https://github.com/AllTheMods/ATM-8/files/10920612/hs_err_pid13320.log)

**Comment by steellz** [comment]
Having the same problem.
[hs_err_pid32328.log](https://github.com/AllTheMods/ATM-8/files/10949864/hs_err_pid32328.log)

**Comment by steellz** [comment]
Though the process of elimination, i discovered it might be the backpack mod, Not using it stops the crashes.
