### ISSUE TITLE
[ATM8 10.0.13] Server crashing when trying to go to the end dimension

### ISSUE THREAD

**Issue by SebastienNin** [AllTheMods/ATM-8#1037]
Hi :)

I wanted to go to the end on my multiplayer server and it crashes when going into it...

My server console gives me this error message

` [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: A single server tick took 60.17 seconds (should be max 0.05)`

I got a crash-report if it can help.

I'm playing on the 1.0.13 version of the pack.

I already tried the suggestion from [this](https://github.com/AllTheMods/ATM-8/issues/886) issue. But it didn't work.

Does someone already had the problem?

**Comment by TheFlyWhiteGuy** [comment]
Yeah i am having this problem and the same error message and the shitty part is that im stuck in the end and as soon as i load in it crashes the server. Minecraft crash report said allocate more memory and when i did that i got further into the world but still crashes

**Comment by SebastienNin** [comment]
Sad to hear :/ I had to reload a server backup. I also was trapped in the end with constant crash of my server

**Comment by SebastienNin** [comment]
I could resolve the problem by increasing the `max-tick-time`. I set it to `-1`, reset the server, ran the command `/forge generate 0 60 0 100 minecraft:the_end` when nobody was on the server. 

Now I can go into the ender :D
