### ISSUE TITLE
exit code 1

### ISSUE THREAD

**Issue by iiJonno** [AllTheMods/ATM-8#1039]
I keep crashing to desktop with exit code 1 
ive read through other posts with this exit code and none of the answers worked

I have tried
- new world
- reinstall curse + mc
- update drivers + java
- disabled spark, rubidium, oculus
it happens whether raining or sunny

https://mclo.gs/qmTla5e

**Comment by drakray** [comment]
I had a similar crash.
I removed/disabled Oculus, Rubidium, RubidiumExtra, and TextruesRubidium, and it fixed this problem.

**Comment by iiJonno** [comment]
> I had a similar crash. I removed/disabled Oculus, Rubidium, RubidiumExtra, and TextruesRubidium, and it fixed this problem.
> 
> EDIT: didn't see you already tried oculus and rubidium, did you also remove the other two?

yeah disabling rubidium auto disabled the others
