### ISSUE TITLE
Dynamic Light isn't present on Server Files 1.0.13

### ISSUE THREAD

**Issue by Othoiko974** [AllTheMods/ATM-8#1045]
Hi, 
I found out that dynamic light mod isn't present on the server files 1.0.13 provided throw Curseforge. Is it a mistake? ?
Was it already mentioned? I apologize if it's the case.

**Comment by Mitchell5200** [comment]
Nope that's completely intentional, as that mod and a few others are Client only, and are not meant to be installed on a server instance

**Comment by Othoiko974** [comment]
That's not true according to the mod page on : [Curseforge](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights) Since 1.16.5 : "the mod is now a "standard" mod that requires both a client and a server to have it when playing online"
I had to install it on the server to make it work, so ....
