### ISSUE TITLE
Server crash on start - Ubuntu 20.04 - Elytra Slot mod seems to be the problem

### ISSUE THREAD

**Issue by lagraviereScience** [AllTheMods/ATM-8#1046]
I'm trying to make ATM8 "Server-Files-1.0.13" to work on Ubuntu 20.04.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

After unziping the archive I got those files:

```
$ ll
total 72
drwxrwxr-x  7 pipiminer pipiminer  4096 Mar  9 20:41 ./
drwxrwxr-x  3 pipiminer pipiminer  4096 Mar  9 20:38 ../
drwxrwxr-x 18 pipiminer pipiminer  4096 Feb 28 20:04 config/
drwxrwxr-x  2 pipiminer pipiminer  4096 Feb 28 20:04 defaultconfigs/
drwxrwxr-x  8 pipiminer pipiminer  4096 Feb 28 20:04 kubejs/
drwxrwxr-x  2 pipiminer pipiminer 24576 Feb 28 20:09 mods/
drwxrwxr-x  3 pipiminer pipiminer  4096 Feb 28 20:04 packmenu/
-rw-rw-r--  1 pipiminer pipiminer 11005 Aug 19  2022 server-icon.png
-rw-rw-r--  1 pipiminer pipiminer  1906 Feb 28 12:06 startserver.bat
-rwxrwxr-x  1 pipiminer pipiminer  2360 Feb 28 12:07 startserver.sh*
-rw-rw-r--  1 pipiminer pipiminer   786 Sep 22 11:56 user_jvm_args.txt

```
You can notice I made startserver.sh executable

Then I run ./startserver.sh

For info my Java version is this one:

```
$ java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
```

I modified eula.txt to set the value at "true"

----

And when I run startserver.sh or run.sh (once it's been created) I get this error:
```
Crash Report UUID: bda2c31d-13b3-4828-8b87-9493188366eb FML: 43.2 Forge: net.minecraftforge:43.2.6 FramedBlocks BlockEntity Warning: Not applicable[20:48:24] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [ Elytra Slot (elytraslot) has failed to load correctly §7java.lang.reflect.InvocationTargetException: null ] at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[fmlcore-1.19.2-43.2.6.jar%23744!/:?] {} at 
net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$24(ModLoader.java:208) ~[fmlcore-1.19.2-43.2.6.jar%23744!/:?] {} at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin} at 
net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:208) ~[fmlcore-1.19.2-43.2.6.jar%23744!/:?] {} at 
net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:185) ~[fmlcore-1.19.2-43.2.6.jar%23744!/:?] {} at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin} at 
net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[fmlcore-1.19.2-43.2.6.jar%23744!/:?] {} at 
net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.2.6-universal.jar%23748!/:?] {re:classloading} at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:classloading,re:mixin,pl:mixin:A} at 
jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} at 
jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} at 
net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.6.jar%2367!/:?] {} at 
cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {} at 
cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {} at 
cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {} at 
cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

***
I tried removing that elytraslot mod thing.
But that caused even more errors

I also tried to chmod -R 777 theWholeServerDirectory/
Just in case -> it did not change anything -> same error.

***
I also tried to run  `java -jar forge-1.19.2-43.2.6-installer.jar  --installServer` and it apparently worked?
"Worked" as in "it did not crashed and terminated on a successful message"
But it did not solve the issue though.
***

Complete logs there (when I run, run.sh)->
https://mclo.gs/kzYIFtz
***

What to do?
How do you make ATM8 work in that context?

**Comment by lagraviereScience** [comment]
SOLUTION FOUND:

Use Official Oracle Java JDK distribution.
Works 100%.

You might need to edit run.sh if you want to point specifically to the version of Oracle Java you want to use.
Or you'll want to change the symbolic link in /usr/bin or wherever it's located on your distrib' to make it point to the right version of Java.

In other words: DO NOT use openJDK for ATM8 -> use Oracle Java JDK(or any other?)

**Comment by tscheer100** [comment]
> SOLUTION FOUND:
> 
> Use Official Oracle Java JDK distribution. Works 100%.
> 
> You might need to edit run.sh if you want to point specifically to the version of Oracle Java you want to use. Or you'll want to change the symbolic link in /usr/bin or wherever it's located on your distrib' to make it point to the right version of Java.
> 
> In other words: DO NOT use openJDK for ATM8 -> use Oracle Java JDK(or any other?)

where can one find the "official oracle java JDK distribution"?

**Comment by lagraviereScience** [comment]
> > SOLUTION FOUND:
> > Use Official Oracle Java JDK distribution. Works 100%.
> > You might need to edit run.sh if you want to point specifically to the version of Oracle Java you want to use. Or you'll want to change the symbolic link in /usr/bin or wherever it's located on your distrib' to make it point to the right version of Java.
> > In other words: DO NOT use openJDK for ATM8 -> use Oracle Java JDK(or any other?)
> 
> where can one find the "official oracle java JDK distribution"?

Google -> Java JDK Linux Download -> https://www.google.com/search?q=java+jdk+download+linux

**Comment by lilithwhite** [comment]
This happened to me when I only had the headless version of OpenJDK 17. Installing the regular version with "sudo apt install openjdk-17-jdk" fixed it for me

**Comment by MrZoraman** [comment]
> This happened to me when I only had the headless version of OpenJDK 17. Installing the regular version with "sudo apt install openjdk-17-jdk" fixed it for me

This fixed my issue as well, thanks! I'm running fedora. For fedora it is `sudo dnf install java-17-openjdk`.
