### ISSUE TITLE
crash while clicking on Me Wireless Transciever from AE2 Additions

### ISSUE THREAD

**Issue by ShadowwDC** [AllTheMods/ATM-8#1047]
https://pastebin.com/m6bFYf2W

if i click on the block or someone click on the block, 

the ones that clicked on it crash instantly.

**Comment by BoereworsG** [comment]
I have the same issue. 
i see all channel names are gone, When trying to add a new one i get an error. Internal Exception: java.lang.NullPointerException. This Crashes the local client only.
