### ISSUE TITLE
Server crashing when going in the End ATM8

### ISSUE THREAD

**Issue by SpectreNero** [AllTheMods/ATM-8#1048]

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by MvanRietschoten** [comment]
I think we had the same situation on our server. Our server didn't really crash, as there was no crash report. Everyone disconnected. I checked the logs while in this process of someone entering the End and it was just a huge lagspike, indicated by the warning of server ticks it was behind, it took about 5 minutes. After that I got a lot of repeating disconnectivity errors and then we where able to login again. I am guessing OP had the same experience?

**Comment by DrewWrobel** [comment]
> Do you have the crash report? If so, can you please post it here?

not op but i had the same issue here's my report
[crash-2023-04-19_00.34.51-server.txt](https://github.com/AllTheMods/ATM-8/files/11267400/crash-2023-04-19_00.34.51-server.txt)
