### ISSUE TITLE
Refine Storage Extra Storage Crafter upgrade recipe not working

### ISSUE THREAD

**Issue by ViceNoir** [AllTheMods/ATM-8#105]
Running latest version as of today 8-0.1.2  I was trying out recipes and found that from the Refine Storage crafter upgrade to the Iron Crafter in Extra Storage the recipe  is missing the RS crafter and even if you place it in the recipe it will not work.  I went ahead and cheated for the iron and gold to test and that one shows a recipe but does not work as well.  I tested this in a RS crafter Grid and a crafting table.  - Should I create ticket for this in the Extra Storage bug page or is this within your configuration due to adding a new mode to the mix?

**Comment by enigmaquip** [comment]
Ah you're on a server, and missing the rest of the recipe visually. This is a known bug and has to do with us adopting kubejs while it's still in an alpha state. The recipe works, it just isn't showing up in jei properly. basically the 4 corners need to be blocks of metal for whatever tier you're making
![image](https://user-images.githubusercontent.com/6134440/195874741-1ab07d8a-052e-42a2-9cc8-815c80c465c2.png)

**Comment by ViceNoir** [comment]
Thanks for the info.  I can let my players know the work around until this
is fixed.  Like alway the support for the ATMs are the best.

**Comment by enigmaquip** [comment]
Combining into one issue, see #111
