### ISSUE TITLE
All The Mods 8 (ATM8) (Not downloading)

### ISSUE THREAD

**Issue by firewolfy112** [AllTheMods/ATM-8#1052]
When I try to install All the Mods 8 (ATM8) it gets to the patches and then after it finishes the patches is delete itself this there anyway to fix this on curseforge app?

**Comment by AciarD** [comment]
![image](https://user-images.githubusercontent.com/85076914/224488786-1193a177-3b54-4341-97f3-a62356decc72.png)
I had the exact same problem. Click the three dots at top right next to create custom profile and repair installation. This fixed it for me picture attached
