### ISSUE TITLE
Thermal: Extra fuels not supported by Advanced Generators

### ISSUE THREAD

**Issue by PutNameHere42** [AllTheMods/ATM-8#1056]
The issue: Sunflower oil, Refined Sunflower Oil & Crystalised Sunflower Oil are not supported by Advanced Generators

The solution: Create a datapack that makes these fuels available to Advanced Generators as outlined in these examples: https://github.com/bdew-minecraft/generators/tree/mc1.19/src/main/resources/data/advgenerators/recipes/fuel

Suggestion: Include this in the pack by default. I understand the complexities of making a modpack mesh well, but a generator that burns fuel should burn all the fuels in the pack.

**Comment by Mitchell5200** [comment]
already done by devs, Closing
