### ISSUE TITLE
Tool Belt mod doesnt work.

### ISSUE THREAD

**Issue by PeaceIsBliss** [AllTheMods/ATM-8#1058]
No matter what I try, I can't get the GUI or Rotate left/right to work. Literally no way to utilize the tool switching. Crafting works, and can open it as an inventory, but the swapping is totally broken. 1.19.2

**Comment by dominikh** [comment]
@PeaceIsBliss Did you ever get it to work?

**Comment by PeaceIsBliss** [comment]
> @PeaceIsBliss Did you ever get it to work?

Nope. But I haven't tried in months either.

**Comment by HeroWillHD** [comment]
Leaving this comment here in case someone else finds this page through a search (as i have): I don't know if you guys are still having this problem, but i found out how to solve it, apparently it's a key bind conflict! Some mods are overlapping the "R" keybind and thus not letting the toolbelt overlay pop up, just search for any "R" key binds in the controls and change them to something else you're not using, or just unbind them, and let only the "R" keybind for Tool Belts mod. Hope this helps some people out there!
