### ISSUE TITLE
Crash while Rain/Snow

### ISSUE THREAD

**Issue by Shadowmaster09** [AllTheMods/ATM-8#1059]
[debug.log](https://github.com/AllTheMods/ATM-8/files/10950621/debug.log)
If it start Raining or Snowing the Game crashes but no Crash Report is available to look whats the Problem.
Its kinda annoying.
It occurs in every Dimension (overworld,Twilight, ...)

**Comment by Michaloo1** [comment]
Had the same issue, just turned off weather, rain, snow.

**Comment by Shadowmaster09** [comment]
This works only for the vanilla Dimensions, in the Twilight Forests this doesnt work =(

**Comment by Hunyol** [comment]
for some reason, it doesnt crash when using shaders
