### ISSUE TITLE
[1.0.11] ticking entity server crash shulker + reliquary gun

### ISSUE THREAD

**Issue by asparagus4040** [AllTheMods/ATM-8#1062]
The whole server crashes every time a apotheosis miniboss shulker is shot with a reliquary gun.
[crash-2023-03-12_14.12.33-server.txt](https://github.com/AllTheMods/ATM-8/files/10951683/crash-2023-03-12_14.12.33-server.txt)

**Comment by Mitchell5200** [comment]
Similar to https://github.com/P3pp3rF1y/Reliquary/issues/610
