### ISSUE TITLE
Local crash when loading large recipe into JEI

### ISSUE THREAD

**Issue by tuxedorose1011** [AllTheMods/ATM-8#1063]
Server doesn't crash, but in refined storage when I tried to add the ingredients for the electric motor using the JEI, my local minecraft crashed with an index out of bounds exception. Probably because too many ingredients were in the crafting grid. Not sure if it's an issue with create add-ons and additions, or the JEI, or refined storage.

**Comment by Mitchell5200** [comment]
Considering that recipe is not a normal 3x3, and should not work in any non create mechanical crafting setup, it's clear that's the cause
