### ISSUE TITLE
Extra Hearts Lost on Death

### ISSUE THREAD

**Issue by fostysnowman** [AllTheMods/ATM-8#1064]
I just started playing ATM8 and noticed the food mod that gives extra hearts for trying new foods was in the pack.  I had 4 extra hearts and died and lost them.  It lets me eat food I have already eaten before as if I had never tried it so I can gain them back, but why?  I won't be coming back to this modpack if this is just how it works. I can't imagine having a long playthrough with 20+ hearts and dying once to lose them all and have to eat all those foods again.  Mod name is Spice of Life, please fix this.

**Comment by MoistTowelettes** [comment]
It's a config setting for the mod, just change it if you don't want to lose them

**Comment by fostysnowman** [comment]
Just tried that, didn't work.  The only other reason it could have not worked is that launching the modpack through curseforge wouldn't have applied the config change but I checked the files before and after and it says it hasn't changed.  Thanks though.

I went to the modpack on curseforge, clicked open folder and went to defaultconfigs -> solcarrot-server and changed: 

"#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = true"

to 

"#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false"

Let me know if I did anything wrong. Here is the full code for that config I have saved:


[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 10
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 2
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [5, 10, 15, 20, 25]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = []
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = true

**Comment by fostysnowman** [comment]
Ok I found a fix.  I just had to disable it in game in the mod folder config it works now thank you.
