### ISSUE TITLE
Crashing with Projector from SecurityCraft 

### ISSUE THREAD

**Issue by DiceRandom** [AllTheMods/ATM-8#1065]
The projector from SecurityCraft doesn't play well with the Basic Mechanical Pipe from Mekanism.
Stick the pipe in the projector, and watch as it soft-locks your world.
The game crashes upon loading the world.
'Cannot read field "lastFluid" because "network" is null'

[Crash Report on Pastebin](https://pastebin.com/KWyKeSNW)

**Comment by EJD799** [comment]
Also happens when you put a projector inside a projector.

**Comment by LeBrayanTS** [comment]
It happened to me with an Universal Cable

**Comment by Montnahp** [comment]
how you craft projector ?
