### ISSUE TITLE
bug: game crashes when you try and craft the mob belt from reliquary

### ISSUE THREAD

**Issue by mfreeman451** [AllTheMods/ATM-8#1066]
<img width="1255" alt="Screenshot 2023-03-13 at 12 09 07 AM" src="https://user-images.githubusercontent.com/1821930/224613134-0afa315f-fc87-4672-9543-e89070b048cb.png">

Getting this crash when I try and craft the mob charm belt. Using ATM 1.0.13 on OSX w/ GDLauncher.

**Comment by Mitchell5200** [comment]
Full crashlog please via https://mclo.gs/

**Comment by zrovihr** [comment]
its still there for me. should I open a new issue?
