### ISSUE TITLE
Fresh atm8 1.0.13 server required 15 gigs of ram

### ISSUE THREAD

**Issue by VoxelVixen** [AllTheMods/ATM-8#1069]
First problem was the server crashing on generating a world with 16 gigs of ram allocated.
Fixed that with running my client in SP and uploaded its world files to the server.

Then on joining the world , this is what i saw in my console.
https://imgur.com/a/FVAdYTi

Restarted the server and now im on 7 gig used when logged on the server.
But im curious what happens when my friends log on later today ...

The pack might be good but i cant justify keeping 16 gig of ram allocated for just 1 server.

Edit
2 Friends joined and we did a little bit of exploring , ram usage went up to 8.1 gigs.
Then 1 of us hit some type of world generation and ram usage spiked to 15.5gigs and stayed there till i rebooted the server.
This is unplayable.

**Comment by James103** [comment]
Try updating Rubidium to the latest version: https://www.curseforge.com/minecraft/mc-mods/rubidium/files/4448157
