### ISSUE TITLE
Invisible Mobs ? Cause crash ?

### ISSUE THREAD

**Issue by AristoTV** [AllTheMods/ATM-8#1070]
Hey ! 

I recently open and Host myself a server on a different PC, but sadly, the modpack is not doing well..
I tried everything to fix this issues, but still got problem and crashes...

And today i wanted to check if there was some Entity that cause that crashes (With some Pathing that can cause some issues. Already got that on other modpacks.) After turning ON the Hitbox by pressing F3+B, i see some random Invisible Entity AFTER killing some Enderman. 

So i try with other mobs than Enderman, and got the same Invisible Entity.
I look everywhere to know which mods was adding that, but got no luck and find nothing.

Can anyone tell me which mods add this, and confirm that it's not only me and my server ?

PS : I tried in Singleplayer, and same result, invisible Entities that despawn between 20-60 seconds.

![2023-03-13_15 54 20](https://user-images.githubusercontent.com/127767237/224744166-79a453be-eefe-4b7c-869a-bbe9f2d70759.png)
![2023-03-13_15 58 17](https://user-images.githubusercontent.com/127767237/224744175-a25f9b59-b15d-4269-89c2-106096b5e6c0.png)

**Comment by Mihoshika** [comment]
Those are intentional. They're ghosts/spirits or whatever, from some magic mod. I forget which. They disappear on their own eventually. There's some gear that lets you see them as well. Anyways, not likely related to your crashes.

**Comment by Mitchell5200** [comment]
Evilcraft vengeance spirits are what you're looking at.

Can't help with crashes without any crashlogs
