### ISSUE TITLE
game crashes after 90 seconds of being in world

### ISSUE THREAD

**Issue by NearlyPro** [AllTheMods/ATM-8#1071]
so the game is fine for the first 2 hours (ish) then crashes then constantly crashes every couple mins

**Comment by Mitchell5200** [comment]
Crashlog please

**Comment by NearlyPro** [comment]
https://mclo.gs/Evc1jzH

**Comment by Mitchell5200** [comment]
okay, that's the particle render crash, same as the below listed
#923,#930,#933,#943,#944,#949,#959,#980,#985,#988,#990,#993,#999,#1025,#1034,#1036,#1039,#1055,#1059,#1071,#1090

I know of three fixes that seem to work for most users
1, Update GPU drivers
2, disable particles
3, enable shaders (some on github report this as a fix)🤷‍♂️
