### ISSUE TITLE
allthemodium axe and create deployer - destroys axe with single use

### ISSUE THREAD

**Issue by perlguy** [AllTheMods/ATM-8#1075]
ATM8 1.0.13

Have only tested with log stripping on a conveyor.

**Comment by perlguy** [comment]
ATM8 1.0.13

**Comment by James103** [comment]
Have you tested using the deployer from Create with any other unbreakable tools (such as Awakened Supremium Axe)?

**Comment by James103** [comment]
These tools should last forever and be unbreakable as they don't even have durability, but somehow Create (or the fake player library it uses) is misreading the "item doesn't have durability" as "item breaks after 1 use" even if that's not the case.

**Comment by James103** [comment]
What is the version of the Create mod in the instance you're running when the axe (appeared to) break instantly on use?
