### ISSUE TITLE
KubeJS crash upon startup of ATM8

### ISSUE THREAD

**Issue by Riptide988** [AllTheMods/ATM-8#1076]
Minecraft loads as usual on startup but displays errors with **KubeJS** towards the end. Attached is the logs file for the crash, the image of the crash and the crash logs. Help is appreciated in advanced

[startup.txt](https://github.com/AllTheMods/ATM-8/files/10967529/startup.txt)

![image](https://user-images.githubusercontent.com/127847648/224981576-edf5c8cd-dd4c-4786-8e5d-1f9982a04f53.png)

[crash-2023-03-14_19.01.01-fml.txt](https://github.com/AllTheMods/ATM-8/files/10967542/crash-2023-03-14_19.01.01-fml.txt)

**Comment by Mitchell5200** [comment]
latest.log via https://mclo.gs/ please

**Comment by Riptide988** [comment]
> latest.log via https://mclo.gs/ please

https://mclo.gs/lDedlw3

**Comment by Mitchell5200** [comment]
```
Startup script errors:
 1) Error loading KubeJS script: startup_scripts:block_modification.js': Line 2: 'onEvent()' is no longer supported! Read more on wiki: https://kubejs.com/kjs6
 2) Line 2: 'onEvent()' is no longer supported! Read more on wiki: https://kubejs.com/kjs6
 3) Error loading KubeJS script: startup_scripts:item_modification.js': Line 2: 'onEvent()' is no longer supported! Read more on wiki: https://kubejs.com/kjs6
 4) Line 2: 'onEvent()' is no longer supported! Read more on wiki: https://kubejs.com/kjs6

```
We do not have those files in our official distribution of Allthemods 8.
Futhermore, we do not support TLauncher or any other Cracked launchers, stop using them.
