### ISSUE TITLE
No Recipe for filled fluid cell in FTB Industrial Contraptions

### ISSUE THREAD

**Issue by Zizes** [AllTheMods/ATM-8#1078]
Hello! 

There is no recipe for automatic filling Fluid Cell from FTB Industrial Contraptions with any liquid. 
The only way to fill Fluid Cell with a liquid is just to right click on it. Thus, it is impossible to automate any recipe that requires filled Fluid Cell.

Thank you in advance!

**Comment by OmgDani** [comment]
Fluid cell filling can be automated via Mekanism's fluid tanks and Thermal Expansions fluid transposer
