### ISSUE TITLE
Refined Storage Issue

### ISSUE THREAD

**Issue by Nite-Hare** [AllTheMods/ATM-8#1087]
I'm using the Pattern Grid and I'm trying to make a pattern for the machine casing. But as you can see from the screenshot, it keeps trying to use Bloody Cobblestone instead of the stone I put in the recipe. 

Does anyone know a fix?
![2023-03-17_17 20 13](https://user-images.githubusercontent.com/13861237/226056310-f970f389-6cd6-4ce8-9b4a-3aeb53ca0c35.png)

**Comment by MoistTowelettes** [comment]
if you want it to only use a normal stone block you need to click the exact checkbox

**Comment by Coreytrnr** [comment]
I want to use any stone like it is in the recipe.
