### ISSUE TITLE
Need help with random Crashing Exit code: -1073740791

### ISSUE THREAD

**Issue by Ravalli03** [AllTheMods/ATM-8#1088]
I'm continuing to get a random crash with the following:

ERROR
Game Crashed

An unexpected issue occurred and the game has crashed

This crash  may be caused by an out-of-date graphics driver or conflicts screen recording software. Please ensure your graphics driver is up-to-date and disable or uninstall any screen recording software in use.

Exit code: -1073740791

I have the latest driver and don't have or use any screen recording software. It happens randomly anytime, even while AFKing.

I have already tried reinstalling the driver.

Minecraft 1.19.2
ATM Version 8-1.0.13
Forge 43.2.6
Windows 11
Nvidia Driver 531.29 

Any help would be awesome. 

[latest.log](https://github.com/AllTheMods/ATM-8/files/11007199/latest.log)

**Comment by Ravalli03** [comment]
No longer crashing, not sure what fixed it.

**Comment by Rodion3003** [comment]
can you please tell what you have done while trying to fix this problem?
