### ISSUE TITLE
ATM8 Crashing

### ISSUE THREAD

**Issue by Pugdog123** [AllTheMods/ATM-8#1090]
I started having this issue earlier today, I played this morning and afternoon, no issues or ingame crashing. I closed the game to play another game. I opened it back up and it began saying "Invalid Player" when I attempted to login to my single player world. I restarted my game and it is now crashing. It gives me the
EXIT CODE: 1 

There are no updates required or ram deficiencies for my computer and I dont know if there is something wrong with my world or the modpack currently. I will post the crashlog in the attached files section below, I am not knowledgeable in understanding it well myself. Any help or advice would be seriously appreciated, my world is fairly progressed and I dont want to lose my progress. 
[atmcrashlog.txt](https://github.com/AllTheMods/ATM-8/files/11007615/atmcrashlog.txt)

**Comment by Mitchell5200** [comment]
try updating your GPU drivers

**Comment by MrCatlio** [comment]
im getting EXIT CODE: 1 error and i have tried everything and still getting the EXIT CODE 1

**Comment by Pugdog123** [comment]
I updated my gpu last night and i am still having the same issue.

**Comment by Pugdog123** [comment]
mitchell ur a gem, the particles disabled fixed my issue <3
