### ISSUE TITLE
[1.0.13] Server tick lag when >1 player is online

### ISSUE THREAD

**Issue by AbstractUmbra** [AllTheMods/ATM-8#1091]
Hey - I want to start off by saying that this issue is really hard to diagnose.

I am running the latest 1.0.13 server files and all works wonderfully... until more than 1 player comes online.
Soon after which the server's TPS start to degrade, pretty hard.

The console reports that we're around 200-400 ticks behind, and `/spark tps` averages around 11-12 tps (approx).

This is a fresh installation, a new world and I'm at a loss on how to diagnose this normally.

This isn't the world generation lag, even if the players live around the same area it still goes askew.

I used a mod included in the pack, Overseer, or something similar, to check high ticking entities in the loaded world and each profile was indeterminate. It seemed like guard villagers were a high ticket source, then it was a chicken, then a random zombie.
Could it be mod AI being weird when there is >1 player?

<details>
<summary>Server properties (sanitised)</summary>
<br>

```
#Minecraft server properties
#Sat Mar 18 05:41:10 GMT 2023
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=hard
enable-command-block=true
enable-jmx-monitoring=false
enable-query=true
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
level-name=world
level-seed=
level-type=minecraft\:normal
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=180000
max-world-size=29999984
motd=**Redacted**
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
previews-chat=false
pvp=true
query.port=**redacted, but works**
rate-limit=0
rcon.password=**redacted**
rcon.port=**redacted**
require-resource-pack=false
resource-pack=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=**redacted**
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=true
```

</details>

<details>
<summary>JVM Arguments</summary>
<br>

```
-Xms16G
-Xmx32G
-XX:+UseG1GC
-XX:+ParallelRefProcEnabled
-XX:MaxGCPauseMillis=200
-XX:+UnlockExperimentalVMOptions
-XX:+DisableExplicitGC
-XX:+AlwaysPreTouch
-XX:G1NewSizePercent=30
-XX:G1MaxNewSizePercent=40
-XX:G1HeapRegionSize=8M
-XX:G1ReservePercent=20
-XX:G1HeapWastePercent=5
-XX:G1MixedGCCountTarget=4
-XX:InitiatingHeapOccupancyPercent=15
-XX:G1MixedGCLiveThresholdPercent=90
-XX:G1RSetUpdatingPauseTimePercent=5
-XX:SurvivorRatio=32
-XX:+PerfDisableSharedMem
-XX:MaxTenuringThreshold=1
```

</details>

I tried the JVM arguments with 4/12GB, 12/16GB and now with 16/32GB but no luck. According to `htop` it barely even uses the max amount of RAM.

<details>
<summary>System details</summary>
<br>

```sh
$ uname -a
Linux DediBoi 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

$ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)

$ free -h
               total        used        free      shared  buff/cache   available
Mem:            62Gi        26Gi       2.5Gi       161Mi        34Gi        35Gi
Swap:           31Gi       1.0Mi        31Gi
```

</details>

Please let me know if you need any more information.

**Comment by Mitchell5200** [comment]
I'll need to see that spark profile if you still have it, as it might have some clues as to a cause

**Comment by AbstractUmbra** [comment]
Sadly the previous ones expired, I'll set up a second client to connect for some testing now - will report back soon.

**Comment by AbstractUmbra** [comment]
Here's a profile of a brand new world, but just running around, nothing else, with 2 players:-
<https://spark.lucko.me/GryJE0Ij15>

**Comment by Mitchell5200** [comment]
Hmm, mobs and the quark feeding trough are at the top of the list... we plan to disable the feeding trough next update after some reports from other server hosts, you can disable it in the quark config, around line 60, in the server's config folder

**Comment by AbstractUmbra** [comment]
> Hmm, mobs and the quark feeding trough are at the top of the list... we plan to disable the feeding trough next update after some reports from other server hosts, you can disable it in the quark config, around line 60, in the server's config folder

This was actually one of the first things I noticed and I did disable it in a run (lost that profile...), but the issue sadly persisted.

I can disable that and generate another profile if that helps?
