### ISSUE TITLE
Very Low FPS with ATM 8

### ISSUE THREAD

**Issue by GObeynew** [AllTheMods/ATM-8#1093]
Installed newest version of ATM8 and can observe very low FPS while gaming regardless of I have shaders on or off. Also changing visual details to lowest come with no effect - still around 17-22 fps. Tired with ATM and it looks good - around 150 FPS so definitely there is something wrong with this version of ATM. My config:
Intel i9-10850K
32 GB RAM (8G for JAVA)
Radeon RX 6900XT
Disk drive - SSD (not nvme)

best regards

Adam

**Comment by subterfuse** [comment]
For me, I gained some fps by tinkering with the Advanced tab, "CPU-render-Ahead Limit", I got better performance when I set it higher, which may or may not help but it's what I gained the most fps from.

**Comment by ariosos** [comment]
In my case, my PC did _not_ like going into the nether, even after lowering chunks back down to 4. What's better, a lower Render Ahead, or higher? Guessing lower - I'll try 0. :)

![image](https://user-images.githubusercontent.com/7917753/226889850-b4126910-1e9e-4d39-9b37-ffbe829c2ce2.png)

**Comment by GentlePuppet** [comment]
@ariosos 
This isn't completely helpful but yer playing a heavily modded pack with a cpu from 2011.
Minecraft is heavily CPU reliant so it's no shock you are running into issues.

This modpack runs at 25-50fps on my 2020 Ryzen 9 5900x, rtx 3070, with 16GB of my 64GB allocated.
I added lightspeed(for launch speed) and rebidium extras to try to help with performance.
 -Xmx16000m -Xms256m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by Monkeycadeyn** [comment]
> @ariosos This isn't completely helpful but yer playing a heavily modded pack with a cpu from 2011. Minecraft is heavily CPU reliant so it's no shock you are running into issues. Yer gpu drivers are also very outdated if that matters at all.
> 
> This modpack runs at 25-50fps on my 2020 Ryzen 9 5900x, rtx 3070, with 16GB of my 64GB allocated. I added lightspeed(for launch speed) and rubidium-extras to try to help with performance. These are my launch settings: `-Xmx16G -Xms16G -XX:+ExplicitGCInvokesConcurrent -XX:NewRatio=3 -XX:NewSize=84m -XX:+UnlockExperimentalVMOptions -XX:ParallelGCThreads=3 -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:G1HeapRegionSize=32M -XX:+OptimizeStringConcat`
> 
> ![image](https://user-images.githubusercontent.com/43224790/247381911-deef9534-f38a-43fa-bb8e-6a95f1a08dd1.png) ![image](https://user-images.githubusercontent.com/43224790/247382026-dbcfc17d-b0fe-404e-94b9-38ca9a7aed63.png)

Sometimes giving minecraft too much RAM can actually make it run worse, try giving it 10-12 gigs instead, because I'm running this modpack, with shaders, on 16 gigs, i7-8700k, and a gtx 1080 and I get a solid 70 pretty consistently. I keep the render distance at 16.
