### ISSUE TITLE
No tag called "minecraft:wool" exists for Soul Jar (Mystrical Agriculture)

### ISSUE THREAD

**Issue by dragonkid828** [AllTheMods/ATM-8#1096]
Soul Jar recipe says for sheep that you can use something with the tag "minecraft:wool" for the Soul Jar recipe, but through experimentation, no type of wool works. It also shows a barrier block in the slot where it says you should be able to use wool. Apologies for edits, many misclicks occured.
![javaw_cKElQfC9Eg](https://user-images.githubusercontent.com/530100/226163310-933807c7-5479-43d5-a625-5a84eb5ec4ec.png)

**Comment by Mitchell5200** [comment]
![2023-03-19_16 34 47](https://user-images.githubusercontent.com/45913837/226163318-954421e5-f8ae-4a25-a2f7-5952b03e525f.png)
Exists for me in a Fresh install, try a game restart

**Comment by dragonkid828** [comment]
Huh, I've restarted multiple times and the server has been to, and it's ALWAYS been like that. Maybe server needs a fresh install. Thanks for your help!
