### ISSUE TITLE
Crashing upon startup

### ISSUE THREAD

**Issue by michaelfiring** [AllTheMods/ATM-8#1101]
Hello, i am a first time installer of this mod and im currently been trying to use the FTB launcher and the Forge launcher but im still ending up with the game crashing when i come to the mojang loading screen at the very start. this is the crash log and im desperate for help about this issue

https://pastebin.com/zzYiPi5L

**Comment by James103** [comment]
The root cause exception in English is: `java.nio.file.FileSystemException: C:\Users\wulsc\AppData\Local\.ftba\instances\f42cf744-dad1-4faf-9406-be372597c364\config\betteroceanmonuments-forge-1_19.toml: The process cannot access the file because it is being used by another process`
