### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by Vali9Degete** [AllTheMods/ATM-8#1102]
Hi there , i keep gettin a crash wheneever my wolrd starts after de 100% joining world and then chrashes ( last thing i made was the rubber thing that extract rubber from wood , finished it worked perfectly ) , Exit code 1 and the rest i paste it here 
https://justpaste.it/6vyhs

**Comment by rctcool0** [comment]
I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue:
Dynamic Lights
Oculus
Rubidium
RubidiumExtra
TextruesRubidiumOptions
