### ISSUE TITLE
Error 1 Java issue

### ISSUE THREAD

**Issue by OneEyedDavid** [AllTheMods/ATM-8#1103]
Game crashes upon loading.
[crash report.txt](https://github.com/AllTheMods/ATM-8/files/11030975/crash.report.txt)

**Comment by LiborVojtek** [comment]
At least for me the solution for now was the same as in #1071.
Disable particles.

**Comment by rctcool0** [comment]
I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue:
Dynamic Lights
Oculus
Rubidium
RubidiumExtra
TextruesRubidiumOptions

**Comment by Mitchell5200** [comment]
> I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue: Dynamic Lights Oculus Rubidium RubidiumExtra TextruesRubidiumOptions

We only removed Extras, options, and lights, Not Rubidium and oculus
please stop copy spamming that same reply

**Comment by rctcool0** [comment]
Oh sorry! Guess I missed that, was just trying to help others that had the same issue as me.
