### ISSUE TITLE
ATM 8 1.0.13 Industrial Foregoing Block Placer Not Working

### ISSUE THREAD

**Issue by Nite-Hare** [AllTheMods/ATM-8#1104]
I'm trying to use the block placer and it is not placing blocks. Any idea why? I have given it power and it still won't place blocks.

**Comment by mellamokb** [comment]
I have seen similar behavior, what's weird is sometimes it does, and sometimes not but seems to depend on where it is located?  I use two to place acacia blocks face up for some Fluid Extractors, one works perfectly, the other one refuses to place blocks.

**Comment by andys11** [comment]
You can solve this by creating a FTB team and then in team interface go to settings and enable fake players.

**Comment by Lord-Volkner** [comment]
> You can solve this by creating a FTB team and then in team interface go to settings and enable fake players.

That didn't work for me.  Block Placer still won't place blocks.

**Comment by Mitchell5200** [comment]
Users need to enable Fake players in their teams settings to get the placer working, Closing
