### ISSUE TITLE
Moonworm Queen only found as rare chance in Large Hollow Hill

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM-8#1105]
After decimating the inside of many hollow hills and finding no moonworm queen I did a search and according to the ftb wiki (https://ftbwiki.org/Hollow_Hill_(Twilight_Forest)) the moonworm queen is a rare loot in large hollow hills. Recommend adding the description of "Large Hollow Hils" to the twilight forest quest for the moonworm queen.

**Comment by Mitchell5200** [comment]
That old FTB wiki is outdated for modern versions of most mods, and on the official Twilight Forest wiki, they are found in "some" hollow hills and the lich tower
http://benimatic.com/tfwiki/index.php?title=Moonworm_Queen

> The Moonworm Queen is a strange green insect found as treasure in some Hollow Hill and Lich Tower chests. The Moonworm Queen is filled with Moonworm eggs, which will attach Moonworms to walls or almost any solid surface. By holding the button down like a bow, the Queen can be instructed to fire the Moonworms as a projectile, which will then stick to any available surface it lands on. It is also capable of firing Moonworms through a Dispenser) when one is powered with a Moonworm Queen inside.

However we will discuss internally if there is a need to change that description in the quest to be more accurate
