### ISSUE TITLE
Echo Shard Recipe

### ISSUE THREAD

**Issue by Merithor** [AllTheMods/ATM-8#1107]
Despite Deeper and Darker existing and the Ancient temples do give some, but they are far and few, even with a Structure Compass, of which still follows the Overworld Ancient City loot tables.
So I propose a way to make them.

Heart of the Deep : HD . Amethyst Crystal Block : ACB . Soul Dust : SD
[SD] [ACB] [SD]
[ACB] [HD] [ACB]
[SD] [ACB] [SD]
Equaling to 4 shards. This requires to have gone into the Dimension and killed the mobs (Soul Dust), have killed a Warden (Heart of the Deep), and a block that isn't heavily used except in some magic mods. It makes them renewable, and worth doing Occultism's Deep Ore Miner if one isnt at Marid tier yet.
Amethyst Shards are also in the loot table which furthers the idea of using Blocks to make new shards.

**Comment by Mitchell5200** [comment]
Covered by HNN and Bees
