### ISSUE TITLE
Leaving the game and returning causes Big Reactor fuel to disappear

### ISSUE THREAD

**Issue by Lord-Volkner** [AllTheMods/ATM-8#1109]
Playing a solo game. Whenever I leave the game and start it back up later, all the fuel that was loaded into my reactor is gone. The reactor has to be reloaded and the previous fuel is lost. This happens if I pop over to my test world and pop back. I didn't notice the problem with my first reactor, but now it's a problem as my new reactor takes almost 9 stacks of fuel.

**Comment by Mitchell5200** [comment]
The dev is aware and has recently managed to reproduce this issue, and is working on a fix
https://github.com/BiggerSeries/BiggerReactors/issues/71
