### ISSUE TITLE
Some Recipes do not show when connected to a server

### ISSUE THREAD

**Issue by enigmaquip** [AllTheMods/ATM-8#111]
Some recipes, especially those we've customized, are not showing up properly in JEI when connected to a server. This is a known issue and a byproduct of us running some bleeding edge mods that are still in alpha state. The recipes do work if you put in the correct items, but the correct recipes only show in a single player game at this moment.
This affects any version 0.1.0 or greater

**Comment by Lacyoreo** [comment]
![ATM8 ERROR](https://user-images.githubusercontent.com/115854462/195966349-65dcf96a-7531-4d26-b546-fb54f64807ec.png)
  

It looks like this- my version is the newest version of the game and its been like it through the updates.

**Comment by enigmaquip** [comment]
Yes, no screen shot necessary. As I previously said
> Some recipes, especially those we've customized, are not showing up properly in JEI when connected to a server.

**Comment by Sl0ter** [comment]
it's an error from kubejs. it won't load any recipe with #Forge: in it on a Server. 
i made a fix here for now. #123

**Comment by enigmaquip** [comment]
Fix with a kubejs update / update to pack version 1.0.4
