### ISSUE TITLE
(0xC0000005) Game crashes randomly. Different reason each time.

### ISSUE THREAD

**Issue by minimutson** [AllTheMods/ATM-8#1116]
***3/22/2023 - Game crashes randomly. Different reason each time. #1116***

I have no clue where to even start with this, so here are the logs.

Oldest: https://mclo.gs/PcA2AUa
Mid: https://mclo.gs/G8NS1SE
Mid: https://mclo.gs/mQEu1eM
Mid: https://mclo.gs/AAK0LkE
Newest: https://mclo.gs/wxiKflZ

If anyone can help out with this, that would be great! Since I have exhausted all options that I am capable of.

**Edit 1:**

Update: A friend logged on earlier, and discovered a temporary fix. Turning down particles to a minimum.

**Edit 2:**

New crash on the multiplayer screen: https://mclo.gs/9MClYuz
(Thought this one would also be useful to find bugs)

**Edit 3: (0xC0000005)**

Update: Another one of these random crashes occurred: https://mclo.gs/IyX0cBT

Research is to follow, and I will work on a permanent solution.

**Edit 4: (0xC0000005)**

A little bit of research has given me some suggestions to fix 0xC0000005. This however has no effect on the other issues that are listed above.

A repair log has been added at the bottom to log all attempted fixes.

**Edit 5: (0xC0000005)**

After playing on my friend's LAN world, the game randomly crash when he states in a vc that it started to rain.

Log: https://mclo.gs/kk5o0Cp

**3/23/23: Continuation of 3/22/23**

Upon today's testing session, where I encountered the same crash.: https://mclo.gs/iw7YkpB

**Edit 1:**

All attempts at mitigating this issue, have failed. This issue does seem to be tied with the others. No further attempts at repair will be made as of this time.

**Comment by minimutson** [comment]
Update: A friend logged on earlier, and discovered a temporary fix. Turning down particles to a minimum.

**Comment by minimutson** [comment]
New crash on the multiplayer screen: https://mclo.gs/9MClYuz
(Thought this one would also be useful to find bugs)

**Comment by minimutson** [comment]
Update: Another one of these random crashes occurred: https://mclo.gs/IyX0cBT

Research is to follow, and I will work on a permanent solution.

**Comment by minimutson** [comment]
Update: Attempting repairs. Logged progress will be edited in.

Attempt 1 - GPU Driver Updates
Status - In progress

Attempt 2 - Reinstall Java Runtime SDK
Status - Not Attempted.

Attempt 3 - User Account Control Bypass
Status - Not Attempted.

**Comment by rctcool0** [comment]
I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue:
Dynamic Lights
Oculus
Rubidium
RubidiumExtra
TextruesRubidiumOptions

**Comment by Mitchell5200** [comment]
> I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue: Dynamic Lights Oculus Rubidium RubidiumExtra TextruesRubidiumOptions

We only removed Extras, options, and lights, Not Rubidium and oculus

**Comment by minimutson** [comment]
Alright, so it seems a confliction between the mods is highly likely. I will investigate further when I have time.

**Comment by Mitchell5200** [comment]
Fixed in 1.0.15
