### ISSUE TITLE
Slimy bee (simulation issues)

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/ATM-8#1117]
I'm trying to automate slimy bees but I can't get them to work. I spawned them in a slime chunk the first time but do I need to keep them in one for them to work or is this a bug.

**Comment by DevilMayCryIfrit** [comment]
I moved my slimy bee to a slime chunk and after about 2 hours it still didn't work. So I removed the simulation upgrade and it started to work right away. So does the slimy bee not work with the simulation upgrade?

**Comment by DevilMayCryIfrit** [comment]
I just noticed that the slimy bee is not the only one that doesn't work with the simulation upgrade. Even the silky bee doesn't work, so I believe that it is a bug with some bees. If this is intentional than the fps will drop because of the bees in the world.

**Comment by enigmaquip** [comment]
Duplicate of #977 
This should be fixed in v1.0.14 though, have you updated to the new release from the last 24 hours?

**Comment by DevilMayCryIfrit** [comment]
Fixed with update thank you
