### ISSUE TITLE
Storage Terminal Crash

### ISSUE THREAD

**Issue by Jophire** [AllTheMods/ATM-8#112]
Modpack version: 0.1.3
Server Type: Dedicated

Server crashes whenever a player attempts to open an Integrated Dynamics Storage Terminal.
Will crash with just a single cable and terminal.

Only repeatable on the server, does not occur in single player.

[Server Log](https://paste.shockbyte.com/qivojoxoxobocadexoju)

[Crash Report](https://github.com/AllTheMods/ATM-8/files/9791166/crash-2022-10-15_04.22.34-server.txt)

**Comment by Kevin-Jansen** [comment]
Can confirm I am experiencing this issue too. Reported this on the Integrated Dynamics page as well: https://github.com/CyclopsMC/IntegratedTunnels/issues/260

To give you some more logs:
Server log: https://pastebin.com/dK0LV8Yf
Crash log: https://pastebin.com/F2AWQCBd

**Comment by jstansel** [comment]
Is this the same issue as https://github.com/AllTheMods/ATM-7/issues/1583 reported for ATM-7 and fixed by the mod author?
