### ISSUE TITLE
AdventureZ missing from the pack

### ISSUE THREAD

**Issue by dragonkid828** [AllTheMods/ATM-8#1121]
It seems with the most recent update, AdventureZ was supposed to be added but was not, leading to a ton of missing items in the quest book. I would screen shot them, but it seems like every single new quest book page has something missing from it.

**Comment by enigmaquip** [comment]
AdventureZ is a fabric mod, that'd be really difficult to add it to a Forge modpack

**Comment by dragonkid828** [comment]
Have you heard of not shooting the messenger or?
![javaw_vq7AhIWbO5](https://user-images.githubusercontent.com/530100/227362058-602cb1eb-84de-49d1-b90d-96a64081c60a.png)

**Comment by enigmaquip** [comment]
are you sure you're in the right place? I know of no quest page in atm8 that looks like that

**Comment by enigmaquip** [comment]
You somehow have a mix of some other modpack's quests in with the atm quests. 
![2023-03-23_15 25 50](https://user-images.githubusercontent.com/6134440/227366673-1de018f3-cdf6-45bf-84c3-a11b03a064be.png)

**Comment by enigmaquip** [comment]
Paradise Lost is another fabric mod, bumblezone is not in atm8, eden ring is another fabric mod. There was no rudeness in asking if you were in the right place

**Comment by dragonkid828** [comment]
I installed the new update from the ATM8 repository with no alterations.

**Comment by dragonkid828** [comment]
Apologies to @enigmaquip, I seem to have had a bad installation or something happened with the 3rd party site I use to host my server.
