### ISSUE TITLE
Crashing When trying to enter world

### ISSUE THREAD

**Issue by Mannyita** [AllTheMods/ATM-8#1122]
https://mclo.gs/rQ6BGxk

**Comment by rctcool0** [comment]
I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue:
Dynamic Lights
Oculus
Rubidium
RubidiumExtra
TextruesRubidiumOptions

**Comment by Mitchell5200** [comment]
> I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue: Dynamic Lights Oculus Rubidium RubidiumExtra TextruesRubidiumOptions

We only removed Extras, options, and lights, Not Rubidium and oculus

**Comment by Mannyita** [comment]
I am playing the current version of the modpack. I have updated it every time it gets an update. I am on 1.0.14, should i still delete those mods from the modpack?

**Comment by Mannyita** [comment]
> I had the same issue in 1.0.13. The latest version, 1.0.14, fixes this issue by removing Rubidium and its addons. If you want to continue to play on a 1.0.13 server, you can safely remove or disable the following mods to temporarily fix the issue: Dynamic Lights Oculus Rubidium RubidiumExtra TextruesRubidiumOptions

I removed Rubidium and oculus and it worked thanks for the help.

**Comment by Mitchell5200** [comment]
Fixed in 1.0.15
