### ISSUE TITLE
v1.0.14 - Phytogenic Insolator not producing secondary seeds from Mystical Agriculture seeds

### ISSUE THREAD

**Issue by dknoma** [AllTheMods/ATM-8#1125]
https://github.com/AllTheMods/ATM-8/blob/946bbe19edcb8c764b9d90c07e0c16f423dc8903/kubejs/server_scripts/mods/mysticalagriculture/crops.js#L133-L136

The above line was changed to 
```       
          {
            item: Crop.getSeedsItem().getId(),
            chance: Crop.getTier().hasSecondarySeedDrop() ? (1 + SecondarySeed) : 1,
            locked: true
          }
```

This seemingly prevents ALL secondary Mystical Agriculture seeds from being produced in the insolator. Reverting these lines back to the original from v1.0.13 produces seeds again. Don't know if this was intended to happen.

**Comment by enigmaquip** [comment]
couple changes were made, all seeds tier 5 and up no longer have an extra seed chance. And for the rest of the tiers and for the insolator specifically, it still has the 1% chance of a second seed it always did, it's just no longer boostable so it truly is a 1% chance as intended.

**Comment by dknoma** [comment]
Okay, so the change is intentional and should be working then. Thanks!
