### ISSUE TITLE
Occultism not highlighting Iesnium ore

### ISSUE THREAD

**Issue by indygwyn** [AllTheMods/ATM-8#113]
Been trying to find iesnium ore in the nether using the Occultism Divination rod and it's not highlighting the ores making it incredibly hard to find

**Comment by P0kys** [comment]
Just tested it and it seems to work fine for me (I was suspicious it might not work with shaders but it does)
The ore seems to be pretty rare so search in a large area. Also, make sure you are right-clicking and holding until the rod finishes the animation

**Comment by perinkkk** [comment]
its not working for me and i am sure i set the iesnium ore and i am holding it like a bow

**Comment by silvernirvash** [comment]
has anyone else figured this one out? I'm playing a custom mod pack Stacia Expert 2 and occultism is in the pack. I can't for the life of me figure out why the ore won't reveal itself when wearing the goggles or eating the demon dreams fruit or using the divination rod. I can't be the only one having this issue still.

**Comment by Brandao2006** [comment]
> Alguém mais descobriu isso? Estou jogando com um pacote de mods personalizado, Stacia Expert 2, e o Ocultismo está incluído. Não consigo entender por que o minério não se revela ao usar os óculos, comer a fruta dos sonhos demoníacos ou usar a vara de adivinhação. Não posso ser o único com esse problema ainda.
I'm playing this modpack too and I can't find it in any way

**Comment by Kolchefen** [comment]
I was having this issue. I believe it is probably associated with the shaders you are using. I was using Complementary Reimagined and when I turned it off it worked.

Tenía este problema. Creo que probablemente esté relacionado con los sombreadores que usas. Estaba usando Complementary Reimagined y, al desactivarlo, funcionó.

**Comment by Brandao2006** [comment]
I was having trouble finding the ore in the stacia 2 expert modepack so I went to their Discord and they replied saying 
"The only thing that worked for me was to go into the occultism config (occultism-client.toml) and change "useAlternativeDivinationRodRenderer" to true" 
and it worked for me
