### ISSUE TITLE
Ethereal glass texture not connecting together properly.

### ISSUE THREAD

**Issue by Lord-Volkner** [AllTheMods/ATM-8#1131]
Sometimes it works fine. Mostly it does this:

![2023-03-24_13 30 47](https://user-images.githubusercontent.com/71194571/227610552-d8ffb9c5-ceeb-453d-8943-c01adc2cbc1c.png)

**Comment by VarianArdell** [comment]
I'm also having this problem, though seemingly worse as just nothing is connecting

**Comment by DevilMayCryIfrit** [comment]
I have the same issue it sometimes connects when I place a torch near the glass but breaks when I break the torch again

**Comment by DrymarchonShaun** [comment]
Seems this is an interaction between Rubidium and the ConnectedTexturesMod. Disabling Rubidium fixes it, with the downside of a loss in performance.

**Comment by beliboba** [comment]
@DrymarchonShaun can you explain a lil bit more how to do this? Same issue for me, just looks awful

**Comment by Lord-Volkner** [comment]
It will fix itself in time is what I found. Though is messes up again if there are any block updates beside the glass.

**Comment by DrymarchonShaun** [comment]
> @DrymarchonShaun can you explain a lil bit more how to do this? Same issue for me, just looks awful

rubidium-mixins.properties is a file in your instance's config folder, mine is at `/home/shaun/.local/share/PrismLauncher/instances/All the Mods 8 - ATM8/minecraft/config/rubidium-mixins.properties`, for example. Just find that file, open it in a text editor, and add `mixin.features.chunk_rendering=false`.

**Comment by beliboba** [comment]
It fixes itself on world rejoin, but error occurs again if nearby blocks are changed

**Comment by DrymarchonShaun** [comment]
> It fixes itself on world rejoin, but error occurs again if nearby blocks are changed

Is that after applying the fix?
