### ISSUE TITLE
1.0.14 - Crystall Staff Acceleration not saving

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-8#1132]
Hi.

Every time I change world  in my game, all machines that I have boosted with cryystal staff acceleration from roots are not saving and lose their effects.

**Comment by fkempf78** [comment]
This is a feature of roots, it should only work for a limited time. So the bug is now fixed, the acc. should only last for some  time.

**Comment by Mitchell5200** [comment]
Closing as working as intended
