### ISSUE TITLE
Update occultism to 1.73.2, fixing a server crash issue

### ISSUE THREAD

**Issue by Kakoen** [AllTheMods/ATM-8#1136]
In https://github.com/klikli-dev/occultism/issues/906, a server crash issue caused by a NPE was fixed. The fix version is 1.73.2, while ATM 8 v1.0.14 has version 1.73.0 bundled.

Please update Occultism to the latst 1.73.2 version.

**Comment by Mitchell5200** [comment]
we already plan to have 1.0.15 out by monday to address some other issues, any mods that have compatible updates will be updated

**Comment by Kakoen** [comment]
We upgraded our server to v1.0.15 today. Occultism has been updated to 1.73.2, and our crashing issue has been resolved. Hereby I close the issue.
