### ISSUE TITLE
Failed to synchronize registry data from server

### ISSUE THREAD

**Issue by KarmaiSAYIn** [AllTheMods/ATM-8#1142]
This is the same issue as #653, except I'm on Linux, so I can't use curseforge, the modpack version is 1.0.13, and the mod versions are as follows:
Mod Name | Server Has | You Have
Mystical Agriculture  | 6.0.8 | 6.0.8
KubeJS | 1902.6.0-build.142 | 1902.6.0-build.142

I'm running the client with multimc where I copied the mods from the server files into the instance mods directory, and copied the overrides directory to the instance directory.

Help would be much appreciated, thanks.

**Comment by Mitchell5200** [comment]
it's not just the mods that you need to copy, you also need `Config`, `Kubejs`, `Defaultconfigs`, and `packmenu`

**Comment by Jtmoney1342** [comment]
would this be different for windows?
