### ISSUE TITLE
Travel Anchors don't render when teleporting. 

### ISSUE THREAD

**Issue by GrimReaper1214** [AllTheMods/ATM-8#1143]
Modpack
ATM8

Modpack version
1.0.14

Log Files
No response

Describe the bug
Travel Anchors don't render when you try to teleport to them.

Steps to reproduce
Place a Travel Anchor
Name it
Try to teleport to it with a Travel Staff or with another Travel Anchor
It doesn't render

Expected behavior
It should render

Screenshots
![javaw_TlHqSh5WkN](https://user-images.githubusercontent.com/18587288/227820968-3cd54f55-fadb-48b8-b241-99f08dbf200d.png)

![javaw_ijhj1Zz8UT](https://user-images.githubusercontent.com/18587288/227820987-3241328b-57f7-43f4-aa4b-5de0b1f05c05.png)

Additional information
this issue also occurs when standing on the anchors

**Comment by Old-Man-D** [comment]
I am also seeing this on modpack version 1.0.13.  I have submitted an issue to the mod dev https://github.com/castcrafter/travel_anchors/issues/67

**Comment by Old-Man-D** [comment]
I have tracked this down via a binary search.  the Tempad mod seems to cause this

**Comment by superdusto** [comment]
For a workaround I was able to get this to work by enabling a shader pack that came with ATM8.

**Comment by Old-Man-D** [comment]
setting the tempad config to timedoorFancy=false in the tempad_client.json file fixes this for me.

**Comment by Mitchell5200** [comment]
Properly fixed with Tempad v1.4.5
