### ISSUE TITLE
Server doesnt have quests.

### ISSUE THREAD

**Issue by L4S7** [AllTheMods/ATM-8#1144]
I created this world in version 1.0.13. When updating to version 1.0.14, I made sure to create a different folder to avoid any issues with the world. I then dragged all the contents of the 1.0.14 server files into this folder. After agreeing to the EULA and starting up the world, I discovered that there are no quests when I access the quests tab in my inventory.

**Comment by bob-anthony** [comment]
"Mitchell52 — 03/03/2023 2:00 AM
two good general server update processes that i do are
1, fresh install each update keeping only the world folder and any custom configs,
or
2, deleting "mods, config, default configs, kubejs" from the server, and replacing fresh from the server zip, that one works well if there's no need to update forge for that update. "

https://discord.com/channels/254530689225981953/1015461480050733157/1081123898915049492

**Comment by four2day** [comment]
doing step two worked for me:
2, deleting "mods, config, default configs, kubejs" from the server, and replacing fresh from the server zip, that one works well if there's no need to update forge for that update. "

I didnt do the mods and it still worked
