### ISSUE TITLE
Client keeps crashing on 1.0.15

### ISSUE THREAD

**Issue by CyberWarden** [AllTheMods/ATM-8#1149]
The game crashed whilst rendering overlay
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing from class net.mehvahdjukaar.modelfix.ModelFix (net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing is in module minecraft@1.19.2 of loader 'TRANSFORMER' @40c76f5a; net.mehvahdjukaar.modelfix.ModelFix is in module modelfix@1.8 of loader 'TRANSFORMER' @40c76f5a)

**Comment by Mitchell5200** [comment]
client latest.log via https://mclo.gs/ please
