### ISSUE TITLE
Client keeps crashing on startup

### ISSUE THREAD

**Issue by iVemmi** [AllTheMods/ATM-8#1151]
Version: 1.0.15
The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ae2additions-common.toml of type COMMON for modid ae2additions
Full crash log: https://mclo.gs/JQQzHh9

**Comment by CyberWarden** [comment]
Sorry it looks is was me that caused the issue.  I had been using worldedit but it's causing a error now.
