### ISSUE TITLE
Starbunkle's dont like beds

### ISSUE THREAD

**Issue by Gumptionless** [AllTheMods/ATM-8#1153]
very none important report but for anyone who over uses starbunkles like me,
for some reason since 1.15 they no longer care about beds, if you assign them a bed they just wont use it ever and instead choose to stand by the storage they last interacted with,

gets funky when you have 3+ bunkles and they stand ontop of eachother and the top one cant get down

**Comment by drakray** [comment]
I got that in v.13 too
