### ISSUE TITLE
Mystical agriculture secondary drop chances

### ISSUE THREAD

**Issue by texis4** [AllTheMods/ATM-8#1157]
Something happened to the secondary drop chances.
Previously they were 20% if crop is on the respective tier, and 10% otherwise. Now it's 11% on respective tier, 1% otherwise.
Reverting this commit seems to f1x it: https://github.com/AllTheMods/ATM-8/pull/1083/commits/f3df304ffc46e457c010bbfe03a06c9fcf6e639f

**Comment by Mitchell5200** [comment]
yes, that was an intentional change by us, to cutoff t5/6/magical seeds from being duped on a massive scale
