### ISSUE TITLE
The QuarryPlus Workbench Plus is not craftable

### ISSUE THREAD

**Issue by Ferro-Giconi** [AllTheMods/ATM-8#116]
When checking in JEI, the recipe is blank.

**Comment by tpjham** [comment]
Works if you check on singleplayer, caused by #111

**Comment by Mitchell5200** [comment]
As stated in #111 Known Issue, only affects servers currently. Closing this Duplicate.

**Comment by Sl0ter** [comment]
i made a fix here for now. #123
