### ISSUE TITLE
Server crashes on going to nether or end.

### ISSUE THREAD

**Issue by Provello** [AllTheMods/ATM-8#1162]
Hey guys,

The server crashes every time you enter the nether portal or any other vanilla dimension.

**Comment by AbstractUmbra** [comment]
This happened to me too! No crash logs but the whole server halted and everyone got timed it. Had to ^C to get out of the console.

**Comment by Provello** [comment]
Exact same for me, my character would fall infinitely upwards, then crash out. Server becomes unresponsive and I have to Ctrl c to halt it

Many thanks
C
________________________________

**Comment by oXNoodleXo** [comment]
same

**Comment by Provello** [comment]
Steps to reproduce:

1. Create server on Ubuntu
2. Start server
3. Go to any dimensions
4. Crash

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

ARGS tested


#-Xms4G
#-Xmx12G
#-XX:+UseG1GC
#-XX:+ParallelRefProcEnabled
#-XX:MaxGCPauseMillis=200
#-XX:+UnlockExperimentalVMOptions
#-XX:+DisableExplicitGC
#-XX:+AlwaysPreTouch
#-XX:G1NewSizePercent=30
#-XX:G1MaxNewSizePercent=40
#-XX:G1HeapRegionSize=8M
#-XX:G1ReservePercent=20
#-XX:G1HeapWastePercent=5
#-XX:G1MixedGCCountTarget=4
#-XX:InitiatingHeapOccupancyPercent=15
#-XX:G1MixedGCLiveThresholdPercent=90
#-XX:G1RSetUpdatingPauseTimePercent=5
#-XX:SurvivorRatio=32
#-XX:+PerfDisableSharedMem
#-XX:MaxTenuringThreshold=1

-Xms2G
-Xmx8G
-XX:+UseG1GC
-XX:+ParallelRefProcEnabled
-XX:MaxGCPauseMillis=200
-XX:+UnlockExperimentalVMOptions
-XX:+DisableExplicitGC
-XX:+AlwaysPreTouch
-XX:G1NewSizePercent=30
-XX:G1MaxNewSizePercent=40
-XX:G1HeapRegionSize=8M
-XX:G1ReservePercent=20
-XX:G1HeapWastePercent=5
-XX:G1MixedGCCountTarget=4
-XX:InitiatingHeapOccupancyPercent=20
-XX:G1MixedGCLiveThresholdPercent=85
-XX:G1RSetUpdatingPauseTimePercent=10
-XX:SurvivorRatio=8
-XX:+PerfDisableSharedMem
-XX:MaxTenuringThreshold=1

**Comment by Provello** [comment]
Unfortunately crash logs folder is completely empty.

**Comment by noahonyejese** [comment]
check out this article: 

https://github.com/AllTheMods/ATM-8/issues/995

**Comment by Provello** [comment]
> check out this article: 
> 
> 
> 
> https://github.com/AllTheMods/ATM-8/issues/995

Good find, however personally won't be taking those steps. Have decided on a new mod pack in the meantime, would rather point out the bug, provide as much detail as I can and wait for an update, thanks though! Hopefully resolved then if this is a duplicate bug, hopefully any details I have provided help and can try provide more if needed. I haven't had this issue with other mod packs on the same hardware so there must be a Mod bug or something else, my thoughts were if dimensions are broke I didn't want to put more time in a pack where there are potentially other issues

**Comment by Mitchell5200** [comment]
Dev here, i have traced a cause the the mod "when Dungeons arise" (DungeonsArise-1.19.2-2.1.54-release.jar), the exact reason as to why is still under investigation, but for now you can safely remove the mod from your servers with no other issues.
Further investigation is ongoing as to why, before reporting to the WDA devs

**Comment by AbstractUmbra** [comment]
For those still suffering the issue, I found a fix but not a solution:

If you disable or increase the `max-server-tick` option in the `server.properties` file, and then load into the problematic dimension, and let the server process it, it will take time to process but it eventually loads the dimension and "removes" this problem.

I used 32GB of RAM and all of my 12 cores were around 40% usage, but the Nether finally loaded on my server and then I got an error message in console:-
`Server is 6348 ticks behind...`

Hopefully this helps anyone still persevering for now!
