### ISSUE TITLE
Apoth spawners no longer work

### ISSUE THREAD

**Issue by Gumptionless** [AllTheMods/ATM-8#1164]
for whatever reason the apotheosis spawners have stopped working, ive tried changing the mob in it, using a fresh spawner, using a creative mode made spawner, adding redstone power,
it just spins and nothing spawns

**Comment by Old-Man-D** [comment]
any chance you're in peaceful?

**Comment by Ravalli03** [comment]
Do you have a Mega Torch from Torchmaster with config set to stop spawners?

**Comment by DevilMayCryIfrit** [comment]
I'm using 2 spawners right now one for pillagers and one for iron golems and they both work fine.

**Comment by Gumptionless** [comment]
> 

no, im getting hunted by apoth mobs from way outside by base turning up at my door despite mega torches, so im assuming they upgraded their pathing and detection range, but yea, not on peaceful

**Comment by Gumptionless** [comment]
> 

i dont think i have one near, and i did have this spawner working fine in 1.10 (i jumped from 1.10 to 1.15)
But i will check

**Comment by Gumptionless** [comment]
ok its not the torches.... my mega mob blender is just unhappy

**Comment by DevilMayCryIfrit** [comment]
What are you trying to spawn and did you try an dragon egg upgrade?

**Comment by Gumptionless** [comment]
yup, dragon egg fixed it, must have been total coincidence that the mob eggs id used befor where fine in the biome, 
and i thought the generic vanilla creeper would be fine spawning in any biome but turns out that was zone restricted aswell, so yay dragon egg!
