### ISSUE TITLE
Allthemodium Paxel Compatibility

### ISSUE THREAD

**Issue by NoBar94** [AllTheMods/ATM-8#1165]
The Allthemodium Paxel doesn't allow all enchants it should - Boon of the Earth and Chainsaw are relevant and missing.
The Apotheosis Reforging Table is also considering the Paxel as a sword for the purpose of Prefixes

**Comment by Naireem-sudo** [comment]
Yes, same issue here.

**Comment by Mitchell5200** [comment]
it should be set as a pickaxe in apoth, as of 1.0.16
