### ISSUE TITLE
Infinite range and dimension card not working 

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/ATM-8#1166]
Infinite range and dimension card not working for refined storage, is this intentional or a bug? Version 1.0.15.

**Comment by PeaceIsBliss** [comment]
This usually happens to folks that dont supply enough power after inserting the card. It requires roughly 10k rf/tick to use these things. Upgrade power, issue goes away.

**Comment by DevilMayCryIfrit** [comment]
I have millions of rf in banks how do I not have enough power?

**Comment by PeaceIsBliss** [comment]
Just saying, make sure you have a power cable or energy cell or something attached that isnt basic tier. millions of rf is useless if it can only transmit 2k rf/t with a cheap cable. if that is NOT the case, than im not sure. In the process of moving my base now so, will test this in a few minutes when I plug myne back in

**Comment by DevilMayCryIfrit** [comment]
I'm using flux points with no limit still doesn't work.

**Comment by PeaceIsBliss** [comment]
Myne is working between dimensions just fine. What version ATM you using?

**Comment by DevilMayCryIfrit** [comment]
Version 1.0.15

**Comment by PeaceIsBliss** [comment]
And your putting the card in a Wireless Transmitter, not a Network Transmitter?

**Comment by DevilMayCryIfrit** [comment]
Advanced Wireless transmitter from RebornStorage

**Comment by DevilMayCryIfrit** [comment]
I found the problem it was the advanced

**Comment by PeaceIsBliss** [comment]
Oh... no idea than, I dont use that stuff, completely untrustworthy. Everything from 'Cable Tiers' is garbage too, never works. Just use the vanilla transmitter

**Comment by DevilMayCryIfrit** [comment]
It works with the basic wireless transmitter

**Comment by DevilMayCryIfrit** [comment]
Thanks for the help

**Comment by PeaceIsBliss** [comment]
No problem. Have fun!

**Comment by DevilMayCryIfrit** [comment]
If any modders for atm8 are read this please check the advanced wireless transmitter for not being comfortable with the dimension card
