### ISSUE TITLE
Botania Ring Of Thor is broken, possibly others.

### ISSUE THREAD

**Issue by PeaceIsBliss** [AllTheMods/ATM-8#1168]
Ring of Thor doesn't apply any HP, so far doesn't prevent drowning, fall damage, lava / fire damage. It's just useless garbage.

since 1.0.14 update

**Comment by Gumptionless** [comment]
Wrong ring?
Thats what ring of Odin does, Thor increases range of the Terra shatterer,
And i just tested my Odin and it works for the HP, not tested the other effects tho

Let me know if needed and ill test out the other effects

**Comment by PeaceIsBliss** [comment]
Your absolutely right, not sure where I went wrong here. I swear i had the Odin ring but now its Thor's, which seems unlikely a sudden bug. Ill do more research but thanks for pointing this out.
