### ISSUE TITLE
Allthemodium Alloy Paxel considered a weapon instead of a tool for Apotheosis Reforging

### ISSUE THREAD

**Issue by dragonkid828** [AllTheMods/ATM-8#1169]
I'm unsure if this is intended, considering the Mekanism paxels are considering tools rather than a weapon, but it's inconvenient because I've grown used to the benefits of the tool reforge enhancements on the paxel (torch placing, block drops teleporting to you, etc).

**Comment by Gumptionless** [comment]
Sadly its also considered a weapon for Blueskies so you cant cheese it for damage like i do with the atomic dissasembler,
Might be classed as a weapon to nerf it for that?
