### ISSUE TITLE
ATM 8 Crash to desktop cctweaked

### ISSUE THREAD

**Issue by Apallo** [AllTheMods/ATM-8#117]
When placing a cctweaked monitor on top of a computer (both non-advanced version) i get a crash to desktop, which continues to happen on restart.  The issue seems to be related to optifine/occulus, as turning the occulus mod off allows me to log in and remove the offending computer/monitor. Crash log attached.
[hs_err_pid2292.log](https://github.com/AllTheMods/ATM-8/files/9795558/hs_err_pid2292.log)

**Comment by Sl0ter** [comment]
i think it's related to the randering. try to change the config of Computer craft for monitor_renderer from "BEST" to "TBO"
