### ISSUE TITLE
Supplementaries lanterns interaction with minecolonies.

### ISSUE THREAD

**Issue by perennialpersephone** [AllTheMods/ATM-8#1171]
Requesting that a config change be made to Supplementaries to change from ON to NO_FIRE. Currently when a minecolonies builder upgrades a building with a lantern it causes the lantern to fall and set the building on fire, this issue happens EVERY upgrade at all tiers with any buildings that use wood as a main building block.

#Allows ceiling lanterns to fall if their support is broken.Additionally if they fall from high enough they will break creating a fire where they land
		#Allowed Values: ON, OFF, NO_FIRE
		fallin_lanterns = "NO_FIRE"

**Comment by DmitryScaletta** [comment]
+1
This is really annoying when half of your building is burned when upgrading.
I'd prefer to set this option to OFF.

**Comment by DmitryScaletta** [comment]
Here is a small demonstration of the problem:
https://youtu.be/7UO7AgTaWDk?t=1913

**Comment by Mitchell5200** [comment]
already implemented, closing
