### ISSUE TITLE
Server kicks all players when spawning in a new When Dungeons Arise structure (Recommendations?).

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM-8#1174]
Even before server opened (Bisecthosting 8gb server) when doing pregenn work with one other person when ever a When Dungeon Arise (WDA) structure spawns in all players get kicked. In the most recent I was able to see the log just before the kicks and noticed that the mod appears to scan 50 chunks for the generation. I don't know if this is standard to other structure mods, but I do know that WDA structures tend to be big/massive. I have copied and  pasted the log entry below. Just looking for recommendations to eliminate kicking everyone on the server when WDA new structures are made.

https://github.com/LunaPixelStudios/When-Dungeons-Arise/issues/1

[29.03 08:38:38] [Server] [asynclocator-1-thread-1/INFO] [br.as.AsyncLocatorMod/]: Async Locator -> Trying to locate TagKey[minecraft:worldgen/structure / dungeons_arise:explorer_maps/mining_system] in ServerLevel[Giggs ATM8] around BlockPos{x=83, y=177, z=-2340} within 50 chunks

**Comment by SpeedSlider** [comment]
It appears whenever the structures are loaded in everyone gets kicked. I was hoping it just happened on first time they were loaded. Pregenning doesn't prevent future kicks.

**Comment by AvrCdavr** [comment]
I believe this has also been making my server crash without making a crash log. Console says it found a dungeons arise dungeon and server instantly restarts.

**Comment by Kniyum** [comment]
Same issue on server 1.0.15: "Async Locator -> Trying to locate ... "
In my case, it happens when any player tries to open one specific chest in a dungeon.
