### ISSUE TITLE
Bug when changing dimension

### ISSUE THREAD

**Issue by SOTR654** [AllTheMods/ATM-8#1178]
1. Use any kind of means that changes your dimension.
2. The player will fall infinitely without dying.
3. Sometimes the world will load, but mostly not.

It happens no matter how long you have been in the game.
Log file: [latest.log](https://github.com/AllTheMods/ATM-8/files/11113279/latest.log)

**Comment by Mitchell5200** [comment]
Likely related to #995, #1162, fixes noted there
