### ISSUE TITLE
Server mod files mismatched compared to modpack mod files v1.0.15

### ISSUE THREAD

**Issue by Goldenolaf20** [AllTheMods/ATM-8#1179]
After creating a server using the "download server pack" option from the pack and hosting it on my server, I downloaded the modpack and attempted to run the modpack and connect to my server. When I did this I received an error of "Connection closed - mismatched mod channel list". 

Both the modpack as well as the server pack were downloaded today from curseforge. The modpack version that I am running is Forge 43.2.6, All the Mods 8-1.0.15. The server pack that I am running is also the 1.0.15 version. 

Any help would be greatly appreciated.

Log file: 
[latest.log](https://github.com/AllTheMods/ATM-8/files/11116903/latest.log)

(A screenshot of the connection failed page is included below.)

![ConnectionErrorSnip](https://user-images.githubusercontent.com/97612518/228986239-672ddb85-3fad-428a-abfa-1f5eba76b53e.PNG)

**Comment by Mitchell5200** [comment]
looking at your log, it looks like the server did not start with any mods in it's mods folder, Please check the server's mods folder, and provide server latest logs
