### ISSUE TITLE
Dark chunks cause by Integrated Dynamics Stuff(Maybe)

### ISSUE THREAD

**Issue by zilla0088** [AllTheMods/ATM-8#1182]
Had dark chunks issue . Single player world , happened in ver. 1.0.15(also .14) . 

I recreated the issue in a single player superflat world , by putting down some Integrated Dynamics stuff in a empty chunk and log out , the issue happens when I join in that world again .

I tried:
1)Erase worlds's cache data in the menu . -> Seeing no dark chunks first-time join in , but happen again after logout-login .
2)Remove ID stuff , and logout-login . -> No fix .
3)Cover ID stuff with ID's facade , and logout-login .  -> No fix .
4)Remove ID stuff then do method 1) . -> Fix . 

But I like Integrated Dynamics so much that I can't Not use it . Just want to report something I found . Wish it helps .

Pics(Not sure if this works):
[https://raw.githubusercontent.com/zilla0088/Pics/main/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20230331203047.png?token=GHSAT0AAAAAACA2QL66STMI5JHQ7HWB7GLOZBG3CDQ](url)
[https://raw.githubusercontent.com/zilla0088/Pics/main/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20230331203120.png?token=GHSAT0AAAAAACA2QL67CFIJP73RJ2KXIWBGZBG3CXQ](url)
[https://raw.githubusercontent.com/zilla0088/Pics/main/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20230331203158.png?token=GHSAT0AAAAAACA2QL66WKPHSRYLGCZQ4GKGZBG3C3A](url)

**Comment by popespydie** [comment]
Same issue. Hadn't made the connection to Integrated Dynamics until you said so. I just added another pipe yesterday and today when I logged in, that chunk was also dark.

**Comment by localzuk** [comment]
Seeing this exact same issue. Player it was affecting has removed all the ID stuff from their base, then restarting the server with --eraseCache option, and this remedied the issue on the server.

**Comment by Lightirius** [comment]
Same problem. Also buttons, pressure plates, some of the Create blocks get stuck in the affected chunks.
Removal of all Integrated Dynamics stuff and restart with --eraseCache seems to work

**Comment by Daverkex** [comment]
Hotfix:
1. Get from the RFToolsBuilder mod a Builder
2. Place the Builder
3. Put any shape
4. Cover all the chunk 16x16 with a long high (50 or more) in the shape
5. Render the preview in the builder and quit it again
6. Fixed!

**Comment by FierceManul** [comment]
Radon !

**Comment by FierceManul** [comment]
I try to replace Radon with Starlight, it works fine, but may cause your old world cant join.  need more test.
