### ISSUE TITLE
Holding Create wrench causes tps drops

### ISSUE THREAD

**Issue by TheBrodsky** [AllTheMods/ATM-8#1184]
**Steps to Reproduce:**
1. Hold "Wrench" item from Create in mainhand or offhand
2. Observe significant increase in tick time ('/forge tps' seems unreliable, we used Spark)

Not sure if this is a Create-specific issue or some kind of mod conflict. This issue was causing TPS drops for us on a server down to ~5 tps (from 20). It happens regardless of if any Create blocks or contraptions are in render distance or loaded.

**Comment by TheBrodsky** [comment]
Found out that the same thing happens when holding the Immersive Engineering hammer. Same conditions, same result

**Comment by EdrikP** [comment]
Hey, just commenting in case you haven't figured out already, or for future readers, but I'm 99% certain there is a mod incompatibility in the pack with integrated dynamics. Try remove/disable that if it's in the pack and see if it helps.
