### ISSUE TITLE
All the mods 8 Server suddenly keeps crashing

### ISSUE THREAD

**Issue by E1nMensch** [AllTheMods/ATM-8#1186]
Hello, my all the mods 8 server just started crashing, whenever someone trys to join.

Here is the Crashreport: https://mclo.gs/jyaWd51

The Server has 8gb of Ram.

I also downloaded the World and startet it in single player, and it worked there just fine.

Thanks in advance :D

**Comment by Chr0n4s** [comment]
Same for me. My server has 6 gb ram (80% usage).
