### ISSUE TITLE
Nether dimension missing @update

### ISSUE THREAD

**Issue by PsytranceGuru** [AllTheMods/ATM-8#119]
My cousin and i made an atm8 server, and after updating it to the newest version our netherportal is stuck in animations and theres not even a nether dimension file.

**Comment by pk11online** [comment]
same problem end all so missing version 0.1.5

**Comment by pk11online** [comment]
still missing on 0.1.6

**Comment by pk11online** [comment]
delete level.dat and level.dat_old
