### ISSUE TITLE
Ad Astra oil not generated by fluid drills

### ISSUE THREAD

**Issue by claudiomerli** [AllTheMods/ATM-8#1190]
Hi, first of all thank you for your incredible modpack! 
I think have met all requirements for Ad Astra oil generation with Fluid Drills but it seems not work:
![image](https://user-images.githubusercontent.com/71256977/229347350-2bbf0dad-83d2-4b82-b35c-02e7b11b541c.png)
![image](https://user-images.githubusercontent.com/71256977/229347441-745d4260-5953-46de-b04b-d6a4e785f690.png)
![image](https://user-images.githubusercontent.com/71256977/229347405-17e7aabb-2465-45dc-83a4-2c93b53d307d.png)
![image](https://user-images.githubusercontent.com/71256977/229347391-931f0535-9a3b-4a73-88ac-f7a5fd5f0c3f.png)

**Comment by claudiomerli** [comment]
Fixed updating to 1.0.15

**Comment by Gumptionless** [comment]
I have the same issue in 1.0.15
trying to get crude oil, got 12 drills, 1 laser base with the grey lense, set to 40 depoth,

not sure entirely how it works as its the first time ive used this thing, but the drills themselves are showing their own coordinates instead of the ones they are drilling for me so im guessing they arnt reading the laser bases coordinates

**Comment by claudiomerli** [comment]
@Gumptionless leave some screenshot

**Comment by Gumptionless** [comment]
the fluid laser base doesnt have power but the arrow is still filling across and there isnt an internal power storage  like other machines so i am assuming it doesnt need power?

**Comment by claudiomerli** [comment]
Seems you're in the wrong biome, and using the wrong lens. To get crude oil you have to use a Black Lens (the grey is used for Oil). About biome you need to stay in one of these
![image](https://user-images.githubusercontent.com/71256977/230037354-02c4d73e-f420-4232-80a9-4c90bb7774fe.png)

**Comment by Gumptionless** [comment]
I knew it would be something obvious...
thank you, id better move my setup,

**Comment by Mitchell5200** [comment]
It currently does not matter what oil you get, as the Ad Astra machines can use any #forge:crude_oil

Ah, i see it's mostly a setup issue. If this is now resolved i can close it
