### ISSUE TITLE
Apoth spawners changed with an egg dont work

### ISSUE THREAD

**Issue by Gumptionless** [AllTheMods/ATM-8#1192]
So any spawner i place works aslong as its collected with silk touch, which is fine,

Any upgrades i make to it with apotheosis take effect and is all good,

But if i change what it is spawning with an egg then the spawner nolonger functions, nothing will spawn atall,

Anyone else had this issue?

**Comment by DevilMayCryIfrit** [comment]
What are you spawning? And did you try using a dragon egg?

**Comment by Gumptionless** [comment]
not tried a dragon egg,

Ive tried changing it to pigs, creepers and slimes,
just the normal mob eggs,

It worked fine in 1.10 becuase i made it an enderman spawner and a villager spawner, but since jumping to 1.15 its not worked atall even if i change location, new spawner, changed lightlevels or anything else i can think off,
It shows the new mob in the cage, lights up with the fire particles , just no spawn actuly happens

**Comment by DevilMayCryIfrit** [comment]
Well for slimes you need to be in a swamp or slime chunk. And if it is a modded creeper the need the biome for the specific creeper to spawn in. When it comes to things like pigs they usually need grass and the right light level. Vut I don't know your setup to be sure that is why I suggested the dragon egg it allows the spawners to ignore any spawn conditions the spawned creatures may have.

**Comment by DevilMayCryIfrit** [comment]
Also if the spawner is in claimed chunks that may be stopping the spawns too. Like with the wither builder will not spawn a wither in claimed chunks.

**Comment by Gumptionless** [comment]
i 100% misunderstood you when you said dragon egg, i thought you meant dragon egg as a spawn egg....

The dragon egg fixed it, i was using normal creepers so i didnt think it would matter, turns out ive just been picking mobs with really specific spawn conditions.

TDLR: spawners are fine, i am stupid
