### ISSUE TITLE
Server Crashing Because of Sculk Snapper spawned using corail tombstone mod

### ISSUE THREAD

**Issue by Parkster090** [AllTheMods/ATM-8#1193]
Hey we are getting the same issue as below wondering if someone would go through my srash log and see what chunk/entity file i need to get rid of in my world file
[crash-2023-04-02_14.56.37-server.txt](https://github.com/AllTheMods/ATM-8/files/11133451/crash-2023-04-02_14.56.37-server.txt)

**Comment by Parkster090** [comment]
Found the Chunk is 34, 4, -103 but im not sure how to get into the file and edit it

**Comment by jinks** [comment]
> Found the Chunk is 34, 4, -103 but im not sure how to get into the file and edit it

Not sure how/if you handled that issue already, but in `world/serverconfig/forge-server.toml` there are two settings to auto-remove broken ticking block and normal entities on load. (Heed the warnings!)
