### ISSUE TITLE
log stripper 9000 not working (create mechanical saw)

### ISSUE THREAD

**Issue by froggyflips** [AllTheMods/ATM-8#1194]
the create mechanical saw cannot be filtered to produce only stripped vanilla logs, and when unfiltered, will make hollow logs from the twilight forest, wood walls from absent by design, and only sometimes (up to 1/2) make the intended stripped logs. this seems like an issue with create, as the filter cannot be used to selectively make stripped logs. Only stonecutter recipes can be filtered, and the other two outputs are stonecutter recipes. the other recipe with create (deployer with axe) will eat allthemodium axes after only one use. I have not tried using farmer's delight to automate stripped logs, but I do not want to have to rely on bees or manual labor to make my stripped logs.

**Comment by lanord** [comment]
Did some test and wood axe is not destroyed like other axes. So could use deployer with wood axe to automate the stripped log with create mod

**Comment by enigmaquip** [comment]
What do you mean that you can't filter the saw to only stripped logs? You can, and it works as it should. With either the normal filter set to the stripped logs, or the attribute filter set to #forge:stripped_logs
