### ISSUE TITLE
Laggy maps

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/ATM-8#1198]
I'm going around to collect quartz from the balloon dungeons and for some reason every time I collect a map from a chest in one I get a lag spike so bad it says waiting for server for a good 2 minutes. Sometimes I have to relog
Just to get it to respond while the map in question does not load and just says Working unknown map.

**Comment by Jeronimo585** [comment]
@DevilMayCryIfrit . I have the same problem. Maps from loot that have an unknown map name and lag the game to the point of restarting it. Did you already get some help with this issue?

**Comment by DevilMayCryIfrit** [comment]
No you are the only comment on this post at this time
