### ISSUE TITLE
Ultimine keybind not working

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/ATM-8#12]
Ultimine keybind does not appear in the controls config. 
If I put key_key.ftbultimine:key.keyboard.r into options.txt it gets ignored and removed. 

Version is 1900.3.4-build.58

**Comment by DAmNRelentless** [comment]
https://github.com/FTBTeam/FTB-Mods-Issues/issues/451

**Comment by Seegras** [comment]
It has been fixed as of 0.0.7, maybe earlier.
