### ISSUE TITLE
ComputerCraft Advanced Monitor Crash

### ISSUE THREAD

**Issue by Jonz00r** [AllTheMods/ATM-8#120]
A friend and I are testing out ATM8 and crash whenever we enter this one village. The logs seem to indicate something to do with computercraft.
 v 0.1.3

[Normal Log](https://hastebin.com/uhogijebok.yaml)

[hs_err_pid11556.log](https://github.com/AllTheMods/ATM-8/files/9796689/hs_err_pid11556.log)

**Comment by Jonz00r** [comment]
#109
#117

**Comment by Sl0ter** [comment]
I found a workaround. I change the config from ComputerCraft for monitor_renderer from "BEST" to "TBO" 
no crash for now.

**Comment by Jonz00r** [comment]
> I found a workaround. I change the config from ComputerCraft for monitor_renderer from "BEST" to "TBO" no crash for now.

I'll try when I get home.

**Comment by Jonz00r** [comment]
> I found a workaround. I change the config from ComputerCraft for monitor_renderer from "BEST" to "TBO" no crash for now.

This works for this issue.

**Comment by whatthedrunk** [comment]
Added the config change in the newest update. When CC updates we will remove the client config.
