### ISSUE TITLE
Space Fire Proof Unit doesn't work

### ISSUE THREAD

**Issue by claudiomerli** [AllTheMods/ATM-8#1202]
I crafted and installed the module from Giselle's mod but it doesn't work at all. Going to mercury I got heat damage. Using Ad Astra's Netherite Suit it's actually the only solution

**Comment by Mitchell5200** [comment]
Do you have the netherite oxygen can in your inventory as per what the dev has stated in an issue post on their Repo?
https://github.com/gisellevonbingen/Minecraft-Ad-Astra-Giselle-Addon/issues/22

**Comment by claudiomerli** [comment]
Thanks! It works!
