### ISSUE TITLE
[1.0.15] duplicating animated blocks creates corrupt entities that crash the server

### ISSUE THREAD

**Issue by FlorianTyroller** [AllTheMods/ATM-8#1208]
Steps to recreate:
- use the Glyph of Animate Block from Ars Nouveau to convert any block to an entity
- catch it with a Mob imprisonment Tool
- duplicate it with the Mob Duplicator from industrial Foregoing
- corrupt entity spawns, instantly crashes the server, when the chunk with the corrupt entity is loaded the server crashes instantly again

Example crasgh log of recreation in Single Player attached
[crash.txt](https://github.com/AllTheMods/ATM-8/files/11170569/crash.txt)

**Comment by GitpocJones** [comment]
I crashed the server with an animated block by summoning it with a receptacle I found in a chest from the mod Corail Tombstone.

**Comment by James103** [comment]
What do you get if you try running `/summon ars_nouveau:animated_block` (without specifying any NBT)? Does the command error (can't summon entity) or does the server crash the next tick?
