### ISSUE TITLE
Refined Storage EXTRA DISKS: Storage Part recipes incorrect

### ISSUE THREAD

**Issue by Ihavethekids** [AllTheMods/ATM-8#121]
The recipes for all the storage parts up to the 4096k storage part only shows the recipe being 4 Processors (Plus bucket when looking at the fluid storage part recipes (256k and 1024k storage parts are fine))

![2022-10-17_02 27 06](https://user-images.githubusercontent.com/75661210/196104515-da5c92e9-88b3-4ce6-8735-94440085fb12.png)
![2022-10-17_02 27 10](https://user-images.githubusercontent.com/75661210/196104518-5e326b95-fda1-4204-bd1f-d6912cfcb803.png)
![2022-10-17_02 27 17](https://user-images.githubusercontent.com/75661210/196104519-0b198e1d-0396-49c6-a515-e5080dbb6456.png)
![2022-10-17_02 27 21](https://user-images.githubusercontent.com/75661210/196104521-241665da-8f9e-4776-a1d7-40212b8d9b3a.png)
![2022-10-17_02 27 22](https://user-images.githubusercontent.com/75661210/196104523-f6989bab-ded2-43b4-99a1-49a50db28a93.png)
![2022-10-17_02 27 27](https://user-images.githubusercontent.com/75661210/196104526-61d4f5d9-c1c2-4f8b-8888-0ef8380749d4.png)

**Comment by Mitchell5200** [comment]
As stated in #111 Known Issue, only affects servers currently. Closing this Duplicate.
