### ISSUE TITLE
My server is crushing 

### ISSUE THREAD

**Issue by rakvvv** [AllTheMods/ATM-8#1214]
my world was corrupted and i dont know how to repair it .Here is the paste bin with crash report form my server on which i downloaded this modpack: https://pastebin.com/2cEJzNpe . 
Here i also add the debug.log if needed:https://drive.google.com/file/d/1wPaWLqQmPjbO65vUyUh1prPipEioocQE/view?usp=share_link

Please help me with this.

**Comment by Mitchell5200** [comment]
looks like some part of integrated dynamics has broken, if you can, try removing those parts from your world and then report to the mod dev so they can take a look and fix it
https://github.com/CyclopsMC/IntegratedDynamics/issues

**Comment by rakvvv** [comment]
the problem is that i cant load the corrupted chunk, if i do then the server crushes
