### ISSUE TITLE
IF's Enchantment Applicator capping enchantment levels

### ISSUE THREAD

**Issue by ChloeDawn** [AllTheMods/ATM-8#1215]
**Pack version:** [1.0.15](https://www.curseforge.com/minecraft/modpacks/all-the-mods-8/files/4461163)

When applying an enchantment that is higher than the vanilla limit, it is capped on the resulting item.
This behaviour can be changed in Industrial Foregoing's miscellaneous config.
I'm unsure if this is intentionally left as-is in the pack.

See https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1288

**`config/industrialforegoing/machine-misc.toml`**
| `[MachineMiscConfig.EnchantmentApplicatorConfig]`
|- `ignoreEnchantMaxLevels = false` -> `true`

**Comment by Mitchell5200** [comment]
Intentionally changed as otherwise it ignores the Apotheosis limits and goes beyond acceptable levels

**Comment by ChloeDawn** [comment]
If that is the case I would consider it to be a bug that IF doesn't support increased limits and will discuss it with the developer.

**Comment by Mitchell5200** [comment]
It did at one stage accept the Apoth limits, but that somehow broke back in 1.18, so now we set it to off for the packs

**Comment by Shadows-of-Fire** [comment]
For other things to work with apoth limits I have to target their classes with my transformer.  The changes are minimal, but I would need to know what classes to hit.
