### ISSUE TITLE
Help shroombee

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/ATM-8#1220]
Hi I would like to know how to get a shroombee
 The only way I can find is with treats that have the shroombee DNA or by converting it from a other type of shroombee. Please help.

**Comment by DWX12** [comment]
Sometimes they are hard to come by, but I have come across plenty of them flying against the ceilings of crimson and warped forests. Once you have a means of flying around (such as a Hexerie or Evilcraft broom), you'll have an easier time finding them. Bees, and sometimes nests, can appear on Journey Map as white'ish dots if you have it set to show icons.
