### ISSUE TITLE
Visual glitches related to PneumaticCraft 

### ISSUE THREAD

**Issue by kazum1kun** [AllTheMods/ATM-8#1229]
Hello,

We ran into 2 visual bugs in PCR. 

1. When there are multiple Pressure Gauge Tube Module in a vicinity, a yellow triangle appears and blocks the view. Adding more modules yields more triangles.
2. The pressure chamber appears to be leaking in the inside. I checked and there are no leaks, but whenever I get close to the chamber a smoke appears.

These two issues can be seen by everyone in the server. Please refer to the screenshot below.

![2023-04-11_11 35 10](https://user-images.githubusercontent.com/4069734/231258919-9d7d9ec0-d4ae-4228-a9cf-d8338db8bbb9.png)

Any help would be appreciated. Thank you!

**Comment by TronWoWGamer** [comment]
still happening ATM10
