### ISSUE TITLE
[All the mods 8 1.0.15] Botania flowers are purchasable from the Market

### ISSUE THREAD

**Issue by DJteaCosy** [AllTheMods/ATM-8#1233]
Botania functional and generating flowers are purchasable from the Cooking for Blockheads market for 1 emerald each. I'm guessing this has to do with them having the flower tag, but it's completely busted to be able to buy things like entropyniums and agricarnations for a single emerald, given that the recipes for some (like the former) require diamonds and other expensive resources.

**Comment by Mitchell5200** [comment]
Sounds like when you updated to .15, your Kubejs files were not updated, as we have already fixed this, and the only botania flowers are the mystical color ones

**Comment by DJteaCosy** [comment]
ah understood, I'll have a look when I next get the chance and revert - thanks for the quick response!
