### ISSUE TITLE
I need help, Server crashes from the shadows i think.

### ISSUE THREAD

**Issue by Yoloaa-laang** [AllTheMods/ATM-8#1238]
The game crashed whilst ticking block entity
Error: java.lang.ClassCastException: class shadows.apotheosis.spawn.spawner.LyingLevel cannot be cast to class net.minecraft.server.level.ServerLevel (shadows.apotheosis.spawn.spawner.LyingLevel is in module apotheosis@6.0.3 of loader 'TRANSFORMER' @47b4ac83; net.minecraft.server.level.ServerLevel is in module minecraft@1.19.2 of loader 'TRANSFORMER' @47b4ac83)

**Comment by Yoloaa-laang** [comment]
I am in a mob farm, the game crash instantly when I open the world

**Comment by Mitchell5200** [comment]
Full crashlog via https://mclo.gs/ please

**Comment by Yoloaa-laang** [comment]
@Mitchell5200 this page says I need to remove a mob spawner, but how can I do it if when i start the world it crashes.

[crash-2023-04-14_14.53.46-server.txt](https://github.com/AllTheMods/ATM-8/files/11233021/crash-2023-04-14_14.53.46-server.txt)

**Comment by Yoloaa-laang** [comment]
It crashes because I put a hedge spider spawner, I put peaceful mode instantly and I removed the spawner, ty for the help.

**Comment by Mitchell5200** [comment]
yeah, we did blacklist those mobs from being put into spawners, but twilight still needs to fix the cause on their side.
there's some instructions in this thread that can help if you get stuck and cannot set to peaceful
https://github.com/AllTheMods/ATM-7/issues/1570
