### ISSUE TITLE
game crashes on launch 

### ISSUE THREAD

**Issue by Jostend050308** [AllTheMods/ATM-8#1242]
when i try to start atm8 it crashes here is the crash loghttps://mclo.gs/c8hQmkU

**Comment by PersiflageTheNinth** [comment]
in your error

> Caused by: java.nio.file.FileSystemException: C:\Users\********\AppData\Local\.ftba\instances\86c40cc6-f7ae-44ab-9cb6-8b256dad3e6b\config\thermal-client.toml: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird

That says it couldn't write to a file because you already had another copy of that modpack open

**Comment by Jostend050308** [comment]
oh okya how can i fix it

**Comment by BalloS-Twok** [comment]
Hi,
how did you solve the problem?
I get the same on a fresh installation.
