### ISSUE TITLE
Bad FPS when using Create with Shaders

### ISSUE THREAD

**Issue by CyrolX** [AllTheMods/ATM-8#1247]
Hi,

I know this is not a bug but intended behaviour in regards to Flywheel. Flywheel's optimizations are turned off when Shaders are active, leading to crazy frame drops for even simple machines using Create. There might be a way to fix that by using the Iris & Oculus Flywheel Compat Mod listed here: https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat

I tried installing it myself, yet it didn't do what it should do. There might be Mods interfering with the fix, which are as of yet unknown (I might try to find out what mod is the culprit here), as this mod worked on my custom pack server with only Create and a few other Mods like Farmer's Delight.

If it would be possible to get this fix enabled, Create would actually be playable with Shaders on.

**Comment by CyrolX** [comment]
Follow up: This is kind off odd... So the mod really does work, yet for some reason Flywheel uninstalled itself (or I am just blind. If it really did uninstall itself its even a wonder the pack started) and for some reason this led to the mod not working (if Flywheel really did uninstall itself that is). There is also this annoying sequence of things you need to do in order to get this to work:

1. Install the Compatibility Mod
2. Start ATM8
3. Disable shaders
4. Join a world
5. Enable Shaders
6. (Perhaps optional) Set the Flywheel Backend Engine to Batching

If these steps aren't followed the graphics of the Create Blocks will glitch out completely

I don't know what other kind of crashes or possible bugs/glitches this combination may cause, the only thing I know at the moment is that it works. Here's a comparison:

Before adding the compatibility mod:
![2023-04-18_01 28 48](https://user-images.githubusercontent.com/31181255/232635904-b851b62a-1c98-4ddf-9e7b-9b55932aa775.png)

After adding the compatibility mod and following the above steps:
![2023-04-18_01 52 51](https://user-images.githubusercontent.com/31181255/232635938-f202f757-90ed-456f-a5c3-1f71e9c4d788.png)

**Comment by CyrolX** [comment]
After some further testing it may not work 100% of the time and may cause graphical issues even when following the steps. This is so weird.

**Comment by Sooperfish** [comment]
> for some reason Flywheel uninstalled itself

to answer this, create comes bundled with Flywheel now, so the mod is deprecated
