### ISSUE TITLE
Issues with Drawers from Sophisticated Storage

### ISSUE THREAD

**Issue by bbf** [AllTheMods/ATM-8#1248]
Hello,

I have a drawer system in which each drawer refuses to take items it already has (and is not full), unless I remove some first and attempt to re-insert. That happens in any variations of: no upgrades, void upgrade, storage upgrade, void + storage upgrades.

I noticed that there are updates to sophisticatedcore that seem to be related to this issue:
https://www.curseforge.com/minecraft/mc-mods/sophisticated-core/files/4471231
Although that is not the latest version.

Can we please update to the latest sophisticarecore and sophisticatestorage mods?

**Comment by bbf** [comment]
I failed to mention that I'm running version 1.0.15. 

I tried updating core/storage/backpack to the latest versions, and it did not fix the issue.
I'll open a bug on their project.

**Comment by bbf** [comment]
Reported here:
https://github.com/P3pp3rF1y/SophisticatedStorage/issues/160

**Comment by Mitchell5200** [comment]
You reported a Functional storage drawer to the the Sophisticated storage dev? wrong mod unfortunately.

**Comment by bbf** [comment]
Oh, sorry, my bad. Let me try to update functional storage and check their issues :)

**Comment by ariosos** [comment]
I've had similar issues, too, and I can't quite get the hang of the configuration tool (still prefer Storage Drawers).
