### ISSUE TITLE
[Bug] JEI Pull Crafting Recipe for Ad Astra rocket in RS Terminal results in client disconnect

### ISSUE THREAD

**Issue by JustAnotherGhostName** [AllTheMods/ATM-8#1250]
ATM8 Version: 
1.0.14, although it has been observed in multiple versions. 

Description:
When you look up the recipe for a Ad Astra rocket in JEI in a RS terminal, and you press the + to pull the items to craft it in the terminal, you get a client disconnect while on a server due to JEI attempting autofill the recipe with more than 9 item slots. 

Steps to reproduce:
1) Open up a crafting terminal from RS
2) Ideally have the parts for a rocket in the system
3) Search in JEI the recipe for said rocket
4) Click the plus button to pull the items to craft the rocket
5) Disconnect with a `java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9` error as a result of trying to put more than 9 items in the crafting tables array (which has a maximum index of 8)

Expected Results:
Ideally JEI should identify that you cannot autofill a Ad Astra Rocket into a RS Terminal so it dosnt try access a slot in the array that is out of bounds.

**Comment by jarl9** [comment]
Hey, I was wondering if you ever found a fix for this. I accidentally came across this exact problem when I hit the autofill for crafting button. I was disconnected from the server and have been unable to reconnect since. I know you posted this in April, so you might not remember the solution if you had one.

**Comment by JustAnotherGhostName** [comment]
There isn't really a solution other than JEI patching it (IE, making it so
you can't click on that in that terminal), or maybe one of the other 2
authors (Which I doubt). It's an extremely minor bug, and realistically the
solution is just not to try and autofill a crafting recipe that you
cant craft in a normal 3x3 recipe slot.

If JEI does decide to work on it, id imagines again they would consider it
a super minor bug as it only affects the client as well on top of this
niche thing. I could be wrong about their priorities of course, but TLDR,
just don't try and auto-fill a recipe that doesn't fit.
