### ISSUE TITLE
[Suggestion] Remove the Connectivity mod

### ISSUE THREAD

**Issue by JustAnotherGhostName** [AllTheMods/ATM-8#1253]
Any way we could get the connectivity mod removed as part of an update? Not certain how much "good" the mod brings, however, it does cause a decent bit of harm. Notably issue #930 and another bug I reported to them, https://github.com/someaddons/connectivity/issues/54 . 

The netty io error with connectivity in the issue reported to them occurs several times a week, more so annoying than anything as a restart will temporarily alleviate it, or sometimes it just fixes itself on its own. 

Regardless, I dont think the good outweighs the bad with the mod in the pack in my opinion.

**Comment by JustAnotherGhostName** [comment]
Update: It appears they claimed to have fixed the issue now in the bug report, so hopefully instead of removing the mod we can just update it.

**Comment by Mitchell5200** [comment]
Yep, will be updated along with any other mods that have available updates, next update
