### ISSUE TITLE
Client crash when hovering over Ars Nouveau Spellbooks

### ISSUE THREAD

**Issue by PureIsntHere** [AllTheMods/ATM-8#126]
After updating to modpack version 0.1.4 , The game will crash when hovering over the archmage spellbook in your inventory with your cursor.

It looks like the issue is related to a patchouli update

crashlog:
[crash-2022-10-17_15.41.43-client.txt](https://github.com/AllTheMods/ATM-8/files/9804776/crash-2022-10-17_15.41.43-client.txt)

**Comment by PureIsntHere** [comment]
edit: Looks like it is any of the books from Ars Nouveau

**Comment by NunbearTWITCH** [comment]
This is a killer as it happens to everyone on server.  had to restore server to yesterdays backup to get it back.

**Comment by PaintingPapa** [comment]
This is a 100% occurrence client crasher. Anyone have a workaround or fix?

**Comment by NicoVIII** [comment]
It seems to happen also on other Ars Nouveau items as well. I had today crashes while hovering over Source Gems and Magebloom Fiber.
I guess this is a crash which happens on every item from Ars Nouveau with a Patchouli Tooltip.

**Comment by AlexisTheCultLeader** [comment]
This issue is being reported more and more, and not just with this modpack I'm sure. Reference case number #136 for some solutions there.

**Comment by indygwyn** [comment]
Verified that just updating the ars jar fixes this crashing issue.

**Comment by whatthedrunk** [comment]
Fixed in today's update thanks.
