### ISSUE TITLE
Mystical Agriculture Seeds Hard to Get

### ISSUE THREAD

**Issue by GianBala83** [AllTheMods/ATM-8#1266]
When i started playing the modpack, i could use Mysitcal's Bone Meal to grow the Mystical's seeds and get more seeds easily, but now i have to use packs of Mysitcal's Bone Meal to get 1 extra seed

Is it a bug or balance for the mod?

if the first case, please fix it

**Comment by kissiesformyfishies** [comment]
btw this was the error thing
The game crashed whilst rendering overlay
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing from class net.mehvahdjukaar.modelfix.ModelFix (net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing is in module minecraft@1.19.2 of loader 'TRANSFORMER' @28367da7; net.mehvahdjukaar.modelfix.ModelFix is in module modelfix@1.8 of loader 'TRANSFORMER' @28367da7)

**Comment by Mitchell5200** [comment]
Seed duping has been intentionally disabled in some spots, and reduced in other spots, for balance reasons
