### ISSUE TITLE
game is broken when loading up?

### ISSUE THREAD

**Issue by kissiesformyfishies** [AllTheMods/ATM-8#1267]
i just updated the mods, and when i went to go play, my game looked like this:
![Screenshot (5)](https://user-images.githubusercontent.com/131623089/233868879-776b2417-7a46-4898-99a4-34d7c5443e98.png)
does anyone else have this issue or know how to fix it?

**Comment by kissiesformyfishies** [comment]
btw the crash report looks like this
The game crashed whilst rendering overlay
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing from class net.mehvahdjukaar.modelfix.ModelFix (net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing is in module minecraft@1.19.2 of loader 'TRANSFORMER' @28367da7; net.mehvahdjukaar.modelfix.ModelFix is in module modelfix@1.8 of loader 'TRANSFORMER' @28367da7)

**Comment by Mitchell5200** [comment]
Client latest.log via https://mclo.gs/ please, not the crash report

**Comment by Miguel-fell** [comment]
> Client latest.log via https://mclo.gs/ please, not the crash report
Hi im experiencing a similar issue it seems. 

https://mclo.gs/FXd5ncu

**Comment by Mitchell5200** [comment]
@Miguel-fell  I need to see the Latest.log file, not the crash report please
