### ISSUE TITLE
Invalid Player Data in Single Player World

### ISSUE THREAD

**Issue by ReiNAce** [AllTheMods/ATM-8#1269]
Hello,

I am using ATM 8 v1.0.13. After connecting 1 RS importer at the back and 1 RS exporter at the side of obsidian furnace, my game crashed. I can no longer access my single player world after restarting minecraft, showing an "Invalid Player Data" error during the world loading phase. Then, I updated my game version to ATM 8 v1.0.16 but the problem persists.
I do not know the cause of the crash if it is because of a mod or other causes.
Can someone help me read and understand the logs and crash report of my world? And what could be the possible solution for me to recover my world and my progress?
Here is the crash report/log files before I update to v1.0.16:
[crash-2023-04-24_04.09.24-server.txt](https://github.com/AllTheMods/ATM-8/files/11305444/crash-2023-04-24_04.09.24-server.txt)
[2023-04-24-1.log.gz](https://github.com/AllTheMods/ATM-8/files/11305464/2023-04-24-1.log.gz)
[2023-04-24-2.log.gz](https://github.com/AllTheMods/ATM-8/files/11305465/2023-04-24-2.log.gz)
[2023-04-24-3.log.gz](https://github.com/AllTheMods/ATM-8/files/11305466/2023-04-24-3.log.gz)

Here is the log after update:
[latest.log](https://github.com/AllTheMods/ATM-8/files/11305467/latest.log)

Thank you for any help.

**Comment by Hamyd1** [comment]
Did you find a fix? my game just crashed randomly too and i have the same issue.
