### ISSUE TITLE
Major Crafting Duplication Bug - ATM 8 1.0.16

### ISSUE THREAD

**Issue by TomasQuraishi** [AllTheMods/ATM-8#1270]
When Right clicking or Shift + Right clicking the crafting output in a crafting grid, the player receives a full stack of whatever the user crafts. 

Example:

Crafting an iron block with 9 iron ingots in a crafting table then Right clicking or Shift + Right clicking the output (the iron block) will result in getting 64 iron blocks.

This happens in single player and multiplayer.

The attached video shows the bug with crafting planks in the players inventory.

The first planks crafted are with left click and the second lot of planks are made with right click.

https://user-images.githubusercontent.com/19708405/233880725-94b250cb-7073-4f3d-ad0e-028dbc934de8.mp4

**Comment by Penhry** [comment]
I'm experiencing it on my client as well after updating from 1.0.15 to 1.0.16 and also on a fresh install. This seems like a pretty major bug that needs looking into.

**Comment by Mitchell5200** [comment]
Yes, we are already aware of this and are speaking to devs about it

**Comment by Mitchell5200** [comment]
Patched in 1.0.17
