### ISSUE TITLE
Crashing at Start up

### ISSUE THREAD

**Issue by A009i8** [AllTheMods/ATM-8#1272]
https://mclo.gs/wIC9E6X

here is the last crash log idk why its chrashing hoping for help

**Comment by Mitchell5200** [comment]
can i see the file Latest.log please, and what pack version

**Comment by A009i8** [comment]
and version 1.0.17 but 1.0.15 is working fine

**Comment by Mitchell5200** [comment]
okay, GD launcher did not update the forge version, change forge to 43.2.8

**Comment by A009i8** [comment]
> okay, GD launcher did not update the forge version, change forge to 43.2.8

its working thanks :)

**Comment by A009i8** [comment]
now my world is crashing xD i cant xD for real xD

**Comment by A009i8** [comment]
https://mclo.gs/76jjBTx Crash log
https://mclo.gs/cUY39Ac latest log
