### ISSUE TITLE
World is crashing

### ISSUE THREAD

**Issue by A009i8** [AllTheMods/ATM-8#1273]
https://mclo.gs/76jjBTx Crash log

https://mclo.gs/cUY39Ac latest log

**Comment by A009i8** [comment]
pls fix you can have extra mods even in 1.0.16 is crashing my world i stay at 1.0.15

**Comment by Mitchell5200** [comment]
more logs please @A009i8

**Comment by A009i8** [comment]
I dont have more this are the same xd its crashing in World loading readiring

**Comment by Mitchell5200** [comment]
Don't worry then , i've just tested it as i was not gonna wait, Project EX is incompatible with forge 43.2.8, report that crash to them.

**Comment by A009i8** [comment]
i can roll back xD
