### ISSUE TITLE
Weired thing on my crosshair?

### ISSUE THREAD

**Issue by LamaTheReal** [AllTheMods/ATM-8#1274]
Since the new version i have a weired thing near my crosshair 24/7 and its rly annoying (adhd) 
![image](https://user-images.githubusercontent.com/130768059/234013964-c076dea1-6c13-4625-87a5-20b29f64f08e.png)
![image](https://user-images.githubusercontent.com/130768059/234013976-6363d1c6-d6e7-40c5-aa59-2b6951a464ec.png)

**Comment by Sproinks** [comment]
Same since update.  Seems to go away with Shaders off.  I tried many shaderpacks and they all seem to do it.  I'm going to try updating the underlying shader mods.

**Comment by Sproinks** [comment]
Workaround: hide your Ars armor with the cosmetic armor mod in your character screen (put nothing in each slot and click the little box).  Your armor will be hidden and the bug on the cursor will be gone.
