### ISSUE TITLE
Can't connect Refined storage network between normal world and Compact dimension

### ISSUE THREAD

**Issue by Natomik** [AllTheMods/ATM-8#1275]
Hello,
I had recently updated my server from 1.0.13 to 1.0.17 and I can't reach my network in the compact dimension since.
I have claimed and force loaded the area.

**Comment by CMDRSlyraccoon** [comment]
I also have this happening

**Comment by Xenxes** [comment]
This happens after a server restart. Temporary solution is to pull out and insert the network card into the network transmitter

**Comment by Natomik** [comment]
Looks like it's working now but I had to change all the receiver and transmitter just pull out and in the network card didn't worked for me.
