### ISSUE TITLE
Mob Grinding Utils - Dreadful Dirt

### ISSUE THREAD

**Issue by RHelm3** [AllTheMods/ATM-8#1279]
Since the new update (version 1.0.17) Dreadful Dirt from Mob Grinding Utils no longer spawns any mobs at all. I have even went into a creative world to test it out, and still nothing.

**Comment by RHelm3** [comment]
Sorry, hit the wrong button. I meant to say is that since the new update (version 1.0.17) Dreadful Dirt from Mob Grinding Utils no longer spawns any mobs at all. I have even went into a creative world to test it out, and still nothing.

**Comment by Mitchell5200** [comment]
Related to https://github.com/vadis365/Mob-Grinding-Utils/issues/249
