### ISSUE TITLE
Items can be duped by right clicking crafted item.

### ISSUE THREAD

**Issue by zendabbq** [AllTheMods/ATM-8#1280]
1. Arrange a recipe in a crafting grid
2. Right click the resulting item
3. All items in the grid are consumed, you obtain 64 (or a full stack) of the resulting item regardless of the amount consumed.

**Comment by Mitchell5200** [comment]
Pleas state your pack version, as this is already fixed in 1.0.17.

**Comment by zendabbq** [comment]
Ah, didn't know another release came out so quick. Thanks.
