### ISSUE TITLE
Game crashed on startup

### ISSUE THREAD

**Issue by chalazae** [AllTheMods/ATM-8#1288]
Been playing ATM 8 for about 2 weeks now with no problems. All of a sudden the game crashes on startup. I tried updating Java to the current version but it did nothing. If anyone can help it would be appreciated
[crash report 4 26.txt](https://github.com/AllTheMods/ATM-8/files/11336356/crash.report.4.26.txt)

**Comment by zephoxe** [comment]
I have exactly the same problem ! what is the solution please ? (chalazae if you find the solution let me know please).

**Comment by nexusGM** [comment]
I have the same issue on two different computers.

**Comment by nexusGM** [comment]
I think there are quite a few people with this same issue.

https://www.reddit.com/r/allthemods/comments/12zrdbw/crashing_issue/

**Comment by zephoxe** [comment]
message on discord :

if the pack is crashing on startup but you were able to play it before, then its probably your drivers. (because lots of ADM users suddenly couldn't play ATM8.)
If so, use ADM adrenalin to update them

**Comment by chalazae** [comment]
Thank you so much!

**Comment by Destinyking1010** [comment]
I am having that problem to but I am using nvidia gforce not ADM
