### ISSUE TITLE
Bug duplication item

### ISSUE THREAD

**Issue by Flashacker-Neo** [AllTheMods/ATM-8#1290]
It's possible to duplicate items with "Witch Hazel Drying rack" from Hexerei.

Just place the item on a wall, then put any item on it and when you break the rack the items on it are doubled.

**Comment by Mitchell5200** [comment]
The crafting recipes for those three drying racks are already disabled in 1.0.16/17, the Hexerei dev is already aware of this as well
Code https://github.com/AllTheMods/ATM-8/blob/6320e84f40b215dbed70bcc4952b4aed56a5121a/kubejs/server_scripts/modpack/bugs.js#L4-L6
Hexerei issue post https://github.com/JoeFoxe/Hexerei-1.19/issues/36
