### ISSUE TITLE
Exit Code 1 on Startup

### ISSUE THREAD

**Issue by iamVormi** [AllTheMods/ATM-8#1294]
I have been able to play with no problems and then the day the 1.0.17 update came out I cannot launch my game. (I did not immediately update to 1.0.17 but it was still crashing on the previous version 1.0.15)

[latest.log](https://github.com/AllTheMods/ATM-8/files/11346305/latest.log)

I own a server for me and my fiance to play on and it's a huge bummer that we aren't able to play together now. Please help!

**Comment by Hyskill** [comment]
I can't launch my game.. the launcher start, and after loading I have a crash with "Exit code 1"

**Comment by iamVormi** [comment]
I was able to solve the problem on my end at least. The computer with the issue is running with AMD so i downloaded AMD Adrenalin and updated all the software. Boom. Fixed.

**Comment by Hyskill** [comment]
Same, thanks @iamVormi
