### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by AxWONDERxPNUT** [AllTheMods/ATM-8#1298]
whenever i try to run the startserver.bat the command prompt spits out this info
was wondering if anyone know what to do to fix it 
[issue.txt](https://github.com/AllTheMods/ATM-8/files/11349644/issue.txt)

i am currently trying to use this server file Server-Files-1.0.17.zip

**Comment by Mitchell5200** [comment]
Wrong java version, install and use java 17
