### ISSUE TITLE
Dreadful Dirt Not Spawning in range of mega torch

### ISSUE THREAD

**Issue by coldfire80** [AllTheMods/ATM-8#1300]
I am playing 1.0.15 and hadn't played since 1.0.15 was current so I updated and now dreadful dirt spawns nothing when in range of a mega torch. Is this intended? Can i change it in configs? Couldn't find the setting in torchmaster configs and I don't know where to find the mob grinding utils config file. Thanks for any help you can offer.

**Comment by Mitchell5200** [comment]
Duplicate of https://github.com/AllTheMods/ATM-8/issues/1279, Related to https://github.com/vadis365/Mob-Grinding-Utils/issues/249
