### ISSUE TITLE
Minecraft Crash Report - java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Slymix98** [AllTheMods/ATM-8#1304]
Hello members and ATMTeam!
Sorry for my dummy letter, but i really need for help. Here is the probelm: I love playing minecraft, epecially when someone can put all my favourite mods together. I cound not play Minecraft because of my bad PC config last year, but now I have the problem solved. The pack works fine, but yesterday it suddenly shuted down with this crash report.
[crash-2023-04-27_00.14.03-server.txt](https://github.com/AllTheMods/ATM-8/files/11356858/crash-2023-04-27_00.14.03-server.txt)

The only change I did with the pack was adding 3 mods: ProjectE, Project Equvivalance and Equipement Compare. Unfortunately, I cannot play without ProjectE because it helps me to save a lot of time. I have a full-time job, I think you understand my deed. Is Minecraft crashes because of my changes or maybe I did something wrong while setting the pack? 

Hope I wrote everything clear, because English in not my native language.

**Comment by Mitchell5200** [comment]
Project Equivalence is a 1.12 mod, i assume you then mean Project Expansion, if so, remove it as it's incompatible with forge 43.2.8, and you cannot change the forge version as other mods need that forge version, or they'll crash.

**Comment by Slymix98** [comment]
> Project Equivalence is a 1.12 mod, i assume you then mean Project Expansion, if so, remove it as it's incompatible with forge 43.2.8, and you cannot change the forge version as other mods need that forge version, or they'll crash.

Thank you for replying! I am sorry, i meant Equivalent Additions (https://www.curseforge.com/minecraft/mc-mods/equivalent-additions). It is an addon for ProjectE and it version is compatable with Minecraft and forge version.

**Comment by Mitchell5200** [comment]
After re-checking your crash report, you do also have Project Expansion, remove that and report the crash to that dev
https://github.com/DonovanDMC/ProjectExpansion/issues
