### ISSUE TITLE
Beacons only work when placed at or above y=1

### ISSUE THREAD

**Issue by AlisAquilae** [AllTheMods/ATM-8#1305]
As is stated in the title, I ran into a potential issue regarding beacons. They only seem to work for me when being placed at or above y=1 (the beacon block specifically, the base does not matter)

Steps to reproduce:
1: Start a new superflat world
2: Place a grid of any beacon-accepted blocks such that when the beacon is placed on top, it is situated at y<1
<img width="934" alt="image" src="https://user-images.githubusercontent.com/80721939/235244978-16c5f0e2-9e82-4649-abb6-a18e220cb5d4.png">
3: Right click on the beacon. It will not show a beam coming from it, and will not allow you to select a buff, even when the sky is clear.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/80721939/235245047-8ab85d61-f3b9-4fa5-abab-06c79d862c8f.png">
4: Now place a grid of any beacon-accepted blocks such that when the beacon is placed on top, it is situated at y>=1
<img width="416" alt="image" src="https://user-images.githubusercontent.com/80721939/235245178-9ee83575-30f4-47d2-b3d4-d77ff20644f3.png">
5: Right click on the beacon. It will now function properly
<img width="372" alt="image" src="https://user-images.githubusercontent.com/80721939/235245250-406bac10-c01c-4366-90cb-2c5cc4def7fe.png">

A couple of notes acquired from me doing some trial and error:
- The size of the base does not matter
- The material of the base does not matter
- It is not a visual glitch, since the UI does not allow for inputs at all. I tried the same steps without shaders as well and got equal results
- I did not modify the installation by adding new mods

I do not know whether this is a feature or a bug. I did some searching online but I could not find anything regarding this being known to originate from any mod included in the modpack. Moreover, it seems like a weird thing to be a feature. 

Of course, I am more than willing to supply any details or files if that helps in some way.

Thanks in advance!

**Comment by Mitchell5200** [comment]
Cause identified, quark's "Beacon Redirection" setting, we'll have that off in the next pack version
