### ISSUE TITLE
Modular Router and FTB chunk bug [1.0.15]

### ISSUE THREAD

**Issue by davidlee0512** [AllTheMods/ATM-8#1306]
Activator Module from Modular Router will not work if the chunk is claimed, either in a team or not.

[This is a video I recorded for demonstrating the bug](https://youtu.be/x255WC7KIRA)

**Comment by enigmaquip** [comment]
have you tried the security upgrade?
![image](https://user-images.githubusercontent.com/6134440/235320745-5b0e2ada-d3c3-40f3-b9e4-c1045c35fdc8.png)

**Comment by davidlee0512** [comment]
It works, thanks for helping
