### ISSUE TITLE
Hostile Neural Networks displaying mobs to kill all the time

### ISSUE THREAD

**Issue by greatmonkey** [AllTheMods/ATM-8#1310]
I updated the pack to the current version 1.0.17 and now the Hostile Neural Networks models display all the time on the upper left of the screen, even when they are not in my inventory.  I think what happen was in version 1.0.16, I was farming some mobs and died then the models got deleted some how after I recover my grave.

**Comment by Mitchell5200** [comment]
Hostile Neural Networks also adds a curio slot, check that for the learner that's stuck in your inventory

**Comment by greatmonkey** [comment]
Well did not know it could be a curio slot.  Thanks for the tip
