### ISSUE TITLE
[ATM 1.0.15-1.0.17] Client crash on startup with exit code: 1

### ISSUE THREAD

**Issue by CLASIX** [AllTheMods/ATM-8#1313]
[Latest.Log (MC Logs)](https://mclo.gs/YPB2FJL)

I first noticed the issue when I updated from ATM .15 to .17. I then tried to install a new profile with the latest version. Still crashes on startup with an exit code of 1. I did some research and found a post on reddit with a similar issue, the fix for them was to update GPU drivers. I was one version out of date, so I updated to Nvidia 531.68 to no avail. I have tried launching the pack with 8, 12 and 14GB of RAM. I eventually caved and tried to go back to .15, where I am now experiencing the same issue with that version as well. Nothing has changed with my pc between the time of .15 actually working and now, besides the latest driver update and windows 11 build. 

![111](https://user-images.githubusercontent.com/48968557/235375051-88ac84ec-91a8-444c-a24f-1ad9eb41f4b1.png)

**Comment by vadcx** [comment]
This is not the full log, it's only the part which Minecraft and mods produced. You need to provide the full log where the Java VM printed the error as well.

> ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0

You are showing the wrong (system default) java too.

**Comment by CLASIX** [comment]
yeah idk thats not very helpful. I just used a different launcher and it worked fine. didnt change java either and it worked fine.
