### ISSUE TITLE
Refined Storage grids look empty

### ISSUE THREAD

**Issue by Bluexin** [AllTheMods/ATM-8#1316]
Similar to #230 . All my grids look empty, but it does autofill crafts (even though they show red in jei) though it doesn't allow me to start autocrafts for them. I tried replacing all the RS blocks, disabling the connection to the drawer controller, to the crafters, removing the disks, nothing does it.
Any idea on how to fix this ?
I'm also not finding any errors in the console.
ATM8 1.0.17
Probably linked to refinedmods/refinedstorage#3502

**Comment by Bluexin** [comment]
I managed to fix it by picking up all my RS stuff and deleting the following files in `<save folder>/data` : 
 - refinedstorage_networks.dat
 - refinedstorage_nodes.dat
 - refinedstorage_tracker.dat
 - SecurityFrequencyHandler.dat
Note that I was able to keep refinedstorage_disks.dat so no need to get everything out of the system first. When inspecting the first 3 they had empty lists after picking up all of the RS stuff. Not sure the 4th one is related but it looked like it could be so I reset it too.

**Comment by Snowgnome** [comment]
when you say picked up all of the refined storage things, do you mean you broke your entire network apart and them deleted the files, or is it just the controller you have to break

**Comment by Bluexin** [comment]
@Snowgnome I broke everything, as I only had a small network. These files are basically caches for the network state, so you could experiment but I strongly recommend backing up before !

**Comment by Snowgnome** [comment]
@Bluexin i think i fixed it by just using an armory cabinet? from functional storage with an external storage(high priority) to storage nbt items
