### ISSUE TITLE
Mahou Tsukai Innate Cap wont go over 200

### ISSUE THREAD

**Issue by R3dPlayz** [AllTheMods/ATM-8#1319]
I am playing the ATM8 modpack and wanted to get the Morgan sword with a high damage.
The problem is that Caliburn cant go over the 200 Innate Cap. I tried it with Smite V and even Smite X (Mods allow it to go so high)

Everytime i throw the Diamond Sword with Smite into the Lake i only get a 100 Innate Cap. By adding nether stars (even with 3 stacks) i only get the Cap to 200 but never higher.
Throwing Caliburn with Smite on it into the Lake only gets higher Attack Damage.

So I stated looking on the internet. Some said that it was changed from nether stars to Vibranium - Allthemodium Alloy Blocks, some said you need the ATM Star.

Tested it in Creative but nothing worked. I got over 30k mana and making the sword only takes 5k-10k 

In the Mahou Tsukai Book it only says "maybe there are some items you could offer to the lake with Caliburn".

Now i wonder if there even is an item that works.

Yt vids that are like 7 months ond use nether stars to get the Innate Cap realy high.

Modpack version 1.0.17

**Comment by Mitchell5200** [comment]
Completely intentional pack change by us to limit the morgan and caliburn.

**Comment by R3dPlayz** [comment]
Thats kinda sad...

But i guess a 10k Damage sword is a little to strong.

Thanks

**Comment by Mitchell5200** [comment]
just FYI, the original mod default cap was 5 million

**Comment by R3dPlayz** [comment]
Is there a way for me to remove or edit the cap? If i want to have the OP sword again?
