### ISSUE TITLE
Server Crash Bug

### ISSUE THREAD

**Issue by RealCrius** [AllTheMods/ATM-8#1323]
Hey I am writing this from my phone but I found a bug that instantly crashes the server I was able to reproduce it easily. 

Dispensing a flint and steel unto a unlit campfire 

Strange right? I mean this is vanilla mechanics we are talking about which means I got no idea what could cause it.

**Comment by scootmando** [comment]
Flux-infused shield, excavator, hammer and more in Redstone Arsenal, causes crash upon trying to place in reforging table & smithing table
