### ISSUE TITLE
Botany Pots produce Ars Nouveau source when full

### ISSUE THREAD

**Issue by ChloeDawn** [AllTheMods/ATM-8#1327]
The event that the script uses, `CropDropEvent`, is specifically for collecting the crops *to be* dropped, and doesn't indicate growth. Botany pots attempt to output to their inventory every 5 seconds, and during this phase fire the event to determine the output. This results in the script allowing pots to generate source every 5 seconds when full and technically not growing.

**Comment by icha-senpai** [comment]
i may not understand why this is an issue, could you please elaborate?
