### ISSUE TITLE
Grammar mistake in "Honey Treat" quest

### ISSUE THREAD

**Issue by vadcx** [AllTheMods/ATM-8#1329]
https://github.com/AllTheMods/ATM-8/blob/d42420b46af7faff54e4ffb01293a08a4c61cd4e/config/ftbquests/quests/chapters/productive_bees.snbt#L831-L840

>"In Productive Bees, you don't spend most of your time flying around trying to find certain bees."
"Instead, **you spawn them *in using* Nests** with &6Honey Treats&r."
"With these, you'll create yourself some Nests and right click them with the treats to lure Bees in."
"Make sure to check out which biome you need to be in to lure in the right bees!"

What is "in using" supposed to mean here? I have no idea about this mod to provide a suggestion.

**Comment by alfredggttv** [comment]
Instead of finding the bees in the wild, you can actually spawn them by using the nests. I can remove "in" to clarify here.
