### ISSUE TITLE
silent gear causing big FPS drops

### ISSUE THREAD

**Issue by xSKILLZXx7697** [AllTheMods/ATM-8#1332]
hi, so i started a new ATM8 world, doing normal stuff, then when i turned my stone tools into the silent gear version, my game fps would tank to 20-30 fps, i later confirmed this when i threw them in lava and the fps immediately returned to 100-120 fps and then made more of the tools and the trend continued, so i have basically confirmed the lag is coming from them silent gear tools, i thought i would report it

**Comment by xSKILLZXx7697** [comment]
i then made a new world and tried it again and yep it was the same

**Comment by Somberous** [comment]
I am experiencing the same issues here. Could not figure out what was causing the FPS issues, but noticed it got significantly worse whenever opening my inventory, which had Silent Gear tools and armor. I removed them and back to normal FPS.

**Comment by Hexx13** [comment]
The same issue here locks me to about 30 fps while having them in inventory in multiplayer.

**Comment by Pixeluted** [comment]
Already made issue on the the mod issue site
https://github.com/SilentChaos512/Silent-Gear/issues/602
