### ISSUE TITLE
Copper doesn't go in Alchemy Bench

### ISSUE THREAD

**Issue by BaronVonHansa** [AllTheMods/ATM-8#1335]
The JEI says to put copper / oxidized copper in the Alchemy Bench (which is named Philosopher's table in the JEI), but it doesn't accept it
![2023-05-05_22 24 59](https://user-images.githubusercontent.com/72192066/236561933-a1912c0c-ebc1-4453-9165-9de219cd9da5.png)
![2023-05-05_22 24 52](https://user-images.githubusercontent.com/72192066/236561939-571b2475-800f-4751-b9f4-e3e64b506fd7.png)

**Comment by Mitchell5200** [comment]
Waxed copper, not normal copper
