### ISSUE TITLE
Chisel Factory Blocks

### ISSUE THREAD

**Issue by korczivo** [AllTheMods/ATM-8#1336]
Hi, kindly asking if there is possible to add factory blocks for ATM8? In the mod pack, there is Rechiseled mod, but there aren't any factory blocks, there are available in Chisel Refabricated, but if I tried to add this mod it doesn't work. 

https://www.curseforge.com/minecraft/mc-mods/factory-blocks

**Comment by Mitchell5200** [comment]
No, that's a fabric mod.

Mod suggestions in #3

**Comment by korczivo** [comment]
So there is no options for get factory blocks in ATM8? @Mitchell5200
