### ISSUE TITLE
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by larholl** [AllTheMods/ATM-8#1337]
Hoping for help with the above error in ATM-8, Seems to occur when attempting to place Minecolonies structures?

[crash-2023-05-06_19.28.06-client.txt](https://github.com/AllTheMods/ATM-8/files/11413571/crash-2023-05-06_19.28.06-client.txt)

**Comment by enigmaquip** [comment]
Have you tried updating your pack? You appear to be on a fairly old version based on your logs
