### ISSUE TITLE
Mod version mismatch for client and server for 1.19-0.17 

### ISSUE THREAD

**Issue by gentlewatcher** [AllTheMods/ATM-8#1338]
silent gear version on server pack for the 0.17 of the pack is outdated and mismatched to the client download.

**Comment by Mitchell5200** [comment]
No? according to my files (release files), both the server and client packs for pack version 1.0.17 have silent-gear-1.19.2-3.2.5.

any logs that you have via https://mclo.gs/ please

**Comment by gentlewatcher** [comment]
my bad somehow got the 1.0.5 version im so sorry.
