### ISSUE TITLE
Ability to switch between multiple recipes missing after update to 8-0.1.5

### ISSUE THREAD

**Issue by Fuzzock** [AllTheMods/ATM-8#134]
Since updating to 8-0.1.5 the ability to switch between multiple recipes has disapeeared.

Examples can be seen with mods Construction Wands, and Structurize

Construction Wands:
https://prnt.sc/MAT2teX0pTdJ

Structurize
https://prnt.sc/vPD7QPn050Oh

This is seen in both SP and MP

Ian...

**Comment by So1embum** [comment]
Polymorph doesn't seem to be compatible with FastWorkbench/FastFurnace. There's already a github issue with them to have it fixed. https://github.com/illusivesoulworks/polymorph/issues/188

**Comment by Fuzzock** [comment]
I can confirm that removing FastWorkbench & FastFurnace resolves the issue on SP not test on MP yet but expect the same results

![Capture 5](https://user-images.githubusercontent.com/69691591/196639192-0b337f57-8bbe-42b5-9fc0-3a0ed115dfa3.PNG)

Ian...
