### ISSUE TITLE
100% UI thing

### ISSUE THREAD

**Issue by slithens** [AllTheMods/ATM-8#1341]
![what is that](https://user-images.githubusercontent.com/75280566/236703489-3cbd9966-bd3a-49a9-a0d0-9b0e6e898fd5.png)
can anyone tell me what is causing this to pop up in the middle right hand of the screen? i'm on a server and everyone else is also seeing this and we cant figure out what is causing this or how to remove it. it seems to randomly add stuff to the "list" at random.

**Comment by icha-senpai** [comment]
in your quest book, lower right hand corner, there's a pin marker...unclick it and it should go away,

**Comment by slithens** [comment]
it wasn't that. it was on disabled mode, but i looked at the individual quest and THAT was pinned. unclicking that did solve the issue. Thanks for your help!
