### ISSUE TITLE
Crash when Small Ships attempts to handle blazes in the nether?

### ISSUE THREAD

**Issue by shinji257** [AllTheMods/ATM-8#1348]
Mods added: 
AI Improvements
Chunky
incontrol
Item Blacklist
Luck Perms
MC2Discord
Permission Levels
WorldEdit

Issue:
This is the best I can determine as I'm not the player triggering it.  On our server when a blaze is rendered it seems that Small Ships is failing to handle it properly.  Attached is a crash log from the server.

[crash-2023-05-08_13.49.17-server.txt](https://github.com/AllTheMods/ATM-8/files/11421847/crash-2023-05-08_13.49.17-server.txt)

**Comment by Mitchell5200** [comment]
That error starts with Canary, we removed that mod many versions ago. try removing that first.

**Comment by Mitchell5200** [comment]
Small ships now removed in 1.0.18
