### ISSUE TITLE
CTD after about a minute loaded into game

### ISSUE THREAD

**Issue by Kaiagarro** [AllTheMods/ATM-8#135]
With or without shaders I CTD. I have played several hours without having any issue but noticed it after I started collecting Dark Ore from Evilcraft.
[crash-2022-10-18_12.14.53-client.txt](https://github.com/AllTheMods/ATM-8/files/9814429/crash-2022-10-18_12.14.53-client.txt)

**Comment by NicoVIII** [comment]
The crash log looks like this is caused by the same issue described in #126.

**Comment by whatthedrunk** [comment]
Fixed in today's update thanks.
