### ISSUE TITLE
Atm8 single player blue skies nature dungeon and struckture compass

### ISSUE THREAD

**Issue by SignuSSnipeS** [AllTheMods/ATM-8#1353]
Hello,
I can not find nature dungeon on blue skies everbright world. I spent 2 hours flying around looking for it and it didn't generate even once. I tried to use structure compass but it doesn't work on any structure.
Can anyone help me?

**Comment by bearded-tomato** [comment]
Also to add to the above, structure compass does not appear to be working in 1.0.17 for ancient pyramids, I have not tried other structures.
![pyramid](https://github.com/AllTheMods/ATM-8/assets/73724848/37792470-252c-4f79-b341-ddd03f371e76)
