### ISSUE TITLE
Refined Storage Network Transmitter/Receiver bug

### ISSUE THREAD

**Issue by ITWastrel** [AllTheMods/ATM-8#1357]
Since the latest patch, after world load refined storage network receivers do not function until a network card is removed, added or replaced.

My scenario:
I have a mature RS network containing at least six network transceiver sets. The system also has a pair of infinite storage disks and multiple crafters, bells, and whistles.

On loading the world, all network receivers do not function. they are lit up, graphically displaying they should be working, but nothing connected actually works.

This condition persists on all network receivers until a new network card is installed, at which time all RS networks are back instantly.

Every time I load my world I have to remember to activate my network, This means opening a transmitter and popping the card out and back.

This behavior is new with the V. 8-1.0.17

**Comment by bearded-tomato** [comment]
Also using V. 8-1.0.17
Experiencing the exact same bug.

**Comment by ibrudiiv** [comment]
Similar random situations with external storages. I end up breaking and re-placing the controller and everything is back in order.

**Comment by bearded-tomato** [comment]
updating this issue is still occurring in ATM8 - 1.0.19b

**Comment by RazeTM** [comment]
Same bug over here

refinedstorage-1.11.6

**Comment by lord248** [comment]
Same here

**Comment by janiswehen** [comment]
Same here

**Comment by lesterktm** [comment]
Same here. Keeps causing my fissile fuel machine setup in a compact machine to no longer get items and stop producing.
