### ISSUE TITLE
Mekanisms Configurator is not working.

### ISSUE THREAD

**Issue by Lord-Volkner** [AllTheMods/ATM-8#1361]
Shift right clicking in wrench mode no longer picks up machines or pipes. Right clicking no longer configures the sides of a machine.

Actually, right clicking on a machine in any mode rotates the machine.
Shift right clicking on a machine in any mode now does nothing.

edit: Turns out that holding something in the left hand was the problem. I don't know how to delete this, or I would. Sorry about the bother.

**Comment by KagamiR99** [comment]
да то оказалась проблемой второй руки из за предмета в ней убрать предмет и все заработает
