### ISSUE TITLE
AllTheModium nugget needed to craft salvager

### ISSUE THREAD

**Issue by SirCammelot** [AllTheMods/ATM-8#1369]
i have run into multiple low/medium tier recipes where you need AllTheModium ingots or nuggets to craft them.
what i can see it should be a semi endgame ore. 

the one i have run in to it especially is the salvager from silent gear that a mining gadget that need a blank upgrade module that need AllTheModium nuggets. this to me just seems to expensive to be intention

link to pics of the recipe

https://imgur.com/a/2Xtql54

**Comment by Mitchell5200** [comment]
Yes, there are several intentional gated recipes throughout the pack
