### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by Fastro** [AllTheMods/ATM-8#137]
Modpack version: 0.1.5

The game crashes after 20 seconds, judging by the logs, because of Mekanism... What to do about it? :с
[crash-2022-10-19_04.31.50-server.txt](https://github.com/AllTheMods/ATM-8/files/9816126/crash-2022-10-19_04.31.50-server.txt)

upd. I think I understood the problem. Building farms with pots is not the best idea, because the mekanism mod is starting to give a crash.

**Comment by Vasa200** [comment]
I'm getting crash to desktop when I put filled Silent Gear took kits or tools in my inventory crafting grid.

I made a better tool kit and after I filled it, then put it back into my grid to repair my tool, crashed as well.  This is an every time occurance.
