### ISSUE TITLE
Crash after killing Wither Skeleton

### ISSUE THREAD

**Issue by praydan** [AllTheMods/ATM-8#1370]
https://pastebin.com/QCKG0q3j

My guess is it's because of the player's Axe but I'm not sure, his axe is an Allthemodium axe with apotheosis upgrades:
https://imgur.com/a/bzq4Uhf
I am using the last modpack 1.0.18.

**Comment by praydan** [comment]
Just had a crash killing a wither skeleton in The Other:
https://pastebin.com/SYpEku5Q

**Comment by k8thekat** [comment]
I have this exact same issue on our server.

Here is another crash report.
[crash-2023-05-23_22.45.30-server.txt](https://github.com/AllTheMods/ATM-8/files/11550996/crash-2023-05-23_22.45.30-server.txt)

**Comment by icywhisker-official** [comment]
I've had several crashes in regards to the wither skeletons. I didnt start having crashes until after I added a bunch of enchantments on my warden sword that werent there before. the only one I had before was capturing. I have 2 or 3 different crash detectors that help prevent the game from fully crashing and there have been 3 different types of crash. here is one of the logs https://bytebin.lucko.me/Vibmvuj2Bn

**Comment by naeast** [comment]
![sword](https://github.com/AllTheMods/ATM-8/assets/140998428/10843d0a-236b-4870-8c1a-583b3d702ad5)
I am having the same issue crash was related to a "Ticking entity" and was caused by a java.util.ConcurrentModificationException.
