### ISSUE TITLE
Warden Pickaxe not Counting as Netherite Tier

### ISSUE THREAD

**Issue by realSamuuu** [AllTheMods/ATM-8#1371]
I wanted to upgrade my pickaxe as far as I could at that moment and the Warden Stuff looked pretty interesting so I wanted to try it out so I made the pickaxe, enchanted it etc. Then I wanted to mine some AllTheModium Ore which requires a Tier of Netherite or higher to be mined and the Warden Pickaxe didnt tick off the box in WAILA neither did it drop anything when breaking the Ore.

**Comment by Zarkazm** [comment]
Still issue in ATM8 v1.0.21b.

![2023-07-05_21 22 27](https://github.com/AllTheMods/ATM-8/assets/10002661/0de66893-1488-4893-b31a-c040463c7097)
![2023-07-05_21 22 31](https://github.com/AllTheMods/ATM-8/assets/10002661/e98ea59c-cc5c-4b6e-b786-c53d7bf2ce85)
