### ISSUE TITLE
Falling Anvil enchantment Bug 

### ISSUE THREAD

**Issue by Meisterhulki** [AllTheMods/ATM-8#1377]
If you have an Item with an enchantment and a gem with + Level of existing enchantment on it. Then you get a book with the combined Level of both. This allows you to get Fortune XXX and so on, for example.

**Comment by alfredggttv** [comment]
This has been identified as an issue with the mod Super Factory Manager, and the dev is aware of this.

**Comment by Mitchell5200** [comment]
and is already fixed
