### ISSUE TITLE
NoMoWanderer sign doesn't seem to work on 1.0.18

### ISSUE THREAD

**Issue by praydan** [AllTheMods/ATM-8#1378]
Since the update, wandering traders started spawning again in my base even though I still have the sign placed outside

**Comment by Whimsy85** [comment]
Charm not working either.

**Comment by zrieprakis** [comment]
Confirming - Sign, charm, and rug are all not working as intended.

**Comment by LittleNyanCat** [comment]
Yup, slaughtering the trader every other day is starting to get a bit old

**Comment by nmiell** [comment]
In addition to all of the above, I'm seeing Wandering Traders spawn next to existing Wandering Traders, and AFAIK in (unmodded) Minecraft, new Traders shouldn't spawn at all if there is an existing Trader in a loaded chunk.

**Comment by zrieprakis** [comment]
It doesn't seem as if anyone has posted this as an issue to the modder's / mod's github page.  Just did so.  May help with getting this noticed.

**Comment by cosmoderp** [comment]
Left my test world running to see if both are broken.  the trader rug worked fine. Its only the sign that wont work.

**Comment by Sapharan** [comment]
For me, singleplayer, sing, charm, and rug doesn't work. On top of that, there is a setting in mod settings, that disables the spawn of wandering trader. But that setting does not work either, the traders still spawn like crazy

**Comment by praydan** [comment]
Mod creator said on his github that it's the forge update that broke his mod, we'll have to wait for an update.
