### ISSUE TITLE
crashes at launch

### ISSUE THREAD

**Issue by KittyKatty1213** [AllTheMods/ATM-8#1379]
will not launch.

[error code.txt](https://github.com/AllTheMods/ATM-8/files/11510573/error.code.txt)

**Comment by alfredggttv** [comment]
Are you using custom args for your launch?

**Comment by KittyKatty1213** [comment]
I don't know what that means :(. I'm trying to play it exactly as it comes downloading it from curse.

**Comment by Mitchell5200** [comment]
amd driver crash, update drivers
