### ISSUE TITLE
[Bug] Sophisticated Backpack deposit upgrade on Sophisticated Barrel results in "Item Loss"

### ISSUE THREAD

**Issue by JustAnotherGhostName** [AllTheMods/ATM-8#1386]
Version:
1.0.18

Info:
When you try to use a deposit upgrade with a sophisticated backpack on a sophisticated barrel, the items "disappear". Upon further investigation, it appears the items were not "lost", rather, they were added to the blocks NBT data similar to normal barrels nbt data for its inventory. (P.S., Rather ironic that sophisticated X uses uuid's, but their mod dosnt support uuid inventories for its upgrades)

Steps to reproduce:
1) Get a sophisticated backpack
2) Place in a deposit upgrade in the backpack
3) Throw random items in the backpack
4) Place a sophisticated barrel 
5) Use the deposit upgrade to place items in the barrel
6) Observe the items are not in the barrel itself, however, it shows the items in WAILA and likely NBT data

Screen Shots:
Looks like it added the items to the blocks nbt data (laptop was acting funky, otherwise I would provide a screenshot of nbt data), similar to how it would work on a vanilla inventory, but because sophisticated storage uses UUID's to open inventories, it never got added to the respective uuid inventory. 
![2023-05-21_17 50 30](https://github.com/AllTheMods/ATM-8/assets/122759195/c9dab86a-7b1f-4f23-a718-dad482b8c6f8)
![2023-05-21_17 50 32](https://github.com/AllTheMods/ATM-8/assets/122759195/6385f97e-bdf3-4de5-a575-dba36ca320cf)

Additional notes:
Likely the same issue as #1054 but is a different block. Choose what yall want to do with it

**Comment by P3pp3rF1y** [comment]
I noticed this one and was wondering how this could be broken (as in dev environment it definitely works) so tried recreating in ATM8 and I am not able to, the items just get deposited in the barrel without any issue. So there's more to this issue than just those simple steps. Also sophisticated storage doesn't store it's contents in separate storage and doesn't use UUID (well with the exception of shulker box that's in player's inventory). it just stores it in pretty much regular inventory as any other in world storage mod.

**Comment by JustAnotherGhostName** [comment]
Not certain why. A player reported it to me, so I went to test it, and this
occured. If it makes a difference I used the advanced deposit upgrade, but
I cant imagune them fundamentally working differently. Ill try one other
things just in case, maybe it has something to do with claims?

**Comment by JustAnotherGhostName** [comment]
I tested it outside of a claim before it was tested in a claim. The same issue occurs.

**Comment by P3pp3rF1y** [comment]
well, I don't know what's happening for you, but just tried testing both in claim and outside of claim with different deposit filter settings and all the time it just works. I feel like there's some block interaction mod setting causing this for you or something like that. Though it's strange that you can actually see the items in top because that means they were inserted into the barrel on server and that caused them to be synchronized to client.
Anything in log when this happens?
