### ISSUE TITLE
No Nether Fortress and No End Fortress

### ISSUE THREAD

**Issue by Juregulus** [AllTheMods/ATM-8#1390]
Hello, my World dont generate a Nether Fortress and the End Fortress (with the Portel).
Also no Anicient Citys and no Buildings from Dungeons Arise.
I didint change anything in the Config.
The World Generation is on" Bioms an Planty".
Its a Server from Nitrado.
In my Console there is a Message "Aysnc Locator- No Location Found. Killing Ender Eye entity.

**Comment by dhasial** [comment]
Was this ever fixed, or it it just not planned? Playing the most up to date version of ATM8 still doesn't show nether fortress under the Structure Compass (only showing `repurposed_structures:fortress_jungle`).

/locate minecraft:nether_fortress does find a (modified) fortress structure though, and it can be teleported to that way, though this isn't ideal.
