### ISSUE TITLE
Compact machines and Refined storages

### ISSUE THREAD

**Issue by Nightmarer98** [AllTheMods/ATM-8#1391]
Refined storage with dimensional upgrade doesn't work inside of the compact storage wireless

**Comment by bearded-tomato** [comment]
As above, both the transmitter and receiver need to be chunkloaded.
There is an annoying issue, which I will call a bug where on game load, you have to replace any network cards in transmitters that are in other dimensions before working. @toqueteos  does this also occur for you or is there a simply solution that i'm missing?

**Comment by toqueteos** [comment]
> As above, both the transmitter and receiver need to be chunkloaded. There is an annoying issue, which I will call a bug where on game load, you have to replace any network cards in transmitters that are in other dimensions before working. @toqueteos does this also occur for you or is there a simply solution that i'm missing?

I'm sorry but it seems my world is blessed and this weird behavior is not ocurring for me. It just works as expected in my world.
