### ISSUE TITLE
Backpack Dupe

### ISSUE THREAD

**Issue by RemainingToast** [AllTheMods/ATM-8#1399]

**Comment by macks2008** [comment]
Assuming you are on 1.0.16 or below, try updating. The patch notes for 1.0.17 mention fixing a dupe bug, and Sophisticated Backpacks is one of the only mods updated in that patch.

**Comment by macks2008** [comment]
PS: no description provided. Even if this isn't the bug that's already fixed, it's pretty much impossible to take action on a bug that's described in 2 words or less.

**Comment by RemainingToast** [comment]
I didn't even mean to post it lmfao - changed my mind last second. (But obviously managed to still click post)

It's a dupe in the crafting table in the backpack- just craft something with gui open for multiple people.

**Comment by macks2008** [comment]
Whoops
