### ISSUE TITLE
Multiple Broken Recipes using the barrier  

### ISSUE THREAD

**Issue by AzerJunior** [AllTheMods/ATM-8#140]
Found a bunch of broke recipes I could could make in 0.1.4, Current version 0.1.5
![Problem 6](https://user-images.githubusercontent.com/34676923/196848493-e8a991a0-fed4-4321-8d2a-733e14ba597a.png)
![Probelm 5](https://user-images.githubusercontent.com/34676923/196848495-4b8991de-58a8-4591-85c4-148139692567.png)
![Problem 4](https://user-images.githubusercontent.com/34676923/196848496-97339970-a04e-4bc0-a700-c1985d4aff83.png)
![Problem 3](https://user-images.githubusercontent.com/34676923/196848497-086e38e2-2c69-4665-98f4-16028fc64404.png)
![Probelm 2](https://user-images.githubusercontent.com/34676923/196848498-577015ba-ec49-488f-81a6-96a0e2bbe9c7.png)
![Problem 1](https://user-images.githubusercontent.com/34676923/196848499-6fcf44a5-6bf7-421f-8440-c0a307eed4d1.png)
![Problem 8](https://user-images.githubusercontent.com/34676923/196848500-ac43525d-ae1d-4a09-9629-2ad09f1759cf.png)
![Problem 7](https://user-images.githubusercontent.com/34676923/196848502-ae74771f-216b-4cf5-94cb-0bd5c5a60924.png)

**Comment by enigmaquip** [comment]
The mega cells recipes are fixed by updating that mod. The dev accidentally included the fabric ingredients instead of the forge ones.
I'll check out the others more

**Comment by whatthedrunk** [comment]
Fixed in today's update thanks.
