### ISSUE TITLE
Creative Disk Manipulator from Cable Tiers not instant.

### ISSUE THREAD

**Issue by Lord-Volkner** [AllTheMods/ATM-8#1403]
The whole reason I built it was because it was supposed to be instant. You can adjust the speed of all the others tiers in the config file, but not the creative one, I suspect because it's supposed to be instant.

Anyway, it's not a super waste of resources. It wasn't that expensive for a "creative" item, but it's still disappointing. Would love to see this get fixed.

On a server here, don't know if that matters.

**Comment by Lucas-Dreveck** [comment]
it is instantaneous, but from item to item, for example, in a system with 30M stone, 10M wood and 1 stick, 1 craftable and 1 furnace, the time it will take for each item will be the same, which has a delay is in the case of going from one type of item to another (google translator)
