### ISSUE TITLE
Steel dust pattern lower fps

### ISSUE THREAD

**Issue by danieljesus7** [AllTheMods/ATM-8#1405]
If I have a steel dust pattern from Refined Storage on my inventory my fps drop from 100 to under 10 and make the game unplayable, it still happens if u drop the pattern on the ground and look at it.

(pattern)
![image](https://github.com/AllTheMods/ATM-8/assets/87709129/55159c43-21e1-416c-8751-01fa1cdace0d)

(without the pattern)
![2023-05-30_13 08 05](https://github.com/AllTheMods/ATM-8/assets/87709129/3035bd7a-f8f0-491f-8e58-350ff1068fe7)

(with the pattern on inventory)
![2023-05-30_13 09 36](https://github.com/AllTheMods/ATM-8/assets/87709129/13797e6d-6086-40ec-8477-2684790c3a0f)

(with the pattern on the ground)
![2023-05-30_13 11 02](https://github.com/AllTheMods/ATM-8/assets/87709129/45c920dc-40ff-4d7e-ad01-c3265358c4fc)

**Comment by bearded-tomato** [comment]
I also encountered this a while back, should have reported, I think it's something to do with the hammer, as any dust recipe using hammer also drops in a similar manner. Solution for me was to autocraft using a mixer with the hammer already in it.
