### ISSUE TITLE
Note Block crash client

### ISSUE THREAD

**Issue by danieljesus7** [AllTheMods/ATM-8#1406]
When I press the JEI button on the note block craft to move items the game crash. 

(Crash message)
![image](https://github.com/AllTheMods/ATM-8/assets/87709129/0cbdf29d-faa3-4b82-9d69-d61b2827544d)

**Comment by Elania21** [comment]
I'm getting the same thing on version 1.0.18. I'm able to successfully craft the Note Block manually, I just can't use the recipe's + button to move it to my crafting grid.

**Comment by algorythm** [comment]
This happens for me in 1.0.22 if I craft a note block.
