### ISSUE TITLE
Server Files Not Working

### ISSUE THREAD

**Issue by DoctorBrandon** [AllTheMods/ATM-8#141]
I'm having issues setting up a server. I've downloaded the server files on Curse. Used the Forge Installer to download the server folder. Added the three files from the Curse download to the forge download.

However, when I run the "run.bat" file, I get "Error: Could not find or load main class @user_jvm_args.txt".

I've tried messing with the bat file adding the direct location to my Java download. I even added direct locations to the "user_jvm_args.txt" file and the location to the "win_args.txt" file just to be safe. But no matter the format I put the bat file in, I still get the same error. Any ideas of what could be going wrong?

**Comment by DoctorBrandon** [comment]
I should also clarify that the "user_jvm_args.txt" is in the same folder as the .bat file. The "win_args.txt" is also in its default location as per the original setup of the run.bat file.

**Comment by DoctorBrandon** [comment]
My Java is also up to date as of 10/20/22 and I have reinstalled the server files from curse and from the forge server download twice already.

**Comment by Miwasak** [comment]
This error is common when you're not using java 17 for the server, try to unistall any other version of java and install java 17

**Comment by DoctorBrandon** [comment]
Yep, that seems to have done it. Seems to have worked as soon as I downloaded java 17. Thanks a lot!
