### ISSUE TITLE
ATM8 1.18.0 Kubejs error

### ISSUE THREAD

**Issue by Surprise678** [AllTheMods/ATM-8#1410]
I have been playing ATM8 via Curseforge in the past few weeks, and since the last few days there are frequent Kubejs errors appearing when loading the game. I tried a full reinstall of ATM8 and the game was able to launch for a few times before the Kubejs error appeared again.

Issue: Kubejs error preventing the game to successfully load
Version: 1.18.0
Laptop used: Macbook 2020 with M1 chip
OS: MacOS 13.0.1

Full crash log is as below:
[crash-2023-05-30_22.11.35-fml.txt](https://github.com/AllTheMods/ATM-8/files/11605719/crash-2023-05-30_22.11.35-fml.txt)

**Comment by Surprise678** [comment]
https://mclo.gs/evHV60v

**Comment by pietro-lopes** [comment]
needs this log too
logs/kubejs/startup.txt

**Comment by Surprise678** [comment]
https://mclo.gs/R6NqZIu

**Comment by pietro-lopes** [comment]
remove kubejs folder, download the pack again and extract only kubejs folder

**Comment by Surprise678** [comment]
This is the kubejs folder I got after reinstalling the pack via Curseforge.
[kubejs.zip](https://github.com/AllTheMods/ATM-8/files/11606593/kubejs.zip)
