### ISSUE TITLE
Blank Upgrade Module (Mining Gadgets) has no recipe

### ISSUE THREAD

**Issue by HaylingZar** [AllTheMods/ATM-8#142]
The recipe added by KubeJS for Blank Upgrade Module from Mining Gadgets is blank. 
This prevents the item's creation without cheating, which gates all upgrades from the mod and the Salvager from Silent Gear. 
To fix, add a recipe for the Blank Upgrade Module.

**Comment by HaylingZar** [comment]
![image](https://user-images.githubusercontent.com/20231408/196920952-934b41a0-1023-48a1-850e-d766c37bf33e.png)

**Comment by Mitchell5200** [comment]
Nope, related to #111, Update to 0.1.4 or 0.1.5

**Comment by HaylingZar** [comment]
Thanks
