### ISSUE TITLE
Crash when i open villiger trade

### ISSUE THREAD

**Issue by MrPol1** [AllTheMods/ATM-8#1430]
[crash-2023-06-09_21.10.30-client.txt](https://github.com/AllTheMods/ATM-8/files/11709452/crash-2023-06-09_21.10.30-client.txt)

**Comment by heroes246** [comment]
This has been happening for me too!

**Comment by pietro-lopes** [comment]
> [crash-2023-06-09_21.10.30-client.txt](https://github.com/AllTheMods/ATM-8/files/11709452/crash-2023-06-09_21.10.30-client.txt)

If you really need to trade, disable Inventory Profiles Next mod, while they find out what is wrong.

> This has been happening for me too!
Post your log/crash.

**Comment by blackd** [comment]
you need to update IPN this is fixed in 1.10.2+
