### ISSUE TITLE
" Out of memory " problem

### ISSUE THREAD

**Issue by drhannibalr** [AllTheMods/ATM-8#1433]
I have a little, which is cliend side I think.
So, the problem is, I tried to install a few mods into the modpack, and after that no matter what I'm doing, or how many ram I allocate the modpack ( currently 12gb ) I get this error every time I try to join the server.
Any ideas what should I do?
I already tried all of the solutions I found on google, and this site.

https://pastebin.com/jSt8NcEi

**Comment by acureau** [comment]
Ran into the same issue just now, you need to edit the init args passed to the JVM. In the Minecraft launcher browse to the installations tab, press the three dots next to the ATM profile and click edit. Press the more options drop-down and edit the `-Xmx4096m` bit. This is the maximum amount of memory the JVM can use (4096mb), I set it to `-Xmx8g` (8gb) and everything worked.
