### ISSUE TITLE
Mekanism Robit Quest cannot be Completed

### ISSUE THREAD

**Issue by grimmspector** [AllTheMods/ATM-8#1436]
This cannot be completed, having it in inventory gives a 0% completion, with a grey checkmark after crafting it. Charging it, dropping it and picking it up, etc., have no effect on changing this.

![image](https://github.com/AllTheMods/ATM-8/assets/65185497/f74c7ad8-8fa7-4e08-994c-b44a05dd34f6)

**Comment by Mahlarian** [comment]
Did you craft a chargepad from Mekanism? You need to craft one so you can summon the Robit. (Notice how the two quests to the side of the Robit point to it, indicating they both need to be completed first)
![image](https://github.com/AllTheMods/ATM-8/assets/32558416/89d594d6-9973-4668-ad38-aa3d6e328409)

**Comment by GruffVP** [comment]
It looks like the issue for the poster has been resolved, but I am now facing a similar issue.
I have completed both prerequisits and have a robit in hand and the quest will not complete.
![image](https://github.com/AllTheMods/ATM-8/assets/8487636/8081179b-7227-4f55-8eda-4b5d8723f89a)

verision: All the Mods 8-1.0.21b

**Comment by BeadiestSkyBlue** [comment]
I am also having this issue. I probably made the Robit before even making the chargepad as i made the digital miner first with the Robit. Robit quest is showing 100% but cannot claim the rewards and it is blacking out the digital miner

**Comment by BeadiestSkyBlue** [comment]
![20230716_181539](https://github.com/AllTheMods/ATM-8/assets/114834942/78874367-f0f2-4557-9f20-45f27e35a63d)
