### ISSUE TITLE
Kubejs Problem

### ISSUE THREAD

**Issue by AlePlets** [AllTheMods/ATM-8#1437]
Hello. We are having this problem on the server.
We have a server that we play with friends, and out of nowhere this list appeared on the right side that makes the game's FPS 6. It crashes a lot.
It gives an error in kubejs but we don't know how to solve it. Could you help us?

<a href="https://imgur.com/yhm20fX"><img src="https://i.imgur.com/yhm20fX.png" title="source: imgur.com" /></a>

**Comment by pietro-lopes** [comment]
Open FTB Quests book, disable Auto-pin on Bottom Right corner
I get 1-2 fps with that enabled.

Don't know how you are triggering this to be enabled.
