### ISSUE TITLE
Found a dupe glitch with the dank storage dock and refined storage.

### ISSUE THREAD

**Issue by Tealn** [AllTheMods/ATM-8#1438]
There's some issue with the crafting with refined storage and external storage connected to the dank storage dock. If you have a resource in the dock and craft with it in your terminal, it will pretty much craft all that it can with the stuff in the dank, without taking any of the items. So you can just set up the recipe again and do it over and over. The attached image is how I have it set up.
![image](https://github.com/AllTheMods/ATM-8/assets/68126679/9d382389-c7e7-4388-87f0-b8493490ab4c)

**Comment by Xplodin** [comment]
I cant reproduce this, are you using singleplayer or multiplayer?

**Comment by Tealn** [comment]
> I cant reproduce this, are you using singleplayer or multiplayer?

This is in multiplayer, but I'm hosting the server from the same computer I am playing on.
What are you doing to try to reproduce it?

**Comment by Xplodin** [comment]
Also in multiplayer, latest version of the pack. I hooked a dank storage to a dock and put a external storage to the dank to see inventory. are you auto crafting?

**Comment by Tealn** [comment]
I'm one version back in the pack, on 8-1.0.18, but there weren't any changes made into the next update to these mods.
You're crafting using the stuff in the dank right? On a refined storage system?

**Comment by Xplodin** [comment]
yes, ive tried refined storage, with disks in, and disks out, crafting with items only inside the dank, it consumes

**Comment by Tealn** [comment]
Ok I first got it using endstone. I had literally like 60k endstone in the dank and then was crafting it into compressed endstone x1 or whatever its called. I made thousands of compressed endstone and it barely took any from the dank. Maybe its a performance issue with the server?
My system had a 4mil item drive and 2 64k fluid drives
