### ISSUE TITLE
Getting kicked out of server whenever I interact with an NPC

### ISSUE THREAD

**Issue by amoldovan11** [AllTheMods/ATM-8#145]
My girlfriend and I have a ATM8 server. Since the latest update, we can not interact with any NPC without getting removed from the world. Any idea what could be causing this?

**Comment by amoldovan11** [comment]
[crash-2022-10-21_14.47.18-client.txt](https://github.com/AllTheMods/ATM-8/files/9841735/crash-2022-10-21_14.47.18-client.txt)
[crash-2022-10-21_14.41.31-client.txt](https://github.com/AllTheMods/ATM-8/files/9841736/crash-2022-10-21_14.41.31-client.txt)
here are two crash reports

**Comment by FluffyLyric** [comment]
I had a similar issue. Turns out my server did not have Hostile Neural Networks in the mod list. All I did was cross check the modlist of what I had in my local folder compared to the server folder. Putting the mod on the server seems to have solved it for me.

**Comment by Mitchell5200** [comment]
Fixed by mod, closing
