### ISSUE TITLE
ATM 8 1.0.19b Broken quests

### ISSUE THREAD

**Issue by Say-fer** [AllTheMods/ATM-8#1451]
The quest "The (Just to get Stone) Starter Tool" quest says 100% in the title but refuses to give a green checkmark for my crafting table so I can progress. 
![2023-06-16_11 37 55](https://github.com/AllTheMods/ATM-8/assets/136835984/4fea6e73-3e13-4ad3-a038-d9bae8fc866f)
![2023-06-16_11 46 08](https://github.com/AllTheMods/ATM-8/assets/136835984/a650b689-b5b9-49ff-8491-90f1f1b2c308)

**Comment by Say-fer** [comment]
I have tried 6 or 7 different listed crafting tables but it will not recognize any of them.

**Comment by alfredggttv** [comment]
I should have a fix for this coming for the next update.
