### ISSUE TITLE
Question regarding the recent virus

### ISSUE THREAD

**Issue by tunse80** [AllTheMods/ATM-8#1452]
Hello, I'm sorry if I'm posting this in the wrong place. It could be classified as an "issue" though, and I had a hard time finding this specific information elsewhere. :)

I guess most are aware that there recently were some infected files on CurseForge [(link)](https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool/). From what I've gathered, it's been sorted by now. I did notice that one of the mods are in this pack though (When Dungeons Arise), unless I'm mistaken?

I checked my own files, ran the tool and didn't find any infected files on my computer. But I'm a bit paranoid and haven't played since I heard of this. This is gonna sound very nooby, but just to be sure and possibly spread the info a bit: Is it safe to play the pack still? Should I wait for an update?

**Comment by Vashta** [comment]
im curious about this too but i would say if you downloaded the pack and the virus tool didnt find anything its probably safe as the mod wont just add a virus without you updating it

**Comment by Mitchell5200** [comment]
The ATM packs were not affected by the recent malware on CF, and the WDA version that was corrupted was taken down by the dev soon after it was uploaded.

**Comment by tunse80** [comment]
I just saw that the Curseforge team said that everything is sorted. Feel free to delete this post. And thank you for letting us know. :)
