### ISSUE TITLE
The game crashed whilst rendering overlay 

### ISSUE THREAD

**Issue by elpatitokawaii** [AllTheMods/ATM-8#1455]
The game crashed whilst rendering overlay
Error: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured

This is the message that apears to me when i tried to open the modpack, in any version, 1.019b, 1.018, etc
 complete issue https://mclo.gs/2IUH9c1

**Comment by BoereworsG** [comment]
Same issue here.
