### ISSUE TITLE
1.0.20 - Mismatched Mods in Server and Client File (Structurize)

### ISSUE THREAD

**Issue by tekook** [AllTheMods/ATM-8#1462]
Server and Client Mods do mismatch currently.
Mod: Structurize
Client-Version: structurize-1.19.2-1.0.492-ALPHA
Server-Version: structurize-1.19.2-1.0.491-ALPHA

Easy fix, but server-pack should be repacked.
Kind Regards

**Comment by Mitchell5200** [comment]
being fixed right now, just waiting on the files to upload. Look out for the 1.0.20b server pack

**Comment by Mitchell5200** [comment]
Fixed @tekook 
https://legacy.curseforge.com/minecraft/modpacks/all-the-mods-8/files/4595211

**Comment by tekook** [comment]
Just tested on my server, works like a charm, Thanks
