### ISSUE TITLE
ticking entity crash twice now

### ISSUE THREAD

**Issue by Vashta** [AllTheMods/ATM-8#1464]
so ive had my game crash twice now since the newest update due to a ticking entity 
https://mclo.gs/nI5DTPS

**Comment by Hanske2** [comment]
I am having the same error, 5+ times within two minutes of loading the world, semi randomly what exactly I was doing. (Opening some sort of menu)
[crash-2023-06-19_22.41.39-server.txt](https://github.com/AllTheMods/ATM-8/files/11793043/crash-2023-06-19_22.41.39-server.txt)
