### ISSUE TITLE
Sophisticated Storage Barrels Have Incorrect Textures

### ISSUE THREAD

**Issue by Bildrick** [AllTheMods/ATM-8#1465]
Pack Version: 1.0.20

Screenshots:
![javaw_Nat20sueMg](https://github.com/AllTheMods/ATM-8/assets/30052796/63d3789f-72ab-4c06-86da-088b1be3738f)
_JEI Listing_
![javaw_xZ69lyWU3n](https://github.com/AllTheMods/ATM-8/assets/30052796/2aa94a7d-89d5-4d25-ac6e-de677153d567)
_Note - These Should Be Normal Barrel Textures_

**Comment by Grisabeller** [comment]
Have you tried reloading as i had this bug look at the resoure pack and then  didnt do anything but it let it reload and then started game and the texture where back to normal. might not work but seem to fix for me
