### ISSUE TITLE
Severe game lag when viewing specific recipes

### ISSUE THREAD

**Issue by Disiduous** [AllTheMods/ATM-8#147]
When viewing certain recipes (IE ancient debris directly, right clicking in JEI, not via machine recipes) the game seems to lag to the point of freezing up.

**Comment by TsmckdTheCLaP** [comment]
ive found this to be apparent whenever a recipe with (accepts any) shows up when it cycles through the various blocks

**Comment by Disiduous** [comment]
I've discovered the way to replicate is if you're in an AE2 storage system and look up recipes, again, like the ancient debris. Had a friend share screens after I crashed again and replicated what I did both in and out of the AE2 interfaces.
