### ISSUE TITLE
Create mod mechaniacal mixer

### ISSUE THREAD

**Issue by Dansky81** [AllTheMods/ATM-8#1470]
Hi,

Just updated to latest version of ATM8, and now ore hammers get used up by mechanical mixers instantly after grinding only 2 dust.
Tried copper and platinum hammer and any ore. 

Dunno if its a bug or intentionally?

**Comment by Trnrr** [comment]
I have the same issue. Hopefully a bug..

**Comment by Mitchell5200** [comment]
some change in create 0.5.1, before in 0.5.0, with the mixer, it would ignore the durability of the items placed in it, leading to infinite uses of the tools, when they should've broken
