### ISSUE TITLE
Builder's wand + Harvest Rod CTD (Easily reproduced)

### ISSUE THREAD

**Issue by theothersteve7** [AllTheMods/ATM-8#1472]
Having any Builder's Wand and the Harvest Rod in your inventory at the same time causes a CTD.  This only happens in Survival as the items skip some checks in Creative.

Suggest disabling the Harvest Rod and notifying the mod authors.

**Comment by theothersteve7** [comment]
Found related issue on the Reliquary github.

https://github.com/P3pp3rF1y/Reliquary/issues/619

**Comment by theothersteve7** [comment]
Latest version (several months ago) appears to include a fix.  Can we get this mod updated?

**Comment by gmanpohl23** [comment]
Having the same issue. I can no longer play on my server since this item prevents me from even joining and crashes my game.
