### ISSUE TITLE
Crash with terrain generation in End

### ISSUE THREAD

**Issue by JustJk245** [AllTheMods/ATM-8#1475]
While generating new chunks in end this crash error keeps happening.

The game crashed whilst feature placement
Error: java.lang.IllegalArgumentException: "byg:features/mushrooms/imparius/imparius_mushroom_canopy6" is not a valid tree part.

**Comment by WyFryMU** [comment]
Same issue and same error on version 1.0.20

**Comment by JustJk245** [comment]
Sorry forgot to mention, this crash has been occurring on 1.0.20. It seems like it’s almost a guaranteed crash when using a jet pack and loading a good number of chunks rapidly. I never encountered the crash on past versions due to never being in the end so it may have been an issue before this version.

**Comment by JustJk245** [comment]
Sorry forgot to mention, this crash has been occurring on 1.0.20. It seems like it’s almost a guaranteed crash when using a jet pack and loading a good number of chunks rapidly. I never encountered the crash on past versions due to never being in the end so it may have been an issue before this version.

**Comment by WyFryMU** [comment]
> Sorry forgot to mention, this crash has been occurring on 1.0.20. It seems like it’s almost a guaranteed crash when using a jet pack and loading a good number of chunks rapidly. I never encountered the crash on past versions due to never being in the end so it may have been an issue before this version.

Looks like 1.0.20b should remove this end generation bug now :)

**Comment by WyFryMU** [comment]
Adding onto this, specifically Im on a server that's using 1.0.20b, I didn't realize that. Error still occurs.

**Comment by Cyumm** [comment]
You can prevent these biomes from generating by removing the line 
			{
				"data": "byg:imparius_grove",
				"weight": 3
			},
  in the file end-biomes located at C:\Users\Admin\curseforge\minecraft\Instances\All the Mods 8 - ATM8\config\byg\

I think it works fine now with the update 1.0.21.

**Comment by bronzobj** [comment]
I second this, using 10.0.20 on multimc and was getting crashes because of those darn mushrooms. deleted the line suggested by Cyumm in the config and the crashes ceased.
