### ISSUE TITLE
Botany pot in compactmachine causes crash on being ticked [8-1.0.20]

### ISSUE THREAD

**Issue by Simmso** [AllTheMods/ATM-8#1479]
Only in .20 reverting to .19 fixed it.
[crash-2023-06-20_10.22.50-server.txt](https://github.com/AllTheMods/ATM-8/files/11797980/crash-2023-06-20_10.22.50-server.txt)
[crash-2023-06-20_10.32.53-server.txt](https://github.com/AllTheMods/ATM-8/files/11797981/crash-2023-06-20_10.32.53-server.txt)

**Comment by Th3C0D3R** [comment]
not only in compactmachine
[crash-2023-06-27_09.41.24-server.txt](https://github.com/AllTheMods/ATM-8/files/11879084/crash-2023-06-27_09.41.24-server.txt)
just a Botany hopper pot ontop of a drawer will also crash in some time
