### ISSUE TITLE
Pls Add minecolony mystical agg essence recipes like you had in atm 7

### ISSUE THREAD

**Issue by Pelkenator** [AllTheMods/ATM-8#148]
I want to be able to use my minecolony to make massive amounts of items but to do this i need the mechanics hut to be able to craft with the essences like in atm 7. should be pretty easy to copy paste the recipes with kubejs since you have already done the work.

**Comment by Mitchell5200** [comment]
Minecolonies Blacksmith does this already, nothing was/will be added by us for this
