### ISSUE TITLE
1.0.21b Bug report.

### ISSUE THREAD

**Issue by gomeris** [AllTheMods/ATM-8#1484]
Hi, we are currently playing the new update and found two new bugs that would need an urgent fix. The first bug is that the 
Chisel mod has been broken, and 80 percent of the textures are messed up on every chiseled block.
The second, bigger issue is that the hotbar stops responding after a while and neither me or my friend are able to
switch between slots. Both scrolling and selecting slots with numbers don't work.

**Comment by gomeris** [comment]
We found out what causes the problem with the inventory getting stuck. If you use the portable crafting table on a binding it makes it glitch out.

**Comment by Zaldos** [comment]
I also had the re-chiseled texture bug. Seems someone raised it here: https://github.com/SuperMartijn642/Rechiseled/issues/36
and the fix (at least for me) was to update the Fusion (Connected Textures) mod.

**Comment by DeWachterGianni** [comment]
> We found out what causes the problem with the inventory getting stuck. If you use the portable crafting table on a binding it makes it glitch out.

I also have the same problem as you. But I am not using the portable crafting table. Really annoying bug, hope it gets fixed soon.

**Comment by mcion3** [comment]
I had the same problem and realized that the Crafting Table on a Stick was bound to v and I would accidentally. Turned off the keybind and have had no issue
