### ISSUE TITLE
[1.0.21b] Rechiseled connected textures broken

### ISSUE THREAD

**Issue by The-Danfoss** [AllTheMods/ATM-8#1485]
1.0.21b
![afbeelding](https://github.com/AllTheMods/ATM-8/assets/667383/710346b6-da36-4a90-acd6-df67cb4b9a0d)

1.0.19b
![afbeelding](https://github.com/AllTheMods/ATM-8/assets/667383/47ec780e-7ced-4553-b905-5814b8b08102)

**Comment by marco3102** [comment]
Unconnected Ones too. For me at least

**Comment by Boxkiteboy** [comment]
I have the Same Problem

**Comment by Boxkiteboy** [comment]
I turn off shaders and the blocks are still broken.

**Comment by DarthPJB** [comment]
Just updated my server.
Same issue - when my players update later i'll update (assuming I remember) if they are also effected.

**Comment by Mitchell5200** [comment]
https://github.com/SuperMartijn642/Rechiseled/issues/36

**Comment by MommaDragon** [comment]
Oh, good. Someone's on the case. Thanks.

**Comment by marco3102** [comment]
Rechisled Mod Author said he fixed it
"> Should be fixed now in version 1.0.1 of Fusion. Thanks for the help!"

**Comment by SuperMartijn642** [comment]
The issue came from a mixin by ModernFix optimising the texture loading process which happened to make it so Fusion's texture loading got skipped.
I have now added a separate step which will load in case ModernFix is installed.
Fusion 1.0.1 thus fixes the issue.
