### ISSUE TITLE
1.0.20 Server Crashing [FIXED]

### ISSUE THREAD

**Issue by ItsNebb** [AllTheMods/ATM-8#1491]
Been playing on a server with my friend for awhile now, and he had just logged off for the day, and I was exploring the end, and the server just randomly crashed, and now every time I try and load in, it crashes the server with the same error, but he can load in fine without the server crashing, did I load a corrupted chunk maybe? every time I connect the console reads: 
Server thread/WARN Can't keep up! Is the server overloaded? Running 2902ms or 58 ticks behind
Crash Report:
https://gist.github.com/ItsNebb/ba8b2aa8459f93954cfc85e70f5b4479

**Comment by Armotik** [comment]
we got the same issue

**Comment by PrestonUI** [comment]
maybe give your friend permission to use commands and then right when the server loads up have the tp command ready so your friend can tp you to him?

**Comment by enigmaquip** [comment]
you can use `/cu unstuck <player>`, even while they're offline, to move a player to worldspawn

**Comment by PrestonUI** [comment]
> you can use `/cu unstuck <player>`, even while they're offline, to move a player to worldspawn

thats great info actually i never knew that

**Comment by ItsNebb** [comment]
Updating to 1.0.21b for the server and my client and it fixed this issue for me! Patch notes:
"1.0.21 and 1.0.21b are both compatible, this update is a patch for servers
Forge 43.2.14
Small update to fix ars break spells, and End generation crashes"
