### ISSUE TITLE
Game goes to "Waiting on Server" when interacting with Poppys in Crafting Grids

### ISSUE THREAD

**Issue by UnlikeLiam** [AllTheMods/ATM-8#1496]
When you place the poppy in the crafting grid, it doesn't present the red dye and then the game idles for a moment and the goes to waiting on server. then it goes back to normal.

This is the same for vanilla crafting grids and other mods like Refined Storage.

**Comment by NamerekWASD** [comment]
I have the same issue. At some point, my server started to freeze after clicking "Move items" in JEI or when I put something in the crafting grid. There is a log attached. 
Versions:  8-1.0.21 and  8-1.0.21b
[launcher_log.txt](https://github.com/AllTheMods/ATM-8/files/11852464/launcher_log.txt)
