### ISSUE TITLE
Mekanism 

### ISSUE THREAD

**Issue by Ultimate1914** [AllTheMods/ATM-8#1498]
There is no recipe for "Improvement: Anchor" although in creative mode it is

**Comment by Aiidoneus** [comment]
I am guessing you are talking about Mekanism's anchor upgrade. That is disabled by All of the Mods team. 
I answered this here. You should use FTB Chunks chunkloading if you want loading. 
https://github.com/AllTheMods/ATM-8/issues/1499#issuecomment-1605869297

**Comment by Mitchell5200** [comment]
Yes, intentionally removed
