### ISSUE TITLE
Anchor Upgrade

### ISSUE THREAD

**Issue by C95M** [AllTheMods/ATM-8#1499]
Hi everyone, i think i found a bug, there is no booster yet in game, i have the latest version of the mod pack

![Upgrade Anchor](https://github.com/AllTheMods/ATM-8/assets/137652451/3f3be75a-18bf-49e3-aa1f-7e557d6efa03)

**Comment by Aiidoneus** [comment]
This is disabled by All of the Mods Team purposely from what I see. 

It is disabled in the mod config https://github.com/AllTheMods/ATM-8/blob/0125d7a08fd05d629cf45fd5953abf52bc802d52/config/Mekanism/general.toml#L7 by the team as well. 

Hidden on JEI client-side here https://github.com/AllTheMods/ATM-8/blob/0125d7a08fd05d629cf45fd5953abf52bc802d52/kubejs/client_scripts/jei_hide.js#L9

**Comment by Mitchell5200** [comment]
Yes, intentionally removed

**Comment by C95M** [comment]
why did they remove it? does the automatic excavator still work?
