### ISSUE TITLE
Comforts recipe conflict.

### ISSUE THREAD

**Issue by Jophire** [AllTheMods/ATM-8#150]
Version 0.1.6
Can't craft Comforts sleeping bags, both the normal recipe and Kubejs recipe conflict with Absent By Designs white wool slabs.

**Comment by enigmaquip** [comment]
![javaw_ZZmzYOXgfE](https://user-images.githubusercontent.com/6134440/197318170-4da114bc-bd59-4735-8714-942d2d8efb3f.gif)
Working as designed in my testing.

**Comment by Jophire** [comment]
Unsure why that might be. When upgrading I delete the kubejs, config, defaultconfig folders then upload the new ones. Do kubejs recipes get stored anywhere else?

**Comment by whatthedrunk** [comment]
Yeah always delete the configs, mods and kubejs when updating and copy the new ones over plus any changes you may have made.
