### ISSUE TITLE
ATM8 1.0.21b - Xnet Red Advanced Connector causes server crash

### ISSUE THREAD

**Issue by westingham** [AllTheMods/ATM-8#1503]
When trying to create a pattern for an Xnet Red Advanced Connector in a Refined Storage Pattern Grid, I timed out / crashed my server twice in a row. Both times it happened as soon as I clicked the recipe from JEI into the Pattern Grid.

I've attached both crash reports.

Seems linked to https://github.com/AllTheMods/ATM-8/issues/1476 and https://github.com/AllTheMods/ATM-8/issues/1478.
[crash-2023-06-26_03.54.44-server.txt](https://github.com/AllTheMods/ATM-8/files/11862965/crash-2023-06-26_03.54.44-server.txt)
[crash-2023-06-26_03.48.48-server.txt](https://github.com/AllTheMods/ATM-8/files/11862966/crash-2023-06-26_03.48.48-server.txt)

**Comment by WaterKing201030** [comment]
I have a similar problem when crafting an Blue Advanced Connector in 1.0.21. When in a crafting table, it will be repaired when exit the crafting GUI(with all ingredients dropping). Then I tried it in a immersive engineering table, the server keep timeout until I broke the table.
[Part of log related to this problem](https://github.com/AllTheMods/ATM-8/files/11902831/test.log)

**Comment by JSGER** [comment]
Update to  jei-1.19.2-forge-11.6.0.1016.jar fix the problem

**Comment by FHoulbreque** [comment]
I noticed the exact same issue as previously described.

It only happens with the *XNet* "Advanced Connector" recipe for me. In any of the colors.

I did ran observable : https://o.tas.sh/#yoJ2
I did ran spark : https://spark.lucko.me/VVr1oKRPRA

I opened my crafting table and set up the recipe into it. Be it manually or through JEI it cause the freeze.
