### ISSUE TITLE
AE2 quest is misleading

### ISSUE THREAD

**Issue by robmart** [AllTheMods/ATM-8#1509]
The first AE2 quest (appropriately titled Applied Energistics 2) says:

> To get started with AE2, you will need to mine an important resource for the mod known as **Certus Quartz**. Just like for Amethyst, you will find Certus Quartz Crystals that you can mine for Certus Quartz **Dust** and **Crystals**.

This, to me, implies that Certus Quartz Crystals are found underground in big hollow spherical structures like Amethysts.

This is not true. Certus Quartz Crystals are found in meteorites that require a Meteorite Compass to find. The Meteorites are mostly filled in except for the small area where the Budding Certus Quartz is found. 

As per the [AE2 Wiki](https://appliedenergistics.github.io/getting-started): 
>* Put a Vanilla compass in the charger and charge it to craft a Meteorite Compass.
>* Use the meteorite compass to find meteorites, which have a chance to contain quartz blocks and budding quartz.

The solution to this is pretty obvious. Either add a Meteorite Compass to the first quest and amend the description, or add a new first quest with only the compass and have the current quest become the follow up quest.

**Comment by alfredggttv** [comment]
Just put in a fix for this!
