### ISSUE TITLE
Witchy Issue

### ISSUE THREAD

**Issue by Faebaequeen** [AllTheMods/ATM-8#1519]
First time posting, so sorry if I don't give enough info. I got a ticking crash when I came across a witch while wearing two pieces of the witch armor.  When wearing two pieces it is supposed to make witches passive to you.  As soon as one came within sight of me my game froze then crashed, and any time I try and reload the world I get to the joining world screen then it crashes again with the same error.

**Comment by seeebz** [comment]
Commenting to confirm this on my end as well. Approaching without Witch Armor does not crash the server.

**Comment by lavelain** [comment]
Commenting to confirm this is happening on my server as well. Regular of "boss" witches, the server behavior is the same. Witch shows up with someone who has Witch armor on, server crashes
