### ISSUE TITLE
Hotbar stuck - can't scroll or use keybinds

### ISSUE THREAD

**Issue by Reioflight** [AllTheMods/ATM-8#1520]
I was messing around in creative to learn about the stuff in the pack and my hotbar got stuck. Scrolling, using my touchpad or a different mouse/keyboard, and restarting the game did not help. I can break and place what is in the slot though. Switching to survival did nothing. How can this be fixed?

I have only added Better Flight and MobNeutralizer (which didn't work anyway so I may remove it). Some keybinds have been changed but mainly unbinding a bunch I won't use at all or for a while.

**Comment by avedium** [comment]
Would you happen to be using the grindstone on a stick? I have  similar issue now and again when using that item though restarting my game seems to resolve it.

**Comment by Reioflight** [comment]
No, I was holding a Netherite Backpack though. I grabbed another from JEI and accidentally clicked the full one (with the backpack-ception upgrade) with the empty one and my hotbar got stuck. Maybe it was a conflict with the shift drag drop fill function? Seems strange it would lock my hotbar though.

**Comment by Rashir** [comment]
I've been getting this issue pretty consistently. Just seems to happen after a long enough amount of time playing rather than a specific action causing it. Decided to just immediately hop off and grab the game log to put here when it happened this time.
[latest.log](https://github.com/AllTheMods/ATM-8/files/11952280/latest.log)

**Comment by e3fell** [comment]
I've got this same issue, have you managed to figure it out yet?

**Comment by Reioflight** [comment]
Nope. Nothing online either. But then again, I can't read coder speak. So nothing legible found so far. That's why I asked for help here.

**Comment by Avrioh** [comment]
I've had this issue before. Guy on reddit mentioned clicking V was the fix, he didn't know why. But yeah, to fix this issue, click V.

**Comment by Mitchell5200** [comment]
the cause was/is the Supplementaries quiver, should be fixed in 1.0.22

**Comment by Reioflight** [comment]
It is fixed! Thank you!
