### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by OwOsucksAwesomeMinecraftbossAlissha6TRM** [AllTheMods/ATM-8#1523]
you guys might not be looking for mods, but these are some cool mods that would improve the game

Mekanism Evolution - more tiers of cables / energy cubes / QIO - https://legacy.curseforge.com/minecraft/mc-mods/mekanism-evolution

Mekanism MoreSolarPanels - adds new tiers of solar panels - https://legacy.curseforge.com/minecraft/mc-mods/mekanism-moresolarpanels

rftools dimensions - idk this isnt in here, all of the other rftools mods are in here, and the dimensional shards are kind of not needed - https://legacy.curseforge.com/minecraft/mc-mods/rftools-dimensions

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
dimension shards are not needed in base game*

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
i would love to make my own dimension no one can access lol

**Comment by Mitchell5200** [comment]
Mod suggestions to > #3

**Comment by AlphaJakeWolf** [comment]
Can we get this?
https://www.curseforge.com/minecraft/mc-mods/shadow-x-blocks-plus/screenshots
