### ISSUE TITLE
No recipe for processor binding.

### ISSUE THREAD

**Issue by iiAmJons** [AllTheMods/ATM-8#1529]
The item Processor Binding from Refined Storage does not have a recipe for crafting.

**Comment by Mitchell5200** [comment]
I was gonna ask for more information, like pack version and if you're on a server, but as you're likely "SenseiNotHere", on our ATM8 public server, then you did not read the rules board at spawn when you first joined, stating many things, like the banning of RS on the server, which then disabled the recipes
