### ISSUE TITLE
Early game tools seemingly uncraftable

### ISSUE THREAD

**Issue by chris-ware** [AllTheMods/ATM-8#153]
Wood and Stone tools don't require sticks, but instead require their own materials in place of sticks, meaning that a shovel and sword are exactly the same recipe, thus meaning that the "Getting Started" questline can't be progressed.

This is on a new world created directly from the 0.1.6 release having not updated at all prior.

**Comment by MrPostHipster** [comment]
Unfortunately work-around above didn't work for me.  I've tried disabling both options above.  Running ATM 8 Minecraft 1.19.2

**Comment by Mopar** [comment]
> > Unfortunately work-around above didn't work for me. I've tried disabling both options above. Running ATM 8 Minecraft 1.19.2
> 
> It has to be done serverside since server is delivering recipes, I assume you were playing on a multiplayer server.
> 
> If not, try deleting kubejs folder

I can confirm that even just changing "better stone tool crafting" to false on server (leaving client side alone) does fix the issue.

**Comment by MrPostHipster** [comment]
Confirmed fix.  Quark config is located at `/config/quark-common.toml`.  Thanks for follow up
