### ISSUE TITLE
Question on Immersive Engineering x Mystical Agriculture

### ISSUE THREAD

**Issue by FluffnTough** [AllTheMods/ATM-8#1530]
From what I've gathered, I understand that Mystical Agriculture's seeds do not work in Immersive Engineering's Garden Cloche by default. However, it seems that they do in this modpack. What I'm not understanding is _how_ . I've poked around in the modpack some but don't see anything obvious. I apologize if this has already been asked, though I haven't seen it asked outright in the threads for this modpack.

So, how does it work? Is there some compatibility mod or datapack I'm not seeing or is Immersive Engineering modified to allow these seeds to work? I'd like to know so I may make it work in a small pack of my own that I'm working on for use by some friends and I.

Apologies if this has already been discussed elsewhere and thanks in advance.

**Comment by Mitchell5200** [comment]
Custom Kubejs code.
