### ISSUE TITLE
Pipez mod stopped working

### ISSUE THREAD

**Issue by TheRealOrigin** [AllTheMods/ATM-8#1531]
![2023-07-06_00 30 32](https://github.com/AllTheMods/ATM-8/assets/138748535/f9f68c7a-027f-42ae-bf64-cadeee3562a4)
Recently started making anti matter towards the star as the last thing left to make everything. Suddenly the entire pipez mod stops working and nothing will transfer anymore, can't be from adding more because it was all working fine earlier in the day and shortly before finishing the supercritical phase shifter. any ideas on what to do to fix this? the last backup i have of the server is from a day ago and the entire antimatter project would be set back to phase 1

**Comment by Zarkazm** [comment]
I noticed one of my fluid pipez stopped working on my brine tower the other day.  Had to break it and put it back down.  Was really weird.
