### ISSUE TITLE
[Bug]: The structure compass waggles uselessly when used in a non-overworld dimension

### ISSUE THREAD

**Issue by dpcollier128** [AllTheMods/ATM-8#154]
The structure compass appears to exhibit default compass behavior whenever used within a non-overworld dimension (ie. waggle uselessly in many directions). This is both before and after selecting a destination. I have also noticed that the item sprite is identical to the default compass item, likely a bug or modpack configuration conflict.

I am using the All The Mods 8 modpack as shown here: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

Pack version is 0.1.5 I'll see if the latest update addresses this. I'll leave the ticket here in case it doesn't... It doesn't.

**Comment by dpcollier128** [comment]
Huh... Apparently this is an intentional design of this Structure Compass mod: https://www.curseforge.com/minecraft/mc-mods/structure-compass

https://github.com/Mrbysco/StructureCompass/issues/6

Oh well...

**Comment by dpcollier128** [comment]
I see. Unfortunately, this one hasn't been updated yet: https://www.curseforge.com/minecraft/mc-mods/structures-compass

**Comment by Mrbysco** [comment]
The compass looking like the vanilla compass is intentional, it wobbling in other dimensions isn't and will be fixed next build
