### ISSUE TITLE
Dice of Fate quest not being exposed

### ISSUE THREAD

**Issue by Zarkazm** [AllTheMods/ATM-8#1550]
Pack version 1.0.21b - After completing the Gaia Guardian 2.0 quest, the Dice of Fate quest isn't appearing.  I had to go into Edit mode and complete it manually.
![2023-07-13_02 48 07](https://github.com/AllTheMods/ATM-8/assets/10002661/5d4c283e-fbba-4347-b6db-ccd30823155f)

**Comment by alfredggttv** [comment]
I'll take a look at this!
