### ISSUE TITLE
[Bug] JEI Autofill Crafting for an Ad Astra rocket when in an Refined Storage terminal causes a disconnect on the client side.

### ISSUE THREAD

**Issue by jarl9** [AllTheMods/ATM-8#1551]
ATM8 Version: 1.0.21b

Description:
When using a Refined Storage crafting terminal of any sort, the client will disconnect if autofill for an Ad Astra rocket recipe is used.

Below, the steps to reproduce are referenced from the exact same issue that JustAnotherGhostName reported in Issue #1250 that hasn't been addressed.

"Steps to Reproduce:

Open up a crafting terminal from RS
Ideally, have the parts for a rocket in the system
Search in JEI for the recipe for said rocket
Click the plus button to pull the items to craft the rocket
Disconnect with a java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9 error as a result of trying to put more than 9 items in the crafting tables array (which has a maximum index of 8)"

I'd really appreciate some help with this as I cannot reconnect now to my friend's hosted server. After this disconnect occurs, I keep receiving a connection time out.

**Comment by Zarkazm** [comment]
I had the same thing happen with a Botania flower recipe that was more than 9 items.

**Comment by CharlieLima53** [comment]
I've also just raised a ticket for this happening with Create Waterwheels. Seems to be an issue with multiple items within JEI. Hopefully one fix will fix them all.
