### ISSUE TITLE
Steam Dynamo Crashing game

### ISSUE THREAD

**Issue by HeavyDeception** [AllTheMods/ATM-8#1555]
I don't know if this is just me but after the last update my game will crash randomly.

https://mclo.gs/mo6BqSC#L5

I feel like this may be happening because of something else, but I don't know just wanted to let you guys know and to see if there were any underling problems.

**Comment by rbaker87** [comment]
Already been reported and fixed. Just needs to make it up to ATM https://github.com/ChiefArug/ThermalSysteams/issues/10
