### ISSUE TITLE
Game Crash when selecting the collector, pusher or puller upgrade from the mod functional storage

### ISSUE THREAD

**Issue by DEADDEALER** [AllTheMods/ATM-8#156]
[crash-2022-10-23_03.24.33-client.txt](https://github.com/AllTheMods/ATM-8/files/9845557/crash-2022-10-23_03.24.33-client.txt)

**Comment by Marvin-gc** [comment]
[crash-2022-12-14_23.02.23-client.txt](https://github.com/AllTheMods/ATM-8/files/10233623/crash-2022-12-14_23.02.23-client.txt)
[crash-2022-12-14_22.57.42-client.txt](https://github.com/AllTheMods/ATM-8/files/10233624/crash-2022-12-14_22.57.42-client.txt)
