### ISSUE TITLE
Mod will not Load up- Crashes with the description: Rendering Overlay

### ISSUE THREAD

**Issue by Knubzie** [AllTheMods/ATM-8#1568]
I have been playing with no issues even played this morning.  Went to log on this evening and I keep getting this crash about Rendering Overlay.  

[crash-2023-07-18_19.00.05-client.txt](https://github.com/AllTheMods/ATM-8/files/12089658/crash-2023-07-18_19.00.05-client.txt)

**Comment by Mitchell5200** [comment]
Full latest.log file please, from the logs folder via https://mclo.gs/

**Comment by Knubzie** [comment]
https://mclo.gs/OE2nWzT
