### ISSUE TITLE
Cant make a All The Mods 8 server

### ISSUE THREAD

**Issue by nikop32** [AllTheMods/ATM-8#1569]
Hey, I'm just trying to make a server so that we can play on it, however I keep getting this issue, I've tried using java 8 and 17 and i just cant get it to work, if I run the run.bat file as administrator then it does not read the user_jvm_args.txt file even though they are in the same folder, if someone could help me that would be great.

![Screenshot 2023-07-19 190211](https://github.com/AllTheMods/ATM-8/assets/140007725/caca49b1-2988-4155-9891-f3c45baa68ec)
![Screenshot 2023-07-19 190221](https://github.com/AllTheMods/ATM-8/assets/140007725/0777ec34-3630-45cb-b120-1640c913373e)
![Screenshot 2023-07-19 190232](https://github.com/AllTheMods/ATM-8/assets/140007725/45804ab1-33b9-4c6c-82dd-ccfdacba6e59)
![Screenshot 2023-07-19 190243](https://github.com/AllTheMods/ATM-8/assets/140007725/03d059c2-5fc1-4ddf-a2e6-35fd3e1e3767)
![Screenshot 2023-07-19 190316](https://github.com/AllTheMods/ATM-8/assets/140007725/f2266a65-4ab6-4930-957b-268500a1ba20)

**Comment by Mitchell5200** [comment]
Server is launching with java 20 instead of java 17
