### ISSUE TITLE
Having trouble starting Server fresh install..

### ISSUE THREAD

**Issue by Tbonepwnge2** [AllTheMods/ATM-8#1575]
Hello i recently just downloaded the newest server files for all the mods 8 and there seems to be a problem where its looking for dependencies and doesn't load properly here is the log.

https://mclo.gs/BoOo3en

any help would be appreciated thanks

**Comment by Iceotty** [comment]
I'm getting the exact same issue! kind of reads like there's some clientside shit added in that shouldn't be there, but I can't work out what it is exactly. I presume everyone else making servers must be getting the same issue

**Comment by Mitchell5200** [comment]
You need to use Java 17, not 20 for the server

**Comment by Tbonepwnge2** [comment]
Its using java 17 compatibility mode so i don't believe that is the issue, but i will try that

**Comment by Tbonepwnge2** [comment]
Can confirm that it works using java 17 oddly now there are more errors now.. lol, but it works now 

here is new log for new errors 

https://mclo.gs/5ldBbzN
