### ISSUE TITLE
item duping using crafting tweaks

### ISSUE THREAD

**Issue by sjoerd1112** [AllTheMods/ATM-8#1577]
Crafting tweaks has an option to compress items to blocks while pressing ctrl+k in a crafting bench while hovering over an item in your inventory. This is supposed to only compress the item if you have enough items in your inventory (so at least 9, can be in multiple slots in your inventory). At the moment it isn't working like that anymore and it only takes the items from a single slot and compresses it, even if you only have 1 item of that type in your inventory, so it's basically giving you 8 extra items for free

**Comment by HumdrumPanic** [comment]
seems to be fixed... tried with cobblestone it consumed the correct amount and cycled back down in to the original amount
