### ISSUE TITLE
Mod SimpleBackups missing in Serverfiles

### ISSUE THREAD

**Issue by katsutosh** [AllTheMods/ATM-8#158]
Version: 0.1.7

The mod ***SimpleBackups*** still missing in serverfiles.
Please add this to the serverfiles, because it's tedious to manually add this after every update..

**Comment by Mitchell5200** [comment]
That's fully on purpose to avoid conflicts with any hosts own auto backup system

**Comment by katsutosh** [comment]
then it's maybe an idea, that the team put the file with the ending _.disabled_ in the server mod's directory.
(if thats still work in 1.19.2), in 1.7.10 the mod with this file end just were skiped loading.
because it's easier to automate an update process with a rename of the file instead of open client mods dir and manually upload the file to server

**Comment by Mitchell5200** [comment]
.Disabled implemented in recent versions, Closing
