### ISSUE TITLE
Easy Villagers converter not working

### ISSUE THREAD

**Issue by kellynkelly** [AllTheMods/ATM-8#1580]
Using the 1.0.22 version of All the Mods, which includes Easy Villagers 1.0.11, I am unable to use the converter to convert my villagers.  I am able to create the converter block and put a villager and a golden apple as the inputs. However, I am unable to add a healing potion of any kind.  I have tried all versions of healing potions; regular and splash. 

I have tried the trader, iron farm, and breeder blocks, and they all work as expected.

**Comment by C-ffeeStain** [comment]
It's supposed to work with weakness potions, not healing ones.

**Comment by kellynkelly** [comment]
> It's supposed to work with weakness potions, not healing ones.

OMG, I am an idiot. You are right.
