### ISSUE TITLE
Persistent crash when loading ATM-8 1.0.22 from CF

### ISSUE THREAD

**Issue by AJRBarley** [AllTheMods/ATM-8#1581]
When I try to load ATM-8 via the CurseForge app, it opens the MC launcher as per normal, I select the ATM Install, and open. It prepares fully then hangs, and crashes. As CF will load any other modpack I've got, I'm left with only hoping this is somehow an issue with ATM-8. 

I'm literally at wit's end, I've tried every fix I can find on this and it still isn't working. I've attached the lunacher crash log for full context.
The most frustrating part is that it was running fine last night! 

I have:
- Completely uninstalled/reinstalled MC
- Completely uninstalled/reinstalled CF and ATM-8
- Rolled back ATM-8 to .21, and had same issue
- Checked and confirmed I have up to date drivers
- Uninstalled/reinstalled Java
- Tried a different user account on the same PC

[Crashreport_1553 230723_hs_err_pid6484.log](https://github.com/AllTheMods/ATM-8/files/12138100/Crashreport_1553.230723_hs_err_pid6484.log)

**Comment by RelatedChaos** [comment]
Hello, saw something like this happening both on startup and joining worlds (on joining server, it gets stuck on encrypting). What worked for me is running MC in windowed mode until i join the world, and then switching to full screen.
Maybe try this?
Regards, RC

**Comment by Mitchell5200** [comment]
AMD GPU Driver crash, reinstall/update drivers.
