### ISSUE TITLE
Dedicated Server will not boot

### ISSUE THREAD

**Issue by Iceotty** [AllTheMods/ATM-8#1582]
Here's my log https://mclo.gs/2iEL4vo
Really can't work out what's wrong here, any help is appreciated

**Comment by MatyasHarvanek** [comment]
I have same issue

**Comment by MatyasHarvanek** [comment]
I fixed it, I just uninstalled all Java versions that I had. And installed just these two:
![image](https://github.com/AllTheMods/ATM-8/assets/50873001/a658ca7b-adfc-40a4-9aeb-9b3db8f402a9)

**Comment by Mitchell5200** [comment]
> Here's my log https://mclo.gs/2iEL4vo Really can't work out what's wrong here, any help is appreciated

You need to use Java 17, not 20 for the server

**Comment by Iceotty** [comment]
> > Here's my log https://mclo.gs/2iEL4vo Really can't work out what's wrong here, any help is appreciated
> 
> You need to use Java 17, not 20 for the server

thanks, it'd be helpful to have that stated somewhere (if it isn't already) as the assumption is that having multiple versions of java would be fine.
