### ISSUE TITLE
Trying to pin down an peculiar issue. 

### ISSUE THREAD

**Issue by Zen-Headshot** [AllTheMods/ATM-8#1585]
I host a small ATM 8 server using g-portal for 2 other friends, they're the only ones that know the IP, have the same pack version as the server, and i know they haven't given the IP to anyone else. I'm consistently getting a vanilla connection attempt refusal at ~20-40 minute intervals. Ive contacted g-portal, they've moved me to a new ip and i immediately received another one of the connection attempts. 
Here is a screenshot of the last couple days of logs, searching for said log string.
[https://i.imgur.com/OYcYqqq.png](Screenshot)
Here is the full log string including the previous line.
`[21Jul2023 18:06:44.464] [Netty Epoll Server IO #13/ERROR] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channels [voidtotem:totem_effect_packet,structure_gel:main,blue_skies:main,sfm:disk,potionsmaster:main_channel,systeams:recipe_version_check,xycraft_core:main,corgilib:network,compactmachines:main,aiotbotania:netchannel,tempad:main_channel,laserio:main_network_channel,reliquary:channel,hexerei:channel,toolbelt:general,mythicbotany:netchannel,moonlight:channel,littlelogistics:tug_route_channel,pylons:main,charmofundying:main,rechiseled:main,littlelogistics:vehicle_tracker_channel,libx:netchannel,endertanks:main_channel,polymorph:main,advgenerators:generators,minecolonies:net-channel,tombstone:tombstone_channel,travelanchors:netchannel,artifacts:main,phosphophyllite:phosphophyllite/configsync,compactmachines:room_tracking,waystones:network,hexal:main,itemcollectors:main,sebastrnlib:sebastrnlib,sophisticatedbackpacks:channel,computercraft:network,constructionwand:main,energymeter:network,mekanism:mekanism,hexerei:network,configured:play,alchemistry:main,gravitationalmodulatingunittweaks:gravitationalmodulatingunittweaks,productivebees:buzzinga,quarryplus:main,blueflame:fire_channel,ad_astra:main,curios:main,rebornstorage:main_channel,trashslot:network,universalgrid:main_channel,sophisticatedcore:channel,multipiston:net-channel,twilightforest:channel,mininggadgets:main_network_channel,utilitix:netchannel,modularrouters:main_channel,structurecompass:main,cfm:network,silentlib:network,simplemagnets:main,modonomicon:main,immersiveengineering:main,morphtool:main,cosmeticarmorreworked:main,alchemylib:main,littlelogistics:locomotive_channel,morered:main,mahoutsukai:main_channel,byg:network,lootr:main_network_channel,nochatreports:main,merequester:network,occultism:main,dpanvil:main,spirit:main_channel,botania:main,wirelesschargers:main,shrink:main_channel,framedblocks:main,supermartijn642configlib:sync_configs,quark:main,silentgear:network,bdlib:misc,supplementaries:network,platforms:main_channel,engineersdecor:default_ch,crafting_on_a_stick:main,buildinggadgets:main,tetra:main,sfm:manager,farmingforblockheads:network,ad_astra_giselle_addon:main,forge:tier_sorting,integratednbt:main,naturesaura:network,harvestwithease:main,caelus:main,rsgauges:default_ch,dummmmmmy:network,sophisticatedstorage:channel,advancedperipherals:main_channel,theurgy:main,hexcasting:main,create:main,tesseract:main,bdlib:multiblock,createaddition:main,comforts:main,phosphophyllite:multiblock/guisync,cookingforblockheads:network,mekanismgenerators:mekanismgenerators,elementalcraft:main,securitycraft:securitycraft,solcarrot:main,structurize:net-channel,fluxnetworks:network,patchouli:main,pneumaticcraft:main_channel,trashcans:main,dimstorage:net,geckolib3:main,ars_elemental:main,elevatorid:main_channel,sfm:labelgun,shetiphiancore:main_channel,refinedstorage:main_channel] rejected vanilla connections`

`[21Jul2023 18:06:44.464] [Netty Epoll Server IO #13/INFO] [net.minecraftforge.server.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.`

**Comment by Mitchell5200** [comment]
From my testing ages ago, this was some sort of bot spam from some datacentre in Europe, just pinging the default MC port
