### ISSUE TITLE
Dupe glitch on materials using CTRL + K

### ISSUE THREAD

**Issue by baegol** [AllTheMods/ATM-8#1588]
When using the bind CTRL + K to compress materials automatically in a crafting table, the material will proceed to create a compressed version over and over without using any materials. Basically an exponential dupe glitch for materials that can be compressed.

Version: 1.0.22

**Comment by joelra** [comment]
Was able to confirm this. Steps I took to produce:

1. Have a stack items of a compressable block like soul sand 
2. Interact with a workbench
3. Hover over the items of soul sand in your inventory with your mouse cursor
4. Press the key combination CTRL + K to compress the soul sand.
5. Repeat until the compression goes to the max level.

**Comment by Mitchell5200** [comment]
https://github.com/TwelveIterationMods/CraftingTweaks/issues/202

**Comment by HumdrumPanic** [comment]
seems to be fixed... tried with cobblestone it consumed the correct amount and cycled back down in to the original amount
