### ISSUE TITLE
Two in One! Light issue + Sophisticated Storage voiding items

### ISSUE THREAD

**Issue by PutNameHere42** [AllTheMods/ATM-8#1593]
Basically, build a dark room mob farm, everything worked perfectly, as intended.
I come back the next day, its fully lit up for some reason. In some spots light level 8, in some corners up to 13, with no light sources present. No feral flare lantern anywhere nearby.

Solution: Ended up having to break down the entire room and rebuild it, some blocks close by are still outputting high light levels for no reason (Smooth Stone for example)

Second issue: Sophisticated Storage Diamond Chest voiding items. 
Tested using an absorption hopper directly and a Pipez pipe.

No solution, seemed to do it no matter what, swapped to a small ME system instead.

**Comment by Tan1al0s** [comment]
I can confirm that Sophisticated Storage is voiding Items. I used it in combination with the Integrated dynamics mod deleted 2/3 of my Items. There was no errors in the log, just the missing items.

@PutNameHere42 You should create a Issue for each problem. This makes it easier to track and for other users to contribute. Thanks
