### ISSUE TITLE
[1.0.14] ATM crashes on launch

### ISSUE THREAD

**Issue by KacperRzadkowski** [AllTheMods/ATM-8#1596]
When launching atm 8 from the minecraft launcher launched by curseforge with error code 1. This issue persists when launching atm 9 as well, other modpacks dont have this issue. I have tried updating windows, JDK and nvidia drivers. I have also reinstalled both curseforge and deleted the .modpack/ folder.

OS: Microsoft Windows 11 Home
CPU: AMD Ryzen 9 with radeon graphics
GPU: Nvidia RTX 3070 mobile
RAM: 16gb

This is the error report I get during the crash:

 A fatal error has been detected by the Java Runtime Environment:

 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffea14d59f0, pid=14036, tid=11844

JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
 C  [atio6axx.dll+0x1759f0]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   https://github.com/microsoft/openjdk/issues
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Djava.library.path=C:\Users\kacpe\curseforge\minecraft\Install\bin\070ed366a79e785aad6a144f5fbab92d766cc08d -Djna.tmpdir=C:\Users\kacpe\curseforge\minecraft\Install\bin\070ed366a79e785aad6a144f5fbab92d766cc08d -Dorg.lwjgl.system.SharedLibraryExtractPath=C:\Users\kacpe\curseforge\minecraft\Install\bin\070ed366a79e785aad6a144f5fbab92d766cc08d -Dio.netty.native.workdir=C:\Users\kacpe\curseforge\minecraft\Install\bin\070ed366a79e785aad6a144f5fbab92d766cc08d -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.6.16 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-47.1.3.jar,forge-47.1.3 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=C:\Users\kacpe\curseforge\minecraft\Install\libraries --module-path=C:\Users\kacpe\curseforge\minecraft\Install\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;C:\Users\kacpe\curseforge\minecraft\Install\libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar;C:\Users\kacpe\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar;C:\Users\kacpe\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar;C:\Users\kacpe\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar;C:\Users\kacpe\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar;C:\Users\kacpe\curseforge\minecraft\Install\libraries/org/ow2/asm/asm/9.5/asm-9.5.jar;C:\Users\kacpe\curseforge\minecraft\Install\libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx4096m -Xms256m -Dminecraft.applet.TargetDirectory=C:\Users\kacpe\curseforge\minecraft\Instances\All the Mods 9 - ATM9 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dlog4j.configurationFile=C:\Users\kacpe\curseforge\minecraft\Install\assets\log_configs\client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username Kappepee --version forge-47.1.3 --gameDir C:\Users\kacpe\curseforge\minecraft\Instances\All the Mods 9 - ATM9 --assetsDir C:\Users\kacpe\curseforge\minecraft\Install\assets --assetIndex 5 --uuid 13800dc5cce346889774ee95bad91b42 --clientId ZWQ1MmJmNWYtN2JkZC00NTYzLTgyODUtODg4YWMwYzg2ZmU0 --xuid 2535452995957631 --userType msa --versionType release --width 1024 --height 768 --launchTarget forgeclient --fml.forgeVersion 47.1.3 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Host: AMD Ryzen 9 5900HX with Radeon Graphics        , 16 cores, 15G,  Windows 11 , 64 bit Build 22621 (10.0.22621.1928)
Time: Fri Jul 28 23:29:02 2023 W. Europe Summer Time elapsed time: 4.123032 seconds (0d 0h 0m 4s)

**Comment by Mitchell5200** [comment]
AMD GPU Driver issue, Reinstall/update drivers
