### ISSUE TITLE
[ATM-8 1.0.22] Digital Miner

### ISSUE THREAD

**Issue by Zethur907** [AllTheMods/ATM-8#1597]
The digital miner will not detect and mine diamonds. Using the tag forge:ores/diamond results in no ores being found even if it is placed directly next to a diamond ore. Using just forge:ores to mine every ore results in everything except diamonds being mined.

**Comment by camp00000** [comment]
using the tag filter "minecraft:diamond_ores" works for me as well as "forge:ores/diamond".

Did you make sure the height and radius settings are set correctly? You may have not set them or accidentally made an extremely small or high up radius which does not take into consideration the diamond ore you've placed & those that spawn naturally.

You can use the button at the top left of the digital miner interface to make it show the radius you've currently selected.
![image](https://github.com/AllTheMods/ATM-8/assets/76262772/1102b003-7fe3-4a28-93e9-cd1255fec4da)
![image](https://github.com/AllTheMods/ATM-8/assets/76262772/a25cf922-9c3e-4086-b2dd-64a010f0a1c8)
