### ISSUE TITLE
mismatched mods list

### ISSUE THREAD

**Issue by Cdreese** [AllTheMods/ATM-8#1599]
![Capture](https://github.com/AllTheMods/ATM-8/assets/89426941/f34288e1-6893-41dd-b4c8-241ff1a6f6d1)

i don't know why it says that when I downloaded all the right things and it still says mismatched mods im using hostigner server hosting

**Comment by camp00000** [comment]
Double check that the version of the modpack the server's using is the **exact** same as the one your client has.
If your host has a preset for ATM8, they may still be using an older/outdated version of ATM8, providers don't update all that fast usually.

You can manually change your client's version of ATM8 in the curseforge launcher.
