### ISSUE TITLE
Mekanism Induction Quest glitched

### ISSUE THREAD

**Issue by ethanouu** [AllTheMods/ATM-8#1603]
Hello, i'm at the quest "Building the Induction Matrix", i crafted all required supplies, the induction casing and port quest part are completed. But for the structural glass i crafted more than 55 and it's stuck at 44/55. I try to disconnect, drop glass and to build the Induction Matrix but nothing happend. Maybe can i bypass the quest ? ty

**Comment by alfredggttv** [comment]
Sometimes this is just a bug that happens. Hopefully the newer FTBquest compat mod fixes this issue, otherwise you can use the /ftbquest complete command to fix it, or by turning on editing mode and completing the quest that way.
