### ISSUE TITLE
Complimentary Shaders missing Ars Nouveau Trees

### ISSUE THREAD

**Issue by WesCook** [AllTheMods/ATM-8#1614]
Complimentary Shaders has leaves for a number of mods whitelisted, but not Ars.  As a result they do not sway in the wind.

This can be fixed in the /shaders/block.properties file, by appending these entries to `block.18`.

    ars_elemental:yellow_archwood_leaves ars_nouveau:blue_archwood_leaves ars_nouveau:purple_archwood_leaves ars_nouveau:green_archwood_leaves ars_nouveau:red_archwood_leaves

You might notice the yellow leaves are under a different mod ID for some reason.

I've not tested Complementary Reimagined, the other included shaderpack, or many other trees.  I just noticed this and fixed it locally.

**Comment by Mitchell5200** [comment]
We cannot distribute a custom version of Complementary without a bunch of changes, this instead needs to be fixed by the Complementary dev.
