### ISSUE TITLE
KubeJS Error

### ISSUE THREAD

**Issue by CrazyDev05** [AllTheMods/ATM-8#1632]
I just made a completly new installation and kubejs throws errors
[latest.log](https://github.com/AllTheMods/ATM-8/files/12313322/latest.2.log)
[server.txt](https://github.com/AllTheMods/ATM-8/files/12313323/server.txt)

**Comment by logitek184** [comment]
there are a few client side mods that need to be disabled
AbstractContainerScreen
ParticleEngine
TextureAtlas
SoundInstance
Sheets

**Comment by logitek184** [comment]
disable those and it should be good

**Comment by Mitchell5200** [comment]
> there are a few client side mods that need to be disabled AbstractContainerScreen ParticleEngine TextureAtlas SoundInstance Sheets

@logitek184 Literally none of those are mods, they are all methods inside of the mods, and have nothing to do with the KubeJS Error posted.



> I just made a completly new installation and kubejs throws errors [latest.log](https://github.com/AllTheMods/ATM-8/files/12313322/latest.2.log) [server.txt](https://github.com/AllTheMods/ATM-8/files/12313323/server.txt)

I am aware of the intermittent tags error @CrazyDev05 and am looking into it, it should disappear on a restart, i am also aware of the cause of the warnings, and am waiting on the devs of Steam and rails to release a mod update that fixes all of that.
