### ISSUE TITLE
ATM8 server 1.0.22 creative items have no recipies in JEI and seem to miss quests

### ISSUE THREAD

**Issue by Madegam** [AllTheMods/ATM-8#1634]
ATM8 server 1.0.22 creative items have no recipes in JEI and seem to miss quests.
I have attempted to search crafting recipes for items like the ATM star however there is no crafting recipe to create it via the Create mod crafting blocks and is only able to be crafted by converting the block into the 9 stars.
This is one example of a recipe missing, all items under the "Creative" tab in the quest line are missing recipes.
I can confirm that this is all available on the single player version.

**Comment by Mitchell5200** [comment]
sounds like your server was not installed correctly if it's a host with a auto installer, speak to them about it, if not, you need to upload the entire contents of the server pack we release alongside each pack update, to the server folders

**Comment by Madegam** [comment]
It is a self hosted server - I have done the upload correctly as far as i can tell, is there a specific folder that may be missing/in the wrong place for JEI or the recipies?

**Comment by Mitchell5200** [comment]
you likely only uploaded the mods folder, and maybe configs, you need to upload [`config`,`defaultconfigs`,`kubejs`,`mods`,`packmenu`], maintaining that folder structure

**Comment by Madegam** [comment]
Ok, i have just gone back and reinstalled those files [config,defaultconfigs,kubejs,mods,packmenu] and i can confirm the world now has the recipes. I couldve sworn i had installed each of these files the same as i just did already but i guess not.
Thank you for your help :)

Ps, is ATM8 still supported for updates? i see in the quests at the end of "part 2: To The End", it mentions "Stay tuned for part 3: To the star!", is the going to ever be released or is it something im just yet to unlock later along the line?

**Comment by Mitchell5200** [comment]
updates, yes, there's an update planned for this weekend, i'll need to bug @alfredggttv about that pt3 bit though
