### ISSUE TITLE
ATM8 Server not starting at all

### ISSUE THREAD

**Issue by Bluemethyst** [AllTheMods/ATM-8#1638]
trying to start ATM8 server, worked fine on my computer, tried it on another machine and this error shows. I used the setup files that come with the server files downloaded from curseforge so everything should be the right version. log is below and screenshot below that is what shows after the server stops.
[latest.log](https://github.com/AllTheMods/ATM-8/files/12326645/latest.log)
![image](https://github.com/AllTheMods/ATM-8/assets/88925092/75611420-6cdd-4124-9845-4d1705676823)

**Comment by Mitchell5200** [comment]
you need to use Java 17, not java 20, to run the server.

**Comment by Bluemethyst** [comment]
I am running on java 20, i saw the other thread, 
![image](https://github.com/AllTheMods/ATM-8/assets/88925092/b1ed3328-10a1-49d7-a596-cda480a7e161)
