### ISSUE TITLE
Game lags when using JEI through refined storage terminals.

### ISSUE THREAD

**Issue by GabFran** [AllTheMods/ATM-8#164]
Modpack version: 0.1.7
Server Type: Dedicated

When checking the recipes and uses for a few items through JEI inside a refined storage crafting terminal, such as items with no further uses in crafting, aswell as other apparently random items (Create's Water wheel, Magma blocks, Pistons, etc...) the game drops to 0-1 FPS, causing the CPU usage to ramp up to 100%.

This doesn't cause the game to crash, just makes it extremely slow, so you can still press esc to exit the interface after waiting a couple seconds.

I am only able to reproduce this in multiplayer (dedicated server).

**Comment by starixed** [comment]
ive been getting it too in single player, but its only with like certain recipes ive noticed for example industrial foregoing pity machine block causes tons of lag an nearly freezes my game

**Comment by starixed** [comment]
it seems only refined is doing it. switched back to AE2 and everything seems ok

**Comment by Xplodin** [comment]
oddly it seems to lag me whenever I use U/uses button (right click) on recipes

Only that and it causes me to have to use jei search for the exact recipe

**Comment by starixed** [comment]
yeah thats why im considering going back to ae2, the lag is just insane when trying to craft something an look up recipes

**Comment by twixthehero** [comment]
i saw this issue occur with AE2. i thought it was related to "syncing" the searchbar with JEI so we had players disable that functionality in terminals

**Comment by MoeHunt3r** [comment]
I'm actually doing some testing and for now it seems that this happens only when there is an crafting recipe with create machines. (singleplayer)

**Comment by Jophire** [comment]
Also occurs in the Integrated Dynamics terminal when looking up many of the same recipes that have already been mentioned. I am pretty sure it has to do with any recipe that uses forge:wood, forge:plank, or forge:stone or other tag that is really common.

**Comment by starixed** [comment]
but what is weird to me is since ive switched to AE, i have not had a single issue with recipe freeze up or lag. 
With update 8-0.1.9, i tested RS again and it still freezes up. Cant say anything about integrated dynamics because ive never touched that mod.

I dont know what AE is doing different behind the scenes but its not buggy like others

**Comment by SuperSpaceMan230** [comment]
Happens with Industrial Foregoing's Pity Machine Frame specifically on my end, on version 1.0.1

**Comment by Quinteger** [comment]
This happens with recipes that have a lot of alternatives (wood, stone, glass, etc) and when you have a lot of items in your grid, due to the way that RS-JEI compat is implemented.
