### ISSUE TITLE
Mekanism: Metallurgic Infuser Problem/Question!!

### ISSUE THREAD

**Issue by Lagorsirion** [AllTheMods/ATM-8#1640]
Hello,

I'm trying to set up autocraftiung for "Infused Alloy" with Mekanism and AE2 and it should work but I got the Problem that I can't turn on "Auto-eject" for Infuse Types. It says "Auto-eject is not supported, manuel extraction may still be possible", is that intended? And why?

My theoretical Setup is as followed:
Pattern 1:
1 Redstone -> Enriching Factory -> 1 Enriched Redstone
Pattern 2:
**_1 Enriched Redstone -> Metallurgic Infuser 1 -> 80mB Redstone_**
Pattern 3:
8 Iron Ingot + 80mB Redstone -> Metallurgic Infuser 2 -> 8 Infused Alloy

I've got my chemical storage cell in AE2 set up to store the 80mb Redstone between the two crafts, so that shouldn't be the problem.

I could work around that problems with chests but that only would be my last resort if it can't be resolved for whatever reason.

So maybe someone can help solve the problem? Pls

Edit:
The direct approach with
"8 Iron Ingot + 1 Enriched Redstone -> Metallurgic Infuser -> 8 Infused Alloy"
also doesn't work. I tryed that too. At least doesn't work without chest inbetween the Pattern provider and the Metallurgic Infuser... But i'm trying to avoid using clunky chest setups.

**Comment by camp00000** [comment]
For the mekanism enrichment autocrafting I usually setup an enrichment factory per material, so one with redstone, one with coal (carbon), dia, obsidian, etc.
Although it means multiple machines for what could be done in one, it works without issue if you use exporters (optimally with a crafting upgrade) to always keep the enrichment factories full.
