### ISSUE TITLE
atm8 server 1.0.23

### ISSUE THREAD

**Issue by anerikse** [AllTheMods/ATM-8#1650]
Hi

After some days my server wont start normal.

I had quarrys up and running, saved server and closed it.

Next time i started the server i says: Set QuarryPlus ic2 integration to false

found a .toml file and in the bottom there is settings for QuarryPlus ic2 integration. but dont understand what to do. 

Anyone?

**Comment by glitchking007** [comment]
If you haven't added any mods to the server then you don't need to worry about "Set QuarryPlus ic2 integration to false"
Its doing that because the pack doesn't contain the mod IC2. So if the server is failing to start your problem is probably elsewhere.

**Comment by anerikse** [comment]
Thank you. That was not the problem.
