### ISSUE TITLE
Apotheosis config

### ISSUE THREAD

**Issue by Slither224** [AllTheMods/ATM-8#1652]
Apotheosis bosses wont spawn in my end and you cant even access the config to try to fix it

**Comment by Mitchell5200** [comment]
Looking at the apotheosis configs, the base spawn rules were changed to not spawn bosses on the main End island, or anywhere within 1024 blocks of 0,0. I have also just tested this and confirmed that i am getting boss spawns while not at the main end island.

current spawn rules in the apotheosis adventure config
https://github.com/AllTheMods/ATM-8/blob/b27a5d9f46e33d4eb19d471c60320d7061ff72b6/config/apotheosis/adventure.cfg#L125-L130
`SURFACE_OUTER_END` code definition below
https://github.com/Shadows-of-Fire/Apotheosis/blob/b21ef6bb1dc840332f10feeb7eca42c318b7a5bc/src/main/java/shadows/apotheosis/adventure/boss/BossEvents.java#L188-L190
