### ISSUE TITLE
Queueing craftable items causes issues in AE2WTLib universal terminal

### ISSUE THREAD

**Issue by Cavin-V** [AllTheMods/ATM-8#166]
Something I've noticed while using the univeral terminal from AE2TWTLib is that when middle clicking to craft autocraftable items in a network, instead of bringing up the crafting menu as expected, it instead sorts the entire inventory as if one had middle clicked a chest to sort it.

Problems with this, as one may expect, are that a universal terminal is not designed to be sorted like a chest, and often puts items into slots they should not belong in.
Because the terminal has an armor area, this means even armor can be unequipped and put into the crafting table, or even the trash slot of the terminal itself.

However most of this can be solved by simply putting one's armor back on and items back where they belong, but there are certain problems with even this.
If one may be connected to their network using a quantum entangled singularity, and using a quantum bridge card on the universal terminal, these items will get sorted as well, causing the terminal, due to being in most cases out of range of the ME system, become unable to be opened again to put the items back in place, forcing you to travel back to within normal wireless range of your system to fix.

Naturally, my first attempt to fix this on my own was to try and unbind all controls from middle click to avoid anything sorting the inventory, but the terminal still sorts.

While this may be as simple as sleuthing through the mods list to discover what mod is sorting inventories, finding whatever config  may be available and fixing it that way, this problem would still exist for anyone else playing the pack, and so I thought to create an issue for it.

**Comment by Happy-Hubba** [comment]
Same Issue for the Wireless Crafting Terminal from AE2!
