### ISSUE TITLE
Server edition Outdated

### ISSUE THREAD

**Issue by Possemaster** [AllTheMods/ATM-8#1660]
This morning all my members could not login and noticed that there was an update x.24 but server files are still on x.23.
This is the second time this happens now everyone needs to rollback.
Please update server files.

**Comment by Mitchell5200** [comment]
The files have already been uploaded to CF, when the pack update was, they are just still stuck in manual review for some reason.
direct download link --> https://mediafilez.forgecdn.net/files/4711/952/Server-Files-1.0.24.zip
