### ISSUE TITLE
SOL Config issue 

### ISSUE THREAD

**Issue by CosmoPoptart** [AllTheMods/ATM-8#1662]
hello, so I recently started a new ATM8 playthrough and I went into spice of life Config in my files to change "resetOnDeath" to false but when I died I still lost my hearts. I then found a post saying to change it in the in game options but When I go to do that It instantly reverts back to true when I set it to false even though I saved how do I make the change permeant so I don't loose hearts on death from the Spice Of Life mod.

**Comment by Mitchell5200** [comment]
`/saves/<savename>/serverconfig/solcarrot-server.toml` is the actual file, close the game first before editing
