### ISSUE TITLE
I found a bug (crafting 2x2 Drawer)

### ISSUE THREAD

**Issue by inoobdroid** [AllTheMods/ATM-8#1663]
Normal recipe:
![image](https://github.com/AllTheMods/ATM-8/assets/128005562/512fb2a8-f0bd-433c-8635-3c3a89b72cfd)
I think its the wrong recipe:
![image](https://github.com/AllTheMods/ATM-8/assets/128005562/7f347a55-dd62-4b7f-8522-29751fe29888)

**Comment by Mitchell5200** [comment]
not really a bug, new feature of Functional storage, will be disabled https://github.com/Buuz135/FunctionalStorage/blob/main/src/generated/resources/data/functionalstorage/recipes/oak_drawer_alternate_x1.json
