### ISSUE TITLE
[1.0.25] Mystical Agriculture Quest is wrong

### ISSUE THREAD

**Issue by WaterKing201030** [AllTheMods/ATM-8#1666]
After the update, now the infusion crystal has been split into 5 tiers. But the quest requires the old infusion crystal.
![2023-08-21_14 48 30](https://github.com/AllTheMods/ATM-8/assets/73704964/eb05fb7c-933c-4919-9794-c8ec829627f0)
![2023-08-21_14 48 37](https://github.com/AllTheMods/ATM-8/assets/73704964/6dbd921e-3d1d-4525-b572-c8b9061e5b28)

**Comment by flarefluffsune** [comment]
You can use /ftbquests editing_mode, which doesn't require cheats enabled, and then you can right click on the quest and select "Complete Now" and it will mark it as completed. You won't get any rewards, not that the rewards are anything exciting to begin with so It didn't really matter to me.

**BIG WARNING:** Make sure you are right clicking on the quest task and select Complete, **DO NOT USE THE GEAR WHEEL ON THE RIGHT TO "COMPLETE TASK" IT WILL COMPLETE EVERY SINGLE QUEST IN THE ENTIRE BOOK**. As I found out. The one and only time I've ever used a backup.
