### ISSUE TITLE
Unable to find Silent Gears' Bort Ore in the overworld

### ISSUE THREAD

**Issue by Veggetossj** [AllTheMods/ATM-8#167]
Have been playing for last 2 weeks on ATM8 and have yet to find any of Silent Gears' Bort Ore in the overworld underground, I have asked other people on the server i play on and they havent found any either.

Is it not being generated? if it is, where? What height are they more frequent?

**Comment by P0kys** [comment]
Did a quick check with a replace command and it seems like it's not spawning at all. Not sure if this is intended
