### ISSUE TITLE
Startup Issue can't start modpack

### ISSUE THREAD

**Issue by Fortnitegamer47** [AllTheMods/ATM-8#1671]
**spent over 5 hours trying to fix the startup issue updated drivers and tried solutions from others but still not fixed so i hope i can find the solution here. I'm using cursedforge to launch the modpack**
[hs_err_pid13780.log](https://github.com/AllTheMods/ATM-8/files/12423423/hs_err_pid13780.log)

**Comment by Mitchell5200** [comment]
fix here --> https://github.com/AllTheMods/ATM-9/issues/211

**Comment by Fortnitegamer47** [comment]
Thank you a lot much swag
