### ISSUE TITLE
No vanilla chest recipe using Refined Storage

### ISSUE THREAD

**Issue by James31047** [AllTheMods/ATM-8#1672]
You cannot make a Minecraft oak chest using Refined Storage crafting. The recipe defaults to a Quark oak chest and then you cannot convert the Quark oak chest to a Minecraft oak chest.

**Comment by camp00000** [comment]
You can add the oak chest crafting recipe and then add another recipe which crafts the oak chest into a vanilla chest 1:1
Just manually drag the oak chest into the left field from JEI or from your inventory and it should work, that did the trick for me.


The drawback being it'll always only use oak planks to make chests but as long as you have mystical agriculture or a tree farm to solve that it's all good.

**Comment by James31047** [comment]
The problem I am referring to is in making a vanilla oak chest using the RS crafting grid. With the latest update, the ability to convert a chest from Quark to Vanilla has been lost. All I can do is convert a quark oak chest to Functional Storage.

**Comment by bbf** [comment]
+1

I can't even teach a RS Crafter and use a processing recipe to workaround since they also do not support alternative recipes like player crafting.
