### ISSUE TITLE
Refined Storage Patterns in Extra Storage Crafters were deleted 

### ISSUE THREAD

**Issue by James31047** [AllTheMods/ATM-8#1673]
I had a full Netherite Crafter from Extra Storage that had all of the patterns deleted. I had updated from 8-1.0.23 to 8-1.0.25 soon before realizing the patterns were gone.

**Comment by xkobalx** [comment]
A user on my server experienced this issue. The recipes reappeared after they removed and replaced a speed upgrade. Since removing upgrades from the netherite crafter the problem has not happened again.

**Comment by James31047** [comment]
I did not have speed upgrades installed.
