### ISSUE TITLE
Silent gear hammer/excavator not working

### ISSUE THREAD

**Issue by Magesticles** [AllTheMods/ATM-8#1674]
Silent gear hammer/excavator now only break one single block rather than 9 after the most recent update.

**Comment by flarefluffsune** [comment]
Its working perfectly fine for me. I believe it disables the 3x3 digging if you hold shift. You could try redownloading the pack, perhaps maybe it didn't download the right version of the mod, or delete the config located in the config folder (silentgear-common.toml, silentgear-client.toml).

**Comment by Magesticles** [comment]
> Its working perfectly fine for me. I believe it disables the 3x3 digging if you hold shift. You could try redownloading the pack, perhaps maybe it didn't download the right version of the mod, or it could be a config fault so delete the config located in the config folder (silentgear-common.toml, silentgear-client.toml), then it should generate a new config file.

thanks reinstalling fixed it.
