### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Ashton273546** [AllTheMods/ATM-8#1676]
when I hit play from the curseforge launcher, then hit play on the Minecraft launcher, the game crashes then pops up with error code 1.  

this is the crash report, I have no idea what any of it means.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa05146280, pid=19572, tid=18384
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x196280]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Dos.name=Windows 10 -Dos.version=10.0 -Xss1M -Djava.library.path=C:\Users\ashto\curseforge\minecraft\Install\bin\bbf5b7666d51425c216f01d73e4bfdeec111882e -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.7.12 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-43.2.14.jar,forge-43.2.14 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=C:\Users\ashto\curseforge\minecraft\Install\libraries --module-path=C:\Users\ashto\curseforge\minecraft\Install\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;C:\Users\ashto\curseforge\minecraft\Install\libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar;C:\Users\ashto\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar;C:\Users\ashto\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar;C:\Users\ashto\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar;C:\Users\ashto\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar;C:\Users\ashto\curseforge\minecraft\Install\libraries/org/ow2/asm/asm/9.3/asm-9.3.jar;C:\Users\ashto\curseforge\minecraft\Install\libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx8672m -Xms256m -Dminecraft.applet.TargetDirectory=C:\Users\ashto\curseforge\minecraft\Instances\All the Mods 8 - ATM8 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dlog4j.configurationFile=C:\Users\ashto\curseforge\minecraft\Install\assets\log_configs\client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username Ashton273546 --version forge-43.2.14 --gameDir C:\Users\ashto\curseforge\minecraft\Instances\All the Mods 8 - ATM8 --assetsDir C:\Users\ashto\curseforge\minecraft\Install\assets --assetIndex 1.19 --uuid d56992c6f88b46a6b5c5994ca1728f0a --clientId NDkzMDI4ZWUtOTliZi00ZjRiLWIyMjctYzBjNjJhODAwMGQ2 --xuid 2535435761579343 --userType msa --versionType release --width 1024 --height 768 --launchTarget forgeclient --fml.forgeVersion 43.2.14 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Host: 12th Gen Intel(R) Core(TM) i5-12400F, 12 cores, 39G,  Windows 11 , 64 bit Build 22621 (10.0.22621.2215)
Time: Fri Aug 25 12:05:07 2023 Eastern Daylight Time elapsed time: 20.886968 seconds (0d 0h 0m 20s)

**Comment by Ashton273546** [comment]
I updated my amd driver then tried it again and it came up with the same thing

**Comment by fred44e** [comment]
happens to me to

**Comment by Mitchell5200** [comment]
Below from ATM Discord,

The `atio6axx` "Problematic frame" in a `hs_err_pid` file, is part of the **AMD** driver for the **GPU**, there's a bad version of the AMD drivers that instantly crashes on an OpenGL task, 
Reinstall/Fresh install your drivers from https://www.amd.com/en/support

**IF** you do not have an **AMD GPU**, then you need to set your system to be using that GPU instead of the AMD integrated GPU on the CPU, steps below.
https://i.imgur.com/TH7lPhr.png
