### ISSUE TITLE
0.1.7 Cannot play Lan hosted servers

### ISSUE THREAD

**Issue by TheMasterTM69** [AllTheMods/ATM-8#168]
This issue has been present in previous version as well but after updating there is still no possibility of playing on a LAN hosted server.

I remember that ATM7? Had some similar issues at the beginning but it was caused by like one life on code which could be the case again? 

This is the error that pops up when trying to join:
![unknown](https://user-images.githubusercontent.com/75620187/197510218-ca5c6b59-bbfe-4dfb-a1a4-cefc681a08fa.png)

No matter how many times you try it will not allow to join.

**Comment by sanyi** [comment]
same happens to me ""lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException""

**Comment by sanyi** [comment]
Yes, loaded my save intro "proper" server and works that way, everyone can join, thank you.
