### ISSUE TITLE
Unable to craft Natural Source Seeds from Elemental Craft

### ISSUE THREAD

**Issue by Gowcu** [AllTheMods/ATM-8#1680]
I have the earth receptacle and the artificial seed, but when i go to craft it there's nothing in the output slot. Is this intended behavior? i thought at first that it may be an unlocked recipe, but even after learning about it in the Elementopedia im still unable to craft it.

im on ATM 8 version 1.0.19b

Elemental craft version 5.8.4

**Comment by Traxexhunter** [comment]
the crafting table recipe dont work , but create mixer recipe work for it  ( i think the problem is NBT data of receptacle , crafting table expect the same NBT as what shows in JEI )

**Comment by Gowcu** [comment]
im now on ATM8 1.0.28 and this is still an issue. now not even the create mixer will make this recipe.

**Comment by Gowcu** [comment]
nevermind, it looks like it's the artificial trait that's preventing it from crafting in the mixer
