### ISSUE TITLE
[ATM8-1.0.22] Minecolonies not updating and tag issues

### ISSUE THREAD

**Issue by Carooosa** [AllTheMods/ATM-8#1692]
Minecolonies has not been updated with the rest of the mods in ATM8. It also looks like the raw ore in AllTheOres are not tagged with the "raw_ore" tag, making it incompatible with some aspect of minecolonies.

**Comment by Mitchell5200** [comment]
Closing as the latest pack version is 1.0.25, and minecolonies has been updated several times between .22 and .25.
Taking Raw tags issues under advisement
