### ISSUE TITLE
Bleeding Effect

### ISSUE THREAD

**Issue by Hyskill** [AllTheMods/ATM-8#1696]
Hey, 

I have the bleeding effect from MahouTsukai but it's don't stop, always bleeding again and again.. I don't even strat this mod, i was doing nuclear waste, plutonium etc. 
First I think it's was radiation, but even if i exit the compact machine... 
I try to clear effect with a command, but it come back.. I don't understand why.. if it's me or a bug.. 
Do you know how to help me? 

(English it's not my langage, so.. i hope you will understand  me..) 
![Capture d'écran 2023-05-14 163101](https://github.com/AllTheMods/ATM-8/assets/112015720/051d8c1f-40e3-4955-931b-f719902157ae)

**Comment by Mitchell5200** [comment]
Closing as bleeding is just the natural effect of taking damage and when irradiated you always take damage.

**Comment by funnycubeguy** [comment]
Is there a way to clear this? This happened to me no radiation nothing I cleared it all. Timer keeps resetting

**Comment by Azmaveth117** [comment]
> Is there a way to clear this? This happened to me no radiation nothing I cleared it all. Timer keeps resetting

If its not a hardcore world, die (IN MINECRAFT), then exit and save, open the mahou tsukai config and turn on bleeding from dagger only, its what I just did and I think it should fix it.

**Comment by Azmaveth117** [comment]
> > Is there a way to clear this? This happened to me no radiation nothing I cleared it all. Timer keeps resetting
> 
> If its not a hardcore world, die (IN MINECRAFT), then exit and save, open the mahou tsukai config and turn on bleeding from dagger only, its what I just did and I think it should fix it.

update, that didnt work, and getting damage every 4 seconds is starting to make me want to put a whole in my wall

**Comment by funnycubeguy** [comment]
I figured it out being radiation. Had to kill myself and respawn then clear radiation with mekanisms command

**Comment by Louie365** [comment]
Same issue here. It is not radiation and nothing is hitting me. It is not constant but from time to time i just get damaged.

**Comment by laprizplays-ctrl** [comment]
For anyone coming here for answers, I think i fixed it. It's probably cause by Apotheosis and what was happening for me was that i had a target dummy that was constanly hurting after i tried my newly upgraded weapon on it. I noticed i was hurting along with the target dummy for some reason, so i just destroyed it and it stopped my hurt.
