### ISSUE TITLE
JEI Crash With Search Bar

### ISSUE THREAD

**Issue by BayTavukYT** [AllTheMods/ATM-8#1700]
When I type in "gu" in the search bar game suddenly freezes and then a few seconds later the game crashes. I didn't check for other keywords but I have replicated this crash several times. All the times replicated gave the same result.

Crash Log: https://mclo.gs/7asqG4X
Game Log: https://mclo.gs/vchbfOq
ATM8 Version: 1.0.25

Steps to reproduce crash:
1. Start up ATM8
2. Launch any world
3. Open inventory
4. Type "gu" in the JEI search bar

Note: The world doesn't corrupt. Just a client sided crash and also KubeJS seems to give an error but I have no idea how to work with KubeJS or its errors so there might not be a KubeJS crash.

**Comment by Mitchell5200** [comment]
Seems to be caused by `CustomSkinLoader_ForgeActive-14.15-SNAPSHOT-353.jar`, as that's not part of the pack by default, and i cannot reproduce this issue in a clean ATM8 install, i'd suggest removing that mod, and anything that depends on that mod and testing again, then report to the mod dev

**Comment by BayTavukYT** [comment]
Oh god I feel like a dumbass after your comment. And yes it was the CustomSkinLoader that was causing it (I am fairly surprised because why would that mod cause such trouble?) I forgot that I even added that. Thanks again
