### ISSUE TITLE
11.9.2023 Update broke Iron Jetpacks

### ISSUE THREAD

**Issue by PrometheanExile** [AllTheMods/ATM-8#1704]
The new update to Iron jetpacks has caused the mod to disappear from JEI and the creative spawn menu and converted existing jetpacks into 'Undefined Jetpack'

I have confirmed that all configs are normal so I'm not sure if this is an issue with the mod or if something else in the Update has disabled them or what.

**Comment by 4risu** [comment]
Downgrading IronJetpacks to 6.0.4 does fix the issue for me.
