### ISSUE TITLE
Laser Drill doesn't mine ancient debris

### ISSUE THREAD

**Issue by Bradderz654** [AllTheMods/ATM-8#171]
I have recently noticed that when I set up a laser drill from industrial foregoing in the correct biome to mine ancient debris it instead mines nickel. They both use the same laser lens and I cannot get a single peice of debris from any of my drills in any of the whitelisted biomes.

**Comment by chadle01** [comment]
same, updated today to see if it would fix it but no ancient debris, right biome lens mining level etc.

**Comment by Bradderz654** [comment]
> same, updated today to see if it would fix it but no ancient debris, right biome lens mining level etc.

I just hope they see this an maybe push a fix or something

**Comment by CStumpf8721** [comment]
Same problem with Unobtainium in the End Highlands. Ore Laser Base is setup with JEI Information.

**Comment by Happy-Hubba** [comment]
I tried to get Vibranium from the lasers and it seems that JEI does not represent the actual values. I didn´t get the 99 weight glowstone dust once but i got 7 stacks of peridot ore (1 weight) in less than an hour. Btw 0 vibranium. Same for allthemodium.

**Comment by dualmacops** [comment]
yep, no allthemodium raw ores too
