### ISSUE TITLE
Main Questline, Chapter 1 quest progression seems bugged?

### ISSUE THREAD

**Issue by Luukver** [AllTheMods/ATM-8#1713]
Hi,

just updated to ATM 8-1.0.27. No changes to the default configuration.
Started server with ATM 8-1.0.25.

Any quests beyond the first 2 in this chapter appears to be impossible to complete without overriding it in the editor.
We thought this was supposedly fixed in a update after 1.0.25. Except that we just updated and it's still not working.
Initially i figured it's just the tools that don't seem to be registered but it's other items as well. the quest says 100% when hovering over it or pinning it. and there is a greyed out checkmark. which tells me there is some other quest i need to complete but isn't listed?

Maybe i need to update the quest file separately and missed it?
Any tips to resolve this would be appreciated.

L

**Comment by alfredggttv** [comment]
This is due to a bug with teams, I believe. Were you on a team before and switched?
