### ISSUE TITLE
Electrolytic Separator

### ISSUE THREAD

**Issue by Hossam-Sami** [AllTheMods/ATM-8#1719]
After the last update of All The Mods 8 (1.0.27), I have noticed that the Electrolytic Separator doesn’t seem to take water as an input by using universal pipe or a fluid pipe.

**Comment by v1lev** [comment]
There is also no more recipe for making oxygen from water directly, but one can pump water into an electrolytic separator and make it broken. This looks like a bug.

The way I found to make oxygen after the update is to use an electric pump with filter.

**Comment by v1lev** [comment]
Seems fixed in the latest release (1.0.28)

**Comment by Hossam-Sami** [comment]
thank you so much sir
