### ISSUE TITLE
Allthemodium alloy paxel is a sword in /apoth loot_category (cannot add extra fortune / mine speed)

### ISSUE THREAD

**Issue by SmashinSkull** [AllTheMods/ATM-8#1726]
If you hold an allthemodium alloy paxel and type /apoth loot_category it will tell you that it is recognized as a sword. This means that then reforging the item you are unable to get any stats related to mining speed or fortune which is very important in a paxel.

**Comment by Mitchell5200** [comment]
![2023-09-28_20 39 55](https://github.com/AllTheMods/ATM-8/assets/45913837/d17db789-c850-4810-ab3f-86e0cd41200d)
Just tested in my main world with a paxel in hand in pack version 1.0.27, and it's set correctly there, and in the Apoth configs as well.
https://github.com/AllTheMods/ATM-8/blob/9799f28478ad1736d60974c8bd12258a3149fe0b/config/apotheosis/adventure.cfg#L5-L13
