### ISSUE TITLE
Unable to start server(ATM-8 1.0.25)

### ISSUE THREAD

**Issue by user6606** [AllTheMods/ATM-8#1728]
I downloaded Server-Files-1.0.25a.zip from www.curseforge.com and ran startserver.sh
![error](https://github.com/AllTheMods/ATM-8/assets/103115555/386d2e47-ab73-48a4-a2b6-3ac43da27e9d)

Thank you for any help.

**Comment by Mitchell5200** [comment]
I have no idea what `il8nupdatemod` is, but the issue is likely with that
