### ISSUE TITLE
Enable HTTP API support in computercraft-server.toml in default configs

### ISSUE THREAD

**Issue by Spleenczar** [AllTheMods/ATM-8#1735]
I'm unsure if this is disabled intentionally or it was just never enabled, but the HTTP API is arguably the most important thing in ComputerCraft and enabling it should really be considered. The ability to get programs from the internet is a core component of the mod that lets non-programmers actually make use of it, and lets programmers write their code in a proper editor then import it into the game  instead of using the extremely basic CraftOS.

Please enable it 🙏 the mod sucks without it, and it's not "overpowered" as some might say, it literally just saves you from having to copy code line-by-line into the editor.

**Comment by Ziplogcom** [comment]
This is true. I don't understand who thought not having to use the bog-basic edit program and instead being able to use VS Code is an "overpowered" ability, but it really isn't.

**Comment by Mitchell5200** [comment]
No, intentionally disabled
