### ISSUE TITLE
Wooden Sword recipe broken

### ISSUE THREAD

**Issue by Jensran** [AllTheMods/ATM-8#174]
The wooden sword recipe is broken. Cannot progress with Bees.

**Comment by DTibbs** [comment]
+1 
Version 0.1.7

Recipe for wooden sword results in a wooden shovel.

Possibly related, the recipe for stone shovel results in a stone sword.

**Comment by HaylingZar** [comment]
https://github.com/AllTheMods/ATM-8/issues/153 

Potential fix is to change the above quark setting server-side

**Comment by Mopar** [comment]
Check out the pull requests. There is one there that properly fixes it, along with some other crafting issues. I have applied it to my server and so far no other crafting issues have come up.
