### ISSUE TITLE
atm 8 with Essential mod

### ISSUE THREAD

**Issue by MCGAMER27** [AllTheMods/ATM-8#1740]
Me and my friend are playing atm 8 with the Essential mod but he cant see all the recipes from just enough item (jei) even if we are in a team the quest are working only the recipes not

**Comment by PhweeDev** [comment]
Similar issue here

**Comment by PhweeDev** [comment]
Spent over 24 hours looking into this. Seems to be a combination of Alchemistry AND The KubeJS scripts. Hopefully the ATM devs can look into this

**Comment by Mitchell5200** [comment]
From what i've been told https://www.curseforge.com/minecraft/mc-mods/e4mc is a better mod for multiplayer world sharing than "Essential"
