### ISSUE TITLE
[ATM8 - 1.0.28] Crash on using numpad on multiplayer connection screen

### ISSUE THREAD

**Issue by falt4** [AllTheMods/ATM-8#1743]
While inputting an IP address to connect to a server, every time the "8" or "9" key is pressed on the number pad of my keyboard, the game crashes. This happens when Num Lock is enabled and when it is disabled. 
This crash does not occur while using the number row above the main section of the keyboard. 
This crash does not occur while actually playing the game (either in JEI or just while walking around the world). 
This crash DOES occur regardless of if you have the text box selected. 
This crash does not occur in vanilla 1.19.2.

Using standard ANSI keyboard layout
en_US keyboard
OS: Windows 10

Crash error log below
```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null
```

**Comment by DuFrizzle** [comment]
I was also experiencing this and was able to replicate it exactly as above.
