### ISSUE TITLE
[ATM8 1.0.28] Can't autocraft Reborn storage crafting storage in Refined Storage

### ISSUE THREAD

**Issue by Max-Pare** [AllTheMods/ATM-8#1747]
The reborn storage "crafting storage" block requires a vanilla minecraft chest, but when crafting a chest with vanilla wood planks I get a Quark chest, and putting the Quark chest in a crafting grid crafts an Oak drawer instead of a vanilla chest.

![javaw_1x6GFWOLeT](https://github.com/AllTheMods/ATM-8/assets/103216511/87269a5a-9ebd-4e24-8dc4-b407683ea3d5)
![javaw_qJtwlS8OtO](https://github.com/AllTheMods/ATM-8/assets/103216511/86ca7387-cec2-4d23-895b-af709796864d)

**Comment by Mo3Nox** [comment]
To solve your issue for now is by crafting the chest in a normal bench. Make sure to change the output from Quark to Vanilla before crafting or use different wood types that are not used by Quark to make those type of chests. (such as undead planks)

Additional info: The mod is a mess.
I had issues building 7x7x7 even though I did everything correctly. Somehow it is working fine when it's 6x6x7 (probably favors even numbers over odd)
Another bug is that you can still have it functional while half of the multiblock is gone. So long it does not update on placing a block it will remain working fine.
And another bug where if you break the whole interior (CPUs and Storages) and then replaced them, when it updates it will add up the whole thing to the previous one. (I have 40 CPUs and 40 Storages but with 68 pages, it should be 40 pages)
Funny enough the controller reads the multiblock correctly.

That's what I got so far when playing with it. It might be risky to lose all the patterns on restart or update.
It's that or Netherite crafters that will eat up all the patterns inside for some reason. (happened when I came back the next day)

Play safe and enjoy mining I mean automations.

**Comment by Max-Pare** [comment]
> To solve your issue for now is by crafting the chest in a normal bench. Make sure to change the output from Quark to Vanilla before crafting or use different wood types that are not used by Quark to make those type of chests. (such as undead planks)
> 
> Additional info: The mod is a mess. I had issues building 7x7x7 even though I did everything correctly. Somehow it is working fine when it's 6x6x7 (probably favors even numbers over odd) Another bug is that you can still have it functional while half of the multiblock is gone. So long it does not update on placing a block it will remain working fine. And another bug where if you break the whole interior (CPUs and Storages) and then replace them again, when it updates it will add up the whole thing to the previous one. (I have 40 CPUs and 40 Storages but with 68 pages, it should be 40 pages) Funny enough the controller reads the multiblock correctly.
> 
> That's what I got so far when playing with it. It might be risky to lose all the patterns on restart or update. It's that or Netherite crafters that will eat up all the patterns inside for some reason. (happened when I came back the next day)
> 
> Play safe and enjoy mining I mean automations.

regarding the issues with the multiblock, [this](https://github.com/TechReborn/RebornStorage/issues/196#issuecomment-1753033488) should help, for the moment being, every time you make a change or build a new crafter multiblock you should reload your world by just going to the main menu.

**Comment by Mitchell5200** [comment]
partly related to #1663
