### ISSUE TITLE
[ATM8 1.0.28] No recipe for making Refined Obsidian Dust in a Metallurgic Infuser.

### ISSUE THREAD

**Issue by Alafian** [AllTheMods/ATM-8#1752]
There is no way to make Refined Obsidian Dust the normal way, according to my research. Since the normal way Diamand plus Obsidian Dust in a Metallurgic Infuser does not work. So unfortunately you can't make the better mashines and other stuff from Mekansim.

The only way to get "Refined Obsidian Dust" at the moment would be via productive bees.

**Comment by rozbrajaczpoziomow** [comment]
Crush or enrich the diamond first, you can't put a non-crushed/non-enriched diamond into a Metallurgic Infuser.
I'm on the same version as you are and I've made lots of Refined Obsidian Dust

**Comment by Alafian** [comment]
Okay a test in a new world, the same problem was no recipe for Refinend Obsidian for the Infuser, after a reperatur of the Minecraft installation by the CurseForge client, the recipe is suddenly there.

The case can be closed directly. Oh well sigh.

**Comment by LimitlessGreen** [comment]
I have the same problem on a server installation. The metallurgic infuser just refuses to accept the obsidian dust. Any ideas on how to fix this?

I think this should be reopened.
