### ISSUE TITLE
Keeps crashing if i explorer a new area (sand biome) atm9

### ISSUE THREAD

**Issue by Squadkiller06** [AllTheMods/ATM-8#1756]
If i explore biomes around it i have no problem but if i try to explore the sand biome it crashes pls help me

**Comment by Mitchell5200** [comment]
Logs via https://mclo.gs/ please, but if this is for AllTheMods9, wrong issues repo, let me know and i can transfer the issue

**Comment by Mitchell5200** [comment]
no reply from poster, closing
