### ISSUE TITLE
Placing corporea spark and master spark causes immediate crash

### ISSUE THREAD

**Issue by Nick-Wa** [AllTheMods/ATM-8#1757]
Placing corporea spark or master spark causes complete crash. Below I included the crash log.
I'm using the atm8 version 1.0.28

[crash-2023-10-30_10.47.10-client.txt](https://github.com/AllTheMods/ATM-8/files/13207195/crash-2023-10-30_10.47.10-client.txt)

**Comment by Mitchell5200** [comment]
https://github.com/ramidzkh/Applied-Botanics/issues/55
