### ISSUE TITLE
Mystial Agriculture Phytogenic Insolator recipes overriden by Thermal Integration

### ISSUE THREAD

**Issue by Mixu78** [AllTheMods/ATM-8#1765]
The custom KubeJS recipes for Mystical Agriculture crops seem to be overridden by Thermal Integration due to the compatibility setting for Mystial Agriculture being enabled.

Both recipes are added but the non-KubeJS recipe is used, leading to processing taking 5x as long compared to the KubeJS recipe and with no possibility of boosting the output using catalysts.

Is this intentional or should the Mystical Agriculture compatibility setting be disabled?

**Comment by Mitchell5200** [comment]
#1770
