### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by adorableweasel** [AllTheMods/ATM-8#1767]
I'm trying to start my server and I'm getting [this](https://pastebin.com/Yd7Msyf1)

I've tried using a fresh server pack and moving the world file, didn't work

Doesn't appear ATM8's server pack has a built in backup system, or I just can't find them. So not been able to try and restore

Tried reinstalling Java DK 17 but no good either

**Comment by Mitchell5200** [comment]
For your main issue, can i see the Latest.log file from the `/server/logs/` path, using https://mclo.gs/

as for backups, the mod "Simple backups" is in the server pack just set as `.jar.disabled` to prevent it loading and interfering with server hosts and their systems, you can enable it by removing the disabled from the file name.

**Comment by adorableweasel** [comment]
Thanks! I've posted the logs now :)

**Comment by Mitchell5200** [comment]
kinda need the link to the log please

**Comment by adorableweasel** [comment]
Sorry, I've updated my comment

**Comment by Mitchell5200** [comment]
Looks like Ferrite core broke during startup, it's config seems broken, locate and delete `ferritecore-mixin.toml` from the configs and restart, if that does not solve it , remove the mod, and start without it, if it works, then re-add

**Comment by adorableweasel** [comment]
Okay, getting somewhere

Did what you asked and it didn't change, I was getting this [error](https://mclo.gs/XY5UxBv)

I added back Ferritcore and it's config

I then followed the same thinking and removed NoChatReports and deleted the config

Then I was getting [this](https://mclo.gs/WionTv8) and [here is the crash report](https://mclo.gs/rVUV2pT) is the crash report

Finally, tried getting a new NoChatReportsv1.5.2 file from the CurseForge site and got [this](https://mclo.gs/zNo5sHN)

**Comment by adorableweasel** [comment]
So I tinkered some more and after removing the mod to test I found like basically every config file was causing the server to no launch. But only the configs within "World -> serverconfig"

I created a new server, deleted every single config from the none working server's world file under "Server config" folder. Moved everything to the new server file and it worked first time

Only needed to tinker with the ops, whitelist etc as expected

Also, I enabled the SimpleBackups mod to help make this process easier in the future (We live and we learn here, I presumed something would be going already for backups)

All working now, thank you for your input :)
