### ISSUE TITLE
Half of the Mystical Agriculture seeds do not work correctly within Phytogenic Insolators

### ISSUE THREAD

**Issue by DarkWolfHunter6** [AllTheMods/ATM-8#1770]
Been playing ATM8 for a while now and have notices that about half of the seeds from mystical don't seem to work correctly within phytogenic insolators. They are incredibly slow to produce essence and don't seem to speed up with augments.

**Comment by Mitchell5200** [comment]
known, it's a "feature" of thermal integration, INDEV fixed for 1.0.29
https://github.com/AllTheMods/ATM-8/pull/1764/commits/10bb3945f15421b9de93c93af64e747a3877c805
