### ISSUE TITLE
Can't see the hotbar

### ISSUE THREAD

**Issue by TigyD** [AllTheMods/ATM-8#1771]
I tried ATM8 7 and 6 and they all have to same problem, when I make a game the hot-bar disappears and i can't see it unless I'm in a menu, i haven't been able to find a way to fix it.

**Comment by Mitchell5200** [comment]
pressed F1 ?

**Comment by TigyD** [comment]
nope it it something i tried multiple times

**Comment by TigyD** [comment]
welp i just decided to try atm8 again and the hot bar appeared
