### ISSUE TITLE
Applied Energistics 2 Quests Are not Right

### ISSUE THREAD

**Issue by llinkindog** [AllTheMods/ATM-8#178]
On the next quest after the Inscriber and Charger, the next quest asked for a “sky compass” which is nowhere. I’ve got the other four presses but not that

**Comment by Miwasak** [comment]
You have to craft it, its pretty easy, you dont need any press, this quest should be before the press tho

**Comment by llinkindog** [comment]
Here’s the quest
![Uploading image.jpg…]()

**Comment by alfredggttv** [comment]
Fixed in 1.0.0
