### ISSUE TITLE
Apotheosis Superior Sigil of Socketing removes sockets and prefix instead of adding

### ISSUE THREAD

**Issue by mfriedrich74** [AllTheMods/ATM-8#1782]
Apotheosis Superior Sigil of Socketing removes all sockets and prefix instead of adding a socket when using it with Industrial Forgoing's Infinity Hammer. All RF charges are lost too.

The item preview looks correct, but this is not the item you receive from the smithing table when clicking the output.

ATM-8 version 1.0.28. Running as server.

**Comment by Mitchell5200** [comment]
Issue post on Apotheosis's github below for reference, but it seems to be an issue that Shadows cannot fix, and has always existed, cause is likely within Industrial Foregoing.
https://github.com/Shadows-of-Fire/Apotheosis/issues/1090

For the future i might just blacklist that tool from being able to be affixed, as there is a config in apoth for these cases
