### ISSUE TITLE
occutltism is makes my game crash immediately when im in creative and open the inventory

### ISSUE THREAD

**Issue by ClickityChicken** [AllTheMods/ATM-8#1785]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry Object not present: occultism:spawn_egg/possessed_ghast

**Comment by Avalon1892** [comment]
same. ATM9

**Comment by Mitchell5200** [comment]
Cannot reproduce in ATM8 1.1.0, Closing without full logs.
