### ISSUE TITLE
Black Sandstone Blank Recipe

### ISSUE THREAD

**Issue by mmblessbrian** [AllTheMods/ATM-8#1790]
ATM8 v. 1.0.28
Black Sandstone has a blank recipe. When using a Crafter from RFTools, if you leave one or more recipe slots empty, it will generate Black Sandstone from "Oh the Biomes You'll Go" (Item ID byg:black_sandstone) 
![blackSandstone](https://github.com/AllTheMods/ATM-8/assets/66796801/ed297f15-be25-43f0-86f2-55a665845419)

**Comment by carlajarchuleta1-a11y** [comment]
https://github.com/AllTheMods/ATM-8/issues/1790
