### ISSUE TITLE
[Bug]: Quest Chapter 3?

### ISSUE THREAD

**Issue by Kad4265** [AllTheMods/ATM-8#1792]
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

Now I could just be stupid, But I am only seeing chapters 1 & 2 still for the quests.
Do I have to complete chapter 2 all the way through to be able to see chapter 3?

### latest.log

NA

**Comment by Mitchell5200** [comment]
yes

edit, Oops hit close on accident
