### ISSUE TITLE
[Bug]: Pipez not reattaching to mekanism multiblock machinery after a reboot

### ISSUE THREAD

**Issue by LeLexaas** [AllTheMods/ATM-8#1796]
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

Since the 1.1.0 update, at each reboot/crash, every pipez's pipes are reset when connected to a multiblock machine from any mekanism related mods. Meaning if a pipez was connected as output, it will reset to input, dropping any upgrade it may contain, and preventing the machine to work.

I have this problem on the Thermal Evaporation thing, and also the fission reactor (which is very problematic because it will explode since the nuclear waste and steam are not outputting anymore)

Also, for some reason, the water input of the thermal evaporation tower will stop working too, I have to replace the pipe for it to input water again. I suspect this problem is also happening with the fission reactor, because even if the waste and steam weren't able to get out, the redstone output should stop the reactor, thus not explode.
But if the water input was severed, the reactor would damage itself at a very fast rate, and explode since the redstone controller would not be able to stop it quick enough.

### latest.log

https://gist.github.com/LeLexaas/23305061940a0575b999803a8cec25a0

**Comment by Mitchell5200** [comment]
https://github.com/henkelmax/pipez/issues/204
