### ISSUE TITLE
[0.1.7] Applied Energistics 2: ME Storage Bus Bugged with multiple similar unstackable items inserted

### ISSUE THREAD

**Issue by HaylingZar** [AllTheMods/ATM-8#183]
Method to reproduce issue:

- Create AE2 System with Me Storage Bus attached to any valid container (in this case, a vanilla chest is used, but multiple others have the same issue). 
- Insert 3 (or more) of the same unstackable item with different metadata e.g. 3 iron chestplates, 2 with different enchantments and 1 unenchanted.
- Observe glitchy behaviour, items disappearing, moving about, reappearing, etc. 
- [This video demonstrates the issue](https://www.youtube.com/watch?v=REpiasIoOKw)

**Comment by XDelta** [comment]
Adding on, this has become a more prevalent issue with all of the affixes from apotheosis making 100s of 'unique' itemstacks. Having many itemstacks is fine and handle-able but the storage appearing to be glitch-y past 3 of them makes it hard to even grab one of the items out.

In the meantime, I've been using a few ME Export Buses to pull most of the armor and tools out of the ME system entirely and just leaving it in normal chests/iron chests without a storage bus.

Also confirming this is happening in MC 1.19.2, ATM8-0.1.7

**Comment by James103** [comment]
Try updating AE2 or the mod pack; the bug should be fixed in newer versions.
