### ISSUE TITLE
[0.1.7] AllTheModium Ores Not Mineable with Miner's Fervor (Apotheosis) Enchantment

### ISSUE THREAD

**Issue by HaylingZar** [AllTheMods/ATM-8#184]
The ores AllTheModium Ore, Vibranium Ore, or Unobtainium Ore cannot be mined if a pickaxe is enchanted with Miner's Fervor.

Steps to reproduce the issue:
- Enchant AllTheModium pickaxe with "Miner's Fervor" enchantment from Apotheosis mod. 
- Attempt to mine either AllTheModium Ore, Vibranium Ore, or Unobtainium Ore.
- The block will not progress towards being mined.
- Removing the pickaxe enchantment is a workaround for the issue.

**Comment by BastionNtB** [comment]
Can confirm, this is an issue currently on ATM8 1.0.7

**Comment by Mitchell5200** [comment]
Miners Fervor was made unobtainable in version 1.0.5 of the pack, it being unable to mine ATM ores is a known bug, and that was our fix
