### ISSUE TITLE
Step up behavior broken

### ISSUE THREAD

**Issue by belikeMIKEY** [AllTheMods/ATM-8#187]
Whatever the actual mod is called, I'm unsure, but the feature that allows you to walk up one block instead of having to jump has randomly stopped working. I fought off a raid and then noticed I couldn't walk up blocks anymore. I'm unsure if it's some hidden key bind but have looked and can't seem to find any info on it.

**Comment by Jkosio23** [comment]
Why was this closed? If you found a fix please let me know cause the step height just stopped working for me

**Comment by P0kys** [comment]
This is a vanilla feature called Auto-jump. Press ESC, Options, Accessibility Settings and turn it on/off. Free runners from Mekanism also have this function but without the animation (you might prefer that)

**Comment by belikeMIKEY** [comment]
> Why was this closed? If you found a fix please let me know cause the step height just stopped working for me

We never found a fix, not sure if it was actually included in the mod pack. 

I Found a gem that gave an extra step climb. So I have been using it since.
