### ISSUE TITLE
Industrial forgoing block placer don't work

### ISSUE THREAD

**Issue by Narviath** [AllTheMods/ATM-8#193]
Hello,

I'm trying to use block placer from industrial forgoing on atm8-0.1.7
but it don't place block, I allow fake player on ftbchunk and ftbteams.

thank for your time for this beautiful mod pack

**Comment by CStumpf8721** [comment]
Hey, 
did you fed the block placer some energy?

FYI this is the face that will place the block. It is a bit tricky to place
![grafik](https://user-images.githubusercontent.com/93430831/199954720-2f4a06f9-b65e-4bb1-b01a-bc7f9d61396d.png)

**Comment by Narviath** [comment]
Yes I feed it with energy and try all face many time but nothing happen, just the animation going

**Comment by guillon77** [comment]
Looks like opened issue #1104 duplicate this one, 

I have the same issue and it looks like it's link to claimed FTB chunk, after unclaiming the chunk the block placer work again,

Block breaker have the same issue 

I Hope this help

**Comment by andys11** [comment]
Added solution on the mentioned open issue above.

**Comment by polinh0** [comment]
Happened to me and my friends too, only work onunclaimed terrains

**Comment by Mitchell5200** [comment]
Users need to enable Fake players in their teams settings to get the placer working, Closing
