### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by burtank** [AllTheMods/ATM-8#194]
When users connect to the server they get this error I've redownloaded it both user/server side and has same issue.

internal Exception: io.netty.handler.codec.decoderexception: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx:12, widx: 12, cap:12)

**Comment by pieter2501** [comment]
What was the solution, if any?
