### ISSUE TITLE
Gold Ore in the ATM Mining Dim

### ISSUE THREAD

**Issue by AzerJunior** [AllTheMods/ATM-8#197]
so idk why, but I have gotten barely any gold ore at all from the mining dimension 64x64 Chunks mined (only got like 2k gold from that?) i've gotten like 200x more diamonds than I have gold(diamond gen seems fine gold is just borked). (Brand new generation as of 0.1.8)

**Comment by AzerJunior** [comment]
from what I can tell the rarity in the mining dimension goes Copper,Coal,Iron,Diamonds,Redstone,Gold,Emerald

**Comment by BennyOfEarth** [comment]
It seems to only start spawning in the lower y levels of the overworld section, might be an oversight with that.

**Comment by Mitchell5200** [comment]
meant to mirror the overworld in some aspects, closing
