### ISSUE TITLE
Mining Dimension not checked in Questbook

### ISSUE THREAD

**Issue by niggelasso** [AllTheMods/ATM-8#203]
Although already visited, the quest for the mining dimension is not completed, but shows 100%, and thus cannot be claimed.

![image](https://user-images.githubusercontent.com/56580376/199074743-0b507f52-730c-428a-9050-0c7ef1cb74d6.png)

**Comment by alfredggttv** [comment]
This will be fixed in a future update. Thanks for letting me know!
