### ISSUE TITLE
QuerryPlus Marker uncraftable 

### ISSUE THREAD

**Issue by MvandeKamp** [AllTheMods/ATM-8#206]
The recipies for the Querryplus marker are not there yet i guess

**Comment by Jonz00r** [comment]
The flexible marker is craftable and more uselful.

**Comment by MvandeKamp** [comment]
> The flexible marker is craftable and more useful.

You need a Marker Plus for a flexible..... Please look up the recipies before commenting

**Comment by enigmaquip** [comment]
Except that it's also made in the workbench.... Should probably follow your own suggestion
![image](https://user-images.githubusercontent.com/6134440/199318019-652b142d-12c0-4c70-91ab-f39d7d996359.png)

**Comment by Mitchell5200** [comment]
intended by dev
https://github.com/Kotori316/QuarryPlus/issues/224
Closing
