### ISSUE TITLE
Aquatic Glyph no longer exists

### ISSUE THREAD

**Issue by LavaCatPlayz** [AllTheMods/ATM-8#208]
![image](https://user-images.githubusercontent.com/69319607/199129773-a48779a7-1945-4372-bfef-b185bea2898b.png)
As can be observed in this image on the ATM 8 Public Server, the aquatic glyph, which was removed, has a quest which is impossible to complete due to the removed item being the requirement. This, while a small issue, means that the Ars Nouveau quest section can not be fully completed and therefore the final goal in any mod pack of completing every quest is now impossible.

**Comment by Jonz00r** [comment]
I mean a lot of it is impossible because the pack isn't finished. Things are still being added and changed. 0.1.9 has a lot of quest changes so try updating to see if they've fixed this.

**Comment by alfredggttv** [comment]
Noted! I'll have this fixed in a future update. Thank you!
