### ISSUE TITLE
(0.1.9) Unobtainium and Vibranium ores can't mineable with any craftable pickaxe.

### ISSUE THREAD

**Issue by JustHmm** [AllTheMods/ATM-8#211]
Only pickaxe can mine these two ores is Allthemodium ALLOY pickaxe which is not craftable. I checked some previous version videos on youtube these ores were mineable with allthemodium pickaxe before. Currently there is no way to mine these ores without cheating.

**Comment by Mitchell5200** [comment]
Some other mod tools, like the Meka tool can mine all three, the ATM tools are getting re-worked and will be added back in some form later

**Comment by JustHmm** [comment]
Thanks for the info, I also found you can mine those ores with warden pickaxe.
