### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by Zack2470** [AllTheMods/ATM-8#212]
Hey 
today I updated my server version from ATM8 0.1.8 to 0.1.9. If I or the players join the server, the game crashes, the server continues to run. Does anyone have the same problems or can someone help? Thanks

**Comment by Mitchell5200** [comment]
without logs it's impossible to help, However i suspect it's related to supplementaries globes, remove them via whatever means and things will be good again

**Comment by Zack2470** [comment]
Thank you for your prompt reply ! Unfortunately I don't get any error message or there is nothing on the server except : "joined the game / left the game". short form

**Comment by Jorue23** [comment]
It won't show as an error message in the console you'll have to go to your instances folder and look for the most recent log called "latest.log" also maybe try the givven solution first.

**Comment by Zack2470** [comment]
I have seen the latest.log file on the gaming pc and it does not record anything when I go to the server. (/minecraf/instance/atm8/log/latest.log). Is there a second one .log datei? On the server the latest.log file just says "join/left"

**Comment by cpspok** [comment]
1.9 crashes mine as well no log no nothing just crashes .

**Comment by Mitchell5200** [comment]
Crash reports then

**Comment by Zack2470** [comment]
found something. where can i upload it?

**Comment by Mitchell5200** [comment]
Share via https://mclo.gs/ , and paste the link back here

**Comment by Zack2470** [comment]
https://mclo.gs/GPNSl7n

**Comment by Mitchell5200** [comment]
That was your latest Log, but that's fine, it's the Supplementaries globes crash like i stated in the beginning.

A pack update will be soon with the updated version, but you can just update Supplementaries to 2.2.13 and it'll solve the crash on your client

**Comment by Zack2470** [comment]
Thanks for the help! will test it soon :)

**Comment by Zack2470** [comment]
thanks for the update everything works great :)
