### ISSUE TITLE
Processor binding doesn't have recipe

### ISSUE THREAD

**Issue by dualmacops** [AllTheMods/ATM-8#213]
After updating the pack from 0.1.8 to 0.1.10 processor binding from refined storage doesn't have a recipe.

Edit: Starting a new world in sp doen't have this issue, so the issue is only with mp or related to the update.

**Comment by chadle01** [comment]
Same, tried making new server from scratch but  also no processor binding recipe

**Comment by BennyOfEarth** [comment]
Having the same issue here, the recipe does not show in jei or work when crafted manually.

**Comment by Mitchell5200** [comment]
**FIX for server players unable to make processor bindings for RS **
Head into your server files and go to the below directory
`\kubejs\serverscrips\`
and **Delete** `public8_server.js`
That file was accidently bundled in the server ZIP, and was only being used for our Public server to aid in server stability and performance

*(why you would want RS on your server is beyond me)*

**Comment by dualmacops** [comment]
@Mitchell5200 May I know where is the problem with RS on a server?
And looking at the file, why is the mekasuit also disabled?

**Comment by Jorue23** [comment]
Rs often causes world corruption. Don't know about the meka suit tho.
