### ISSUE TITLE
Hoppers don't load items into Little Logistics chest cars

### ISSUE THREAD

**Issue by alex123abc15** [AllTheMods/ATM-8#214]
This issue is being created to document the issue and the potential fix for future reference.

This issue was found when trying to add items into the `train chest car` from the [little logistics mod](https://github.com/MuradAkh/LittleLogistics). The items don't go from the hopper to the `train chest car` but the train itself recognized the hopper contained items and stopped at the docking station to fill up but the items never left the hopper.

The issue is with the [canary mod](https://github.com/AbdElAziz333/Canary) the mod [changed how hoppers work](https://github.com/AbdElAziz333/Canary/blob/mc1.19.2/architectury_forge_loom/src/main/java/com/abdelaziz/canary/mixin/block/hopper/README.md) for optimization. To fix this you need to change the `canary.properties` file in the config folder and add the line `mixin.block.hopper=false`. This happens with hoppers interacting with other modded items apparently, like from this ticket: https://github.com/AllTheMods/ATM-8/issues/198.

**Comment by AerikAwesome** [comment]
I tried this change on my server, but all vanilla/quark chest became invisible (temporarily), and empty (not temporary). Guess I should've backed up my world beforehand...
