### ISSUE TITLE
Enhanced Celestials is required to join the 0.1.10 dedicated server but not included in the client 0.1.10 modpack

### ISSUE THREAD

**Issue by BennyOfEarth** [AllTheMods/ATM-8#215]
Upon attempting to join I get a message that it is missing two enhanced_celestials datapack, simply adding v 2.1.0.1 of enhanced celestials (the same version as the current one in the server files) it works fine.

**Comment by Mitchell5200** [comment]
Enhanced Celestials was removed from the pack in 0.1.9, it also should not be in the 0.1.10 version either, ensure you updated your server correctly

**Comment by BennyOfEarth** [comment]
Oops, my bad, this linux distro handles transferring files differently than I'm used to with windows, yeah works just fine.
