### ISSUE TITLE
Tier 6 Seeds giving secondary seeds via botany pots

### ISSUE THREAD

**Issue by ctallet8** [AllTheMods/ATM-8#218]
Can't confirm this isn't intended, but putting a tier 6 seed in a botany pot has a small chance to give more seeds. I assume this happens because insanium farmland is set to not give any seeds, but the botany pots only use the crux and no farmland.

**Comment by enigmaquip** [comment]
MA crops with botany pots have a 1% chance of dropping the seed. I could probably go back and cut that off at a certain tier, but for the moment it's all tiers
