### ISSUE TITLE
Opening refined storage crashes the client

### ISSUE THREAD

**Issue by j0viss** [AllTheMods/ATM-8#219]
After updating 0.1.7 to 0.1.10 i've noticed that server takes way longer to start. Checking same world on previous working version (0.1.7) is the same. Server was not restarted after upgrading to 0.1.7 and I havent played for few days so it was discovered only after stopping server and upgrading. After taking out and putting in storage disk server laggs for few minutes.

It seems that there are either some items in refined storage that cause the crash or maybe it reached some limits with unlimited storage.
Error message: Failure Splitting Packets on Channel "refined storage:main channel". with class com.refined mods.refined storage.network.grid.GridItemUpdateMessage. Number of Packets sent 5, expected number of Packets 7, maximum number of packets for a message of this type 5

**Comment by Drizein** [comment]
try searching in RS for something with high NBT, like enchanted items/books. It fixed my problem with RS where I couldn´t get items out of RS

**Comment by zuccali** [comment]
same for us
