### ISSUE TITLE
Vibranium ore not mineable with AllTheModium pickaxe

### ISSUE THREAD

**Issue by vladivarsd** [AllTheMods/ATM-8#221]
Hi tooltip shows X when trying to mine a vibranium ore also with a netherite ore

**Comment by BennyOfEarth** [comment]
Thought this was due to the other issue with the enchantment (boon of the earth?) preventing it from being mineable, but just tried it out with a plain allthemodium pickaxe and it does indeed show an X in v0.1.10 and does not drop an ore chunk when broken.

**Comment by HaylingZar** [comment]
Maybe related to https://github.com/AllTheMods/ATM-8/issues/184

**Comment by BennyOfEarth** [comment]
> 

That's the enchantment I meant, this is a separate issue, tried with an unenchanted pick as mentioned above.

**Comment by IsaiahMM** [comment]
i am also on the same version and it won't allow me to mine the vibranium, i just ended up having to spawn myself in some vibranium after trying many times.

**Comment by SuperSpaceMan230** [comment]
Seems like the mining gadget can't mine it either when it could in ATM6, although not sure if that's intended behaviour

**Comment by Jutsch** [comment]
> Hi tooltip shows X when trying to mine a vibranium ore also with a netherite ore

The same here

**Comment by Mitchell5200** [comment]
Known Issue, has been fixed in dev and will be fixed in the next update, for now use a mekanism atomic dissembler
