### ISSUE TITLE
Occultism Dimensional storage is Crashing my game when I get near it

### ISSUE THREAD

**Issue by SuperHasch** [AllTheMods/ATM-8#222]
Any time I place the Occultism Storage into my game it causes A crash on .1.10 or 1.09. Any version before that it seems to work fine.
[crash-2022-11-02_19.27.06-client.txt](https://github.com/AllTheMods/ATM-8/files/9924934/crash-2022-11-02_19.27.06-client.txt)

**Comment by PoPoGH** [comment]
To fix this crash, you need to update geckolib to the latest version.
https://www.curseforge.com/minecraft/mc-mods/geckolib/files

**Comment by LoaderB0T** [comment]
Same problem here, updating to the latest version of geckolib fixed it for us, thanks @PoPoGH
