### ISSUE TITLE
Apotheosis anvil enchantments "Splitting" and "Obliteration" not working

### ISSUE THREAD

**Issue by ddesousa11** [AllTheMods/ATM-8#223]
I'm not sure if it hasn't been working the entire time, but I can confirm it isn't working from versions 0.1.7 to 0.1.10. 

When dropping the anvil on top of an enchanted book, the book simply bounces around a bit and is not split like it is intended to be.

**Comment by GhostRider584** [comment]
Having the same issue here on version 1.0.4

**Comment by codesmith47** [comment]
Same here, hope this gets fixed soon.

**Comment by alfredggttv** [comment]
This has been fixed as of v. 1.0.18
