### ISSUE TITLE
Server crash when EvilCraft Environmental Accumulator finishes processing a bottle

### ISSUE THREAD

**Issue by hgjensen** [AllTheMods/ATM-8#224]
As soon as the progress bar reaches the end, the server crashes.
Crashlog [here](https://pastebin.com/mSUGm3Jk)

Server can start again, but crashes as soon as a client connects (and the chunk with the Environmental Accumulator is loaded)

**Comment by PaintingPapa** [comment]
Reproduced on my server, and what do I do now?

**Comment by hgjensen** [comment]
@PaintingPapa i have no solution. This in just a bug report.
I restored my world from backup.
