### ISSUE TITLE
Integrated Dynamics missing Fluid description

### ISSUE THREAD

**Issue by niggelasso** [AllTheMods/ATM-8#226]
In tanks or inventories of blocks, the fluid "Menril Resin" only shows up as unregistered:
![image](https://user-images.githubusercontent.com/56580376/199806906-4c211ba0-a668-4656-9602-ae405e21eba1.png)

**Comment by CStumpf8721** [comment]
Not only in inventories. It also is shown in JEI.
I think it is a generall issue with Integrated Dynamics fluids (Menril Resin and Crystallized).

Pack version 0.1.10
