### ISSUE TITLE
Refined Storage 

### ISSUE THREAD

**Issue by cebarks** [AllTheMods/ATM-8#230]
The Refined Storage system suddenly stopped showing anything. The disks in the disk drive continue to show change in usage but nothing is shown in any of the grids (they are all empty). I can still add items to the system through importers, grids, etc. and things are automatically exported as well.

I'm on version 0.1.10

**Comment by Dominik9798** [comment]
Three of us play on a self-hosted server. Two of us can access the system. After a reconnect it works at least with us again.

**Comment by cebarks** [comment]
> I could not access the system. the other players had no problems. after I reconnected, it worked again.

That was happening to me too for a while, but then this happened and now it wont work even i restart the client or the server.

**Comment by cebarks** [comment]
Seems to fixed itself now, not sure what changed but it works after not logging in for a few days.
