### ISSUE TITLE
Quest Issue: Building Materials

### ISSUE THREAD

**Issue by xaerorazor** [AllTheMods/ATM-8#231]
Version: 0.1.10
Problem quest: Building Materials 
Main Quest Line - Getting Started - Building Materials

minecraft:red_sand (Vanilla Red Sand) is not being accepted as a Sand substitute for the quest. 

Fix: change to accept forge:sand instead of just minecraft:sand

**Comment by alfredggttv** [comment]
Added to my current quest update. Will be fixed in a later version.
