### ISSUE TITLE
Stuck on load 100% (Solved)

### ISSUE THREAD

**Issue by Williamem** [AllTheMods/ATM-8#236]
Solution: Create new world, load, then open old world.

When I try to open my save it loads to 100% and then nothing happens. Been playing the world for several hours and would hate to give it up. Creating a new world works and loads as it should.

Playing on macbook pro with m1 pro chip, 32gb ram.

Had some problems previously when it won't open the world and complains about something with server (don't remember and can't recreate now), kicks me out to server list (I just play in regular single player).

Tried deleting the severconfig files based on advice found inline, did not work.

Tried creating a new world which worked fine, then loaded old world which now suddenly also works. Posting anyway since someone else might have the same problem and would be interested in the solution.

**Comment by Cxjhg** [comment]
It didn't work for me, I created a new world that loaded and worked well, but when I went to enter my old world again, it kept stuck on the 100% screen and only the new world entered. I don't want to give up on this old world of mine, it's been more than 3 months of progress and out of nowhere it won't load anymore.
