### ISSUE TITLE
Random Mini-Boss mobs spawn too frequently

### ISSUE THREAD

**Issue by Siegurd33** [AllTheMods/ATM-8#237]
The spawn rate of these named champion mobs is unreal. I had 3 spawn back to back in the nether within 60 seconds. Even in the overworld at night, it's not uncommon to get 5 or 6 spawned in a single night.

**Comment by taj1994** [comment]
I second this. The default cooldown timer is a bit much at 400 ticks (20 seconds). Sounds like you got extra unlucky and had them spawn exactly when the cooldown finished

If you want to adjust it for yourself for now, go to Config > Apotheosis, open the `adventure.cfg` file, and change `I:"Boss Spawn Cooldown"=400` to something higher (keeping in mind that every 20 you add will add 1 second to the timer)

**Comment by James103** [comment]
Another way to reduce apoth boss spawns is by reducing the chance values in the following:
```cfg
bosses {
    # Dimensions where bosses can spawn naturally, spawn chance, and spawn rules.
    # Format is dimname|chance|rule, chance is a float from 0..1.
    # Valid rules are NEEDS_SKY, NEEDS_SURFACE, and ANY [default: [minecraft:overworld|0.02|NEEDS_SKY], [minecraft:the_nether|0.03|ANY], [minecraft:the_end|0.02|NEEDS_SURFACE], [twilightforest:twilight_forest|0.05|NEEDS_SURFACE]]
    S:"Boss Spawn Dimensions" <
        minecraft:overworld|0.02|NEEDS_SKY
        minecraft:the_nether|0.03|ANY
        minecraft:the_end|0.02|NEEDS_SURFACE
        allthemodium:the_other|0.09|NEEDS_SURFACE
        twilightforest:twilight_forest|0.05|NEEDS_SURFACE
     >
}
```
