### ISSUE TITLE
Unable to craft Seeds in AE2

### ISSUE THREAD

**Issue by camberme** [AllTheMods/ATM-8#238]
It looks like Mystical Agriculture has taken over the pattern for 
Certus Quarts Seeds, Fluix Seeds, and Nether Quartz Seeds
This hampers the auto growth / doubling of the crystals you need for AE2

**Comment by enigmaquip** [comment]
Growing seeds is no longer a mechanic in AE2, All crystal growth is based around amethyst style growth off the budding crystal blocks found in meteorites
