### ISSUE TITLE
Iron Jetpacks not working

### ISSUE THREAD

**Issue by GoldenRoar47** [AllTheMods/ATM-8#24]
the iron jetpacks mod is not working, the jetpacks are NOT showing up in jei and when i hit the button for show uses in Jei the coils and leather strap dont have any uses and yes the coils and leather strap are showing up but the jetpacks are not.
![Desktop Screenshot 2022 09 17 - 15 11 09 33](https://user-images.githubusercontent.com/113804723/190877993-7ec91dfd-969a-47a7-bced-f73b5134e0c9.png)

**Comment by osirus31** [comment]
Having same issue, any fix?

**Comment by osirus31** [comment]
Never mind, delete the folder [instance location]/config/ironjetpacks and restart.  This folder had an empty "jetpacks" folder in it.  Deleting it seems to have triggered the folder to be re-created

**Comment by GoldenRoar47** [comment]
ok thanks so much, ill try it this weekend when i can play on my computer :D
