### ISSUE TITLE
Server Crash on Players Loading due to Laser IO

### ISSUE THREAD

**Issue by frenchiestspy** [AllTheMods/ATM-8#242]
I am using Laser IO to automate the fluid, power and item flow for Hydroponic Beds on a locally ran server. Everything worked fine when I first set it up, but after restarting the server it crashes. If anyone knows a fix to this it would be greatly appreciated.

Crash report below.
[crash-2022-11-04_20.07.45-server.txt](https://github.com/AllTheMods/ATM-8/files/9954819/crash-2022-11-04_20.07.45-server.txt)

**Comment by User52525252** [comment]
I have also run into this issue.
