### ISSUE TITLE
Visual bug with Smooth Stone

### ISSUE THREAD

**Issue by TwistedKindn3ss** [AllTheMods/ATM-8#25]
So there's regular smooth stone that should stay as individual blocks giving a checkered pattern if you put 3x3 in a square. Similar to how it would be for smooth stone slabs. But when you put 3x3 or any smooth stone block next to another, it connects the textures. 

Whereas shouldn't this only be in effect if I were to rechisel it to smooth stone block (connecting)??

Not a super high priority, but just a weird connecting texture thing.

**Comment by WhitePhant0m** [comment]
Not a bug.

This caused by[XyCraft: Override](https://www.curseforge.com/minecraft/mc-mods/xycraft-override). It also makes a few other vanilla blocks have connected textures by default.

**Comment by TwistedKindn3ss** [comment]
Got it, thanks.
