### ISSUE TITLE
Game crashes when interacting with scorchia pillar in framed wall board.

### ISSUE THREAD

**Issue by ItsMourn** [AllTheMods/ATM-8#250]
There is a bug i encountered with my friend when he tried to put a scorchia pillar (chiseled block) into a framed wall board (FramedBlocks Mod) . After he crashed the first time, everytime he tried to remove it or interact with blocks nearby, the game would crash and hed have to restart. A temporary fix is to blow up the framed wall board block with TNT, or any indirect way to break it, and then re-entering the server, but other than that i dont think theres another way.

**Comment by XFactHD** [comment]
This issue was fixed in FramedBlocks v6.6.0, so you'd need to update FramedBlocks to v6.6.1 on the server and client.
