### ISSUE TITLE
Unable to mine Vibranium Ore with Allthemodium Pickaxe

### ISSUE THREAD

**Issue by jetamphetamine** [AllTheMods/ATM-8#251]
Hi

As the title says, I'm unable to mine Vibranium ore with my Allthemodium pickaxe for some unknown reason. 

Please see screenshots below.
![vibra](https://user-images.githubusercontent.com/117840193/200861779-bfe72389-7445-4798-9589-23ac48922d80.png)
![vibra2](https://user-images.githubusercontent.com/117840193/200861794-4e350529-ee89-41b1-9aff-71f26402f0af.png)

Please advise on how to resolve this, thanks!

**Comment by Mitchell5200** [comment]
fixed in pack version 1.0.0, Update
