### ISSUE TITLE
1x compressed soul sand is uncraftable because of Spirit

### ISSUE THREAD

**Issue by SnakerBone** [AllTheMods/ATM-8#254]
When trying to craft 1x compressed soul sand from AllTheCompressed it will craft the compressed soul sand recipe from Spirit

**Comment by quentin-miranda** [comment]
Same issue here

**Comment by RhamaDaragaaz** [comment]
Can confirm this issue. Unable to create the 5x compressed soul sand for the Dimensional Seed for the ATM star as a result unless I manually select the recipe in a normal crafting table. Refined storage/AE2 don't accept the recipe. Tried AE2 for autocrafting and it doesn't accept substitutes or anything to make it work.

**Comment by FallenPumpking** [comment]
If it helps, to autocraft with AE2, manually make one 1x, make a processing pattern of 9 soulsand to 1x, and use a Crafter from RFTools with a pattern interface and your preferred method to reinsert into your ME system. Then you can craft up to the 5x in AE.
