### ISSUE TITLE
Game crashes when right clicking mobs ATM 8 1.0.0

### ISSUE THREAD

**Issue by scooper93** [AllTheMods/ATM-8#255]
As the title suggests, right clicking a mob causes the game to save and crash in mutliplayer. This is not the case in 0.0.15. I have not tested this in single player.

**Comment by Speelo** [comment]
So i never got a reply in a similar issue created 30 days ago. it was two version older (0.1.10) https://github.com/AllTheMods/ATM-8/issues/155. my issue was not present on a sever i started myself.
