### ISSUE TITLE
Structure Compass Crashes Game 

### ISSUE THREAD

**Issue by Kingsllly** [AllTheMods/ATM-8#256]
Using the Compass to find a Minecraft:monument overloads my server and and it exceeds tick rate, I had 8 GB on it of Ram and upgraded it to 10 still crashes.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2022-11-09 15:50:23
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.world.level.biome.Climate$RTree$SubTree.m_183370_(Climate.java:129) ~[server-1.19.2-20220805.130853-srg.jar%23380!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.biome.Climate$RTree$SubTree.m_183370_(Climate.java:129) ~[server-1.19.2-20220805.130853-srg.jar%23380!/:?] {re:classloading,pl:accesstransformer:B}
-------------

**Comment by UnknownnAznn** [comment]
I am having the same problem. I quit ATM8 just because I couldn't get to end game. Structure Compass crashes my server. I have ran around for 4-5 hours in THE OTHER dimension and still haven't found one single piglich. Love IT.

**Comment by sprocketaudio** [comment]
same thign happens to us and my max tick time is at 600000 (10 mins!)

**Comment by sprocketaudio** [comment]
Is thre any more on this - people on my server complain its 'required' for the pack, but ifd you search for ocean monuments it wil crash with a time out.

**Comment by Bobcatplays** [comment]
you need to look for a 'betteroceanmonuments:ocean_monument' the vanilla ones are disabled so when searched for the game crashes

**Comment by sprocketaudio** [comment]
I ended up disabling the recipe for structure compass and installing explorere's Compass from the same team as Natures compass on the server and client, then swapping the recipe and updating the quest text. It only shows biomes that exist so much better.
