### ISSUE TITLE
since latest update pack has  been unplayable

### ISSUE THREAD

**Issue by starixed** [AllTheMods/ATM-8#261]
![image](https://user-images.githubusercontent.com/112789167/201144462-f7ccc7f7-cefa-4f85-9bf5-45accf4ce3a9.png)

everytime i join the world i get this. ive reinstalled many many times on different launchers. ive even tried to create a brand new world and still getting this. please fix this pack its the only one that is doing this

**Comment by starixed** [comment]
now everyytime i leave a world i keep getting invalid player data like wtf

**Comment by starixed** [comment]
there has to be a mod that is corrupting playerdata or something i cant even start a new world or a do a fresh install to play this pack

**Comment by starixed** [comment]
i am closing this issue because apparently its only me having this issue so i give up and will never again play this pack

**Comment by Jonz00r** [comment]
maybe give more than a day for someone to get back to you or try getting help in the discord if you're going to be impatient.

**Comment by starixed** [comment]
funny enough i did and got ignored, apologizes for being impatient but im just frustrated that this pack is the only pack that i cannot play because something is corrupting my player data

**Comment by Jonz00r** [comment]
@Mitchell5200 You might know the technical stuff better than me.
@starixed I mean hundreds of people dont have an issue playing. Is curseforge one of the launchers you've tried considering its the official source.

**Comment by starixed** [comment]
i was first on ftb launcher when it started then moved to curseforge and i also tried multimc and still the samething everytime i can create a new world and play it fine but when i exit out and comeback i get invalid playerdata and that is downloading a fresh pack each time

**Comment by Jonz00r** [comment]
probably worth posting logs.

**Comment by starixed** [comment]
[latest.log](https://github.com/AllTheMods/ATM-8/files/9994123/latest.log)
this is the latest one i have since i deleted the other instances.

**Comment by starixed** [comment]
hopefully you guys can fix it. thanks and sorry about before

**Comment by fusionmc-evilscoop** [comment]
Im having the same issue, though I suspect its one of the mods ive added to the pack that is causing a conflict.
For now ive rolled back to the older version until I have time to test them

Player data isnt corrupt, if you roll back you can load the world again
creating a new world does the same.
It looks like a failure to connect to minecraft api

For me this is likly projectE and its addon mods...but my AE2 system is heavily tied into projectE so im not removing that, id rather roll back.

for ref im posting my add on mods as there maybe a common one this person is using 
![atm8extra mods](https://user-images.githubusercontent.com/2187683/201468729-81be990d-90bb-4c3c-97a8-4ce51c112bd7.JPG)

**Comment by starixed** [comment]
i see, i have ic2 classic and its addons so maybe thats the problem. i know cyclic was causing issues so i removed it but i will not remove ic2 because its been forever since i played it and i wanted to experience again plus its 1000x better than ftb ic2 version. so ill rollback the update and see how that goes and if i can get my world back.

I also get the modpack makers not wanting people to add mods in because it messes with balance but if i cant update the pack because of these issues then im cool with it as long as i can at least play it with some of my favorite mods that are not included in it

**Comment by fusionmc-evilscoop** [comment]
if I add mods and it breaks, I do expect myself to fix it, this then isnt the devs fault.
knowing that so many others have this pack working (and it is a popular pack) leads me to believe it was just me and my extra mods, so I will fix it at some point, but for now im happy on older version....there is only compressed blocks that appeal in the new pack and I could add that myself :D

when projE updates from beta I might look into updating again....

I suggest just roll back and run your mods and enjoy fix it later...or wait for all the mods 9 lol

**Comment by starixed** [comment]
yeah im trying now but kubejs is throwing issues lol

**Comment by starixed** [comment]
well at least i realized it was my own wrong doing that caused this. im so forgetful and dumb at times

**Comment by enigmaquip** [comment]
the 6198 is a separate issue from kubejs errors. The 6198 error tends to come from silent gear (unless they've fixed it recently, because they were the cause in atm7) and can be passed by logging into a single player world first before trying to connect to a server.
If you're adding mods that add ingots and other materials (ores, dust, etc) around that, add the mod name to the priority order in the almostunified unify.json config. A portion of our kubejs scripts are adding more recipes back in after unifying materials.

**Comment by starixed** [comment]
ok ill take a look at that as well

**Comment by starixed** [comment]
ok i got everything working again, just have to watch which mods i update because something caused minecraft to not even launch

**Comment by enigmaquip** [comment]
welcome to the battle of every update for a pack dev :-D

**Comment by starixed** [comment]
yeah im starting to remember why i stopped making my own custom packs back in 1.12

**Comment by starixed** [comment]
so i think i got the new patch working after changing the scripts

**Comment by starixed** [comment]
I FIXED IT !!!!! Delete the unify scripts in kubejs>sever_scripts>postUnify and no errors and i can play the latest update with ic2 classic or any mod i wanna add. Yay lol

**Comment by starixed** [comment]
however it does seem i have lost a lot of resources and items but its worth it
