### ISSUE TITLE
ATM 8 after update i cant connect Invalid item: minecraft:air

### ISSUE THREAD

**Issue by LiveSide** [AllTheMods/ATM-8#264]
Hello,

i updated a ATM8 server from version 0.0.16 to version 1.0.0.
now i cant join to the server.
here the logs
Server latest Log : https://mclo.gs/SY8gpht
Server debug log : https://mclo.gs/XDsF65G
client latest log : https://mclo.gs/ttwSZf1 

io.netty.handler.codec.EncoderException: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air

how can i fix it?

**Comment by twixthehero** [comment]
I had this same issue. In my case, I was able to move past it by NOT copying the `config/` and `kubejs` folders when doing the upgrade.

**Comment by Jonz00r** [comment]
Those folders are where a lot of the updates are. If you are not updating those folders then I would not expect support for your issues.

**Comment by Jonz00r** [comment]
> I had this same issue. In my case, I was able to move past it by NOT copying the `config/` and `kubejs` folders when doing the upgrade.

Those folders are where a lot of the updates are. If you are not updating those folders then I would not expect support for your issues.

**Comment by twixthehero** [comment]
> Those folders are where a lot of the updates are. If you are not updating those folders then I would not expect support for your issues.

I should have specified: I did not copy `config/` and `kubejs/` from the old server to the new one. If you do "in-place" upgrades (i.e. download new server zip, install forge, copy old world/configs to new dir), it's likely that `config/` would be copied since modifications could have been made.

**Comment by LiveSide** [comment]
hello togather,
thank you for de quick support

i installed the server new and did not copy the config/, the kubejs/ i did not had

now the server dont start

https://mclo.gs/2VCxeAL
https://mclo.gs/OKAcxMB

**Comment by Jonz00r** [comment]
I would unzip the server files and move your world folder over. It seems like you're trying to load copies of mods or something from my quick skim of the logs. Start with an empty folder and move just your world folder over.

**Comment by Salem55ksa** [comment]
I had the same issue but my server work after I removed the extra mods I added.

**Comment by LiveSide** [comment]
i have the same problem, if i just install the server without anything from the old server.

**Comment by LiveSide** [comment]
after alot of reinstalls now it works
i dont know why... but all works now...


thank you for the help
