### ISSUE TITLE
Incorrectly written crop > seed recipes between Farmer's Delight and Croptopia

### ISSUE THREAD

**Issue by tanyan-tanyan** [AllTheMods/ATM-8#268]
When attempting to get **Farmer's Delight** Cabbage OR Tomato seeds from Cabbage OR Tomato through crafting, I end up getting **Croptopia** Cabbage OR Tomato seeds.
This is because the recipes accept "any `forge:cabbage`," and then "any `forge:crops/tomato`".

While I can't do anything about the fact that there are two food-providing mod in the modpack, I would still like to be able to get the appropriate seeds from intended mods.

**Comment by Mitchell5200** [comment]
The Market stall exists to provide almost all/all seeds and crops ingame, viable work around, Closing
