### ISSUE TITLE
MineColonies

### ISSUE THREAD

**Issue by IgnisAstra** [AllTheMods/ATM-8#27]
I keep receiving an error: "block has lost its respective building; try restarting or loading a backup." I was unable to load a backup before I activated the block, in this case, the guard tower. I have already restarted multiple times.

If this is a bug with the mod, it's okay. I can hopefully continue but I think the citizen I have is glitched because they won't grab a work order and do it.

**Comment by tabbek** [comment]
I had one of those, and I ended up mining what would have been the building's "main" block with a pickaxe, clearing the old building, and replacing / having a builder rebuild it.
