### ISSUE TITLE
Console Spam on Server

### ISSUE THREAD

**Issue by MoeHunt3r** [AllTheMods/ATM-8#277]
Hey there! 
I'm getting the console of my server spammed with 
`[Server thread/WARN] [pneumaticcraft/]: Amadron: failed to find any trades for profession evilcraft:werewolf ?`
I never used any Amadron and I don't know where this message comes from. 
This message is always followed by "Can't keep up! Is the server overloaded?"
And I think because of this I'm getting connection issues on the server.

Server Version: All_the_Mods_8-1.0.1

![Bild_2022-11-14_200824858](https://user-images.githubusercontent.com/38086254/201744964-a8126604-b45d-45b5-88db-6e3159c8eb62.png)

**Comment by Aternix12** [comment]
I too have this spam on my server

**Comment by Homerdu29Off** [comment]
I have this spam too, it's kinda annoying 😕

**Comment by mynameiskaren** [comment]
Thank you for opening a ticket. Several reddit users and myself have encountered this issue. I have searched everywhere and do not see a solution to this. Could we please have this addressed?

Has anyone come up with a solution? Please let us know! =)

Greatly appreciated, thank you!

**Comment by mynameiskaren** [comment]
Same issue here. 

Has anyone else figured out how to fix this? 

TIA!

**Comment by brendonsanderson** [comment]
This is caused by PneumaticCraft and the mod team has advised this is not an issue so has no intentions on fixing it, see below:

> The warning (not error) is completely harmless, so you can just ignore it. Evilcraft does in fact register a "werewolf" villager profession, but I guess it doesn't add any trades to it. The Amadron system periodically scans all known villager professions, looking for trades at random to add to the live offers list, and just warns about the lack of werewolf trades, because it's strange having a villager profession which doesn't have any trades.

From [this issue](https://github.com/TeamPneumatic/pnc-repressurized/issues/1104) on the PneumaticCraft Repressurized repo.
