### ISSUE TITLE
Invisible chunks and blocks with collision

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-8#279]
I have been encountering this bug a few times now, sometimes I come across these invisible chunks with blocks in them that still have collisions.
Reloading the save fixes the issue and makes the chunks and their blocks render correctly.
[Latest Log](https://paste.gg/p/anonymous/7a2f342df2c4455b9bd42412afe300f9)
![image](https://user-images.githubusercontent.com/88629925/201765660-4e377f17-7a0f-4341-9dc9-de62164fa123.png)

**Comment by jmarfernandes** [comment]
The same is happening to me, have you found a fix?

**Comment by codesmith47** [comment]
I've tried the default shaders and it fixed it seus seems to have Problems.
