### ISSUE TITLE
ATM8 wont load after 1.0 update

### ISSUE THREAD

**Issue by casvantas** [AllTheMods/ATM-8#280]
So when I updated to 1.0 on both of my pcs I noticed that it wouldn't let me join my server because I was missing the enhanced celestial mod, so I went and put it in and on the first pc it loaded fine but on the second minecraft won't load at all anymore. Any suggestions?

**Comment by James103** [comment]
Can you please post the resulting log files?

The game may have crashed on startup. If so, can you please also post the crash report?
