### ISSUE TITLE
all the mods 8 crashing on start up 

### ISSUE THREAD

**Issue by Liladamant22** [AllTheMods/ATM-8#282]
been trying stuff out and no dice not sure whats up
[hs_err_pid6928.log](https://github.com/AllTheMods/ATM-8/files/10009907/hs_err_pid6928.log)

**Comment by megan-black** [comment]
I'm having the same issue after trying to restart the server

**Comment by Liladamant22** [comment]
Lol it’s pissing me off honestly I’ve been trying different methods and no dice but this was my last option so I hope the devs or someone can help me out

**Comment by megan-black** [comment]
Ok so I found a workaround, mine was caused by forge/atm8 updating so I forced a rollback to the forge version I have my client on (stopping an auto-update) and my server started up just fine

**Comment by Liladamant22** [comment]
I'm happy you figure, on my case still nothing
