### ISSUE TITLE
cant craft a turtle cc:tweaked

### ISSUE THREAD

**Issue by melb123** [AllTheMods/ATM-8#284]
whenever inputting the recipe to craft an advanced turtle i only get a advanced computer back 
![image](https://user-images.githubusercontent.com/47229188/201950898-72a6abb8-7721-441f-9a7b-603a11d42012.png)  (what i get)
![image](https://user-images.githubusercontent.com/47229188/201951077-ef57d37d-b8f5-4906-94c0-8b8f85b67782.png)  (recipe)

for what its worth i also tried looking for a config file just in case it was a setting turned off came up empty handed.

**Comment by ThePotato97** [comment]
> whenever inputting the recipe to craft an advanced turtle i only get a advanced computer back ![image](https://user-images.githubusercontent.com/47229188/201950898-72a6abb8-7721-441f-9a7b-603a11d42012.png) (what i get) ![image](https://user-images.githubusercontent.com/47229188/201951077-ef57d37d-b8f5-4906-94c0-8b8f85b67782.png) (recipe)
> 
> for what its worth i also tried looking for a config file just in case it was a setting turned off came up empty handed.

![image](https://user-images.githubusercontent.com/10260415/202070613-a67e61a0-89ec-4922-84dc-176f979d510b.png)
