### ISSUE TITLE
Updating server to 8-1.0.1

### ISSUE THREAD

**Issue by Minecraftasaurus** [AllTheMods/ATM-8#285]
Yesterday I attempted to update my server to the latest modpack version 8-1.0.1. Once the pack was updated I attempted to login and test it to make sure everything is working. To my surprise I wasn't able to login due to the update not having over 100 mods installed from the previous versions. It is possible this issue could be server host related or just user error. Also keep in mind I haven't had any trouble updating the server to any other version until now with the new version. So, I went back to the dashborad, reinstalled everything again to the newest version and the same thing happened. If you or anyone else has any idea what could be causing this please let me know. I can't for the life of me figure out if it is caused by the new modpack update or not. For now we have to keep the server on the current 8-1.0.0 update until I find a workaround for this problem.

**Comment by frnikho** [comment]
I believe that an issue from the server host, I did this update two days ago with this following guidelines 
https://www.reddit.com/r/allthemods/comments/uy4mzr/guide_to_update_server_all_the_mods_7/ 
and eveything seem to work with the 8-1.0.1 client and server
