### ISSUE TITLE
Refined Storage Questline

### ISSUE THREAD

**Issue by pkrjuzam** [AllTheMods/ATM-8#288]
Advanced Importer and Advanced Exporter are removed from JEI. as there Cable Tiers is part of the Pack.
Both can't be crafted. but they are both still in the Questline. So Chapter can't be finished.

**Comment by alfredggttv** [comment]
Currently, I am rewriting the Refined Storage chapter. These will be removed in a future update. In the meantime, you can complete these quests by using the command: 

> Importer: /ftbquests change_progress {username} complete 355BFF36994B3916

> Exporter: /ftbquests change_progress {username} complete 383DCC6ADE5364B5

If you're on a server, you'd need an admin to be able to do this.
