### ISSUE TITLE
Immense lag when viewing variable recipes in JEI within a large storage system with many items

### ISSUE THREAD

**Issue by sSasha-uwu** [AllTheMods/ATM-8#289]
To repro:

1) Create large storage system (Eg. Refined Storage)

2) Fill storage with many random items

3) View large storage system

4) Open a recipe with a variable item recipe (Eg. Crafting Table)

5) FPS drops massively. With a very big storage system and/or a recipe with many variants the FPS can drop well below 1

Importantly, this issue does not occur when not concurrently viewing a large storage system.

This issue happens in both singleplayer and multiplayer and is independent of hardware configurations.

If I had to guess this situation is forcing JEI to make far too many item comparisons in order to figure out if the crafting grid can be filled via the + button or not. Assuming I'm correct, either JEI's code needs to be heavily optimized or a cap needs to be introduced that prevents it from making too many item comparisons.

**Comment by Jonz00r** [comment]
The answer you're likely to get is to switch to AE2. It only happens with refined storage. It seems to have something to do with RS and create from all the issues I've read here.

**Comment by HealYouDown** [comment]
Having the same issue in my world. RS is literally unusable with this issue, even with a small amount of items stored.

I recorded a video that shows the lag spikes.

https://user-images.githubusercontent.com/28159123/202901448-854d1da1-897c-48c6-96c8-8cda009616f7.mp4

**Comment by NiciusB** [comment]
Same thing happening to me. Like others said, it lags only when in a Refined Storage's Crafting Grid with a large amount of items. If I just open JEI in my inventory it doesn't lag at all.

I had the same issue in Stoneblock 3, so I think it has to do with JEI or RF in recent minecraft versions, and not ATM8
