### ISSUE TITLE
Botany Pot don't work with Menril Sapling

### ISSUE THREAD

**Issue by menguele** [AllTheMods/ATM-8#296]
When using a Menril Sapling in a hopper botany pot, production occurs once, sometimes twice, then stop completely, even if progress is 100%

**Comment by Mopar** [comment]
Can confirm. it doesn't matter on which pot you use (standard or hopper) or where its placed (indoor/outdoor/underground/etc).

**Comment by Dunwich** [comment]
There is a bug in botany pot for custom loot table where if the loot roll ends up with nothing, the plant will stop growing. The author is going to fix it

See : https://github.com/Darkhax-Minecraft/BotanyPots/issues/275

**Comment by Darkhax** [comment]
Sorry for the delay, this was fixed in 9.0.16. The updates since then also added support for a significant number of trees and crops.
