### ISSUE TITLE
exit code: -1

### ISSUE THREAD

**Issue by iFenix24** [AllTheMods/ATM-8#298]
when i try to start the ATM 8 the game doesn't start and it say exit code: -1. I tryed to reinstall minecraft (even delete the .minecraft in the %appdata% fonder) reinstall java (this started after i update it trying to fix a bug) and reinstall the ATM but it still say exit code: -1. At this point i don't know what to do, if someone know please tell me how to fix it.

**Comment by Eld0r** [comment]
Oi,
sounds like wrong java version.
make sure you have java17 installed.

**Comment by iFenix24** [comment]
> Oi, sounds like wrong java version. make sure you have java17 installed.

still doesn't work
