### ISSUE TITLE
Failed to log in: The authentication servers are currently not reachable. Please try again.

### ISSUE THREAD

**Issue by alpacaqueen42** [AllTheMods/ATM-8#305]
This is the message me and my friend both get when trying to join my server. It is not port forwarded, we just use hamachi. I've been troubleshooting by myself for hours and I've tried: adding new rules to firewall for both java and hamachi, inbound and outbound. Allocated more ram to minecraft, allocated more ram to atm, allocated more ram to the server. reinstalled java and forge. Edited the run.bat file to replace "java" with the install path for java 17 as per the instructions. Checked the host file thing in powershell but I didn't have "mojang" to delete in there. Cleared DNS cache and reset winsock. I have very good internet connection and in the server list, it shows that the server is online with full bars. What more can I try?

**Comment by Sean3926** [comment]
I am also having this issue

**Comment by Sean3926** [comment]
Anyone have any input still having this issue

**Comment by rickym-h** [comment]
I am also having this issue, has anyone found a solution yet?

**Comment by alpacaqueen42** [comment]
> 

The issue turned out to be totally on Microsoft, it was finally fixed when my computer updated to windows 11, hope this helps.

**Comment by alpacaqueen42** [comment]
> Anyone have any input still having this issue

The issue turned out to be totally on Microsoft, it was finally fixed when my computer updated to windows 11, hope this helps.

**Comment by alpacaqueen42** [comment]
The issue was solved for me when my computer updated to windows 11
