### ISSUE TITLE
The Soul Engulfing recipe for Dimensional Seed is directional.

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-8#310]
As of ATM8 1.0.2, the Soul Engulfing recipe for the Dimensional Seed is not symmetric at all. Since the Spirit mod checks blocks in a specific order, it assumes a specific rotation for any recipes used.

Therefore, the recipe **must** be built with the Teleport Pad facing **south** and the Dimensional Storage Actuators and Miniature Nether Portal on the **north** side. No other direction will work.

**Comment by alfredggttv** [comment]
I have had a chat with the mod author to see if we could find a potential fix, as it has to do with the render being shown. For the time being, I have added info to JEI in my latest PR to help with this.
