### ISSUE TITLE
Server crashes 60 sec after Startup (Corrupted World)

### ISSUE THREAD

**Issue by gefJoghi** [AllTheMods/ATM-8#314]
## What happend
Every Wednesday on 1 am my server restarts automatically.
After restart, the server crashes 60 seconds after startup.
If I started the server on a new world, the server worked without crashing.

## Crash reports
[crash-2022-11-23_07.38.53-server.txt](https://github.com/AllTheMods/ATM-8/files/10073423/crash-2022-11-23_07.38.53-server.txt)
[crash-2022-11-23_07.53.59-server.txt](https://github.com/AllTheMods/ATM-8/files/10073424/crash-2022-11-23_07.53.59-server.txt)

## Something I tried that worked
My server is now working again because I deleted the disk file (Item: **4096k Storage Disk** from Extra Disks) for Refined Storage.
Back in my world I took that storage disk and yeah it's empty (Not that bad but slightly annoying)

Edit:
I removed the disk and insert the "refinedstorage_disks.dat" file and filtered the Quiver from the Supplementaries mod
and now it worked with all my Items ._.
![2022-11-23 08_59_52-Minecraft_ 1 19 2 - Multiplayer (3rd-party Server)](https://user-images.githubusercontent.com/86330394/203496720-9201e36a-a89f-4024-8e49-b749c2f0d91a.png)

**Comment by Dunwich** [comment]
It didn't crash but I had a similar issue on my debian server.

My login attempt failed (timed out) and the server TPS was horrible, CPU stuck @ 100% according to top every time I attempted to login, dropped to 5% only after 15 minutes of not doing anything, tick @ 200000 ms behind on average.

Removing Refined Storage fixed everything in a local copy of the server and allowed me to log in. 

The real solution I found was removing a 4096k drive from refinedstorage_disks.dat with an NBT editor. as well as other filled drives. 

At the time I had a fully upgraded Stray spawner (enchanted bows) running 24/7. I looted hundreds of quivers. I think I soft-banned myself out of my server in a similar manner to the duplicated shulker box full of written book glitch in vanilla. Tbh I should have filtered the farm output, but I was lazy.

**Comment by James103** [comment]
It's possible the lag has to do with the number of types of items stored in the Refined Storage system.
Every Apotheosis gem counts as a different type, as well as every quiver, affix tool/armor item, etc.
If there's thousands of different types of items in the digital storage system, the server may lag horribly, whether the items are in external storage, on a single 64k (or greater) disk, on several 1k disks (in Refined Storage), or on many disk drives (in AE2).
