### ISSUE TITLE
[Feature Requested] Voicechat for multiplayer

### ISSUE THREAD

**Issue by Tomboru** [AllTheMods/ATM-8#317]
As the title already says it. It would be very nice if there would be a voicemod in this modpack.
For many server it can be a good feature, because often players don't want to chill with 20people in one discord call.

For every server and player that doesn't want it, can just turn it off and go on.

I am talking from this mod: https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat
Or some simillar that has the same functionallity.

**Comment by Mitchell5200** [comment]
Please use the mod suggestions pinned issue instead. #3
