### ISSUE TITLE
[Extra Storage] Crafter speed limited

### ISSUE THREAD

**Issue by Artcore1992** [AllTheMods/ATM-8#318]
Hi! I'm currently having an issue of netherite crafter (extra storage mod - RS addon) crafting speed being limited by any quality of I furnaces. Screenshot below. Any ideas whats going on?
I tried adding speed upgrades to crafter, speed upgrade to furnace - limit persists.
Basic Crafter from RS with speed upgrades yelds 5x crafting speed (working as it should i believe)

Tested with base game furnaces, both on server and in single player - limit present in both.
![pobrane (1)](https://user-images.githubusercontent.com/105590053/203650104-5cf0d534-ae0d-470d-8dc7-82c85c4c1d45.png)

**Comment by Artcore1992** [comment]
Did a little testing around and it seems to be related to spots available in the container connected to crafters (issue persists through all Extra Storage crafters) - Chest (default 27 slots) - limited to 27x speed, diamond chest (default 108 slots) - limited to 108x speed
![pobrane (2)](https://user-images.githubusercontent.com/105590053/203653154-f0fb0a4d-1656-4bf5-8d67-e12d3a9c8d4f.png)

**Comment by xBlackPoison357x** [comment]
I believe this is intentional: https://github.com/AllTheMods/ATM-8/pull/308#discussion_r1030923863

**Comment by Artcore1992** [comment]
Thanks, consider case close. 
Personally, I don't see any point in this change, since using chest was mostly for the purpose of set crafting, and now I have to use it for no reason to use Iron Furnaces to maximum potential. Given that, the space taken for setups is unnecessairly big.

**Comment by James103** [comment]
> I believe this is intentional: [#308 (comment)](https://github.com/AllTheMods/ATM-8/pull/308#discussion_r1030923863)

The change was actually done to fix https://github.com/Edivad99/ExtraStorage/issues/55, which was the issue about higher tier crafters not distributing the crafting job uniformly amongst themselves.

**Comment by parafson** [comment]
> > I believe this is intentional: [#308 (comment)](https://github.com/AllTheMods/ATM-8/pull/308#discussion_r1030923863)
> 
> The change was actually done to fix [Edivad99/ExtraStorage#55](https://github.com/Edivad99/ExtraStorage/issues/55), which was the issue about higher tier crafters not distributing the crafting job uniformly amongst themselves.

L change
