### ISSUE TITLE
[1.0.3] Game Crashes on Loading Screen / Missing Textures

### ISSUE THREAD

**Issue by MAXimized490** [AllTheMods/ATM-8#322]
Upon launching the game on version 1.0.3, the loading screen has missing textures. It crashes near the end of the loading bar. Possibly related to #320 
[crashLog.txt](https://github.com/AllTheMods/ATM-8/files/10080660/crashLog.txt)
![missingTextures](https://user-images.githubusercontent.com/36754183/203689681-68fcbb69-fc5b-4671-a2bc-6a98c319989e.png)

**Comment by Mitchell5200** [comment]
yeah the forge version is wrong set it to 43.1.55 or above, a fixed version will be soon

**Comment by Mitchell5200** [comment]
Version 1.0.3 has been re-uploaded with the correct forge version now.
Forge is now 43.1.57
Update, Closing.
