### ISSUE TITLE
ATM8 1.0.3 - "Connection Lost - Null pointer Exception" on starting singleplayer world

### ISSUE THREAD

**Issue by LamMods** [AllTheMods/ATM-8#323]
When trying to load up my world, I get a connection lost error on the first attempt. On 2nd attempt, it loads the world.

`Internal Exception: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null`

![image](https://user-images.githubusercontent.com/13630899/203709441-01d04428-0661-4492-bbc3-a6c026063e87.png)

**Comment by LamMods** [comment]
> You may need to do the following before attempting to rejoin (in singleplayer):
> 
>     1. Use an NBT Editor to open the level.dat file.
> 
>     2. Expand "Data", then "Player".
> 
>     3. You should find a "recipeBook" tag. Delete that tag.
> 
>     4. Save the changes and exit the editor.
> 
>     5. Try logging in again.
> 
> 
> In multiplayer, do the above steps for whoever's trying to join but can't, but the player data for a given player is held in the corresponding file's root tag meaning step 2 is not needed.
> 
> If you want to (try to) prevent the problem from happening in the future, do the following:
> 
>     1. Shut down the instance if it is running.
> 
>     2. Go into your instance's `minecraft/config` folder and open `quark-common.toml` in a text editor of your choice.
> 
>     3. Scroll down to the line that says `"Automatic Recipe Unlock" = true` and change that `true` value to `false`:
> 
> 
> ```toml
> [tweaks]
> 	"Automatic Recipe Unlock" = true
> ```
> 
>     4. Restart the game and try rejoining.
> 
>     5. If you are able to rejoin, and you have cheats enabled, you may want to run the following commands to prevent the recipeBook data from being too large again:
> 
> 
> ```mcfunction
> gamerule doLimitedCrafting false
> recipe take @a *
> ```

Didn't work. Still get the exact same error on the first attempt to load the world.

**Comment by jdpatdiscord** [comment]
Having the same issue. Btw using ATLauncher.

**Comment by James103** [comment]
If you get this error when trying to create a new world or join a world, you will need to restart the instance (as it appears from my testing) as otherwise all further attempts to create or join a world will result in being kicked with the same error.

**Comment by LamMods** [comment]
> If you get this error when trying to create a new world or join a world, you will need to restart the instance (as it appears from my testing) as otherwise all further attempts to create or join a world will result in being kicked with the same error.

Not what happens with me. That first attempt after launching is the only time it shows. I need to kill the client and restart it to reproduce it.
