### ISSUE TITLE
Functional Storage Items don´t render anymore

### ISSUE THREAD

**Issue by derpicasso** [AllTheMods/ATM-8#324]
Since updated to ATM 8 1.0.3 the items in a functinal storage drawer don´t render anymore. Blocks somehow still render correctly. Ofc i tried the configuration tool, its not that. 
The items are still there, they just don´t render. 
![2022-11-24_15 41 31](https://user-images.githubusercontent.com/94746886/203811811-8f240916-1047-43cb-86ef-f296c595dd83.png)

**Comment by chadle01** [comment]
same for me too

**Comment by chengheipui** [comment]
same here with version 1.0.3

**Comment by Mitchell5200** [comment]
Seems to be a forge issue, changing to forge 43.1.55 fixes the visual issue, it's been reported to the dev
https://github.com/Buuz135/FunctionalStorage/issues/130

**Comment by vvaffaru** [comment]
Also Buuz135/functionalStorage#122

> Seems to be a forge issue, changing to forge 43.1.55 fixes the visual issue, it's been reported to the dev [Buuz135/FunctionalStorage#122](https://github.com/Buuz135/FunctionalStorage/issues/122)
