### ISSUE TITLE
Conflict between Quark and All The Compressed blueprints

### ISSUE THREAD

**Issue by Wassep** [AllTheMods/ATM-8#329]
When putting Cobblestone, for example, in a crafter, filling all 3x3 squares, you can toggle between compressed cobblestone and Sturdy Stone, however when using a formuliac assemblicator/any crafting machine it doesn't show any recipe to auto craft compressed blocks. I assume this is because the conflict of both mods and it cannot display any formula to craft.

**Comment by James103** [comment]
One way to fix this is to change the Sturdy Stone recipe such that it is crafted with single-compressed Cobblestone plus some other item such as deepslate or iron nuggets.

**Comment by benjamin-poncet** [comment]
This doesn't seem to be a major downgrade given that the block isn't used in any other recipe...
What's your take on pushing this to the main branch?

**Comment by Mitchell5200** [comment]
Fixed in 1.0.7
