### ISSUE TITLE
Spam error in console from dimstorage

### ISSUE THREAD

**Issue by towzzer** [AllTheMods/ATM-8#33]
I have been getting spammed with this error "[Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file C:\Users\black\OneDrive\Desktop\The one true server\.\Boi\serverconfig\dimstorage-server.toml is not correct. Correcting" 

How can I fix this?

**Comment by tabbek** [comment]
I end up with the same issue.  The file and the copies it "replaces" are the same.  Tried things like removing comments, nothing helped.  On freebsd, in a jail.

`[00:04:45] [Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /var/games/minecraft/servers/atm8_1_19/./world/serverconfig/dimstorage-server.toml is not correct. Correcting`
`[00:04:47] [Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /var/games/minecraft/servers/atm8_1_19/./world/serverconfig/dimstorage-server.toml is not correct. Correcting`
`[00:04:49] [Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /var/games/minecraft/servers/atm8_1_19/./world/serverconfig/dimstorage-server.toml is not correct. Correcting`

**Comment by alfredggttv** [comment]
Going through several logs on both singleplayer and my server, this seems to be fixed.
