### ISSUE TITLE
Double Doors are broken

### ISSUE THREAD

**Issue by haruofwater** [AllTheMods/ATM-8#331]
Double Doors when opened by hand close immediately. Single doors are fine , create doors that slide are fine, redstone opening works aswell. seems to be a double door opening glitch.

**Comment by LamMods** [comment]
Same. Also, multiple reports of the same issue over on discord: https://discord.com/channels/254530689225981953/1045248944122368070

**Comment by seemsindie** [comment]
Same

**Comment by xYuyuma** [comment]
Shift + Right click works to open double doors
