### ISSUE TITLE
Dimensional Seed includes base stone of Nether and End but not Overworld

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-8#332]
Currently (ATM8 1.0.3), the Dimensional Seed recipe includes the base stones of the Nether (Netherrack) and the End (End Stone), but not the Overworld.

In other words, the Dimensional Seed can be crafted without mining a significant amount of base stone from the Overworld, even though mining such base stone is effectively required in the Nether and the End for a successful craft.

Fixing this would probably involve adding a sextuple-compressed Stone Block and/or a sextuple-compressed Deepslate Block in the recipe for the Dimensional Seed. The first option would have the blocks replace the Dimensional Storage Actuators, while the second option would have the blocks replace the compressed Diamond and Emerald blocks in the recipe. Either way, the cobblestone would need to be placed on the left side and the deepslate would go on the right side (or vice versa).
(Compression amounts are subject to change)

Furthermore, the Dimensional Seed includes a significant amount of blue in its texture, signifying that it may have some Overworld components to it.

**Comment by alfredggttv** [comment]
This will definitely be considered for a future iteration of the recipe. Thank you for the review!
