### ISSUE TITLE
Crash at startup - 1.0.4

### ISSUE THREAD

**Issue by MoeHunt3r** [AllTheMods/ATM-8#339]
Client crashed while starting 
Crashlog:
https://pastebin.com/EX63QLL9

**Comment by Nav1ra** [comment]
same issue here after updating to 1.0.4

**Comment by 0xRowie** [comment]
A friend of mine and myself included are also having this issue.

**Comment by weaponoftheday** [comment]
Server launches fine but client not starting, same as the others above.

**Comment by 0xRowie** [comment]
> 

I will try this as well, will update this message soon

**Comment by weaponoftheday** [comment]
I think it was downloading something when it hangs. After the initial stall on startup I have had no issues with this I even lowered memory space back and it still starts without issue.
