### ISSUE TITLE
Unable to lavalog Mekanism Heat Generator

### ISSUE THREAD

**Issue by RoyalReject** [AllTheMods/ATM-8#34]
Mekanism Heat Generators have a function of shift clicking the heat generator with a lava bucket to log the machine with lava thus adding a valid side for passive energy generation, I am unable to do this, I originally found this out in version 0.0.8 but it also occurs in 0.0.10, I have loaded up an instance with only mekanism and this function works so it is not mekanism itself something is interacting weird within the pack

**Comment by Mitchell5200** [comment]
possible canary issue, working after removal, closing
