### ISSUE TITLE
How to remove a mod witout having data pack fail on world creation

### ISSUE THREAD

**Issue by Huginn-Odinbro** [AllTheMods/ATM-8#340]
I'm trying to remove when dungeons arise because the spawns are just way too frequent in my world and I don't understand how to modify it. When I remove it though I am unable to create a world because I get a data pack error, which then brings me to a screen with what looks like over a hundred data packs, most of which say they are incompatible, and I have to go and manually add every single one. Do I just find and delete the "when dungeons arise" data pack from that list, and manually add all the others?

**Comment by Huginn-Odinbro** [comment]
Sorry, I figured out I could go through the data pack list DURING world creation and just remove the dungeons arise data pack from the list. Is there a way to configure it though? Anyways, you can consider this closed, sorry for taking up your time.

**Comment by enigmaquip** [comment]
You need to remove the folder `kubejs/data/dungeons_arise` from your install, that's why it's failing
