### ISSUE TITLE
MEGA CELLS: Mega Radioactive chemical storage cell is not working

### ISSUE THREAD

**Issue by Rafamzo** [AllTheMods/ATM-8#341]
Automatization the fission reactor, Solar Neutron Activator and pressurized reaction chamber  for crafting polonium.
 The problem is the Mega Radioactive chemical storage cell is not import the waste and polonium (chemical), I'm not sure is this happen to plutonium, not tested.
![Cell](https://user-images.githubusercontent.com/16180666/204117772-36841751-b0e5-4ee8-b907-7a19dcad2b14.png)
![not import nuclear waste 2](https://user-images.githubusercontent.com/16180666/204117774-a14fda7d-ddba-4084-9816-ac3df0a4697e.png)
![not import nuclear waste](https://user-images.githubusercontent.com/16180666/204117775-e591649f-749b-40a2-a0b6-5874301f632b.png)
![polonium](https://user-images.githubusercontent.com/16180666/204117776-db24ec45-b7b2-4230-a157-cbf660066cab.png)

**Comment by James103** [comment]
The Radioactive Storage Cell is only able to store 1 type of gas (which may be radioactive), but the gas type the cell is to hold must be set beforehand by partitioning the cell in the Partitioning Table.

The Radioactive Storage Cell is useless if it is "Not Partitioned" (as shown in the tooltip).

**Comment by Rafamzo** [comment]
Yes, you right. Thanks for the help

**Comment by dekzgh** [comment]
How were you able to partition the drives?

**Comment by Jekian** [comment]
> How were you able to partition the drives?

Cell workbench from AE2

**Comment by QarthO** [comment]
How did u partition the drives? I'm not able to use a gauge dropper, and I cant drag it from JEI

**Comment by NotGreyghost** [comment]
How were you able to?

**Comment by dekzgh** [comment]
I cant remember exactly but i eventually got drag and drop to workSent from my iPhoneOn Nov 3, 2023, at 1:55 AM, Greyghost ***@***.***> wrote:﻿
How were you able to?

**Comment by zeng-github01** [comment]
JEI needs to be installed to label these gases. Search for the corresponding gas in JEI, then hold down the left mouse button and drag the corresponding item in JEI to Cell Workbench.

This is a text using translator, I hope there is no understanding problem
