### ISSUE TITLE
ADD CORAIL RECYCLER MOD

### ISSUE THREAD

**Issue by Vicmargel55** [AllTheMods/ATM-8#344]
It could be interesting that they add Corail Recycler mod for uncraft items of all mods.
Thanks!

I tried to put it manually but it doesn't work in my worlds (i don't know why). It says "invalid player data".

**Comment by Mitchell5200** [comment]
Do not open new issues for mod Suggestions, use #3 

Closing.

**Comment by enigmaquip** [comment]
This is not the proper place for suggestions, there is an issue specifically for that. As a side note, if we wanted a recycler we wouldn't have removed twilight's version. So this suggestion wouldn't be added anyways
