### ISSUE TITLE
ATM 8

### ISSUE THREAD

**Issue by Ebolahasla** [AllTheMods/ATM-8#345]
Hi all. When a friend tries to log in to me (I opened the world to the network), I get a stable error "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException." Completely reinstalled assemblies and java, but still nothing helps. The same error comes out if I try to access it. We use RadminVPN and Hamachi. There are no problems in vanilla minecraft, only when entering on this build. Please, help.

**Comment by Mitchell5200** [comment]
Open to LAN is known broken, the best solution i have is to self host a server instance on one of your PC's
