### ISSUE TITLE
1.0.2 Server looping crash

### ISSUE THREAD

**Issue by Gayanfalor** [AllTheMods/ATM-8#346]
Hello, we were in atm miing dim setting up a reactor with imporiting items from menril network, and after a bit the server crashed and now he non stop crash.

How to fix that ? is that crash from integrated dynamics ? as the network is in overworld and not chunkloaded? or from something else ?

[crash-2022-11-27_14.01.05-server.txt](https://github.com/AllTheMods/ATM-8/files/10098781/crash-2022-11-27_14.01.05-server.txt)

**Comment by KagetaneHiruko** [comment]
Hi, can you check the server.properties? There should be a line called "max-tick-time", it should be on -1.
