### ISSUE TITLE
Crafting Allthemodium alloy tools. ISSUE! BUG! IMPORTANT!

### ISSUE THREAD

**Issue by tykoATM** [AllTheMods/ATM-8#347]
Hey,
The only way to craft a Allthemodium ally tool is to use a mod called ars nouveau.
As shown in the screenshot this is the correct format that matches the recipe (dev confirmed it was correct) . Im also using a creative jar with has infinite source. Possible fix is to remove the source requirment from the recipe.
Im not sure what the problem is exactly but im almost positive its on ATM's end.

![image](https://user-images.githubusercontent.com/119271649/204176147-aaa0d299-2471-4671-b734-fe13f44080ea.png)
![image](https://user-images.githubusercontent.com/119271649/204176595-85fe8d36-7edd-4e08-afbd-bdc61fda9d67.png)

Any suggestions are much appreciated
Thanks tyko.

**Comment by Mitchell5200** [comment]
Yes we are aware of this, and it's getting fixed in the next release, #342 is the PR where it's fixed
