### ISSUE TITLE
Wrong forge version preinstalled on server package for modpack verison 8-1.0.4

### ISSUE THREAD

**Issue by Lollerix** [AllTheMods/ATM-8#350]
On a fresh install using Server miner's installer, the server can't start on it's own because a mod is looking for a more recent forge update.

**Comment by weaponoftheday** [comment]
I've had no issues. It sometimes stalls on MixIn initialization but stopping and restarting the sever works for me.

**Comment by Mitchell5200** [comment]
pack version 1.0.4 comes with forge 43.1.55, there was only one other forge version available at the time of release, and that was causing render issues client side, ensure Server miner is correctly using the forge version we set
