### ISSUE TITLE
No server start scripts in the latest release

### ISSUE THREAD

**Issue by kBraDrs** [AllTheMods/ATM-8#355]
I am trying to install this via docker on Linux, but keep receiving an error that there are no start scripts in the modpack. The README file also says to run the start script provided to open the server but there are none provided.

**Comment by kBraDrs** [comment]
Below is the line in the logs that indicate that a start script cannot be found. As previously mentioned, this is on docker with Linux so I do not have a GUI to be able to run the forge installer jar file manually

11/29/2022 8:47:23 AM
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
11/29/2022 8:47:23 AM
[init] ERROR: Modpack missing start script and unable to find Forge jar to generate one
11/29/2022 8:47:25 AM
[init] Running as uid=1026 gid=100 with /data as 'drwxrwxr-x 1 1026 100 556 Nov 29 07:54 /data'
11/29/2022 8:47:27 AM
[init] Resolved version given LATEST into 1.19.2 and major version 1.19
11/29/2022 8:47:28 AM
[init] Resolving type given CURSEFORGE
11/29/2022 8:47:29 AM
[init] Looking for Feed-The-Beast / CurseForge server modpack.
11/29/2022 8:47:29 AM
[init] Unpacking FTB server modpack /modpacks/ATM8.zip ...
11/29/2022 8:47:35 AM
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
11/29/2022 8:47:35 AM
[init] ERROR: Modpack missing start script and unable to find Forge jar to generate one
11/29/2022 8:47:37 AM
[init] Running as uid=1026 gid=100 with /data as 'drwxrwxr-x 1 1026 100 556 Nov 29 07:54 /data'
11/29/2022 8:47:39 AM
[init] Resolved version given LATEST into 1.19.2 and major version 1.19

**Comment by kBraDrs** [comment]
This is my docker compose for context

version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - UID=1026
      - GID=100
      - TYPE=CURSEFORGE
      - SERVER_NAME="Server"
      - CF_SERVER_MOD=/modpacks/ATM8.zip
      - JVM_XX_OPTS=-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15
      - MAX_MEMORY=4G
      - EULA=TRUE
    volumes:
      - /volume1/docker/minecraftjava:/data:rw
      - /volume1/docker/minecraftjava/modpacks:/modpacks
    network_mode: host
    restart: always

**Comment by Mitchell5200** [comment]
while i don't know much about Docker and linux, it seems (after checking some notes) this command will install forge with the installer `java -jar forge-1.19.2-43.1.55-installer.jar --installServer`

**Comment by kBraDrs** [comment]
It seems like maybe it's only the "Simple Server Startup" files that are currently working for my solution. Do you think there will ever be one of these for ATM8?

**Comment by Mitchell5200** [comment]
you might be able to tweak and edit the the atm7 one to work for atm8, it should be a forge variable and changing some 7s to 8s, but i'll look into it for future pack versions.

**Comment by kBraDrs** [comment]
Thank you, and if you could possible let me know what changes are needed or when the release will be coming, that would be great

**Comment by Mitchell5200** [comment]
i've just looked at the file and given it a test, you just need to change the forge version to `43.1.55`, change anything saying 1.18.2 to 1.19.2, and change any `ATM7` references to `ATM8`, and maybe change the MOTD to be atm8 instead of atm7.
I'll speak with the rest of the team and check if there's anything else needed for that, but for now it seems to be working for me on my windows PC.

**Comment by kBraDrs** [comment]
Which file are you looking at?

**Comment by Mitchell5200** [comment]
in my case, the `startserver.bat` from the atm7 server zip, for you it'll be the `startserver.sh` but it's 90% the same

**Comment by kBraDrs** [comment]
This is the file, doesnt mention ATM nor ForgeVersion anywhere

#!/bin/bash

# `-d64` option was removed in Java 10, this handles these versions accordingly
JAVA_FLAGS=""
if (( $(java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1) < 10 )); then
    JAVA_FLAGS="-d64"
fi

DO_RAMDISK=0
if [[ $(cat server-setup-config.yaml | grep 'ramDisk:' | awk 'BEGIN {FS=":"}{print $2}') =~ "yes" ]]; then
    SAVE_DIR=$(cat server.properties | grep 'level-name' | awk 'BEGIN {FS="="}{print $2}')
    mv $SAVE_DIR "${SAVE_DIR}_backup"
    mkdir $SAVE_DIR
    sudo mount -t tmpfs -o size=2G tmpfs $SAVE_DIR
    DO_RAMDISK=1
fi
if [ -f serverstarter-2.2.0.jar ]; then
    echo "Skipping download. Using existing serverstarter-2.2.0.jar"
    java $JAVA_FLAGS -jar serverstarter-2.2.0.jar
    if [[ $DO_RAMDISK -eq 1 ]]; then
        sudo umount $SAVE_DIR
        rm -rf $SAVE_DIR
        mv "${SAVE_DIR}_backup" $SAVE_DIR
    fi
    exit 0
else
    export URL="https://github.com/BloodyMods/ServerStarter/releases/download/v2.2.0/serverstarter-2.2.0.jar"
fi
echo $URL
which wget >> /dev/null
if [ $? -eq 0 ]; then
    echo "DEBUG: (wget) Downloading ${URL}"
    wget -O serverstarter-2.2.0.jar "${URL}"
else
    which curl >> /dev/null
    if [ $? -eq 0 ]; then
        echo "DEBUG: (curl) Downloading ${URL}"
        curl -o serverstarter-2.2.0.jar -L "${URL}"
    else
        echo "Neither wget or curl were found on your system. Please install one and try again"
    fi
fi
java $JAVA_FLAGS -jar serverstarter-2.2.0.jar
if [[ $DO_RAMDISK -eq 1 ]]; then
    sudo umount $SAVE_DIR
    rm -rf $SAVE_DIR
    mv "${SAVE_DIR}_backup" $SAVE_DIR
fi

**Comment by kBraDrs** [comment]
I see the confusion, I mean this file SIMPLE-SERVER-FILES-0.0.32.zip

Its the only way it seems to work properly

**Comment by Mitchell5200** [comment]
that is certainly not the file that's in the atm7 server zip that i was talking about, below is `startserver.sh` file from the ATM7 0.4.34 server pack
```
#!/bin/sh
set -eu
FORGE_VERSION=40.1.80
# To use a specific Java runtime, set an environment variable named ATM7_JAVA to the full path of java.exe.
# To disable automatic restarts, set an environment variable named ATM7_RESTART to false.
# To install the pack without starting the server, set an environment variable named ATM7_INSTALL_ONLY to true.

INSTALLER="forge-1.18.2-$FORGE_VERSION-installer.jar"
FORGE_URL="http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.18.2-$FORGE_VERSION/forge-1.18.2-$FORGE_VERSION-installer.jar"

pause() {
    printf "%s\n" "Press enter to continue..."
    read ans
}

if ! command -v "${ATM7_JAVA:-java}" >/dev/null 2>&1; then
    echo "Minecraft 1.18 requires Java 17 - Java not found"
    pause
    exit 1
fi

cd "$(dirname "$0")"
if [ ! -d libraries ]; then
    echo "Forge not installed, installing now."
    if [ ! -f "$INSTALLER" ]; then
        echo "No Forge installer found, downloading now."
        if command -v wget >/dev/null 2>&1; then
            echo "DEBUG: (wget) Downloading $FORGE_URL"
            wget -O "$INSTALLER" "$FORGE_URL"
        else
            if command -v curl >/dev/null 2>&1; then
                echo "DEBUG: (curl) Downloading $FORGE_URL"
                curl -o "$INSTALLER" -L "$FORGE_URL"
            else
                echo "Neither wget or curl were found on your system. Please install one and try again"
                pause
                exit 1
            fi
        fi
    fi

    echo "Running Forge installer."
    "${ATM7_JAVA:-java}" -jar "$INSTALLER" -installServer
fi

if [ ! -e server.properties ]; then
    printf "allow-flight=true\nmotd=All the Mods 7\nmax-tick-time=180000" > server.properties
fi

if [ "${ATM7_INSTALL_ONLY:-false}" = "true" ]; then
    echo "INSTALL_ONLY: complete"
    exit 0
fi

JAVA_VERSION=$("${ATM7_JAVA:-java}" -fullversion 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
if [ ! "$JAVA_VERSION" -ge 17 ]; then
    echo "Minecraft 1.18 requires Java 17 - found Java $JAVA_VERSION"
    pause
    exit 1
fi

while true
do
    "${ATM7_JAVA:-java}" @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-$FORGE_VERSION/unix_args.txt nogui

    if [ "${ATM7_RESTART:-true}" = "false" ]; then
        exit 0
    fi

    echo "Restarting automatically in 10 seconds (press Ctrl + C to cancel)"
    sleep 10
done
```

**Comment by Mitchell5200** [comment]
> I see the confusion, I mean this file SIMPLE-SERVER-FILES-0.0.32.zip
> 
> Its the only way it seems to work properly

and that file is a outdated file from 0.0.32 of the pack, from when it was briefly on MC 1.17

**Comment by enigmaquip** [comment]
Our old `SIMPLE-SERVER` format was before Curseforge changed their API rules, we no longer include a mod downloader in the modpack zip and in fact include all server side mods in the zip. Your best bet, and what I do when I use itzg's docker, is to make a Forge server with it instead with the appropriate version of forge and then copy over the directories from the zip to your data folder

**Comment by kBraDrs** [comment]
It appears that I may have gotten it working with help from Mitchell5200.
The only issue now is that I do only have 6gb of RAM in my NAS server, I knew this would be a problem and I was going to have to upgrade either way, I was just hoping that I could at least get the server to run without destroying my NAS as it is currently my DHCP and DNS server, so everything went offline when I try and launch it.

Thank you for the help guys

**Comment by jdnossaman** [comment]
The solution I found for  itzg/minecraft-server is to repack the .zip file. The container will try and unzip the server files and rename the folder to FeedTheBeast. It will then look for the start script and run it. The problem I found was the way the server files are packed results in a folder structure like "FeedTheBeast/Server-Files-1.0.5/<files>". So I repack the files without a parent folder before transferring it to the server. Then when the container unpacks the zip file you get a folder structure of "FeedTheBeast/<files>". I hope that makes sense.

**Comment by captainhook** [comment]
> It appears that I may have gotten it working with help from Mitchell5200. The only issue now is that I do only have 6gb of RAM in my NAS server, I knew this would be a problem and I was going to have to upgrade either way, I was just hoping that I could at least get the server to run without destroying my NAS as it is currently my DHCP and DNS server, so everything went offline when I try and launch it.
> 
> Thank you for the help guys

Could you kindly share the Dockerfile and any other info? Thanks
