### ISSUE TITLE
[Player] moved too quickly! since update 1.0.4

### ISSUE THREAD

**Issue by tairogriz** [AllTheMods/ATM-8#363]
Hello, 
since I updated the server, I can not fly or move fast. If I do so, I will be tped back ever 1 to 2 seconds. Even if I just fall from the sky, this happens 1 to 2 times till I arrive at the bottom. The log says "[Player] moved too quickly![...]". TPS are never below 20. 
I set /gamerule disableElytraMovementCheck true, but this does not change anything.

**Comment by Bassat273** [comment]
i am also seeing the same issue in 1.0.8
