### ISSUE TITLE
ATM 8 1.0.4 Sulfur can not be exported from ME

### ISSUE THREAD

**Issue by fkempf78** [AllTheMods/ATM-8#364]
Edit: Thermal Sulfur is not exported through ME Exporter.
Steps to reproduce: 
Build ME
Insert Thermal Sulfur
Try to Extract with Exporter.
Manual Pick up is possible

**Comment by Mitchell5200** [comment]
I'm unable to reproduce this issue, are you sure your export bus is connected to your system, and is configured to output sulfur

![2022-12-01_11 53 09](https://user-images.githubusercontent.com/45913837/204962055-a3aaf7d3-5b8d-4920-b60c-207512f98e3e.png)
![2022-12-01_11 52 58](https://user-images.githubusercontent.com/45913837/204962060-12cda4ed-a96b-4697-90ba-358715592acd.png)
