### ISSUE TITLE
Fix wrong heights for Vibranium Ore in the Allthemodium Book + Quest Book

### ISSUE THREAD

**Issue by CyrolX** [AllTheMods/ATM-8#368]
The Allthemodium Book states, that Vibranium Ore is found in Warped and Crimson Forests in the Nether around y = 107 and y = 113. The Quest Book states, that Vibranium Ore is found in the aforementioned biomes between y = 100 and y = 123. (The Allthemodium Book also mentions Vibranium being generated in the The Other dimension in the vicinity of Piglin Villages, which I haven't yet confirmed).

Both of these coordinates aren't true though. It seems Vibranium can only be found on walls (and probably ceilings, which I couldn't verify yet) in the Warped and Crimson Forest biomes between y = 81 and y = 102, as far as my research goes.

Here are some screenshots showing the issue in the Nether:

Excavation site in a Warped Forest at y = 111. I would've expected at least one Vibranium at this height, yet there was none. For comparison: I found one block of Ancient Debris there.
![2022-11-30_22 45 42](https://user-images.githubusercontent.com/31181255/204917899-d0d77e03-fb7e-42e7-93a6-a2f752794769.png)

Highest Vibranium Ore source found in the Warped Forest at y = 102. (Ignore Jennifer, she's doing her best)
![2022-11-30_23 07 50](https://user-images.githubusercontent.com/31181255/204918621-1252c25d-21f5-4607-a3b9-ea0d2e45a6cc.png)

Lowest Vibranium Ore source found in the Crimson Forest at y = 81.
![2022-11-30_23 03 07](https://user-images.githubusercontent.com/31181255/204918771-3324c1d8-1332-44be-8a27-f67105477a95.png)

**Comment by G33kman** [comment]
"Ignore Jennifer, she's doing her best" I probably shouldn't have laughed out loud at that...
Thanks for the info though!

**Comment by James103** [comment]
From what I can tell, Vibranium ore appears to only generate replacing netherrack blocks **that have at least two sides exposed to air**.

This leads to the ore being found in singles &#x2248;90-95% of the time, with the rest being pairs and a minute amount of triplets.

In ATM8, the ore generated in bigger patches, replacing netherrack blocks that were not necessarily exposed to air.

**Comment by AceDrago** [comment]
same levels but in atm7 .34 in a new world that was generated from that version
