### ISSUE TITLE
Refined Storage elite and above importer and exporters bug

### ISSUE THREAD

**Issue by Sora21182** [AllTheMods/ATM-8#373]
I've using refined Storage for a while now but I keep running into a issue where all the importers and exporters that are elite grade or above wont change to fluids filter or wont let me change between blacklisting or whitelisting items

**Comment by kurbar** [comment]
Same issue. It applies to all configuration options on the exporters/importers (item/fluid, whitelist, redstone etc). They are not persisted when the gui is closed.

**Comment by Hiattech** [comment]
Adding my own comment to this.
Whitelist/blacklist mode do not work for importers. When setting items in whitelist mode, it pulls everything EXCEPT those in the whitelist. Clicking to change it to blacklist doesn't change it, instead it turns on redstone mode - requires redstone.
See my filter here: https://imgur.com/a/SfgVcRh
When I put these in the filter, it leaves those in the box and pulls everything else out. The exporters work just fine.

**Comment by Mitchell5200** [comment]
Fixed in RS core in 1.20, fix is unable to be backported at risk of breaking other addon mods

https://github.com/starforcraft/Cable-Tiers/issues/34#issuecomment-1627718193
