### ISSUE TITLE
Game crashing after placing Ars Nouveau Lectern

### ISSUE THREAD

**Issue by ConnerMcC12** [AllTheMods/ATM-8#38]
I placed a Bookwyrm Lectern (Ars Nouveau Mod) on my ATM8 Minecraft server, however as soon as I placed it the game crashed. My partner signed on to the server and could play until they tried to go to my base area and the game also crashed for them. Crash first occurred on ATM8 0.0.8, currently using ATM8 0.0.11 and issue is persisting.

Error Description:

The game crashed whilst registering texture
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.m_135827_()" because "p_215482_" is null

Exit Code: -1

**Comment by Mitchell5200** [comment]
now disabled according to the dev
https://github.com/baileyholl/Ars-Nouveau/issues/781
