### ISSUE TITLE
Crashes when the game stars up

### ISSUE THREAD

**Issue by SoupsGood** [AllTheMods/ATM-8#386]
Hey there, I really enjoy this modpack, very dynamic and has a lot to explore but I felt there was missing a couple of mods, 6 or 7, and then I added them. After that, I started the game on CurseForge launcher and then on the Minecraft Launcher and the game instead of loading with the customized textures(stars and everything else) loads with a missing texture and then gets back to the launcher, saying there's an error.
  Hope anyone can solve this.

**Comment by Mitchell5200** [comment]
logs via https://mclo.gs/ please

**Comment by SoupsGood** [comment]
> logs via https://mclo.gs/ please

 I'm so sorry to answer now but I need to put the logs folder, or just a specific file?

**Comment by Mitchell5200** [comment]
> > logs via https://mclo.gs/ please
> 
> I'm so sorry to answer now but I need to put the logs folder, or just a specific file?

the Latest log file will do, or a crash log if you have one

**Comment by SoupsGood** [comment]
> > > logs via https://mclo.gs/ please
> > 
> > 
> > I'm so sorry to answer now but I need to put the logs folder, or just a specific file?
> 
> the Latest log file will do, or a crash log if you have one

you got something?

**Comment by SoupsGood** [comment]
oh i'm so sorry, new to this

**Comment by SoupsGood** [comment]
https://mclo.gs/i1L7evk

**Comment by SoupsGood** [comment]
hey, now this is working, I updated the whole modpack to .57 and it works, I think that was something that you tried to explain so, thank you so much

**Comment by Mitchell5200** [comment]
Not the solution i was telling you to do, i said roll back FTB chunks to version build.168, and FTB ranks to version build.46.
But whatever, problem solved, closing.
