### ISSUE TITLE
functionalstorage.item.UpgradeItem Render issues, game crash when hover over Quest Icon 

### ISSUE THREAD

**Issue by MineCherry** [AllTheMods/ATM-8#388]
i just hovered with my cursor over quest in Storage ( pull & push upgrades ) 
tried 3 times. everytime the same crash

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-12-06 00:10:59
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122433_()" because the return value of "com.buuz135.functionalstorage.item.UpgradeItem.getDirection(net.minecraft.world.item.ItemStack)" is  

more in doc.
[crash-2022-12-05_23.54.48-client.txt](https://github.com/AllTheMods/ATM-8/files/10159302/crash-2022-12-05_23.54.48-client.txt)
[crash-2022-12-06_00.10.59-client.txt](https://github.com/AllTheMods/ATM-8/files/10159303/crash-2022-12-06_00.10.59-client.txt)

**Comment by Mitchell5200** [comment]
Fixed in 1.0.7
