### ISSUE TITLE
MEGA Cells crashes the game when changing mipmap levels or resource packs.

### ISSUE THREAD

**Issue by EdwardTheMememan** [AllTheMods/ATM-8#39]
[0.0.11] When you remove MEGA Cells the issue is fixed.
![image](https://user-images.githubusercontent.com/85826942/192098343-cb72a752-bf33-4dd2-90b4-dbdc4b2f25d8.png)

**Comment by 62832** [comment]
Both this and #37 have been fixed with the release of MEGA Cells 1.3.1.

**Comment by EdwardTheMememan** [comment]
Oh, thanks.

**Comment by theBeardyDwarf** [comment]
> Both this and #37 have been fixed with the release of MEGA Cells 1.3.1.

it keep crashing even with version 1.3.1
<img width="589" alt="Captura de Pantalla 2022-09-24 a la(s) 10 10 59" src="https://user-images.githubusercontent.com/22403094/192108042-1de82a7c-04d4-4475-b5eb-56206797e092.png">
<img width="929" alt="Captura de Pantalla 2022-09-24 a la(s) 10 11 55" src="https://user-images.githubusercontent.com/22403094/192108064-f17a6880-b0aa-4ecc-8e47-ccb5f4637a21.png">

**Comment by Mitchell5200** [comment]
> > Both this and #37 have been fixed with the release of MEGA Cells 1.3.1.
> 
> it keep crashing even with version 1.3.1 

Full crashlog via https://mclo.gs/ please

**Comment by theBeardyDwarf** [comment]
> > > Both this and #37 have been fixed with the release of MEGA Cells 1.3.1.
> > 
> > 
> > it keep crashing even with version 1.3.1
> 
> Full crashlog via https://mclo.gs/ please

https://mclo.gs/m4dcnuF

**Comment by theBeardyDwarf** [comment]
deleting the jar file and reinstalling it again , seems to have been fixed the issue.

thanks
