### ISSUE TITLE
Adding plugins

### ISSUE THREAD

**Issue by ItsAJonah** [AllTheMods/ATM-8#398]
Hi I am new to this modding scene, and I can't seem to find a easy way to get plugins onto the server file provided. Any assistance is appreciated.

**Comment by TheHentaiSama** [comment]
I second this. 
Since the public server uses plugins I was wondering how to do so on a private one. SpongeForge looks promising but it only works for up to version 1.16.

**Comment by enigmaquip** [comment]
We use no plugins on our servers, they're standard forge installations
