### ISSUE TITLE
No Flowers with Bonemeal

### ISSUE THREAD

**Issue by Cratios** [AllTheMods/ATM-8#40]
Version 0.0.10

If you bonemeal Gras there are no flowers anymore. Only Flax from SilentGear

**Comment by Cratios** [comment]
Version 0.0.15 same issue

**Comment by CoreyWarren** [comment]
Same issue today with ATM 8

**Comment by CoreyWarren** [comment]
Additionally, flowers cannot be bone-mealed by right clicking. Are flowers meant to be a non-renewable resource?

**Comment by Mitchell5200** [comment]
Silent Gear issue https://github.com/SilentChaos512/Silent-Gear/issues/540

**Comment by SilentChaos512** [comment]
Fixed in Silent Gear 3.2.3

**Comment by Mitchell5200** [comment]
> Fixed in Silent Gear 3.2.3

Ohh excellent to hear, we have a pack update planned in a day or so, so perfect timing, Thank you.

**Comment by Mitchell5200** [comment]
Fixed in 1.0.10
