### ISSUE TITLE
when I run the .bat I have this displayed

### ISSUE THREAD

**Issue by Ahrox57** [AllTheMods/ATM-8#400]
**unable to find or load main class @user_jvm_args.txt**

I followed the INSTRUCTION READ ME.TXT to install the modpack on a personal server with some friends but I don't understand why it doesn't work

can someone help me i am at step 4 where we are supposed to start the run.bat ?
![Capture](https://user-images.githubusercontent.com/120049027/206259515-7c1533d3-5fe2-4337-822e-b1e616ff86f2.PNG)

**Comment by autumnfire** [comment]
Double check you have Java 17 installed and remove older versions if necessary. I had this on a server where I forgot that Java 8 was installed.
