### ISSUE TITLE
Mekanism Chemical Injector chamber making wrong dust

### ISSUE THREAD

**Issue by cstalker** [AllTheMods/ATM-8#404]
MA makes sulfur dust (mekanism) Yet the sulfur dust made by the Chemical Injection Chamber, From Mekanism no less, makes thermal series Sulfer Dust

https://gyazo.com/9c55cc3f388037497321e866c16aeb20

**Comment by BastionNtB** [comment]
Additionally, the sulfur from Mystical Agriculture makes Mekanism sulfur, and is not interchangeable with Thermal Series sulfur.

My suggestion is to make both sulfurs completely interchangeable.
