### ISSUE TITLE
Refined Storage quests reward silicon from Refined Storage and not AE2.

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-8#405]
As of ATM8 1.0.5, various quests from the Refined Storage questline reward Refined Storage silicon instead of the expected AE2 silicon.
This is inconsistent with other parts of the modpack, where all recipes that use or output Refined Storage silicon have that ingredient/output replaced with the equivalent AE2 silicon as part of the unification process.

Caused by: https://github.com/AllTheMods/ATM-8/blob/e172171b7eeea43dfa1ceed897896b7701c016a8/config/ftbquests/quests/reward_tables/refined_storage_base_materials.snbt#L7

To fix, replace the above line with:
```
 { item: "ae2:silicon", count: 5 }
```

**Comment by Mitchell5200** [comment]
Fixed in 1.0.7
