### ISSUE TITLE
Infinity weapons of "Industrial foregoing: tools" reset when used gems of "Apotheosis"

### ISSUE THREAD

**Issue by Rafamzo** [AllTheMods/ATM-8#407]
When the infinity weapon is used on the forge table to socket the gem, the infinity weapon reset.

![Infinity Hammer](https://user-images.githubusercontent.com/16180666/206781518-a270771f-531f-49ab-b2b3-025fcbdd8d57.png)
![Expected Result](https://user-images.githubusercontent.com/16180666/206781525-00e4a28b-0adc-4b5d-b548-30b06301e4c3.png)
![infinity hammer has been reset](https://user-images.githubusercontent.com/16180666/206781538-a957a201-d6f4-4f22-9261-85e48ee208db.png)
![Infinity Loucher](https://user-images.githubusercontent.com/16180666/206781711-fa4de278-b9af-4f6e-86c7-12ba72d5d6ef.png)
![Infinity Loucher reset](https://user-images.githubusercontent.com/16180666/206781722-588e8f0b-67fb-4f7b-843e-0e22149618c1.png)

**Comment by James103** [comment]
See also https://github.com/Shadows-of-Fire/Apotheosis/issues/733

**Comment by Mitchell5200** [comment]
Closing as neither devs can really do much for this one
