### ISSUE TITLE
1.0.5 - Fluid Pipez on Ad Astra Cryofuel genertor cause crash

### ISSUE THREAD

**Issue by niconicodrake** [AllTheMods/ATM-8#408]
`Details:
	Name: pipez:fluid_pipe // de.maxhenkel.pipez.blocks.tileentity.FluidPipeTileEntity
	Block: Block{pipez:fluid_pipe}[down=false,east=true,has_data=true,north=false,south=false,up=false,waterlogged=false,west=true]
	Block location: World: (-1852,87,-433), Section: (at 4,7,15 in -116,5,-28; chunk contains blocks -1856,-64,-448 to -1841,319,-433), Region: (-4,-1; contains chunks -128,-32 to -97,-1, blocks -2048,-64,-512 to -1537,319,-1)
	Block: Block{pipez:fluid_pipe}[down=false,east=true,has_data=true,north=false,south=false,up=false,waterlogged=false,west=true]
	Block location: World: (-1852,87,-433), Section: (at 4,7,15 in -116,5,-28; chunk contains blocks -1856,-64,-448 to -1841,319,-433), Region: (-4,-1; contains chunks -128,-32 to -97,-1, blocks -2048,-64,-512 to -1537,319,-1)`

Case:

After setting a fluid pipe to Ad Astra Cryofuel generator (where you can generate cryofuel)
the server crashed and is unable to start again.

Just also aquestion here:

Is it possible to mitigate somehow to delete a specific block in an mca file? because the coordinates are clear but I dont know which file it is.

**Comment by enigmaquip** [comment]
you can try enabling forge's setting to kill ticking blocks. In `<world>/serverconfig/forge-server.toml` you'll see `removeErroringBlockEntities`

with NBTExplorer you can edit the block out. Based on your error (you're looking for region) you'll want to open `<world>/region/r.-4.-1.mca` there will be a bunch of Chunk folders. You're looking for `Chunk [4,15]`. Should then see a `block_entities` entry that you can delete

**Comment by niconicodrake** [comment]
Thank you I will try it out maybe it will help
