### ISSUE TITLE
Options not saving between instances

### ISSUE THREAD

**Issue by ninjabunny66** [AllTheMods/ATM-8#42]
When opening a new instance in version 0.0.11 all video settings revert to default.
Manually editing the Options.txt file has no effect - a new window will still have default settings.

**Comment by Cratios** [comment]
Same here

**Comment by RealNenzar** [comment]
Same .. Current solution for me set options.txt to read-only

**Comment by Zarkazm** [comment]
Same here.  Using GDLauncher, if that makes a difference.
