### ISSUE TITLE
 [FULL][1.0.6] Blocks (Conrete, Stone, Obsidian, etc) have "No Tool" available. 

### ISSUE THREAD

**Issue by mcphe103** [AllTheMods/ATM-8#421]
After updating, we learned there are blocks that have no tool available when they should.  It's made breaking blocks such as stone, concrete, and obsidian, extremely difficult with a diamond pickaxe.

**Comment by Mitchell5200** [comment]
Yep, a new update is being released now. give curse 10-20 to approve the update, then you can update to 1.0.6b and the problem will be fixed

**Comment by Mitchell5200** [comment]
Update Released, Closing
