### ISSUE TITLE
Same issue as #421 with v1.0.6b

### ISSUE THREAD

**Issue by KazukiUchiha** [AllTheMods/ATM-8#424]
resources as stone, obsidian, ores etc. still say "no tool" and cant be mined with pickaxes.

**Comment by KazukiUchiha** [comment]
Found out my server (hosted at Dawn-Servers) runs version 1.0.6 and i cant update manually. Will 1.0.6b release for servers soon?

**Comment by Jonz00r** [comment]
That's entirely up to your host.

**Comment by James103** [comment]
At the very least, if you can't update your modpack fully, at least try to update Integrated Dynamics to 1.14.3.

**Comment by KazukiUchiha** [comment]
> At the very least, if you can't update your modpack fully, at least try to update Integrated Dynamics to 1.14.3.

Newest version I can get is 1.14.2 (ran into version issues while connecting, 1.14.1 was installed but 1.14.2 was the newest I updated manually)
