### ISSUE TITLE
idk the problem but it crashes every time i try to open the game(1.0.6b)

### ISSUE THREAD

**Issue by jojizu** [AllTheMods/ATM-8#426]
it hapens to every version 
i install the modpack in curseforge i press play and then it crashes(in mc launcher)
plz i rly wana play this modpack with my firends but the modpacks work for them nad it makes me sad
anyway heres the log(https://mclo.gs/7Z0QziT)
pls help me

**Comment by P0kys** [comment]
Someone had a similar issue a few days ago - check whether your GPU and CPU drivers are up to date and that you are using Java 17

**Comment by firestorm0825** [comment]
does it have to be 17 i have 19 and it still wont work the only other thing i can think of is forge itself having java problems with the pack?

**Comment by P0kys** [comment]
Java 19 is fairly new, not everything is necessarily working with it. I think 17 is verified to work for almost everyone. Try it, check your drivers. If that doesn't work, try repairing the profile in Curseforge (three dots next to the play button) and if that doesn't work, delete the pack and install fresh

**Comment by firestorm0825** [comment]
well i have good news to it i changed nothing no updates no repairs or anything and now all the sudden it works fine
