### ISSUE TITLE
[FULL][0.11] Mystical Agriculture seeds not working in Immersive Engineering Garden Cloche

### ISSUE THREAD

**Issue by TheGreyRaven** [AllTheMods/ATM-8#43]
The seeds from Mystical Agriculture does not work with Immersive Engineering's Garden Cloche.
There is a datapack that fixes the issue: https://www.curseforge.com/minecraft/customization/garden-cloche-mystical-agriculture
Maybe it could be added into the pack somehow?

**Comment by Mitchell5200** [comment]
Confirmed working in v 0.1.10, Closing
