### ISSUE TITLE
ancient bee + wither bee + simulator upgrade + babee upgrades != allthemodium baby bee

### ISSUE THREAD

**Issue by Quezler** [AllTheMods/ATM-8#431]
I do not understand why this setup only seems to make baby ancient bees, and not baby allthemodium bees:

![2022-12-14_19 08 49](https://user-images.githubusercontent.com/3179271/207673492-3ae07829-bb74-4d62-97bb-251ddd4e7d9d.png)
![2022-12-14_19 08 51](https://user-images.githubusercontent.com/3179271/207673506-4ec34389-95ae-43ba-95ab-165dc1ab3049.png)
![2022-12-14_19 09 00](https://user-images.githubusercontent.com/3179271/207673512-4f04b5a1-13a7-4e82-9746-b70d56447bde.png)
![2022-12-14_19 09 47](https://user-images.githubusercontent.com/3179271/207673516-3b1286b7-acb9-4235-a3cc-10cf45c1d4b5.png)

**Comment by alfredggttv** [comment]
To get an Allthemodium bee, you must breed them together in the world, or with a Breeding Chamber. Withered and ATM bees cannot breed within themselves, nor can they produce a baby bee using the BaBee upgrade. 

For clarity, if a bee says "This species of bees can't breed amongst themselves", that typically means that they can't use the BaBee upgrade or breed for more. Hope this helps!

**Comment by Quezler** [comment]
> For clarity, if a bee says "This species of bees can't breed amongst themselves", that typically means that they can't use the BaBee upgrade or breed for more. Hope this helps!

says nothing about crossbreeding with other bees tho

> To get an Allthemodium bee, you must breed them together in the world, or with a Breeding Chamber. Withered and ATM bees cannot breed within themselves, nor can they produce a baby bee using the BaBee upgrade.

it did end up pooping out some atm bees without breeding items, but the chance was so low that it only appeared to output ancient bees 😅
