### ISSUE TITLE
1.0.6b crashes on start-up

### ISSUE THREAD

**Issue by xPe7ey** [AllTheMods/ATM-8#432]
Hi everyone my game keeps crashing on start today, i've been playing for the past few days just fine but today i can't get it to open

logs: https://mclo.gs/yu4Ap2D

**Comment by xalixilax** [comment]
I've got pretty much the same issue at launch for the first launch. The second one seems to work fine.

[crash-2022-12-15_19.14.22-client.txt](https://github.com/AllTheMods/ATM-8/files/10241636/crash-2022-12-15_19.14.22-client.txt)

**Comment by Mitchell5200** [comment]
> I've got pretty much the same issue at launch for the first launch. The second one seems to work fine.
> 
> [crash-2022-12-15_19.14.22-client.txt](https://github.com/AllTheMods/ATM-8/files/10241636/crash-2022-12-15_19.14.22-client.txt)

@xalixilax  that issue is different to the poster's issue, yours is a random thermal issue that they are aware of and are working on



> Hi everyone my game keeps crashing on start today, i've been playing for the past few days just fine but today i can't get it to open
> 
> logs: https://mclo.gs/yu4Ap2D

@xPe7ey, if you're still having issues with this, try deleting the config `comforts-server.toml` from your configs and restarting your game

**Comment by xalixilax** [comment]
I have gotten this issue only once and I played
6-7 times at this point. Without having to do anything.
