### ISSUE TITLE
World Not Loading In 

### ISSUE THREAD

**Issue by ChivalKnight** [AllTheMods/ATM-8#433]
After I successfully loaded into the world the first time, it threw in error at me the next. I tried again, and successfully loaded in. I crashed after misclicking in the quest book, and when I tried to load back in, it threw another error at me. I tried again, and it worked. Now, the next day, I can't join the world, no matter how many times I try. 
     The error I get is Internal Exception: java.lang.NullPointerException: Cannot invoke “net.minecraft.client.multiplayer.ClientPackListener.m_6198_()” because the return value of “net.minecraft.client.Minecraft.m_91403_()” is null. 
     This error does not crash me, and when I click out of it I am booted to the "Play Multiplayer" screen.

**Comment by Mitchell5200** [comment]
> “net.minecraft.client.multiplayer.ClientPackListener.m_6198_()” because the return value of “net.minecraft.client.Minecraft.m_91403_()

that error is a silent gear issue that should be fixed in pack version 1.0.6b, update.
If that issue still persists after, i'll need your latest log via https://mclo.gs/

**Comment by ChivalKnight** [comment]
So, I updated to version 1.0.6b, and have successfully managed to log in to my world. However, now whenever I load into the world I crash after a few seconds.

**Comment by ChivalKnight** [comment]
https://mclo.gs/0ThGYDk

**Comment by Mitchell5200** [comment]
> https://mclo.gs/0ThGYDk

Great... the Evilcraft blood stain crash, again... please forward that one to the evilcraft dev then, so they can finally fix that
