### ISSUE TITLE
Mekanism Anchor Upgrade doesn't keep chunk loaded on server

### ISSUE THREAD

**Issue by gvillwrstlr** [AllTheMods/ATM-8#434]
Recently built a digital miner about 10 chunks away from my base, but it stops working when i'm home and my generators stop working when I'm at the miner even though both quantum entangleporters have the mekanism anchor upgrade loaded. No server error messages, when I visit either chunk directly the respective machines work again but the other will stop.

**Comment by Mitchell5200** [comment]
The anchor upgrade was turned off in the configs, that shouldve also removed the recipe, you can use FTB chunks to force load chunks instead

**Comment by gvillwrstlr** [comment]
> The anchor upgrade was turned off in the configs, that shouldve also removed the recipe, you can use FTB chunks to force load chunks instead

Thank you!
