### ISSUE TITLE
Thermal Series <-> Server and Client Sync Issue

### ISSUE THREAD

**Issue by morgan2233** [AllTheMods/ATM-8#438]
Hi,

I am trying to play 1.0.6b. I have a client and a server setup, however, when i try to connect I get the following error saying the versions do not match but visibly they do.

Tried re-install, doesnt work :(

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/17581221/208179579-7f4bb706-6eb5-4527-a6e3-52d22d96040c.png">

**Comment by Mitchell5200** [comment]
that error is usually fixed by a client restart, i think the thermal team are aware and are working on a fix

**Comment by skybix** [comment]
I got this too.

**Comment by Mitchell5200** [comment]
COFH core updated in 1.0.7, closing unless the issue persists
