### ISSUE TITLE
upgrade from 0.0.8 to 0.0.11

### ISSUE THREAD

**Issue by LiveSide** [AllTheMods/ATM-8#44]
Hallo ATMTeam,

ich habe das Modpack in der v0.0.8 angefangen (root server) und wollte jetzt auf die v0.0.11 upgraden.

leider habe ich jetzt das Problem, dass erst der Server nicht startet mit der alten Map, (welche ich gerne behalten würde)
und wenn ich dann versuche zu verbinden, stimmen die Mods local nicht überein.

Sobald ich die Mods local anpasse, startet das spiel nicht mehr.

Wie kann ich das Problem beheben und welche daten / logs braucht ihr, um das nachzuvollziehen?
Grüße Live

**Comment by LiveSide** [comment]
?

**Comment by Mitchell5200** [comment]
latest.log and any crashlogs please
https://mclo.gs/

**Comment by LiveSide** [comment]
https://mclo.gs/Sj9IINQ

this is the client log
its now the version 0.0.14 with the server install file and the curseforge version

**Comment by Mitchell5200** [comment]
can i have the server logs too please

**Comment by LiveSide** [comment]
https://mclo.gs/D6lF79W =latest.log
https://mclo.gs/dKXwR6G = Debug.log

**Comment by Mitchell5200** [comment]
Comparing both of these logs, it looks like the client is running a updated version of many of the mods, ensure you're using the same server pack version as the server

**Comment by LiveSide** [comment]
yes its the same server pack 
curseforge 
downloaded server files 
https://mediafiles.forgecdn.net/files/4009/156/Server-Files-0.0.14.zip

**Comment by LiveSide** [comment]
but if i copy the mods from the client mod to the server mod ordner the server dont start
if i deleat some mods, that not in the server version, the client dont start

**Comment by LiveSide** [comment]
ok is running now with a new map... i guess the server have a problem with the map

**Comment by LiveSide** [comment]
Thank you for your help mitchell :D
