### ISSUE TITLE
Game crashing after 5-10 minutes after loading world

### ISSUE THREAD

**Issue by VioletFijurii** [AllTheMods/ATM-8#441]
When I first started playing on my world, it got notably more laggy when breaking/placing blocks or opening inventories. First crash happened when I opened a loot chest from Roguelike dungeons after around 4-6 hours of playing. I lowered RAM from 6 gigs (exactly half of my RAM) to 5, opened it, and ran perfectly fine for the remaining time I was on.

I opened it the next day, and experienced 4 consecutive crashes after 5-10 minutes of being on the same world. I gave up and waited until the next day and pondered how to fix it. Today I have tried adjusting the RAM from 5 to 5 1/2 gigs, then up to 6 again, and then AGAIN up to 7, only to experience the same crashes after 5-10ish minutes.

In the time that I have been playing on this world, I have travelled to one of those forests added by Ars Nouveau. It was only after I had travelled to this area that I had every single crash occur. I'm not sure how to attach the crash log, but I will try to add it.

I have not had any issues with this pack before now, and it runs beautifully on my mediocre pc. I hope this issue can be fixed soon.

https://mclo.gs/1XtJEVU

**Comment by NoMoreStars** [comment]
I had a [similar crash](https://pastebin.com/c8aBSCRM) the other night, looks like it might be related? Game was running fine for me other than the issues JEI is having currently interacting with storage network interfaces and crafting recipes. Was simply trying to get a basic mob grinder setup with mob grinding utils when the crash occurred on my end.
