### ISSUE TITLE
Villager zombification

### ISSUE THREAD

**Issue by chimebox** [AllTheMods/ATM-8#442]
When trying to zombify villagers, the zombies just kill the villagers and not convert them into zombie villagers. I am playing on a dedicated server and I've tested it on single player and the zombification works as expected.

Version: 1.0.6b

**Comment by VioletFijurii** [comment]
Is the server set to hard mode? Villagers only have a 100% chance of getting infected on hard mode

**Comment by chimebox** [comment]
Oh yeah. Forgot that that was a thing since I always play single player and in hard difficulty. Didn't think of that since this is my first time setting up a dedicated server. Thanks for the advice. Closing the issue.
