### ISSUE TITLE
connection lost while trying to play on LAN with family

### ISSUE THREAD

**Issue by jokerjosh1** [AllTheMods/ATM-8#444]
every time me or my wife try to join one anothers world it gives us the same connection lost, Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException. Please help!!!!

**Comment by P0kys** [comment]
As pinned at the top of the issues page, LAN is currently not working for ATM 8. You need to run a server to play MP

**Comment by Mitchell5200** [comment]
Duplicate of #23 , Closing
