### ISSUE TITLE
Crash related to quests

### ISSUE THREAD

**Issue by CasterMx13** [AllTheMods/ATM-8#445]
When viewing quests the game crashes. Has happened to me about a dozen times over the last few hours.

"The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Style.m_131182_()" because "style" is null"

[crash-2022-12-17_17.17.21-client.txt](https://github.com/AllTheMods/ATM-8/files/10252901/crash-2022-12-17_17.17.21-client.txt)

**Comment by SatanPrime1** [comment]
Same here, please tell if someone has a solution

**Comment by Mitchell5200** [comment]
FTB quests is updated in 1.0.7 (like 10-20 mins soon), hopefully that fixes this one

**Comment by alfredggttv** [comment]
This appears to be fixed in the latest version.

https://github.com/FTBTeam/FTB-Quests/commit/33a4c9d936fc0be1a3498556d8b0148355086ec2
