### ISSUE TITLE
Quest reward for ars nouveau aquatic glyph, but no such item exists

### ISSUE THREAD

**Issue by spicyusername** [AllTheMods/ATM-8#446]
i collected my quest rewards from the ars nouveau tab and it gave me an FTB Quests missing item with the name ars_nouveau:glyph_aquatic, i searched through the existing glyphs and found none with the id of ars_nouveau:glyph_aquatic, see image for item
![image](https://user-images.githubusercontent.com/120858014/208271298-36511f39-07b6-4f55-9953-ac600fc22420.png)

**Comment by Mitchell5200** [comment]
Fixed in 1.0.7
