### ISSUE TITLE
1.06b Unpossible to uncraft Steel Block x1 (ATO)

### ISSUE THREAD

**Issue by bemerged** [AllTheMods/ATM-8#449]
There is a recipe mismatch currently.

Steel Block x1 (ATO) -> Steel Block (ATO) -> END

Whereas steel ingots (ATO) can be converted to any steel block. This is especially stupid, because there exists a recipe for Infusion (Mekanism) which converts one Iron Block x1 (ATO) to one Steel Block x1 (ATO).

Guess who no got 1k Steel Block x1 and can't uncraft them :P

**Comment by Mitchell5200** [comment]
i guess a temporary measure would be to use a compacting drawer to uncompress the blocks, we'll look into it further
