### ISSUE TITLE
Exit Code Error 1 when game boots.

### ISSUE THREAD

**Issue by flyinggoatman** [AllTheMods/ATM-8#45]
I'm running Minecraft 1.19.2, I am installing the mod pack through Curse Forge.

Here is my log. 

https://pastebin.com/KxefQw5G

I have fixed the issue by manually installing CreativeCore. The mod pack didn't install this by default and had to be added by hand. Is this a bug?

**Comment by flyinggoatman** [comment]
Bug: **Missing dependency CreativeCore**

**Comment by Mitchell5200** [comment]
User Error, ambient sounds and environment are not part of the pack, Closing
