### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by voislav1** [AllTheMods/ATM-8#450]
I am very interested in the All the Mods 8 Modpack but for some reason it is the only one that is not starting.
When i try to open the created world the entire game crashes.

Attached is the latest crash report. I saw that it has something related to the render but not sure what?
[crash-2022-12-18_20.19.44-client.txt](https://github.com/AllTheMods/ATM-8/files/10254398/crash-2022-12-18_20.19.44-client.txt)

I've been trying to fix this for 4-5 hours already but can't seem to find a solution.
I saw that in some cases the java was the problem so i reinstalled it with Java 17.
There was also a driver issue in some cases and updated all of the drivers, but still the same thing.

Thank you all.

**Comment by Mitchell5200** [comment]
For some reason your forge version is wrong, by default the set forge version is 43.1.55, change back to that and things should work.

**Comment by voislav1** [comment]
Hello Mitchell, 
Thank you for the assistance provided, indeed there was an issue with the forge version, i have downloaded the 43.1.55 and tried to start the world and indeed it loaded, in addition to that i had removed quite a lot of data packs as it seemed that they were not supported. Anyway thank you again for the help. Have a great day and wonderful holidays :) 
Also i guess we can close this issue.
