### ISSUE TITLE
1.06b SIGSEGV error during world gen

### ISSUE THREAD

**Issue by imposiblaa** [AllTheMods/ATM-8#453]
This error occurs in both the client and the server versions of ATM8 while generating a new world. I run on Arch linux and have installed the modpack client to MultiMC using a command line tool and installed the server version in many different ways including the method described in the instructions text file. On the client I can launch into a navigable title screen but it crashes when I try to create a new world. 

Both the client and server exit with the following error:

```
[WARN] Install JVM debug symbols to improve profile accuracy
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007faaa7e62aed, pid=2224, tid=2671
#
# JRE version: OpenJDK Runtime Environment (19.0.1+10) (build 19.0.1+10)
# Java VM: OpenJDK 64-Bit Server VM (19.0.1+10, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xe62aed]  JVM_handle_linux_signal+0x14d
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/colinn/.local/share/multimc/instances/ATM8/.minecraft/core.2224)
#
# An error report file with more information is saved as:
# /home/colinn/.local/share/multimc/instances/ATM8/.minecraft/hs_err_pid2224.log
[thread 2672 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

This error occurs on java 17, 18, and 19 and does not occur in ATM7

**The full log can be found [here](https://gist.github.com/imposiblaa/03ca87f49cdfb3c6e9ceae228dcaa3a8)**

**Comment by ToastedWookiee** [comment]
I have this issue on 2 systems running Arch Linux, endeavourOS, looks to be an issue with Spark, both crash, client or my server system when Spark starts its "Background profiling", removing the Spark mod causes both systems to run fine.

**Comment by imposiblaa** [comment]
> looks to be an issue with Spark,

Ok, thank you! I suppose I should close this here.
