### ISSUE TITLE
Game crash on clicking play

### ISSUE THREAD

**Issue by Ar-sel** [AllTheMods/ATM-8#456]
I click play, and the game looks like itll start, but closes instantly without ever opening or making an output log
![image](https://user-images.githubusercontent.com/121017991/208392489-6c9805fc-a38a-4437-8872-bc3c6bf7a2f3.png)

**Comment by Mitchell5200** [comment]
Check your instance folder for the logs folder, and then paste the file `Latest.log` into https://mclo.gs/ and share the URL back here.
If there is no log i'll need more information, did you add any additional mods to the pack?, what's your RAM allocation?, did you add any additional java args?, What's the forge version that the launcher is listing?

**Comment by TjerkFaaij** [comment]
I have the same issue

https://mclo.gs/0cBlaGN

**Comment by TjerkFaaij** [comment]
[latest.log](https://github.com/AllTheMods/ATM-8/files/10261514/latest.log)

**Comment by TjerkFaaij** [comment]
I had to update my drivers
