### ISSUE TITLE
Super Wireless Grid - Appears to be no way to keybind.

### ISSUE THREAD

**Issue by aidey124** [AllTheMods/ATM-8#460]
Hi,
I have a Refined Storage System and have upgraded the 'Wireless Grid' to the 'Super Wireless Grid' (From RebornStorage). However, there appears to be no keybind functionality (to my limited knowledge). If such a thing does not exist, please could this be added as this would allow for the 'Super Wireless Grid' to be used from the Curio Slot and have the same functionality as the original.
I appreciate any help/guidance on this topic
Thanks,
A happy Player.

P.S. Keep up the great work, I have been enjoying 'All The Mods 8' with a bunch of friends on a server and this is a great way to spend the holiday season ;D

Additional Information:

Version of modpack = 1.0.6 B

![Screenshot_1](https://user-images.githubusercontent.com/121037786/208443607-53a3451e-7bbf-47a8-b5b0-3c893a42a97c.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/121037786/208443609-8f897d2d-406e-4f3e-8b53-e8cda8953465.jpg)

**Comment by Calvin-McG** [comment]
I have noticed this same issue and have subscribed to notifications. I have noticed that the "Ctrl + G" bind changes the mode, but searching that bind in the bindings screen reveals nothing.

**Comment by rpop0** [comment]
Seems like the mod has a registered keybind for CTRL+G, but I think it may be conflicting with the Mode switch, which it seems like they also made it CTRL+G

https://github.com/TechReborn/RebornStorage/blob/92693ce1c6c34743b13291f8ce35569ded551700/src/main/java/net/gigabit101/rebornstorage/client/KeyBindings.java

**Comment by Zank82** [comment]
I'm seeing this as well, Can't find in the configs either.
 Also if you change your keybinds in-game for any other bind ctrl-G stops working for the open wireless grid, you can only change mode.
