### ISSUE TITLE
"Sorry, we cant load this project. Missing dependency: 4167046, Project ID 351264"

### ISSUE THREAD

**Issue by finalfrog** [AllTheMods/ATM-8#465]
Get this error trying to install the mod pack with Curseforge:

"Sorry, we cant load this project. Missing dependency: 4167046, Project ID 351264"

![Overwolf_WQilIqjdKB](https://user-images.githubusercontent.com/1310434/208483194-92fb89c9-8247-4fd7-b208-505321c2384d.png)

I saw there was a [similar report](https://github.com/AllTheMods/All-the-mods-7-Sky/issues/244) for ATM 7 Sky a couple months ago where a file needed poking on the backend. Similar issue here?

Edit: It's working now!

**Comment by Mitchell5200** [comment]
yeah CurseForge was briefly down about 20-30 mins ago, it's back up now, so please try again

**Comment by thepure12** [comment]
Can confirm, still happening.

**Comment by Mitchell5200** [comment]
same project ID? or a different one?

**Comment by thepure12** [comment]
Project ID: 241319

**Comment by thepure12** [comment]
Issue seems to have been resolved.
