### ISSUE TITLE
Mystical Agriculture + Rubber issue

### ISSUE THREAD

**Issue by BastionNtB** [AllTheMods/ATM-8#468]
I'm wanting to make rubber for the Thermal Series machines

There is a rubber seed, but it seems to be broken.
![image](https://user-images.githubusercontent.com/15705306/208537263-30e85d3f-a26a-4f1e-bc20-5b048ad38ae0.png)

Is there a way to fix this? Seems forge needs some rubber definitions. There are currently 3 different types of rubber, ftbic:rubber, then industrialforegoing:dryrubber then lastly thermal:rubber

Either different mystical ag recipes added via kubejs or I dunno. But as it stands you can't make rubber from MA.

**Comment by shrad1994** [comment]
![image](https://user-images.githubusercontent.com/96917010/208836325-39e627f9-8367-4015-8c64-32fdd7ec45db.png)
It would appear that tiny dry rubber is tagged as a glass pane? I confirmed it doesn't work in recipes requiring any "forge:glass_panes" so many i'm just misunderstanding

**Comment by JustAnotherGhostName** [comment]
Could we get this fixed?

**Comment by BastionNtB** [comment]
Still an issue in 1.0.8, just fyi

**Comment by Mitchell5200** [comment]
Duplicate of #278, Closing
