### ISSUE TITLE
Mystical Ag Awakened Supremium dosent work

### ISSUE THREAD

**Issue by PoshNokk** [AllTheMods/ATM-8#47]
I got the mats for it and redstone dosent activate it ive moved the altars filled em to max instead of the recipe it has the pop up to make it but redstone just dosent make it work.

**Comment by RealNenzar** [comment]
The reciepe is wrong u need cognizant dust on the pedestrals -> https://github.com/BlakeBr0/MysticalAgriculture/issues/541#issuecomment-1257099577
