### ISSUE TITLE
Error trying to open a server with the MODPACK

### ISSUE THREAD

**Issue by XENIP** [AllTheMods/ATM-8#471]
I'm trying to open a server and i keep receiving the same error

FramedBlocks BlockEntity Warning: Not applicable[23:50:05] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        KubeJS (kubejs) encountered an error during the complete event phase
§7java.lang.RuntimeException: There were KubeJS startup script syntax errors! See logs/kubejs/startup.txt for more info
]

https://prnt.sc/n9fRvvLlpkOh
![Screenshot_9](https://user-images.githubusercontent.com/36553615/208571465-3e47d7e6-a5e0-48bf-8ba4-1ac34b0d50d1.png)

**Comment by Mitchell5200** [comment]
Full crash log and Latest Log using https://mclo.gs/ please

**Comment by XENIP** [comment]
> Full crash log and Latest Log using https://mclo.gs/ please

https://mclo.gs/Q26j4Bp

**Comment by Mitchell5200** [comment]
whatever host you are using has a bad version of our pack, as it has scripts from 1.18 in it, please fresh install your entire KubeJS folder from the server pack we host on curseforge and report it to the host provider.
