### ISSUE TITLE
Botany pots with saplings stuck at 100%

### ISSUE THREAD

**Issue by P0kys** [AllTheMods/ATM-8#476]
Tried a bunch of saplings from Botania, Twilight, and Quark and only vanilla ones seem to work. Others will just stay stuck at 100%. Some of them will seemingly at random tick once (I think it's after loading the game) but will also get stuck on the second cycle

**Comment by Bimmbamm** [comment]
You'll need the Hopper Botany Pots with a chest or barrel under it.

**Comment by P0kys** [comment]
I have hopper pots with chests (double checked just now). Same exact setup as for vanilla saplings but moded just stop working after a while

**Comment by firestorm0825** [comment]
the only thing i could think of would be installing bonsai trees on top of the normal pack but i haven't figured out why it crashes when i put the mod in yet so? but the mod also only supports up to 1.18.2 so that may be the problem of not loading

**Comment by P0kys** [comment]
Solved with the latest Botany Pots update (I guess)
