### ISSUE TITLE
ATM 8 currently does not come with a backup mod preinstalled

### ISSUE THREAD

**Issue by Quezler** [AllTheMods/ATM-8#477]
Yes i am aware there is a backup mod suggested in the pinned issue, but in my opinion it justifies an issue of its own. 

A wither escaped from its confinement and caused havoc at the base's expansion that hadn't yet been ftb claimed:

![F2](https://cdn.discordapp.com/attachments/1051102716740513862/1054778552282796122/image.png)

It was a little scary to want to rollback and there to not be a backup folder, unlike basically all other major packs.

**Comment by Mitchell5200** [comment]
Simple backups is in the client pack, but not the server pack to avoid conflicts with hosts and their backup systems

**Comment by Quezler** [comment]
![thats-the-evilest-thing-i-can-imagine](https://i.kym-cdn.com/entries/icons/facebook/000/012/367/evilest.jpg)

**Comment by Mitchell5200** [comment]
simplebackups.jar.Disabled implemented in recent versions,
