### ISSUE TITLE
It cancels its intallation in its own

### ISSUE THREAD

**Issue by MantoAR** [AllTheMods/ATM-8#48]
When trying to install any version with curseforges launcher it cancels itself after patch 4 starts installing.
Video showing this issue happening:
https://youtu.be/0jlET55OcfE

**Comment by blueAnguiano** [comment]
Hi, have you resolved this problem? I'm facing the same problem as you and I tried everthing

**Comment by fadoartpokebr** [comment]
already know the problem?

**Comment by Mitchell5200** [comment]
CF install issue, top threedot menu, "Repair installation"
