### ISSUE TITLE
Server Crashing because of KubeJS

### ISSUE THREAD

**Issue by Shlorple** [AllTheMods/ATM-8#480]
Every time I go to launch my server on startup it says there is a scrip issue with KubeJS
[crash-2022-12-21_00.47.13-fml.txt](https://github.com/AllTheMods/ATM-8/files/10273611/crash-2022-12-21_00.47.13-fml.txt)
this is the crash report if anyone can help it would be greatly appreciated :)

**Comment by Mitchell5200** [comment]
Latest log too please. sounds similar to #471 though

**Comment by Shlorple** [comment]
> Latest log too please. sounds similar to #471 though

It was that exact same reason as to why they posted. thank you for enlightening me and happy holidays :)
