### ISSUE TITLE
Crash when trying to open the trash can

### ISSUE THREAD

**Issue by Dr69onS6mur6i** [AllTheMods/ATM-8#482]
When I try to open the trash can from the inventory, the one in the upper left corner near the quest book, the game hangs and crashes. Happened twice in a row. The game crashed then I logged back in and attempted it again, and it got hung up and crashed again.

[crash-2022-12-20_18.46.41-client.txt](https://github.com/AllTheMods/ATM-8/files/10274140/crash-2022-12-20_18.46.41-client.txt)
[crash-2022-12-20_18.26.56-client.txt](https://github.com/AllTheMods/ATM-8/files/10274141/crash-2022-12-20_18.26.56-client.txt)

**Comment by Mitchell5200** [comment]
I just tried to re-create this in SP, and am unable, but please report this to the mod devs for the FTB library and Journeymap
https://github.com/FTBTeam/FTB-Mods-Issues/issues
https://github.com/TeamJM/journeymap/issues
