### ISSUE TITLE
Showing Recipes creates lags

### ISSUE THREAD

**Issue by codesmith47** [AllTheMods/ATM-8#483]
When opening some recipes, it causes a very sudden and hefty lag on the client.
One of the items is the Prediction Matrix and the Nature's Compass, for example.

**Comment by shrad1994** [comment]
Refined storage had issues with jei which was causing many users intense framerate drops, they've since released an update to fix the issue on their end. This MAY be your issue as well.

**Comment by codesmith47** [comment]
Okay, I will try this later this day, thanks!

**Comment by shubham8550** [comment]
same thing happens with me most items which dont have many recipes (right click)
makes lag and sometimes game die
