### ISSUE TITLE
Apotheosis library of alexandria doesn't let you take tombstone soulbound enchant out by its self

### ISSUE THREAD

**Issue by shrad1994** [AllTheMods/ATM-8#484]
![image](https://user-images.githubusercontent.com/96917010/208835667-6769ae8d-eff7-43a2-90d3-e57e9e891615.png)

I am unable to take tombstone soulbound enchant out by its self, HOWEVER, 

![image](https://user-images.githubusercontent.com/96917010/208835734-8ccb1d7b-8f93-44fe-aaa7-f6be07922a2b.png)
I can take it out with another enchant

**Comment by Mitchell5200** [comment]
that's likely due to us disabling the tombstone soulbound enchant, in favor of the ensorcellation soulbound
