### ISSUE TITLE
Engineer's Decor "small tree cutter" only cuts bottom block on Myrtrees' Rubberwood Log

### ISSUE THREAD

**Issue by shrad1994** [AllTheMods/ATM-8#485]
![image](https://user-images.githubusercontent.com/96917010/208842337-b9ffb8e1-68b3-4b74-a2db-ac16cbc7333b.png)

**Comment by stfwi** [comment]
Hi guys, fix is in curse approval: `engineersdecor-1.19.2-forge-1.3.28` . Cheer's, wile
