### ISSUE TITLE
Silent Gear cycle 1.0.6b

### ISSUE THREAD

**Issue by brokenscrub** [AllTheMods/ATM-8#486]
Hello

When i go through silent gear stats of items, it skips a cycle.
Example when i wanna see tool rod stats of this item [Main Stat](https://prnt.sc/CEynNz2ALDTV), it skips over the tool rod and goes to [Tip Upgrade](https://prnt.sc/oR54dFI9BC4U)

It also happens in the Blueprint book, it skips 1 everytime

**Comment by KoloXD** [comment]
Can confirm, I'm having the same issue. Whenever I press any of the cycle buttons it seems to do so twice, meaning on an item that has only two uses I can only see one of them, most often it is the Main stats, but in case of uneven numbers it eventually cycles through all of them, like with 3 use materials or the blueprint book if I put an uneven amount of blueprints in it.

**Comment by brokenscrub** [comment]
This is still a problem in 1.0.7
