### ISSUE TITLE
Apotheosis: Shelf of Masterful Sight not craftable

### ISSUE THREAD

**Issue by Cyler1992** [AllTheMods/ATM-8#487]
Hi,

Recipe mentioned by JEI for "Shelf of Masterful Sight" is the following:
![image](https://user-images.githubusercontent.com/42421344/208897976-be4fedb4-241e-4684-a04a-460fca3dfaa5.png)
![image](https://user-images.githubusercontent.com/42421344/208898683-3f513b94-ed91-4fcd-992c-2402fdda024e.png)

Crafting in any crafting grid does not work:
![image](https://user-images.githubusercontent.com/42421344/208897937-f058655d-b2c8-46ef-b20a-46e4471c6387.png)
![image](https://user-images.githubusercontent.com/42421344/208898144-7240a35d-4d41-4f0a-9da6-b5602046aa11.png)

It seems like the potion of night vision is not being accepted for the recipe. The rest is working.

Modpack version is 1.0.6b.

Greetings
Cyler

**Comment by James103** [comment]
The Night Vision potions used must have their duration extended to 8 minutes (with Redstone) when crafting the Shelf of Masterful Sight.

To brew the required Night Vision potions in a Brewing Stand:
1. Place 3 water bottles in the stand.
2. Fuel the stand with blaze powder.
3. Add Nether Wart, then wait for the brew to finish.
4. Add a Golden Carrot, then wait for the brew to finish.
5. **Add Redstone**, then wait for the brew to finish.
6. You should have the required potions.
