### ISSUE TITLE
Naga Drop Bugged

### ISSUE THREAD

**Issue by EdwardTheMememan** [AllTheMods/ATM-8#49]
I've killed three Nagas yet they have only dropped Shader Grabbags and nothing else. [0.0.12]

**Comment by Zarkazm** [comment]
The Twilight Forest boss drops are now in a chest that appears after you kill them.  Go back to where the Naga spawner would have been before and see if there's a chest there with the loot.

**Comment by EdwardTheMememan** [comment]
Thanks figured it out in creative, just didnt notice the chests.

**Comment by Zarkazm** [comment]
Word.  I thought the same thing first time.
