### ISSUE TITLE
"Sorry, we cant load this project. Missing dependenct: 4005376. Project ID :241319

### ISSUE THREAD

**Issue by miliezz** [AllTheMods/ATM-8#493]
![error in atm8](https://user-images.githubusercontent.com/121207207/209036894-3933ba70-30bc-4132-a577-7a3f0839e665.PNG)

**Comment by SirBenny024** [comment]
I am having the same issue. The pack wouldn't load so I tried redownloading it but now it won't even download. I really hope I didn't lose my world I was playing on.

**Comment by TanshiWasTaken** [comment]
Same issue. No more information that I have worth sharing.
