### ISSUE TITLE
Crash on startup Exit Code:1 (1.0.6b/Forge 43.1.55)

### ISSUE THREAD

**Issue by Drachenreiter12** [AllTheMods/ATM-8#494]
Hello, i too have the problem, that ATM 8 crashes on startup with Exit Code:1 
Version 1.0.6b
Forge 43.1.55)
12 GB RAM allocated

Log: https://mclo.gs/KwDPb1d (also saved the other Logs if needed)

**Comment by Wolfernand** [comment]
I am also having issues starting this latest version

**Comment by Wolfernand** [comment]
> I am also having issues starting this latest version

Tried restarting the server again and it is working now

**Comment by Drachenreiter12** [comment]
Thats not my problem, my game doesn`t even launch.

**Comment by P0kys** [comment]
Make sure your CPU and GPU drivers are up to date. Saw a similar problem caused by an old CPU driver

**Comment by Drachenreiter12** [comment]
Nvidia drivers are up to date. I even reinstalled them before posting about this issue.

**Comment by Drachenreiter12** [comment]
Problem solved. For some reason my Pc decided it would be a great idea to launch ATM 8 on my iGPU.
