### ISSUE TITLE
Issue with locating Allthemodium Ore

### ISSUE THREAD

**Issue by leighmckenna** [AllTheMods/ATM-8#50]
Hey all:

Installed default/current version from the polymc launcher and everything works perfectly but I'm having trouble finding Allthemodium Ore in the pack. The JEI tooltip states it's found in the deep dark biome and I've searched multiple biomes for 2 hours or so before checking the in game manual it states the ore is found above 170y! What's the intended location and am I making a stupid mistake on this front? 

Thanks!
![image](https://user-images.githubusercontent.com/26859518/192444746-79e2d2f5-fb31-4d76-abd8-9c6b6779896f.png)

**Comment by IsaiahMM** [comment]
The book isn't updated, also you can find a ton of it in the mining dimension.

**Comment by HaylingZar** [comment]
The easiest way for me to find it (latest version required for PotionsMaster mod):

- Locate Deep Dark biome and plant waystone
- Collect 30-50 lollipops (corail tombstone mod)
- Locate cow and bucket
- Consume lollipops and purge effects with milk if they grant sight of any other ores, or any negative effects (e.g. third eye). 
- Repeat until you gain "allthemodium sight" effect (should last 10 mins)
- Use waystone to return to deepdark biome
- Mine around and you should find at least 1 ore in 10 minutes as you essentially get free X-ray. 
- Once one ore is found, you can produce teleporter for mining dimension and 3 potions of allthemodium sight. (make sure to fortune ore and then double raw ores)
- Go to mining dimension, drink potion, enjoy

**Comment by James103** [comment]
> * Collect 30-50 lollipops (corail tombstone mod)

That only works during Halloween and for the few days preceding it. At other times of the year (IRL), mobs do not drop lollipops and the player will need to either:

1. Kill the Warden to fill the bounty, then claim it to obtain an Allthemodium Ingot.
2. Somehow find some Allthemodium Ore in the Deep Dark without the effect, then mine it (with at least a Fortune III Netherite Pickaxe), use an Iron Ore Hammer to convert the raw ore 1:2 into dust, then smelt the dust to get ingots.

After obtaining an ingot, it should be possible to make the potions of Allthemodium Sight.
If possible, combine the potions into a charm (costs 6 blaze powder) to make them last a bit longer and allow turning on/off the effect as needed.
