### ISSUE TITLE
Ars Nouveau Magebloom seed quest, unable to get passed 33% 

### ISSUE THREAD

**Issue by Lyedar** [AllTheMods/ATM-8#500]
After creating my first Magebloom seed with the Enchanting Apparatus, no matter how many more I make with it I am not getting credit in the quest. You need to make 3 to move on in the quest, it says I have 1/3, but I've made nearly 5 seeds now with now quest progression.

**Comment by alfredggttv** [comment]
I recently updated the pack to test this bug out. Doesn't seem to give me this issue, as gathering 3 seeds completed my quest. Let me know if you still have issues!

**Comment by James103** [comment]
Make sure you have all of the required items in your inventory **at the same time** or else the quest won't complete.
In this specific case (for the magebloom seeds), make sure you craft three and have all three in your inventory at once.

**Comment by Lyedar** [comment]
> Make sure you have all of the required items in your inventory **at the same time** or else the quest won't complete. In this specific case (for the magebloom seeds), make sure you craft three and have all three in your inventory at once.

I think this was the issue. I at first decided just to make a new world and everything worked fine. So I thought the issue may have just been the world. But I don't think I ever held three at a time.
