### ISSUE TITLE
Botany Pots having issues with Menril Saplings

### ISSUE THREAD

**Issue by FoxDogist** [AllTheMods/ATM-8#503]
Either form of the Botany pot seems to get stuck at 100% with the menril sapling. I can harvest it manually if it isn't the hopper varient, but no matter what kind of inventory I attempt to use, the plant just freezes at max progress without producing anything.

**Comment by JonKashaia** [comment]
I have the same issue and i tried so many variants(different soils, different botany pots)
I cant get it to work
