### ISSUE TITLE
Functional Storage draws not accepting items

### ISSUE THREAD

**Issue by FoxDogist** [AllTheMods/ATM-8#506]
For some reason, items of the same type aren't being accepted into drawers. For example, spider eyes won't enter one of the 2x2 drawers I have attached to a storage controller. The controller itself is being fed items via an absorption hopper from Mob Grinding Utils

**Comment by Mitchell5200** [comment]
Did you link the drawers with the linking tool?

**Comment by lazygamerz** [comment]
I've noticed the same issue. Its quite a pain with mob farms. With my extremely limited knowledge it has something to do with NBT tags. For example: I have two pieces of iron and two pieces of netherrack to name a few with this issue. 

One has 1 NBT tag that says "apoth.equipment: 1b" and the other has no NBT tag. This is for both the netherrack and iron ingot.

**Comment by emuller42** [comment]
+1, ran into this same issue.  I'm also using Mob Grinding Utils, so I wonder if the Mob Masher is skipping whatever is in place to strip that tag from items that don't usually have NBT data when they get dropped from Apotheosis-modified mobs (ones with non-standard armor).

**Comment by ViRb3** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/744

**Comment by alcheya** [comment]
> +1, ran into this same issue. I'm also using Mob Grinding Utils, so I wonder if the Mob Masher is skipping whatever might be in place to strip that tag from items that don't usually have NBT data when they get dropped from Apotheosis-modified mobs (ones with non-standard armor).
> 
> @FoxDogist , I'm piping my items into a Sophisticated Storage chest, and my workaround is to use memory slots for all the bulk items I'm grabbing and turn on the setting to enforce NBT-matching for memory slots.
> 
> Update: It's the burning damage from the Mob Masher Upgrade Fire. Appears that mobs that burn to death don't have the Apotheosis tag stripped from their non-equipment drops. This doesn't seem to happen with mobs that burn to death from Fire Aspect enchantments or from environmental fire.

I don't have anything but sharpness and looting on my mobmasher, still does it.
