### ISSUE TITLE
Issue with sophisticated backpack's crafting upgrade

### ISSUE THREAD

**Issue by Elrik35** [AllTheMods/ATM-8#508]
When shift clicking items into/out of the backpack, items will sometimes go into/out of the crafting menu in the backpack, even when it is not open. Also, while dragging items in the upgrade's crafting menu, it will randomly close.

**Comment by mazunki** [comment]
Also happens on ATM7 to the sky

**Comment by bigsexyjoe** [comment]
This wasn't happening on 1.05 but is now happening on 1.07

**Comment by e-SonOfAnder** [comment]
Still happening in 1.0.8; have you tried updating the mod to a newer version to see if that fixes it?

**Comment by e-SonOfAnder** [comment]
Updated the following mods:
Sophisticated Backpacks to v3.18.40.779 (current as of me typing this)
Sophisticated Core to 0.5.38.203 (current as of me typing this)

So far things seem to be behaving much better.

**Comment by osirisgothra** [comment]
atm8 now it is not closing the backpack just crashing the whole game
