### ISSUE TITLE
Sophisticated Storage Advanced Compacting Upgrade Recipes

### ISSUE THREAD

**Issue by Ninjawolf0007** [AllTheMods/ATM-8#509]
The Sophisticated Storage Advanced Compacting Upgrade no longer compresses cobblestone to Sturdy Stone from Quark (hooray!! thank you!) But now it no longer compresses Cobbled Deepslate in the "Compact Only Uncraftable" mode. If you switch to upgrade to the "Compact Anything" mode, it compresses Cobbled Deepslate into ATC Compressed Cobblestone rather than ATC Compressed Cobbled Deepslate.

**Comment by Ninjawolf0007** [comment]
This is still/is again a problem in version 1.10 of the ATM8 modpack

**Comment by Mitchell5200** [comment]
Fixed, Closing
