### ISSUE TITLE
Lava Bucket filling recipes create Securitycraft Fake Lava Buckets by default

### ISSUE THREAD

**Issue by DocBuhGok** [AllTheMods/ATM-8#512]
After updating to All the Mods 8-1.0.7 normal Lava Bucket filling recipes are now defaulting to SecurityCraft Fake Lava Buckets instead of making normal vanilla Lava Buckets (unless I'm missing some intended change).

I created a brand new instance in both Prism and Curseforge Launchers to test this in v1.07.  It happened in both instances.  It works fine in 1.05(edit here, was in 1.05 when it worked not 1.06b as originally mentioned)

In Game Methods Tested
Mekanism Tank - Basic Tank filled with Lava, placed empty bucket in the fill slot and it should produce a normal Lava Bucket but it produces a Fake Lava Bucket instead
Create Spout - Filled Spout with Lava, placed empty bucket below spout on a depot and it fills the bucket but produces a Fake Lava Bucket instead.
Immersive Engineering Bottling Machine - Fill machine with Lava, toss Empty Bucket on machine's conveyor belt, machine fills it as a Fake Bucket instead of a vanilla Lava Bucket.
Thermal Expansion Fluid Encapsulator - same as above

ps...I'm not used to submitting these so if I've left something out that's needed to check this out let me know and i'll get it :)

**Comment by NuclearCowboy88** [comment]
So, this seems to have started happening again in the 1.1.0 version. What was the fix? I don't mind doing it myself, just need to be pointed in the right direction.

Edit: I know I am reviving a year old post to ask about this, and I am sorry. but id does not seem to have been sorted anywhere else
