### ISSUE TITLE
Fluid Extractor makes backpack unusable

### ISSUE THREAD

**Issue by cddrury** [AllTheMods/ATM-8#513]
As soon as I make a Fluid Extractor from Industrial Foregoing, any backpack I have in my inventory becomes unusable. This has happened to me twice. The first time I tried to make a Fluid Extractor in the crafting table, it deleted some of my materials (specifically the gold pressure plate and one or two other items). I then made the Fluid Extractor in my backpack crafting table, and from then I could not open my backpack. Tried using the hotkey, changing the hotkey, left clicking from my toolbar - nothing worked.

**Comment by PacifistMage** [comment]
Can confirm this is still happening as continuing the quest above makes any current equipped backpack "locked" (even with rebinding with other available key)

**Comment by PacifistMage** [comment]
Fixed in version 1.0.10, as i can access my backpack which was bugged from the previous version now.

**Comment by cddrury** [comment]
Thank you PacifistMage. I've also verified that I can access my previously bugged backpacks.
