### ISSUE TITLE
Freeze when loading in world.

### ISSUE THREAD

**Issue by KasiWL** [AllTheMods/ATM-8#515]
Uppon loading a singelplayer world, the game freezes after "reading world data". I've got about 12GB of allocated RAM to the profile. And the Issue is only in "All The Mods 8" instance.  

[latest.log](https://github.com/AllTheMods/ATM-8/files/10299302/latest.log)

**Comment by AndresVillaVilla** [comment]
Hello, i have the same problem with 9GB of RAM allocated. I tried saving a copy of the world, reinstalling the modpack and then trying to reopen it, but after the first time it happens again. Have you found any way to repair it ?

**Comment by P0kys** [comment]
Try repairing your profile (three dots next to the Play button in CurseForge). It seems like you might be missing a config file

**Comment by KasiWL** [comment]
I've just tried repairing the profile, and reinstalling it, reinstalling made it possible to play a new world, but not the backup save i imported. The backups save still has the issue in the first post.
Does this imply a new update could be the cause? or is the save just corrupt?

**Comment by P0kys** [comment]
Sorry mate, don't really know much about that stuff. Maybe try asking in Discord.

**Comment by AndresVillaVilla** [comment]
Do you have a link to their discord @P0kys ?

**Comment by AndresVillaVilla** [comment]
Found it ! https://discord.gg/allthemods

**Comment by KasiWL** [comment]
Give a shout if you get a response, but I'd guess a crash ruined the save files, corrupting them. 
Only a guess tho.
