### ISSUE TITLE
Server claims incorrect mod version, tho the client side has the same version as serverside. See imbeded picture.

### ISSUE THREAD

**Issue by DarkLordDLDL** [AllTheMods/ATM-8#517]
The server is using Pebblehost with pre-installed All The Mods 8 v.1.0.6b.
I installed All The Mods 8 v.1.0.6b on the CurseForge launcher by going into 'versions' and choosing that version, as it is the same as the pre-install on the server.

![image](https://user-images.githubusercontent.com/19656381/209472735-3baa5f44-35f6-4b5a-9279-948a28fc718f.png)

**Comment by Mitchell5200** [comment]
usually fixed by restarting your client, i believe it's also fixed in pack v1.0.7

**Comment by DarkLordDLDL** [comment]
Might be yes, but then the client side modpack version is one newer then serverside. There is only pre-install for v.1.0.6b, and I couldn't get the forge jar installer from the downloadable server files at the CurseForge launcher to run, so I can't install the server myself.

Using v.1.0.7 clientside and v.10.6.b serverside create some missing mods on server. I removed those from the client but then I got this error when on the loading screen when joining the server "internal exception java.lang.nullpointerexception: cannot read field "provider" because "type" is null".

**Comment by Mitchell5200** [comment]
> Using v.1.0.7 clientside and v.10.6.b serverside create some missing mods on server. I removed those from the client but then I got this error when on the loading screen when joining the server "internal exception java.lang.nullpointerexception: cannot read field "provider" because "type" is null".

Well that's of course gonna happen when you use different pack versions.
as for a manual install, just delete the folders `Config, defaultconfig, mods, KubeJS` off of the pebble host server (if they let you), and then upload the folders from the server Zip we provide, or wait for pebblehost to update their server files

**Comment by DarkLordDLDL** [comment]
> Well that's of course gonna happen when you use different pack versions. As for a manual install, just delete the folders `Config, defaultconfig, mods, KubeJS` off of the pebble host server (if they let you), and then upload the folders from the server Zip we provide, or wait for pebblehost to update their server files

A restart of the client did the trick. I will try uploading those folders later on. Do you know/remember is there is any big changes between those two versions? So that I should try to update the serverside before we start playing?

**Comment by Mitchell5200** [comment]
The critical thing is mod updates, and many do not like different client-server version mismatches

**Comment by DarkLordDLDL** [comment]
Hm, okey. I will try updating those folders from the download now and see if I can get it working.

**Comment by thecrypticace** [comment]
throwing my two cents in here: This exact error (same mod, version, and everything) happened to me after a client crash. I had to re-install the instance to fix it. The server I was playing on was unaffected. I'm guessing something was being written to disk when the crash happened resulting in corruption. I haven't been able to reproduce it again though.

**Comment by redrafa** [comment]
Only fixed it by supplying the server mod to all the clients. New users weirdly can join but after restarting the second or third time they will have to get the server mod to permanently fix it.
