### ISSUE TITLE
There are two types of honey that are incompatible with each other.

### ISSUE THREAD

**Issue by beaverrrr** [AllTheMods/ATM-8#518]
Output of Productive Bees' Centrifuges produces honey that's different from honey that's produced by the Thermal Series' Centrifugal Separator and there is no direct way of converting one into another, and there is no reason for two types to exist.

**Comment by lazygamerz** [comment]
I believe this extends to more than honey. A lot of mob drops are having the same issue as well as a few standard blocks such as netherrack and sand.
