### ISSUE TITLE
Breaking generic chests

### ISSUE THREAD

**Issue by Sassy404** [AllTheMods/ATM-8#52]
So, in a previous patch placing generic chests would cause a game crash with a crash report.
In the latest version, attempting to break generic chests causes the game to close down immediately, without producing any form of crash report, and didn't even bring the launcher back up upon closing.

**Comment by DylanBruzenak** [comment]
We are experiencing the same issue, version 8-0.0.12.zip. It doesn't appear to be all generic oak chests, just some in specific areas. No crash report, no server logs, just the regular disconnected messages.

**Comment by DylanBruzenak** [comment]
3 different players. Empty chest, but not sure if that matters, 100% repeatable.

**Comment by Fuzzock** [comment]
Experiencing the same on my server. Version 8-0.0.14. Seems to be just generic chests. Repeatable, and just crashes client out with no error message.

**Comment by InFuRiTy** [comment]
Same errors are happening in our community server as well with chests, waystones and different  TP commands as well!!
Our server admin looked into it in detail and recommended to us to remove both oculus and rubidium mods from the client.
Our ethereal crash percentage dropped 95% after the removal of those two, so I'm guessing these mods need a hotfix fast!!
If anyone can confirm this, let them know!!

**Comment by Jorue23** [comment]
@InFuRiTy This one seems to have nothing to do with the random game close ones. Allthough here the removal of rubidium could help that's not a real solution cause rubidium is pretty essential for middle to lower end pcs running this pack.

**Comment by DylanBruzenak** [comment]
Updating to 8.0.0.14 fixed this for us.

**Comment by Fuzzock** [comment]
> Updating to 8.0.0.14 fixed this for us.

Only found it on 8-0.0.14. More testing tonight show it is just generic chest that are effected and not Quark chests.

**Comment by mstefan21** [comment]
@whatthedrunk can be closed, last change of config in 0.1.3 fixed this problem
