### ISSUE TITLE
Wind generator quest shows wrong (outdated?) information.

### ISSUE THREAD

**Issue by beaverrrr** [AllTheMods/ATM-8#521]
Currently on 1.0.7, in "All the Power" questline that has Wind Generator task, and description for that task reads "(About 160FE/Tick at Y319 if you are wondering)". There are two problems with that statement, one is that you can't put wind generator at Y above 315, as it requires 4 blocks of clearance, and two: it only generates about 83 FE/t.
Setup (note JourneyMap Y level):
![javaw_O8l7lmzqwT](https://user-images.githubusercontent.com/1652025/209484679-47a68e86-cd69-447e-a282-4cd5d03f7352.png)
Wind generator status window:
![javaw_pA6gmeuW0K](https://user-images.githubusercontent.com/1652025/209484687-8785d112-a1a1-4f06-beea-d09c69e81f39.png)
Quest:
![javaw_pdyaTRA1oE](https://user-images.githubusercontent.com/1652025/209484696-3753d753-4793-4237-9f53-87006b12ec25.png)

**Comment by alfredggttv** [comment]
Will take a look at this and fix it! I need to revamp the questline as most of it was from 7. Will put in my notes for next update!
