### ISSUE TITLE
[1.0.6b]Lagging server and Invalid entity rotation: NaN, discarding. spam in console

### ISSUE THREAD

**Issue by krystofkrticka** [AllTheMods/ATM-8#522]
Hello, today I was playing ATM8 with my friend and suddenly server started lagging and when I looked into console I saw spam of `Invalid entity rotation: NaN, discarding.` We were playing on version 1.0.6b.

**Comment by krystofkrticka** [comment]
I also tried updating server to version 1.0.7 but than it spams java exceptions with very long message. I'll try to capture it and send it here.

**Comment by zekeflynn** [comment]
Hey did this ever get a specific resolution? I'm having the same issue with my pack.

**Comment by krystofkrticka** [comment]
Well I don't I was fixed by waiting a bit until server killed that invalid entity. I got help with this by one of mods on ATM discord server.
