### ISSUE TITLE
Constant memory allocation crashing

### ISSUE THREAD

**Issue by Sw3kt** [AllTheMods/ATM-8#523]
I've been trying to play this modpack for a couple of days now and the game constantly crashes. I'm trying to play singleplayer, and the game crashes with an "**Exit Code: 1**" saying I need to allocate more RAM. I allocated 8gb, 9gb, 10gb and even 12gb max but the game still crashes after about 10 minutes of playing. My system has 16gb of RAM in total and I have all my drivers updated and playing the latest version of ATM 8 (1.0.7). I tried playing other versions of the modpack but I still have these same crashes. I don't know how or what version of Java I need to install in order prevent this crash from happening. I really want to play this modpack so I appreciate any feedback on what I should do.

My rig:
CPU - Ryzen 5 5600x
GPU - Radeon 5600XT
RAM - 16GB

([crashReport1.txt](https://github.com/AllTheMods/ATM-8/files/10301823/crashReport1.txt)
3600 MHz)

**Comment by P3rf3ctXZer0** [comment]
Its memory leak. I narrowed it to spark.

**Comment by P3rf3ctXZer0** [comment]
Yeah remove spark

**Comment by Mitchell5200** [comment]
> Its memory leak. I narrowed it to spark.

Have you reported this to the spark dev's issues page?, if not, can you, with as much information as possible that proves it's spark.
https://github.com/lucko/spark/issues

**Comment by P3rf3ctXZer0** [comment]
Feel free. I am not really dealing with mods per se right now.

**Comment by Sw3kt** [comment]
> Yeah remove spark

I removed spark from the mods folder. Had a few crashes loading into the world, but once the world was loaded, it seems fine for a few minutes. At this point (from my experience), going to or loading in new chunks crashes the game with same error code. I tried increasing(12gb) AND lowering(8gb) ram in forge but that doesn't seem to help. Again, I am playing this modpack in singleplayer so I don't know what is causing these crashes.

**Comment by redrafa** [comment]
Even with Spark off, something is messed up. Have a server with friends that started with 6 RAM and kept going up, currently I've thrown not 10 but 20Gb of RAM and it crashed with a out of memory error, even with restarts etc, it will, eventually clog itself up to run out of RAM. Hosting servers is basically almost impossible unless you modify this modpack a ton and make other additions to fight and fix the leaks.

On single player the RAM just rises up and then resets itself with a FPS drop (clears itself) and goes back down to repeat, server however doesn't do the same, it tanks till it crashes.

**Comment by Sw3kt** [comment]
> Even with Spark off, something is messed up. Have a server with friends that started with 6 RAM and kept going up, currently I've thrown not 10 but 20Gb of RAM and it crashed with a out of memory error, even with restarts etc, it will, eventually clog itself up to run out of RAM. Hosting servers is basically almost impossible unless you modify this modpack a ton and make other additions to fight and fix the leaks.
> 
> On single player the RAM just rises up and then resets itself with a FPS drop (clears itself) and goes back down to repeat, server however doesn't do the same, it tanks till it crashes.

Try removing Rubidium and Oculus. Rubidium is "performance" mod and "Oculus" is used for shaders. The downside to this is that you won't be able to use shaders. Once I removed these two, it helped me with my crashing. I don't play on a server so I don't know how this will affect it.

**Comment by Sw3kt** [comment]
I might have a fix: remove ALL previous versions of Microsoft Visual C++ 20XX... and install the latest one. [Link here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170). Also, make sure you're running the modpack on Java 17 or newer. I hope this helped as this fix the crashes I was having.

**Comment by abyss5561** [comment]
> I might have a fix: remove ALL previous versions of Microsoft Visual C++ 20XX... and install the latest one. [Link here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170). Also, make sure you're running the modpack on Java 17 or newer. I hope this helped as this fix the crashes I was having.

You are wonderful, thank you.
