### ISSUE TITLE
Crashing at startup - 1.0.7

### ISSUE THREAD

**Issue by ThatFineFellow** [AllTheMods/ATM-8#526]
I've been trying to start up ATM 8 for a few hours now but haven't been able to get past the launcher, which has consistently shown an Exit Code: 1 error. Below is the latest crash report. 
Forge 43.1.55
12GB RAM allocated

[hs_err_pid13888.log](https://github.com/AllTheMods/ATM-8/files/10304367/hs_err_pid13888.log)

Let me know if I should include anything else. Thanks to anyone in advance.

**Comment by alekthefirst** [comment]
IIRC the solution to this is to update your graphics driver to the latest version

**Comment by ThatFineFellow** [comment]
> IIRC the solution to this is to update your graphics driver to the latest version

I'd figured that updating from settings would have been sufficient, but I decided to download the update from the driver's website instead, and lo and behold, it worked! Thanks
