### ISSUE TITLE
Lacking/short texts in quests

### ISSUE THREAD

**Issue by Zajozor** [AllTheMods/ATM-8#527]
Hey, I recently started playing ATM8 and noticed that a lot of the quests are missing descriptions, or their descriptions are quite.. succinct.

examples:

- this could say a sentence or two about what industrial foregoing is about
![CleanShot 2022-12-26 at 23 54 19](https://user-images.githubusercontent.com/1835434/209587360-a162e56e-da9f-41f8-998c-4edbb873e0b8.png)

- this quest is about tanks and chests, but only mentions chests in the text
![CleanShot 2022-12-26 at 23 56 59](https://user-images.githubusercontent.com/1835434/209587440-c9cdc2dd-de8c-4698-8503-68482abca757.png)

- these boss quests have no descriptions about what/where these bosses are
![CleanShot 2022-12-26 at 23 58 22](https://user-images.githubusercontent.com/1835434/209587490-1c5e66d6-73fb-4891-872e-58bef4d14bb5.png)

To veteran players, these might not be very interesting, but maybe to new players, or returning players without knowledge of certain mods, the texts can help quite a lot!

_Are you accepting PRs for quest improvements, like these descriptions? I might be interesting in contributing._

From my understanding, the quests are editable via the files in https://github.com/AllTheMods/ATM-8/tree/main/config/ftbquests/quests/chapters but there is also an in-game editing mode (https://help.ftb.team/help/en-gb/5-ftb-quests/26-quest-creator-guide)

Here is a sample text I produced for the Latex Processing Unit (did not have a description/subtitle before).

![CleanShot 2022-12-27 at 00 14 57](https://user-images.githubusercontent.com/1835434/209587940-3e7e22cb-6358-4889-9e35-e2a64973cf09.png)

Let me know if you would be interested in reviewing/accepting some quest improvements like this. Also feel free to direct me towards certain quests/chapters so that I don't write for chapters which you plan to change completely :) 

Have great holidays!

**Comment by alfredggttv** [comment]
A lot of these quests that are lacking, whether just a single quest or an entire section, were the initial quests that started with the pack. It was just a barebones kind of thing, something meant to just be a little guide.

I've been pretty backed up in terms of writing questlines, but some examples of my work and the standard that I want to set for the pack can be found in the newest rework of Refined Storage. The Getting Started questline was also done by me, but I'm reworking that as well. I've been pretty swamped between the holidays and getting sick. lol

> Are you accepting PRs for quest improvements, like these descriptions? I might be interesting in contributing.

If you want to shoot me a DM on discord, we can work something out. AlfredGG#3697
