### ISSUE TITLE
Constant crash shortly after world load

### ISSUE THREAD

**Issue by DeltaDesigns** [AllTheMods/ATM-8#528]
As of today I haven't been able to play for more than a few minutes in my world before I crash back to the launcher

[hs_err_pid11204.log](https://github.com/AllTheMods/ATM-8/files/10304984/hs_err_pid11204.log)

**Comment by DerpyKiptin** [comment]
hello there. try increasing the ram in both forge, and the mod pack profile options itself. Again, you will have two locations to do so. Bottom left of forge, and the mod pack. You will find a slider.

**Comment by DeltaDesigns** [comment]
> 

I currently have 16gb allocated, tried with lower (12) as well

**Comment by redrafa** [comment]
Some user said Spark is the mod issues, I honestly quit the modpack for now since not even 20 gigs feed the modpack, it will always eventually clog up even with world caring and server restarts. All my 3 servers suffered the same even with different processing power and insane amounts of RAM

**Comment by Sw3kt** [comment]
I had the same issue with the constant crashing. Someone told me to remove spark but I was still getting crashes when loading into new chunks. After looking further, a redditor suggested to remove Rubidium and Oculus and so I did. I haven't had as many crashes as I did. I tested on modpack version 1.0.5 without Spark, Oculus, and Rubidium and it is running a lot better for me. You may notice some stuttering here and there. I have a decent rig so my fps didn't dip below 100 frames. I still need to try it on 1.0.7 to see if these three mods are the issue. I installed Canary mod and Starlight which improved performance to some degree.

TLDR; Remove Spark, Oculus, and Rubidium

**Comment by DerpyKiptin** [comment]
> Some user said Spark is the mod issues, I honestly quit the modpack for now since not even 20 gigs feed the modpack, it will always eventually clog up even with world caring and server restarts. All my 3 servers suffered the same even with different processing power and insane amounts of RAM

spark removed from my server here. its better. i disabled oculus on client side (me)
my mob spawning is still broken lol. its using 5.5 gb on the server out of 6.
