### ISSUE TITLE
Crash upon death or teleport

### ISSUE THREAD

**Issue by McKitten** [AllTheMods/ATM-8#53]
ver 0.14 no change/extra mods (discord issues sidelined due to RL)

https://paste.ee/p/bH9qz (MMC output from self)
https://mclo.gs/BoX8BYc (a player)
+1 pending i hope, likely wont see him for 12hours.

Previous server memory issues seem to have stabilized with top reporting a consistent 48.5% usage and no tick lag at the time of my death. So this seems purely client but members (not personally) also crashing on any teleport (don't think i can get a report from that unless people stop dying ;) )

**Comment by InFuRiTy** [comment]
Check out my response on this issue post:
https://github.com/AllTheMods/ATM-8/issues/52#issuecomment-1260815178

**Comment by McKitten** [comment]
The problem with this is that .014 does not have Oculus in it. Create was an issue for it so it was removed.
Create is not anywhere near these teleport locations.
My current bed is in fact one of the fishing huts while I complete my house and i died in a vanilla desert while trying to find cactus.
I was actually thinking journeymap. There does not seem to be another common denominator, unless there is another new or updated mod?

**Comment by InFuRiTy** [comment]
In my post i also mentioned Rubidium. The removal of that mod fixed the crashes for me. I haven't had a crash ever since.
