### ISSUE TITLE
Bug with Blueprints book and ars neveau spell books

### ISSUE THREAD

**Issue by Vashta** [AllTheMods/ATM-8#530]
so when i put my blueprints in the book it says like press x and c or something to cycle the selected blueprint but it only goes thru like 5 of them at random even though i have like 11 in the book it wasnt too big of a deal as i could just take them out but the same bug is happening to the ars neveau spell book with the cycle next spell buttons! it goes up by two instead of 1 so if i set my spell to the first one and hit next spell several times it goes to third spell then 5th spell then 7th and so on and after that i found out its doing the same thing for the blueprints book from silent gear!

**Comment by Wyvernity** [comment]
It looks like section swap buttons for Silent Gear items broken on the current version of the mod. I downgraded it to version 3.0.8 and it seems fixed for me.

**Comment by Vashta** [comment]
> It looks like section swap buttons for Silent Gear items broken on the current version of the mod. I downgraded it to version 3.0.8 and it seems fixed for me.

would that affect the ars neveau spell book too? that one is the main reason i even reported it as the silent gears part wasnt that big of an issue seeing as other then upgrade parts i wouldnt need certain blueprints more then once

**Comment by tyler0587** [comment]
This is also effecting the tool tip window you get when hover and press ctrl. Swap with [z]/[c] key will only cycle in increments of 2. Going to try downgrading on next load.
