### ISSUE TITLE
all the mods 8 curse forge crash WHEN I PRESS PLAY 

### ISSUE THREAD

**Issue by b0dz** [AllTheMods/ATM-8#532]
i was able to play yesterday  and today i can't lunch it i get a game crashed error -1 (The game crashed whilst rendering overlay
Error: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured) 
here is the log : https://mclo.gs/PR6zIsM 
my pc specs are : I5-13600K - 3060 - 16GB 3600MHZ 
if any1 can help me to fix this i will be grateful

**Comment by fluffybunny4sale** [comment]
Same here :(

**Comment by Alle-thebug** [comment]
I have the exacy same issue, have any of u come up with a solution, we need to get helped
