### ISSUE TITLE
Server crash due to The Twilight Forest mod

### ISSUE THREAD

**Issue by haisuts** [AllTheMods/ATM-8#533]
[crash-2022-12-25_09.36.23-server.txt](https://github.com/AllTheMods/ATM-8/files/10308330/crash-2022-12-25_09.36.23-server.txt)

**Comment by Blockguy24** [comment]
Can confirm this is an issue, crashed on my friend's server:
[crash-2023-01-28_04.53.00-server.txt](https://github.com/AllTheMods/ATM-8/files/10526074/crash-2023-01-28_04.53.00-server.txt)

It appears to be related to the generation of the lich tower

**Comment by Icerith** [comment]
I'm having the same issue, I believe. Has anyone found a fix for it?
[crash-2023-01-28_04.53.00-server.txt](https://github.com/AllTheMods/ATM-8/files/10834830/crash-2023-01-28_04.53.00-server.txt)
