### ISSUE TITLE
Crude oil not generating from Fluid laser

### ISSUE THREAD

**Issue by mikededecker** [AllTheMods/ATM-8#535]
Hi there ATM team.

incredible modpack again but I found an issue with the crude oil generation within the fluid laser. If I've met all the requirements to get crude oil I still don't get it

**Comment by Mitchell5200** [comment]
Current known and reported issue in Industrial Foregoing
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1313
