### ISSUE TITLE
[1.0.7] Unable to select hotbar slots

### ISSUE THREAD

**Issue by Epicycle23** [AllTheMods/ATM-8#537]
Version: 1.0.7

I am unable to select/change the active hotbar slot using keys 0-9 or the scroll wheel.
It started happening after I visited the twilight forest.
Sometimes it is fixed when restarting the game once but occasionally I have to restart the game multiple times emptying out my inventory, changing dimensions, etc not sure what helps in the end but at one point it just works again for a few minutes.
Had it working for about 20 minutes than I left the game in the twilight forest and when I rejoined the world the active hotbar slot was "locked" again.

**Comment by Epicycle23** [comment]
Can't remember using a quiver before, but a few minutes ago I was opening the quiver inventory/arrow selection and it did not close.
After I put the quiver away in a chest the UI from the quiver disappeared and I had that exact issue where the active hotbar slot is locked/unchangeable.
If i put the quiver back in my inventory the quiver UI reappears and using the scroll wheel changes the selected arrow...
So it seems to me that it has something to do with the quiver although, as I said, I can't remember having used a quiver before when it happend, but I had it in my backpack

**Comment by Youqik** [comment]
I ran into the same problem as you. I'm not sure how it happened. Maybe when I switch screens (Tab + Alt). Every time I need to restart the game, it will fix it. Neither the scroll wheel nor the 0 to 9 buttons work. Do you have any new discoveries?

**Comment by abrossimow** [comment]
Pining this - why was it closed?
