### ISSUE TITLE
Chunk lost after using Quarrry from Quarry Plus

### ISSUE THREAD

**Issue by indigobl4k** [AllTheMods/ATM-8#546]
Yesterday I was playing in my world all good, I decided to use a Quarry to test it and after a few minutes my game crashed.
I opened my game again, enter my world and suddenly that whole chunk was lost :( 

This never happened to me before using this modpack and i'm sad because I invested a lot of time on it.

I will attach an image about chunk lost
![2022-12-28_13 51 17](https://user-images.githubusercontent.com/81390756/209846309-ed4e2cdd-8b75-4ef8-ab93-cccea80794ef.png)

**Comment by redrafa** [comment]
Any logs on the crash? Might be mod specific or compatibility issue which then it's both a modpack and mod issue.
Need more info, can't work on what happened and how to fix based on this
