### ISSUE TITLE
ae2 formation plane does not place blocks

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/ATM-8#547]
the formation plane from ae2 does not place blocks and if no block is set in the filter it places water even if there is no water in the system.

**Comment by James103** [comment]
Try setting the priority on the Formation Plane to be higher than any storage devices attached to the same ME system. The Formation Plane works almost like a storage device except that it accepts a single block at a time and attempts to place whatever block it receives when that block is added to the ME system.

**Comment by Schrimpes** [comment]
thx, the higher priority works, but the fact that a block is only set when added to the system is not what i need. so I think I can't avoid a block placer. but i dont understand why the plane places water when no filter is set.

**Comment by PinkerTee** [comment]
is there a way to change the formation plane to use blocks that are already in the system? maybe via config settings or smth?

**Comment by gund** [comment]
bump
This is actually very weird behavior that it would only place a new block from the system and not extract existing ones from the system.
Is there any way to overcome this limitation? Maybe with some combination of storage buses and me interfaces?
Any guidance would be greatly appreciated!

**Comment by Hatry1337** [comment]
agree on this. in older ae2 versions formation plane was working like export bus, but now it is like storage bus. maybe add a mode toggle button inside gui?

**Comment by ropi336** [comment]
a solution would be to just permanently have an exporter and an importer hooked to a chest that just constantly pushes those items and picks them back in but that's incredibly shoddy and hacky
