### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by jmar8888** [AllTheMods/ATM-8#548]
Just trying to get an ATM 8 server running in a docker on unraid. New to all of this and can't figure out how to get a world started. do I need to install something other than the ATM 8 docker from the community apps on unraid? Do I need to run something to set up the unraid docker for ATM 8 that I can't do from the unraid GUI?

**Comment by redrafa** [comment]
Honestly the place for aid would be with other unraid users, the installing procedure would be the same as any other modpack, I had no problems with it, just requires manual work, it's already well "documented" with unraid users from what I searched before answering.

This GitHub is specifically to deal with the ATM8 problems, which extends only to modpack problems on the client and server side issues (starting from when the servers loads up and generates the world, not the before part of setting up).
