### ISSUE TITLE
Client crash with ME Wireless Transceiver

### ISSUE THREAD

**Issue by madkoin** [AllTheMods/ATM-8#550]
Hello, I am currently playing on a server in version 1.0.7.
I am having trouble with the ME Wireless Transceiver. I manage to use it normally and after X time, clicking on the ME Wireless Transceiver makes me crash the client.
I noticed that by rebooting the server, I can use the ME Wireless Transceiver normally again for X time. You will also find my client crash log. Thanks in advance

[crash-2022-12-29_10.01.56-client.txt](https://github.com/AllTheMods/ATM-8/files/10319021/crash-2022-12-29_10.01.56-client.txt)

**Comment by Mitchell5200** [comment]
https://github.com/the9grounds/AE-Additions/issues/114
https://github.com/the9grounds/AE-Additions/issues/116

**Comment by RadegasTCZ** [comment]
It's been a while, any news on that? Struggling on the newest version today as well.

**Comment by Beachman4** [comment]
I'm working on this bug now, sorry folks.
