### ISSUE TITLE
Game randomly closes 

### ISSUE THREAD

**Issue by Cratios** [AllTheMods/ATM-8#56]
Since 0.0.14 the Game randomly closes when using Waystones, /home, walking around!

When you uninstall Rubidium it works. So i guess Rubidium is the Problem

**Comment by InFuRiTy** [comment]
Yeah those recent issue posts are all about these ethereal crashes!!
Removing Rubidium and in older versions Oculus helped a lot but not 100%..

I'm starting to feel like the addition of Create was rushed a bit if it causes so many incompatibilities with other mods and especially performance enhancing ones that the pack does need with big and active player bases!!

**Comment by DylanBruzenak** [comment]
We are also seeing this when teleporting, even to areas we have been before (but not ones that have been loaded, it usually only happens the first time teleporting to a place after a reboot). No crash log. 8.0.0.14.

**Comment by Bneboy** [comment]
Remove Rubidium for now, I had the same issue and figured out that it crashes with Rubidium.

**Comment by DylanBruzenak** [comment]
A note: without removing rubidium with 8.0.0.15 I am not experiencing this, but another person on our server with the exact same version is with every teleport to an area they haven't been before.

**Comment by BioPrince** [comment]
Game randomly closes when looking up or moving mouse quickly
https://paste.atlauncher.com/view/3b13c24c-3109-448a-b99d-6209e3cb4a3e
