### ISSUE TITLE
A modern modpack without a backup folder

### ISSUE THREAD

**Issue by Pelkenator** [AllTheMods/ATM-8#561]
My friend playfully nuked me then said just back it up to my surprise NO Backup Cool Guess if you want to backup you have to copy your world into your own folder. We just lost about 18 hours of gameplay because of that lucky I just updated or we would either have to restart fresh or move somewhere else with nothing.

**Comment by Mitchell5200** [comment]
simplebackups.jar.Disabled implemented in recent versions,
