### ISSUE TITLE
Random Server Crash-clients unable to join, no reason given

### ISSUE THREAD

**Issue by PlaguedTide** [AllTheMods/ATM-8#563]
Made a change to a copper forge's input/output schema and ran into the aforementioned crash. 

attached for your review.
[crashreport-2022-12-31.txt](https://github.com/AllTheMods/ATM-8/files/10327615/crashreport-2022-12-31.txt)

**Comment by Hiattech** [comment]
Only have iron forges in the game (8 of them). made a change to one of the inputs several minutes before. One character was digging dirt and the other just standing not accessing the forges at all when the game crashed and continues to crash immediately upon login.
[crash-2023-01-05_12.22.54-server.txt](https://github.com/AllTheMods/ATM-8/files/10355265/crash-2023-01-05_12.22.54-server.txt)
