### ISSUE TITLE
Problem with Bigger reactors

### ISSUE THREAD

**Issue by Kapuupa** [AllTheMods/ATM-8#565]
Sometimes when I login to my server the liquids from mine machines from Bigger Reactors(Reactor, Heat exhanger and turbine) disappears. Not only that but sometimes the fuel also from reactor disappears(but if I have a constant flow of fuel it doesn't disappears I think). And with the turbine not only water/steam disappears but also all the settings go back to the standard(if I change the flow rate it will go back to normal). This problem will also arrive when I change dimension.

Btw: I play on 1.0.6 b version if that's helpfull information

**Comment by Adagnitus** [comment]
Same issue here. 
Playing on 1.0.8
I built a Bigger Reactors reactor in the mining dim and every time I go through the portal (at least into the dimension) all fuel in my reactor is gone, even if the reactor was off when I left.

**Comment by RogueLogix** [comment]
a bug with this behavior was very easy to have occur in 1.0.6b fixed in 1.0.7, 1.0.7+ has a much rarer and different bug.
related to 1.0.6b: https://github.com/BiggerSeries/BiggerSeries/issues/78
related to 1.0.7+: https://github.com/BiggerSeries/BiggerReactors/issues/71
