### ISSUE TITLE
Game Crash on private server hosted on own machine

### ISSUE THREAD

**Issue by ghostpanda0** [AllTheMods/ATM-8#566]
Friend was using an emerald furnace upgraded to factory with fuel effeciency for 10 minutes when a watchdog error occurred. 
 
Attemps to fix:
Used the -1 to disable watchdog error. server crashed on startup. 
Increased max tick time. sever crashed on startup
cloned world into single player. Removed solar panel that was fueling the emerald furnace. Sever still crashed calling a tick error. 
reverted to the normal max tick rate. server crashed shortly after coming online. 
Cloned world again into single player, removed the furnace. Sever finally started up. 
No other issues as of yet. 
[crash-2022-12-31_12.16.33-server.txt](https://github.com/AllTheMods/ATM-8/files/10327879/crash-2022-12-31_12.16.33-server.txt)
[crash-2022-12-31_12.31.50-server.txt](https://github.com/AllTheMods/ATM-8/files/10327880/crash-2022-12-31_12.31.50-server.txt)
[crash-2022-12-31_12.32.52-server.txt](https://github.com/AllTheMods/ATM-8/files/10327881/crash-2022-12-31_12.32.52-server.txt)
[crash-2022-12-31_12.46.57-server.txt](https://github.com/AllTheMods/ATM-8/files/10327882/crash-2022-12-31_12.46.57-server.txt)

Four crash logs given for devs to try and figure out the issue.

**Comment by Hiattech** [comment]
> Attemps to fix: Used the -1 to disable watchdog error. server crashed on startup. Increased max tick time. sever crashed on startup cloned world into single player. Removed solar panel that was fueling the emerald furnace. Sever still crashed calling a tick error. reverted to the normal max tick rate. server crashed shortly after coming online. Cloned world again into single player, removed the furnace. 

How do you remove the offending furnace? Trying to remove the one that's broken my world.
