### ISSUE TITLE
while holding something, even things without a right click - I'm unable to shift right click to close double doors

### ISSUE THREAD

**Issue by shrad1994** [AllTheMods/ATM-8#568]
![image](https://user-images.githubusercontent.com/96917010/210169350-45b018d0-6743-48eb-b0c6-99a080046354.png)
To reproduce:

1. hold something in main hand
2. hold shift and right click double doors
3. profit

Still happens with nothing equipped.

**Comment by shrad1994** [comment]
Appears you can't open the door either shift holding shift right click

**Comment by Mitchell5200** [comment]
Tracked at https://github.com/MelanX/UtilitiX/issues/36

**Comment by Mitchell5200** [comment]
Fixed in 1.0.14, when that gets released
