### ISSUE TITLE
Can not open Ars spell book

### ISSUE THREAD

**Issue by WarEagle93** [AllTheMods/ATM-8#570]
There is no bound key for Ars spellbook.  The tooltip says "Press not bound for quick craft".  Key Bindings has nothing listed for "quick craft".  

I have tried to reset all keybindings.  It did not work. 

![image](https://user-images.githubusercontent.com/65616438/210175090-fcb1146a-36eb-4a81-8c45-5f9e30f573ef.png)

**Comment by jorgeRambla** [comment]
Ars book don't have a key set by default. You need to set it up by yourself I settings - controls - by category - search `ars`
