### ISSUE TITLE
Blue Skies questline unable to progress

### ISSUE THREAD

**Issue by Letholdius** [AllTheMods/ATM-8#578]
Getting an Upgrade quest on Blue Skies questline unable to complete for people who went to Everdawn first and not Everbright due to quest only accepts Turquoise Stone pickaxe, not both Blue Skies stone pickaxe variants.

**Comment by alfredggttv** [comment]
Will be fixed in a future update. Thank you!

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
