### ISSUE TITLE
Mekanism blocks cant see the sky

### ISSUE THREAD

**Issue by hamurci** [AllTheMods/ATM-8#583]
I've built some wind generator in the sky at max build level. They sometimes works but sometimes just dont care. They show "Sky is blocked" error message on their interfaces. But there is nothing above them. they are in the sky. I was just ingoring that bug and built some reactors for power, and today I've discovered a  new problem. I've placed Solar Neutron Activators(which turns nuclear waste into polonium with sunlight)  to same place as wind generator in the sky. And they just store nuclear waste and dont work.

**Comment by tekook** [comment]
have you tried to build them a few blocks down? Having no problem with the wind generators at max height - 5 blocks

**Comment by hamurci** [comment]
Yes,they are 5block below than max build height. For now the problem is gone without me doing anything
