### ISSUE TITLE
Ars Nouveau Toggle Selection HUD key not working

### ISSUE THREAD

**Issue by DorianSlay** [AllTheMods/ATM-8#584]
Hi, so i am currently running the newest version of ATM8 on my server, and for some reason, the toggle selection HUD command for AN isnt working, it works in the world i have in the 1.0.5 but not the 1.0.7 version of ATM8. No, i do not have anything else bound to the key that i set to this command, and i have tried it on other keys, also the cycle to next and previous spells commands only cycle to odd or even number spell slots for some reason.

**Comment by Vashta** [comment]
the reason its cycling by odd or even numbers is that anything that cycles like that is going up and down in increments of 2 the same thing happens to the blueprints book from silent gear
