### ISSUE TITLE
Shader issues

### ISSUE THREAD

**Issue by eggonaise** [AllTheMods/ATM-8#59]
Hello, I downloaded ATM8 and noticed there was no shader pack option tab in video settings, I added oculus to my mods folder and now there is a shader pack tab in options, the shaders work for the most part, however, in most villages there is a chunk of invisible blocks. When I turn the shader off the blocks generate. F3+A does not load the chunks. This is with the complementary shaders pre installed with this modpack.
![2022-09-28_14 13 38](https://user-images.githubusercontent.com/114621273/192890368-37be382a-9f52-41c2-8f94-ab1b22b5e197.png)
![2022-09-28_14 14 01](https://user-images.githubusercontent.com/114621273/192890387-dd952cad-a794-4d0b-a3a8-22a91172c7a7.png)

**Comment by Danilovskiy-31415926** [comment]
Same, 0.0.14, just dont have oculus in mod list, and i had chunk errors on old versions of atm8, didnt khow how to fix

**Comment by P0kys** [comment]
Oculus doesn't work with Create. Either remove Oculus (if you want Create and don't care about shaders) or remove Create and Ars Creo (dependant on Create)

**Comment by Mitchell5200** [comment]
Create has released an update to fix this issue, update create or wait for a pack update

**Comment by whatthedrunk** [comment]
Update to 0.0.15 and you should be good!
