### ISSUE TITLE
Fatal error in Java Runtime Environment after entering a portal

### ISSUE THREAD

**Issue by ZeldaFlask** [AllTheMods/ATM-8#593]
Hi, Im trying to go to the Nether but the game keeps terminating itself and gives me an exit code 1. Does that mean the world is corrupt? Playing in the overworld is fine. This happens when I step through a portal. When I load the game again, it spawns me back into the overworld. 
I attached the crash report below.

[hs_err_pid5896.log](https://github.com/AllTheMods/ATM-8/files/10351791/hs_err_pid5896.log)

**Comment by Jukime1** [comment]
Try to remove everything from these slosts and try again for me it worked
![image](https://user-images.githubusercontent.com/122056050/210879319-f76e45a8-ab5c-4539-aea0-c85d38afd963.png)
