### ISSUE TITLE
No Soliciting Sign not working

### ISSUE THREAD

**Issue by janella1404** [AllTheMods/ATM-8#594]
Hi,
I've placed the No Soliciting Sign so the wondering trader will not spawn. Since then, it appeared a lot more often, directly near it.

**Comment by Vashta** [comment]
mine worked but i put mine next to the trader rug thing that you make from those fabric pieces the trader and his llamas drop as it forces them to spawn on that rug perhaps the sign is bugged and rather then 6 chunks its set to 6 blocks?
