### ISSUE TITLE
Entering nether crash Fix !

### ISSUE THREAD

**Issue by Jukime1** [AllTheMods/ATM-8#596]
I got 4 crashes when i first tried to go in the nether and i didn't know why so i removed all my items and tried again and it worked then i investigated a bit and it turns out that if you have any item in these slots you get instantly crash after going in the portal ! (i hear that its about the backpack being there but i tried and its about the slot not the item because i had 4 backpacks on me in the toolbar and i had no problems going in) These are the slots  (didn`t test if all of them do the same thing (crash) because it takes too long to load and yeah.. just remove everything and its all good )
![image](https://user-images.githubusercontent.com/122056050/210879176-98a7f55a-d4a7-4977-a86b-b4cd6669ac2e.png)

**Comment by ViRb3** [comment]
Need logs. I can definitely go through the nether portal with those slots filled, even with a backpack.

**Comment by h671466** [comment]
This did solve my issue aswell so it might be a combination of things that make it crash, i wouldnt know how that works, but it helped me atleast
