### ISSUE TITLE
Hose Pulley not working

### ISSUE THREAD

**Issue by Zhannan23** [AllTheMods/ATM-8#597]
I see youtubers using the hose pulley from create, liquid pipez, and an ender tank to transfer lava to magmatic generators. 

My hose pulley doesn't work, and my ender tank has black decoration lines instead of the normal white or orange you would see in JEI or on someones video. 

I run a server using Akliz, and their support doesn't see anything happening on their end, so it has to be client side. 

Anyone have a fix for this?

**Comment by Vashta** [comment]
not sure about the horse pulley but did you use black wool for the ender tank? as those lines are based on what color wool you used and act like a code as ender chests and ender tanks share inventory with the same "code" or lines which you can dye with any color
