### ISSUE TITLE
RFTools All Builder Quarries Break

### ISSUE THREAD

**Issue by Nwebb03** [AllTheMods/ATM-8#599]
After trying to use a quarry in the other, all other RFtools Quarries will be unable to mine any ores. I first set up a builder in the mining dimension and it was working fine until I tried to set one up in the other. After the builder quarry in the other didn't work, I headed back to my mining dimension quarry and noticed that it is now unable to mine ore. The message "Break was canceled" pops up when the builder hits any ore.  Here is what the quarry looks like when you set the builder to skip operations that the builder cannot do.

![Screenshot 2023-01-05 165004](https://user-images.githubusercontent.com/82986564/210907459-6f34bc78-5be8-41e9-ab8d-312082c70ff3.png)

**Comment by Mitchell5200** [comment]
Under investigation, a game Restart should clear that issue though.
However you are not intended to use any quarries in the other anyway.

**Comment by Mitchell5200** [comment]
"fixed" in 1.0.8
