### ISSUE TITLE
Builder in minecolony

### ISSUE THREAD

**Issue by L-mask** [AllTheMods/ATM-8#60]
I ran into a issue playing with minecolony. Every time i want to build the builders hut the worker assigned would not start the job canceling and re assigning would not solve his problem. I also tried to just place the builders hut lv1 in creative and start any other build but they just wont claim the job.

I am playing on the current build 8-0.0.15

**Comment by BeadiestSkyBlue** [comment]
i am also experiencing this problem

**Comment by ellisxl** [comment]
Have the problem that after setting the builder's-hut and commissioning the build, the builders just stand around stupidly and do nothing, it's a shame that the mod doesn't work

**Comment by theBeardyDwarf** [comment]
> I ran into a issue playing with minecolony. Every time i want to build the builders hut the worker assigned would not start the job canceling and re assigning would not solve his problem. I also tried to just place the builders hut lv1 in creative and start any other build but they just wont claim the job.
> 
> I am playing on the current build 8-0.0.15

Im having this problem as well, same version , in a 3rd party server

**Comment by ViceNoir** [comment]
FYI - I looked at the closed tickets the other day and found this.... Could it be your issue?  https://github.com/AllTheMods/ATM-8/issues/26.  You may need to get the server settings adjusted...

**Comment by L-mask** [comment]
I am aware that you can disable and enable the Tape around the construction site. I believe this is just visual because I had the tape around while I tested and it didn't resolve the problem. 

Thanks for you're input @ViceNoir

**Comment by L-mask** [comment]
> FYI - I looked at the closed tickets the other day and found this.... Could it be your issue? #26. You may need to get the server settings adjusted...

I am aware that you can disable and enable the Tape around the construction site. I believe this is just visual because I had the tape around while I tested and it didn't resolve the problem.

Thanks for you're input @ViceNoir

**Comment by ViceNoir** [comment]
Sorry, this is the part I wanted you to read.
From the minecolonies discord:

If you are playing ATM8, and experiencing issues with a builder who isn't building, or a builder stuck or not not moving, etc., the issue is with the config. Right now the AI Update rate is set to 100(defaults to 1) which makes them take hours to think, change the line in the config manually to 1 for now. I also recommend changing the builder block placement delay back down to default from 250.

Minecolonies serverconfig is in your world folder.

**Comment by L-mask** [comment]
> Sorry, this is the part I wanted you to read. From the minecolonies discord:
> 
> If you are playing ATM8, and experiencing issues with a builder who isn't building, or a builder stuck or not not moving, etc., the issue is with the config. Right now the AI Update rate is set to 100(defaults to 1) which makes them take hours to think, change the line in the config manually to 1 for now. I also recommend changing the builder block placement delay back down to default from 250.
> 
> Minecolonies serverconfig is in your world folder.

This has actually resolved the problem perfect .

**Comment by BeadiestSkyBlue** [comment]
the supplied resolution didn't work for me
