### ISSUE TITLE
FTB Utilities missing?

### ISSUE THREAD

**Issue by KappaKonchu** [AllTheMods/ATM-8#603]
Hey guys,

I'm trying to disable /back and /home on my server. Normaly I was able to access it ingame or via the serverfiles. I can't seem to find FTB Utilities at all and I have not found the mod that is responsible for these commands without it. can you guys help me?

**Comment by Mitchell5200** [comment]
the config is `\world\serverconfig\ftbessentials.snbt`

**Comment by KappaKonchu** [comment]
Thank you very much! 

> the config is `\world\serverconfig\ftbessentials.snbt`
