### ISSUE TITLE
Recipes removed.

### ISSUE THREAD

**Issue by Skrutten1** [AllTheMods/ATM-8#604]
I have a server on atm8 and some recipes like invar plate i cant even see even though i can make it if i know the recipe. I dont understand why this is happening. It is very frustrating not being able to open and see the recipe on alot of things.

On singleplayer everything is normal but on server it is bugged. Could it be kubejs? Its the only thing i saw that could do anything.
I got the server "pack" from curseforge/overwolf or whatever its called.

**Comment by Sunshine-Lolipop** [comment]
I am having this issue as well. Many of the recipes that are added by AllTheOres are not visible in JEI for me, however they still work.
