### ISSUE TITLE
NBT cleared from Pure Ores in Vibranium Furnace

### ISSUE THREAD

**Issue by MindBrain27** [AllTheMods/ATM-8#610]
When putting Pure Ore Chunks (Elementalcraft) in a Vibranium Furnace (with auto split enabled) all of them are converted into blank Pure Ore, only when the auto split feature happens in the furnace.

Happens with all ore types (that I tested) as long as the furnace auto splits them, the first slot will be fine but the rest will be ruined.

Have not tried with other furnace types but I image any that auto split will do the same.

**Comment by Dragonseel** [comment]
I can confirm this happens reliably to me too, on ATM8 version 1.0.9 with the Unobtainium Furnace in Factory mode. When auto-splitting the NBT is cleared ant Pure Ore is created which is useless in game. A vanilla furnace, and a Iron Furnace without factory upgrade both handled the Inert Pure Ore Chunks correctly.

**Comment by Mitchell5200** [comment]
now tracked at https://github.com/Qelifern/IronFurnaces/issues/147
