### ISSUE TITLE
FTBRanks not showing title in chat

### ISSUE THREAD

**Issue by KullGames** [AllTheMods/ATM-8#618]
Hi team! 

The ftbranks mod (ftb-ranks-forge-1902.1.11-build.46) has a missing feature of the chat not showing the players rank.  This was patched in ftb-ranks-forge-1902.1.13-build.65.jar

`fix: make rank-based message text decoration work properly on 1.19.2 - Des Herriott`

Could the ftbranks mod be updated to 1.13+ (https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge/files/4143404) in the next patch as it cannot be deployed server side only?

Thanks!
KullGames

**Comment by Mitchell5200** [comment]
In the previous updates we could not, as another mod was holding forge back, that mod has updated, and as such forge will be updated along with any other mods that have updates or were being held back, the plan for release is sometime within the next 24 hours or so

**Comment by KullGames** [comment]
baller... thanks!
