### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by G4ming69** [AllTheMods/ATM-8#619]
[crash-2023-01-08_08.34.49-server.txt](https://github.com/AllTheMods/ATM-8/files/10367919/crash-2023-01-08_08.34.49-server.txt)

**Comment by Eld0r** [comment]
So when in All the Mods 8 v1.0.7 with forge-43.1.55...
a Bat in a cave collides with blood stains...
The game will crash?
huh...

**Comment by G4ming69** [comment]
yeah, unfortunately i have no plan, i play the game normally, all of a sudden the game freezes completely and it crashes.
Forge version: 43.1.55
ATM Version: 1.0.7

**Comment by G4ming69** [comment]
is this a feature?
