### ISSUE TITLE
ATM8 randomly crashing every 30 minutes or so

### ISSUE THREAD

**Issue by queijoz** [AllTheMods/ATM-8#624]
I think my world started crashing after making a Phytogenic Insulator from Thermal Series. Also, after making a farm with a few more Phytogenics it looks like that crash happens more frequently, but I'm not sure.
My Phytogenics were running Mystical Agriculture seeds with Phyto-gro as catalyzer, each one of them had the augments Cyclical Reprocessing, Resonant Parts and 2x Auxiliary Reception Coil.
[crash-2023-01-08_23.38.43-server.txt](https://github.com/AllTheMods/ATM-8/files/10370067/crash-2023-01-08_23.38.43-server.txt)

**Comment by Eld0r** [comment]
again the evilcraft:blood_splash
there is another problem with a crash when a bat collides with blood stains: [#619](https://github.com/AllTheMods/ATM-8/issues/619)
