### ISSUE TITLE
Game crashes almost instantly on bootup

### ISSUE THREAD

**Issue by Alle-thebug** [AllTheMods/ATM-8#628]
So here I am, at the issues of ATM8 as a last resort, I've tried everything I could find on the internet but nothing seems to work. Now I'm asking for your help, the MC launcher says The game crashed whilst rendering overlay Error:com.electronwill.nightconfig.core.io.WritingException: An I/O error occured I will of course upload the crash report. Could you please help me, I've almost pulled my hair out trying to solve this problem.
[crash-2023-01-09_18.27.26-client.txt](https://github.com/AllTheMods/ATM-8/files/10375737/crash-2023-01-09_18.27.26-client.txt)

**Comment by Alle-thebug** [comment]
Btw the caused by doesn't really show anything, I've tried removing the file it says in can't access but when I do that it just jumps to another file, I've even tried to remove the entire configs folder

**Comment by SerenityFire** [comment]
Did you run the forge-1.19.2-xxx-installer.jar in your directory?

**Comment by Mitchell5200** [comment]
```Caused by: java.nio.file.FileSystemException: C:\CurseForge\Instances\All the Mods 8 - ATM8\config\tombstone-common.toml: The process cannot access the file because it is being used by another process```
that usually means some other program is accessing the files at the same time as your game is, ensure you have no other java apps running at the same time

**Comment by SerenityFire** [comment]
Also when you run the installer he ask you what you want to install. For the server you need to select "Install server" and then you choose you server install location. Mine is directly on my C: drive. This is if you a running your server on a Windows machine.

![forge_installer](https://user-images.githubusercontent.com/51133457/211835339-5dd396d2-71d2-46ea-9ba3-ebcb92d17193.PNG)

Like Mitchell says, there is an other program accessing your files. I had a similar problem back when I installed my server on my Desktop and Microsoft OneDrive synced the files. My server crashed and could not run properly. Maybe it can be a sync or cloud problem?

Maybe a third option to check, if you have Windows Security Ransomeware protection activated. This can also sometimes cause problems with fast changing files. Deactivate only the Ransomeware protection.

**Comment by Alle-thebug** [comment]
Thanks alot for the help, it worked to disable the realtime ransomware protection, the only thing I wonder is why don't more people have this issue if it's related to windows defender?

**Comment by SerenityFire** [comment]
> Thanks alot for the help, it worked to disable the realtime ransomware protection, the only thing I wonder is why don't more people have this issue if it's related to windows defender?

The ransomeware protection is not always on by default.

**Comment by Alle-thebug** [comment]
Ohh I see

**Comment by Alle-thebug** [comment]
Wait, if ur still here, I can't get into a world, it just freezes and then whitescreens before entirely crashing

**Comment by SerenityFire** [comment]
Do you have an error message on your server? Sometimes it can takes a few moments for loading the world. 
Sometimes I need to click my server cmd window and type something in because the server is freezing. I don't know how to prevent this atm.

**Comment by Alle-thebug** [comment]
Well I tried to do it in regular single player and it didn't work, I can't remember the exact code but it started with a bunch of eights and said allocating more ram may fix the issue but I already got 16GBs of ram allocated

**Comment by Alle-thebug** [comment]
Wait a minute,
[crash-2023-01-11_16.30.58-server.txt](https://github.com/AllTheMods/ATM-8/files/10394118/crash-2023-01-11_16.30.58-server.txt)
 I checked the logs and it says about the same as before, com.electronwill.nightconfig.core.io.WritingException: An I/O error occured but instead of rendering head overlay it says exception in server tick loop. It also says that there is a server file in use

**Comment by SerenityFire** [comment]
Check if you have double files in your serverconfig folder or a corrupted one. Maybe replace them all with the new ones in the zip from the mod pack. 

The Ram allocation is done in the user_jvm_args.txt file. Don't allocate all the Ram from your server to the Minecraft server. So if you have 16G give mc 12G (xmx) and xms 8G or 10G.
But I don't think that it is the problem.

Do you run your server and client on the same machine?

**Comment by Alle-thebug** [comment]
I have the server and the client on the same machine

**Comment by SerenityFire** [comment]
Check the task manager to see if your ram is maxed out.

**Comment by Alle-thebug** [comment]
No it's not maxed out, I have about 50% free when everything is allocated

**Comment by Alle-thebug** [comment]
Well I don't have any other antivirus program

**Comment by Alle-thebug** [comment]
Ye I have the 1.0.8 version

**Comment by SerenityFire** [comment]
Try to set up a new folder with a new instance of the server, extracted and installed from the zip file. Don't copy the files. Maybe some files are corrupted because of the ransomeware from earlier. And check if the same problem occurs.

**Comment by Alle-thebug** [comment]
Seems to be working now, just needed to remove radium which I had aciidentally added to both mods folders. btw dont use it it makes the game crash

**Comment by SerenityFire** [comment]
> Seems to be working now, just needed to remove radium which I had aciidentally added to both mods folders. btw dont use it it makes the game crash

ah ^^ yeah you have to be carefully with added mods.

**Comment by Alle-thebug** [comment]
Ye I noticed that lmao it's very annoying when such things happen thank god that you can sort by time modified

**Comment by Alle-thebug** [comment]
So ehum hear me out, the server has now started booting me for weird reasons, like kicking me for having the wrong mystical aggriculture version although I have the same

**Comment by Alle-thebug** [comment]
So basically this is what happens if ur still interested in helping me lol
![Minecraft_ 1 19 2 1_11_2023 9_14_59 PM](https://user-images.githubusercontent.com/81678497/211909028-1e5f33ca-b218-42de-8c12-07adb05fae02.png)
And here u have a log 
[latest.log](https://github.com/AllTheMods/ATM-8/files/10395712/latest.log)

**Comment by SerenityFire** [comment]
Yes I try my best.
Can you check in the Server Mods Folder if you have double mods files there. Always check the version. If there a double ones, delete the old ones.

If you have still problems, maybe open a new threat with the new problem, so also other people can help :)

**Comment by Alle-thebug** [comment]
Oh okay sure will, for now I've resorted to playing single player which actually works now

**Comment by Alle-thebug** [comment]
Btw in the single player world the ftb quests don't generate, the questbook is just empty. And also I tried to go back and just reinstall the entire modpack, then it didn't work again but once I restored it to what I had before it worked again but with some issues like the server one and the quests thingy

**Comment by Alle-thebug** [comment]
I don't have the config files for the ftb quests, do you know where I can get them?
