### ISSUE TITLE
Crashes Game when mining any chest

### ISSUE THREAD

**Issue by CyanceMachine** [AllTheMods/ATM-8#63]
My friends and I noticed that if you try to mine a chest it crashes your game and anyone nearby

**Comment by MoeHunt3r** [comment]
Tried to reproduce the crash. 

Found out that the crash only happens with chestes in generated villages (from minecolonies?). 
Crashlog: [Log](https://paste.ee/p/vL1LQ)

ATM Version:  0.0.15

**Comment by Henning-K** [comment]
> Found out that the crash only happens with chests in generated villages (from minecolonies?). Crashlog: [Log](https://paste.ee/p/vL1LQ)

For me the crash consistently happened from some point on with chests I placed myself (also Version 0.0.15).

**Comment by papillo12** [comment]
> he crash only happens with chests in generated villages (fr

hi, i don't use the atm modpack, but i was seeing if anyone else has the same bug as me and i can confirm that the bug causes it create

**Comment by kulzae** [comment]
game crashes for me and others on my server when breaking minecraft chests (ones from mods do not cause the crash)

**Comment by Glysterine** [comment]
I had the same issue.  Modded chests work fine but I converted a jungle chest to a standard minecraft chest (placed jungle chest in crafting table) and the created vanilla chest is not able to be picked back up after placing.  I have tried punching, mining with pickaxe, and chopping with axe.  All methods crash the game.

**Comment by Ferro-Giconi** [comment]
I was able to reproduce this bug consistently by trying to break a vanilla chest that I placed. I also had a friend try breaking it and it crashed both of us while he tried to break it. It seems to only be vanilla chests. I only tried a couple random modded chests and neither caused a crash. Double or single vanilla chests both do it. Going into creative and breaking the chest doesn't trigger the crash.

**Comment by ztx-lyghters** [comment]
I have the same problem, trying to break any vanilla chest crashes the game. But not from the game start, which is weird. I have to play for some time, then it starts happening. Tried in different worlds, tried to switch java from 17 to 19. I'm on Void Linux. I'll attach the log.
[hs_err_pid3394.log](https://github.com/AllTheMods/ATM-8/files/9738685/hs_err_pid3394.log)

**Comment by Fairweather-Furry** [comment]
Can confirm that this crash is still happening with vanilla chests in the recent modpack update 0.0.16, though the changelog doesn't claim to fix it.

**Comment by ztx-lyghters** [comment]
So, uh... Turns out it's not a ATM problem at all, at least for me. It was **Create** in my case, which I've added myself, it not a part of ATM yet

**Comment by mstefan21** [comment]
@whatthedrunk can be closed, last change of config in 0.1.3 fixed this problem
