### ISSUE TITLE
My brother cannot connect through LAN. 

### ISSUE THREAD

**Issue by JoeMamma421** [AllTheMods/ATM-8#631]
It says "player joined" and then "player left" instantly. The new ATM8 update just released and the problem is still persistent. I havent found ANY solutions online and anything ive tried myself hasent worked either. Please help!

**Comment by BastionNtB** [comment]
Need some details.

Dedicated server host? Or singleplayer opened to LAN? OS of both of you? version of ATM8?

**Comment by AfkUserMC** [comment]
this is a known issue.

**Comment by Mitchell5200** [comment]
Duplicate of #23 , Closing
