### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by keeootee** [AllTheMods/ATM-8#633]
https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod - adds working cars and things like gas stations. great addition to city builds

https://www.curseforge.com/minecraft/mc-mods/litematica - super helpful for building, adds layouts of builds and material lists

**Comment by Mitchell5200** [comment]
please use #3 for mod suggestions, not new posts.
and litematica is a fabric mod, we will not be adding it
