### ISSUE TITLE
Game crashes after typing in server ip address

### ISSUE THREAD

**Issue by MarcelskyXD** [AllTheMods/ATM-8#635]
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_5661_(net.minecraft.network.chat.Component, boolean)" because "net.minecraft.client.Minecraft.m_91087_().f_91074_" is null

**Comment by Joshbr32** [comment]
I noticed for me that my game crashes when I type the "v" in server. I just didn't type the v. default name is 'Minecraft Server', and I changed it to 'Josh Server' by not deleting the original "server" just the "minecraft"

**Comment by MarcelskyXD** [comment]
> I noticed for me that my game crashes when I type the "v" in server. I just didn't type the v. default name is 'Minecraft Server', and I changed it to 'Josh Server' by not deleting the original "server" just the "minecraft"

Turns out its a bug in some mod, i dont remember the name of it now

**Comment by Mitchell5200** [comment]
Supplementaries, it's quiver keybind
