### ISSUE TITLE
Duplicate Quest

### ISSUE THREAD

**Issue by AfkUserMC** [AllTheMods/ATM-8#637]
There are 2 quests for killing the warden:
Kill The Warden [Bounty Board]
Kill The Warden [Getting Started: Part 2]

**Comment by alfredggttv** [comment]
This is intentional!

The Getting Started questline is meant to be for those who want a little more help along the way, or just want to complete everything. The Bounty Board is great for anyone who is playing the pack, as it gives a little extra resources and helps people along their progression!
