### ISSUE TITLE
Refined Storage Issue

### ISSUE THREAD

**Issue by Zoidey** [AllTheMods/ATM-8#640]
Has anyone else had the issue where you log in one day and all your Refined Storage Disks and Pattens have mysteriously disappeared after a restart? This has happened to me and even though I back up the world regularly I don't know exactly what day this happened. I regularly backup via the server and also regularly with simple backups mod but since that only keeps a few backups to save SSD space it probably deleted the backup that I could have used to recover everything in my Refined Storage system that still had the disks.

I know this was a common problem with Refined Storage two or three years ago as it happened to me and I stopped using the mod then but started using it as I figured it's been literally years so surely they have fixed that issue, but clearly not.

It's left a bad taste in my mouth and has kinda put me off ATM 8 for a bit as I lost a lot of stuff and have to start over trying to replace it. Some of it will be easy enough to do others not so much as it was like six 64k drives, four of which were full or close to being full. It would be quite as bad if I had been playing for a while as a soft restart might have been a nice fresh challenge but when I've been playing for a few weeks it's rather annoying and disappointing. Not the end of the world but it's disheartening to lose so much stuff you've been working hard on gathering to just lose it in a blink of an eye after a server restart.

**Comment by SerenityFire** [comment]
Hi, 
sorry to hear that.
Did you lose anything else?

I had the same issue that all my Disks were gone. 
I know from where my bug came from. My Server made a Windows Update when I was still on the server, so after the restart, my User Profile in the world folder was corrupted. I did not only lost all my disks from RF but also my Backback an everything else on me. 
I think that RF is saving the disks in the profile data but I'm not 100% sure.

I had no backup back then, so I had only some chests and barrels left.
I use now FTBBackups with polylib. It's working fine and I have regular Backups now.

I hope they will add a Backup soluntion to the pack.

**Comment by Zoidey** [comment]
Just lost all the Disks and the Patterns, Patterns I couldn't care less about.
No idea where they save the data also, I wish now that I just stuck to Applied Energistics as that mod is more reliable, not as cheap and easy to use compared to Refined Storage but it's more reliable.

When I get the heart to get back into it I'll move on to gearing up to switch to AE, I was able to before but not now sadly. Ah well, it'll give me something to do at least.

**Comment by fjsventura** [comment]
I had the same issue twice already. Fully netherite crafters that just went puff..... empty

**Comment by Wadimich** [comment]
I've also encountered this bug. Lost some patterns in a few crafters. After a careful [log](https://pastebin.com/ajg2xDvK) reading, found probable reason.

This might happen on server load and caused by Fast Suite mod, which does some optimization. I think, this should be configured somehow to stop doing such optimization at least for Refined Storage? Or at least removing this mod "for future time"...?

**Comment by jmyoung** [comment]
I've had this happen numerous times - both with Netherite crafters, and also with the RS multiblock crafter thing.  It's particularly frustrating because I don't usually find out until I've been playing for a little, then I have to restore from backup :|

**Comment by Wadimich** [comment]
> I've had this happen numerous times - both with Netherite crafters, and also with the RS multiblock crafter thing. It's particularly frustrating because I don't usually find out until I've been playing for a little, then I have to restore from backup :|

I still testing, but i think i fixed issue. I just need to play a few more days to make sure it is fixed.

**Comment by siqNezz1337** [comment]
experienced the same issue today. i have 3 netherite-crafters in total connected to my main system just to split patterns into categories, unfortunately the one with the most patterns inside of it got "cleared". i still have my backpack and all the other patterns. myself and a friend of mine are playing on a private server that is hosted on g-portal, his crafters are still fine and nothing went missing so far.

@Wadimich how is your testing going so far?

**Comment by Wadimich** [comment]
@jmyoung @siqNezz1337 @fjsventura well, after playing a while i've increased my amount of crafters, none of them lost any templates.

I still not sure, if this is real fix, but you can try.

For singleplayer you need to open modpack folder/config and file `fastcuite.cfg`. For servers - same thing is done in server config folder.

In this file you need to add line `refinedstorage:pattern` in `S:"Single Threaded Recipe Types"` config value

So, in my case it just look like so
```
S:"Single Threaded Recipe Types" <
        refinedstorage:pattern
     >
```

This might decrease performance a little, but on my side nothing changed, maybe on big servers with big bases it may be noticed.

Hope this helps!

Also - this is not for topic, but i was using Functional Storage armory cabinet and lost ALL items in it for somehow, even enchantent books, while it was connected to RS system.

**Comment by Wadimich** [comment]
Well, i still lost all recipes in one of my crafters, so this does not help...

**Comment by LordSteppenwolf** [comment]
I have experienced this same issue 3 times since upgrading to 1.0.19b 2 weeks ago.
