### ISSUE TITLE
Platinum ore when crushed makes an unusable Crushed Platinum Ore

### ISSUE THREAD

**Issue by TheTeams** [AllTheMods/ATM-8#643]
Platinum ore from AllTheOres when crushed in the Create crusher makes unusable Crushed Platinum Ore (listed as from Create). Can't be smelted or used in any crafting recipe to become usable.

Playing on All the mods 8 v 1.0.8 through curseforge launcher
![image](https://user-images.githubusercontent.com/17695850/211801271-5671040f-b1d1-4d71-bf8d-8a1e836b4ef6.png)
![image](https://user-images.githubusercontent.com/17695850/211801360-ab00ffd6-2b75-4061-b4e5-dd67cea42d0e.png)

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
