### ISSUE TITLE
[1.0.8] Applied Energistics 2 - Quest

### ISSUE THREAD

**Issue by curacerto** [AllTheMods/ATM-8#647]
The quest to obtain the Color Applicator keeps with the status "uncompleted dependencies" even when you have all the dependencies ready.

You are not able to complete this quest even after you complete all the steps before it.

![image](https://user-images.githubusercontent.com/115930912/211918778-e8168cca-6b27-47cf-b77b-4570314a78d8.png)

**Comment by curacerto** [comment]
No issue at all. I should check the dependencies of the quest...

![image](https://user-images.githubusercontent.com/115930912/211921636-dc737918-5694-425a-888c-c5cd0241f6ac.png)

**Comment by AfkUserMC** [comment]
lol

**Comment by curacerto** [comment]
Sorry about that
