### ISSUE TITLE
Game/Server Crash with Structure Compass

### ISSUE THREAD

**Issue by AfkUserMC** [AllTheMods/ATM-8#650]
Sometimes when using the structure compass on a server, the server crashes.

**Comment by trueangryyeti** [comment]
Myself and everyone on my server has the same issue.

**Comment by CodeEventHorizon** [comment]
Once I use Structure Compass in my singleplayer world, let's say to find ctov large desert village, the game sort of freezes in terms of interacting with objects, I'm not able to lay in bed, or teleport using JEI map and it displays "Waiting for server", the only thing that fixes it is restarting the game. It would be nice to add the limit to the search algorithm it is using, like maximum number of samples, like the nature's compass does it.
