### ISSUE TITLE
Charm of Keeping III quest gives 100 xp levels, not 100 xp

### ISSUE THREAD

**Issue by FranticShooter** [AllTheMods/ATM-8#651]
Fairly simple issue to fix, though I was dying laughing once we realized how many levels we had collectively. It seems to be just a simple input error, if you need any additional information let me know I'll gladly provide more.

**Comment by alfredggttv** [comment]
Ah! Simple misclick on my part. This should be fixed in a later version! Thank you for letting me know!

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
