### ISSUE TITLE
Quest "fancy Tables" from Ars Nouveau isn´t progressing

### ISSUE THREAD

**Issue by DeBalZac** [AllTheMods/ATM-8#654]
Hello Guys!
I am new to ATM and I love it!
However, i do have a problem -> My Quest "Fancy Tables" does not progress whatsoever. I already built like 20 of them and it still says that i only made 5
Is there already a fix for that?
Thank you in advance!

**Comment by alfredggttv** [comment]
Taking a look at this now. I cannot recreate this issue. You must have all 8 in your inventory at the same time to complete the quest, and the previous quest must be completed before it will track.

Just covering the basics here! Can you screenshot yourself with the 8 Arcane Pedestals in your inventory (scrolling over it to check exact item) and then showing the quest not completing?

**Comment by DeBalZac** [comment]
Hello Alfred!
Thank you very much for your response.
I actually didn´t have all 8 Pedestals in my Inventory at the same time, because i built 3 of them first and 5 afterwards. 
I picked them all up and now the quest is finished! 
Once again, thank you very much :)
Sorry for the inconvinience and I wish you a nice day.

Kind regards
