### ISSUE TITLE
Eccentric Tome lost during crafting

### ISSUE THREAD

**Issue by z-Tau** [AllTheMods/ATM-8#658]
I had an eccentric tome which I'd added a bunch of books & manuals to, and decided to upgrade the cooking for blockheads recipe book to the crafting book.  This involves crafting it with some diamonds and crafting tables.  So I switched the tome to the recipe book and crafted it.

Now the tome appears to have been lost.  Left clicking with the new book in the air does not return it back to the tome as expected, it seems to be just a regular book now.

**Comment by enigmaquip** [comment]
you should always remove a book from the tome if you need to use it for anything besides reading even including tossing botania's book in the alfheim portal

**Comment by z-Tau** [comment]
Why would it ever occur to anyone to need to do that without clear in-game messaging to be wary of such bugs?  Either warnings should be added or the mod should be removed from the pack until it's fixed.

**Comment by Vashta** [comment]
> 

how do i remove books from it?

**Comment by z-Tau** [comment]
You can press shift-q to drop the current book.

**Comment by Vashta** [comment]
thanks wish it said that somewhere in game

**Comment by Mitchell5200** [comment]
Now documented in the quest section "Tips and Tricks"
