### ISSUE TITLE
server wont launch

### ISSUE THREAD

**Issue by shylarest** [AllTheMods/ATM-8#659]
Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file C:\Users\mixed\OneDrive\Desktop\Server-Files-1.0.8\config\silentgear-common.toml is not correct. Correcting
this message keeps spaming.... please help

**Comment by Mitchell5200** [comment]
remove your server from Onedrive, and then try again
