### ISSUE TITLE
Create causing crash on block break

### ISSUE THREAD

**Issue by DestinedToSuffer** [AllTheMods/ATM-8#66]
Placed a create block down and apon interaction the game crashes. No crash logs.

**Comment by treg2** [comment]
Same Problem here. I have crashed a couple of times trying to break Create Shafts/Cogwheels, but was able to reload the world.
Today I accidentally tried breaking a windmill bearing and now am no longer to load the world as my game crashes when trying to join the world.

Error Log when I broke the windmill bearing:
[hs_err_pid19988.log](https://github.com/AllTheMods/ATM-8/files/9693179/hs_err_pid19988.log)

Error Log when trying to join the world afterwards:
[hs_err_pid17344.log](https://github.com/AllTheMods/ATM-8/files/9693180/hs_err_pid17344.log)

When breaking Create Blocks with a Wrench the game does not crash.
It only crashes when you try to mine Create Blocks like any other block in the game

**Comment by lewnewby** [comment]
Ran into the same thing

**Comment by mstefan21** [comment]
Same Problem here. I have crashed a couple of times trying to break any Create block, but was able to reload the world.

**Comment by lewnewby** [comment]
Like @treg2  said, use the wrench and right click/Sneak Right Click to recover the block as a work around.

**Comment by mstefan21** [comment]
@lewnewby thank you for the info I missed the last part about the wrench.

I discover a new problem with that. After connecting Andesite Funnel to the chest and trying to break the chest also crash the game without crash logs. If I remove the Andesite Funnel, trying to break the chest also crashes the game.

**Comment by mstefan21** [comment]
Work around for destroy this chest is use for example tiny tnt

**Comment by mstefan21** [comment]
@whatthedrunk can be closed, last change of config in 0.1.3 fixed this problem
