### ISSUE TITLE
Ender chest unable to have importer attached directly

### ISSUE THREAD

**Issue by dazedpro** [AllTheMods/ATM-8#661]
Ender chest (not vanilla) doesn't seem to let you attach an RS importer directly onto it. Instead, you have to put an importer next to it, and reorient it with the RS wrench to attach it to the ender chest. 

See below for an example:
https://gyazo.com/75fed2ed0d63315e4e5fa026df963091

**Comment by James103** [comment]
Actually, **no block** can be placed directly next to an ender chest by shift-clicking on one of its sides.

**Comment by Mitchell5200** [comment]
please forward to the mod dev --> https://github.com/ShetiPhian/Localizations-and-Issues/issues
