### ISSUE TITLE
No Gaia Spirit Seeds Recipe

### ISSUE THREAD

**Issue by dekzgh** [AllTheMods/ATM-8#662]
With Botania being added, the mystical aggregations Gaia Spirit seeds is missing a recipe

**Comment by enigmaquip** [comment]
not missing, purposefully disabled

**Comment by dekzgh** [comment]
Ah, understood.On Jan 13, 2023, at 8:06 AM, enigmaquip ***@***.***> wrote:﻿
not missing, purposefully disabled
