### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by MOH1412** [AllTheMods/ATM-8#667]
[crash-2023-01-13_09.16.44-server.txt](https://github.com/AllTheMods/ATM-8/files/10416894/crash-2023-01-13_09.16.44-server.txt)

**Comment by ch-ckmate** [comment]
Hi, i encountered the same probblem. Have you resolved?
[crash-2023-01-13_13.26.33-server.txt](https://github.com/AllTheMods/ATM-8/files/10419722/crash-2023-01-13_13.26.33-server.txt)

**Comment by MOH1412** [comment]
maybe it related to refined storage mod , my friend using AE2 and didn't have any problem.

**Comment by ch-ckmate** [comment]
Thanks for the info, how you recovered the world? Removed the mod?
