### ISSUE TITLE
AJUDA 

### ISSUE THREAD

**Issue by pedroboyy** [AllTheMods/ATM-8#668]
Olá queria ajuda para tirar umas escrita que aparece perto do braço do persogem, esse e o link do video pra entender https://youtu.be/rNHrRVXpdtU
![Java-runtime-gamma Screenshot 2023 01 14 - 14 48 29 29](https://user-images.githubusercontent.com/122692837/212487730-c28be40e-a67c-49ec-b7e1-9849d3681639.png)

**Comment by enigmaquip** [comment]
https://minecraft.fandom.com/wiki/Subtitles
