### ISSUE TITLE
AE2 + industrial foregoing bug?

### ISSUE THREAD

**Issue by LegionPrime97** [AllTheMods/ATM-8#670]
whenever i use my Wireless crafting terminal (i'll call it WCT) and craft something from industrial foregoing and the advanced machine frames are(not sure if the other machine frames from industrial foregoing do the same) to be put back in the system afterward 1 of 2 scenarios happen, the game instantly crashes and when i reboot the game, the WCT stops working entirely doesn't matter even if it has full battery, forcing me to create a completely new one for it to work or 2 it doesn't crash the game but again just does not work anymore unless i craft a new one from scratch.. :/

**Comment by TomasGnG** [comment]
This bug is already known and was fixed in the IE mod (said the author of IE). 
https://github.com/BluSunrize/ImmersiveEngineering/issues/5527
