### ISSUE TITLE
Game Crashes when going to The End.

### ISSUE THREAD

**Issue by HeavyDeception** [AllTheMods/ATM-8#673]
I can seem to load the end every time into the portal it will have me floating for a few seconds then my items will load in and it crashes.

[This is the crash log.](https://puu.sh/JwDXV/77008d8601.log)

[latest.log](https://github.com/AllTheMods/ATM-8/files/10419377/latest.log)

**Comment by HeavyDeception** [comment]
This problem was fixed in the discord server with the help of Mitchell52 than you for the help Cause was a corrupted world.

**Comment by PinkerTee** [comment]
How did you fix that

**Comment by HeavyDeception** [comment]
@PinkerTee 
It was me being dumb, one of the backpacks has a void upgrade in it and I just gave it a black list with backpacks added to it. Wish the void only worked with the backpack it was in.

**Comment by HeavyDeception** [comment]
> How did you fix

I can't remember how we fixed it, I think it was something with the mods and a new world had to be made. but I will try looking it up.
