### ISSUE TITLE
Soul Steel bee from spirit mod

### ISSUE THREAD

**Issue by shubham8550** [AllTheMods/ATM-8#678]
i was trying to make soul steel bee 
but pedestal consumed items and performs animation but bee doesn't gets spawn

tried these twice

**Comment by duhduhdana** [comment]
can confirm this is happening for me as well on atm 8 patreon server

**Comment by Azeuz9** [comment]
Seems like the spirit mod is having a bunch of issues, soul steel block cant be made either, only ingots.

**Comment by Anirra** [comment]
I'm also having this problem, can't seem to get the Spirit Bee either.

**Comment by Kulrock** [comment]
> i was able to automate making blocks just recently, i'd double check azeuz9, make sure youre using compressed blocks

That does not answer the question!

**Comment by duhduhdana** [comment]
Don't be rude, if you read my comment properly you can see I'm replying to Azeuz9 who mentions not being able to soul steel blocks ...

**Comment by gtokarz** [comment]
Make sure crude gem has at least 1 soul of bee in it

**Comment by shubham8550** [comment]
> Make sure crude gem has at least 1 soul of bee in it

it worked for you?

**Comment by Kulrock** [comment]
> Don't be rude, if you read my comment properly you can see I'm replying to Azeuz9 who mentions not being able to soul steel blocks ...

I apologize mate, It was rude and there is never any need to be. I knew you were replying to Azeus9 but I was a lil bit drunk when I wrote that and unfortunately had turned me into a rude twat :)

**Comment by Kulrock** [comment]
> Make sure crude gem has at least 1 soul of bee in it

Unfortunately this still did not work for me, I've ended up just spawning in the be as I've lost enough resources trying to make it as per the recipe.

**Comment by GohanSenior** [comment]
Hi, **they all spawned**. Go check on **X:0, Y:0, Z:0**.
It was that for me.

**Comment by shubham8550** [comment]
> Hi, **they all spawned**. Go check on **X:0, Y:0, Z:0**. It was that for me.

yeeey thanks i also confirm it , they are spawning at 0 0 0

i guass I'll close this issue then?
