### ISSUE TITLE
Botania - Livingwood Twig recipe

### ISSUE THREAD

**Issue by Vortiporius** [AllTheMods/ATM-8#685]
The recipe for Livingwood Twigs shown in the JEI doesn't work, it instead produces regular sticks.

**Comment by enigmaquip** [comment]
You can use polymorph to swap over from the sticks to twigs
![image](https://user-images.githubusercontent.com/6134440/212751801-dad4452f-1860-42d9-88ae-461326a7d242.png)
make sure you are actually using logs and not planks

I will tweak the recipes though for future versions

**Comment by Vortiporius** [comment]
Thank you very much! I always use the AE2 wireless crafting terminal where that button doesn't show, so I didn't even notice that button existed!
