### ISSUE TITLE
ATM8 Server issues, minecolonies etc

### ISSUE THREAD

**Issue by Ragecinemas** [AllTheMods/ATM-8#686]
Lots of mods so nobody expects them to mesh 100% but it seems quark and a few other mods mess up super important core mods. I cant get a builders hut to be built due to chest always being made as quark mod chests regardless of wood. Framed oak planks are not seen by the builders either. Cannot create back packs due to quark chests. These are the handful of things already run into in just the first two days of the server. Trying to work around them but really puts a hinder on development of the world having limited storage and no use for minecolonies. Hope theres a fix shortly or a work around, any suggestions welcome.
(1.19.2 version 1.0.8)

**Comment by enigmaquip** [comment]
quark's "textured" chests can be put back into the crafting grid to be turned into a vanilla chest, I've also added in recipes for the next release that every plank not having a textured chest will craft into a vanilla chest as well. Sophisticated Backpacks with accept any wooden chest, including the quark ones. As will storage drawers.
re: framed oak planks, you have to be very careful with domum ornamentum (a sister mod made by the minecolonies team) that you build them in the architect's cutter exactly the way the builder expects to see them. You can see their setup in the requirements and the stats/info need to match exactly
