### ISSUE TITLE
Mekanism > "Tier 4 Ore Processing Factory" broken image

### ISSUE THREAD

**Issue by CrossOnDiscord** [AllTheMods/ATM-8#690]
![image](https://user-images.githubusercontent.com/105819281/212889594-c3d10047-474b-4e55-8345-a012fd688031.png)
Titles says it all, the image for the Tier 4 Ore Processing Factory is a broken texture.

**Comment by alfredggttv** [comment]
This was a bug whenever we first started making quests for ATM8. Pictures weren't working at all in the questbook, so this is a good sign that they are attempting to work again! I'll see if I can fix this up for a future update. Thank you for letting us know!

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
