### ISSUE TITLE
disableElytraMovementCheck true not effecting modes of movement such as Jetpacks brooms or running shoes.

### ISSUE THREAD

**Issue by Bassat273** [AllTheMods/ATM-8#695]
With so many means to get to ludicrous speed the disableElytraMovementCheck true is only effecting Elytra, players not using them in conjunction with jetpacks or traveling with hexeri brooms at the speed of chunk as well as on foot are being teleported every few blocks and server side the console is filling with spam warnings. asking the server host to correct the speed trap was a fruitless attempt because its a minecraft anti cheat done by Mojang. Is there something the Mod Gods behind this wonderful Pack can do to let us break the chunk barrier and forever ban the Teleportation rubber-band we experience? 

"Mahogany Broom (vehicle of Playername) moved too quickly!" and "playername moved too quickly!" are both examples of the warning strings being spammed in the console of the server.

**Comment by derrickmehaffy** [comment]
As a server-side mod, I believe this should be able to handle it: https://www.curseforge.com/minecraft/mc-mods/too-fast

**Comment by Bassat273** [comment]
You're the Goat! Thank you so much!

**Comment by Bassat273** [comment]
Great fix but it doesn't actually work on servers running 1.19.2
