### ISSUE TITLE
Cyclic Item User not working in compact machines

### ISSUE THREAD

**Issue by ACampingPanda** [AllTheMods/ATM-8#701]
As the title suggests, I added cyclic to the pack and the Item User is not working in my compact machines. It works just fine in the overworld. I even loaded up a few creative worlds and it works inside compact machines in those too. Any ideas will be greatly appreciated.

Also, this is my first time really using Github so if this isn't the place, I apologize

**Comment by ViRb3** [comment]
Sadly unless Cyclic is added to the modpack, I don't see anyone being able to provide support for this issue.

**Comment by taj1994** [comment]
The modpack devs have said Cyclic will never be added to ATM 8 (and I'd assume it likely won't be in any future ATM packs either). It just causes too many issues

That being said, I'd report it to the [Cyclic Github](https://github.com/Lothrazar/Cyclic/issues), and maybe the [Compact Machines Github](https://github.com/compactmods/compactmachines/issues)
