### ISSUE TITLE
[ATM-8 v1.0.8] AE2 Terminal and Mekanism QIO Terminal both cannot display a sea of items

### ISSUE THREAD

**Issue by Killyice** [AllTheMods/ATM-8#702]
[Environment]:
Env: Remote Server & Multiplayer
OS: Win10
Ver: ATM-1.0.8

[Details]:
I've  stored about 900K items in 5 "256k ME Disk Drive (Deep Item Storage Disk)" of **AE2 Things**. When I open the terminal now, none of the stored items show up. Except for a very few items transferred via the "ME Input Bus". Other players also find this error.

I thought it's the mistake of this disk. So I craft 4 "64k ME Disk Drives (Deep ...)" and export from 256k to them.
Fine. The terminal now display all items.

After that, I also try a "ME 16384k Storage Cell (200 Types)" of the **AE Additions mod**. But the result is the same as the 256k.

Finally, I get one "Antimatter Pellet" of the **Mekanism** and craft a "QIO Drive Array". THANKS FOR the **Applied Mekanistics**, and then I can store all items in it and access it by AE2 terminals.

But, when I open the "Portable QIO Dashborad" (**Mekanism**) or any "Terminal (includes any wireless terminal)" (AE2), the same error occurs.

I don't know which mod causes this error, or is it just a problem with the vanilla game?

[How to reproduce]
Try to store very very large amount of items(about 900,000 if contains items with Apotheosis's Name, and about 270,000,000 if only contains common items) on any drive over 64k and then open your terminal.

[Images]
I'm sorry. I only have these pictures after building the QIO Drive.
![image](https://user-images.githubusercontent.com/19776936/213189949-8af13b91-f7b1-4ca8-b831-312154072f33.png)
![image](https://user-images.githubusercontent.com/19776936/213193594-49e9561f-ec6c-4501-b0e0-e3cf87b27bf7.png)
![image](https://user-images.githubusercontent.com/19776936/213190146-cb3f6647-abe2-441b-b19a-c2323029d491.png)
![image](https://user-images.githubusercontent.com/19776936/213193049-e8a1e966-dd7c-4af5-9b78-0164096a984a.png)
![image](https://user-images.githubusercontent.com/19776936/213190311-cb5fbbee-a9dd-4040-ace4-1b417cb49fee.png)
![image](https://user-images.githubusercontent.com/19776936/213190386-8649003a-16d8-455f-98e2-722c67a3703d.png)

**Comment by Killyice** [comment]
![image](https://user-images.githubusercontent.com/19776936/213344823-f74e7d54-c257-43ff-91b2-21d5ffabdf4c.png)
After communicating with friends who manage the server, We found that there is such a record in the background when accessing AE Drive.
This is a classic issue.😩

**Comment by Killyice** [comment]
We have tried [**XL Packet**](https://www.curseforge.com/minecraft/mc-mods/xl-packets?page=2#comments) and [**packet size doubler**](https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler) before, but neither of them will work.

**Comment by Killyice** [comment]
Finally, we delete the **Apotheosis**, because its **Adventure Module** causes this error.
However, if we just simply change the adventure module to "false", the map will not be loaded successfully.
So we have to delete this mod and add it again after loading the map.
It's sadly to say that: **DONT PUT ANY APOTHEOSIS THINGS IN ANY STORAGE DRIVE**

**Comment by Killyice** [comment]
Yesterday, the number of items has grown to 3 millions.
This issue resurfaced even though I removed all the items with _forge:tools_ and _forge:armors_ from the QIO Drive.

**Comment by brainytwoo** [comment]
I started having the same issue just a bit ago.
I've got it narrowed down to the number of either unique or unstack able items in a single network. I tried with many unique items from various mods with no change, after x number of unique items, the system bugs out. I have no way of determining the exact number at this time as I am doing all this testing in game without logs and debugging tools.

**Comment by brainytwoo** [comment]
Can confirm the same thing happens with (RS) Refined Storage. 
Same solution applies, remove some unique items.
