### ISSUE TITLE
Nether crashed on server and now i can't go through portal anymore

### ISSUE THREAD

**Issue by Makkalusi** [AllTheMods/ATM-8#703]
My Nether is no longer working which makes the modpack not playable in the long run. It crashed after i went trough for the first time after i got hit by a mob. Now i get the portal effect while trying to go through, but no teleporting.

**Comment by James103** [comment]
Try running this command: `execute in the_nether if block ~ ~ ~`
If you get an "Unknown dimension `minecraft:the_nether`" error message, your world no longer has the vanilla Nether dimension.
If you get no output, the command run fine which means the dimension still exists.
