### ISSUE TITLE
Apatite craft is gone

### ISSUE THREAD

**Issue by caiofelipetz** [AllTheMods/ATM-8#711]
after update, apatite craft by mystical essence is gone

**Comment by mickwok** [comment]
Same here, the crafting recipe of apatite in Mystical Agriculture is missing in 1.0.9

**Comment by vedalken254** [comment]
Just a quick addition: The crafting recipe is "gone" but it still works. You'll notice a create recipe with no output, follow that input layout and it'll craft in an RS system or a crafting table. However, RS autocrafting for Apatite from the essence is broken as a result of the recipe being broken.

**Comment by caiofelipetz** [comment]
not in my case, it appeared as an invalid pattern and it didn't work, I asked a friend that for some reason the craft for him was normal, and then we managed to use it in RS

**Comment by vedalken254** [comment]
yeah, the autocraft doesn't work due to the invalid recipe but RS manually allows it.
