### ISSUE TITLE
Handcrafted

### ISSUE THREAD

**Issue by adheydonuts** [AllTheMods/ATM-8#712]
You're supposed to be able to put planks in a stone cutter to make boards for the mod handcrafted. Not working

**Comment by enigmaquip** [comment]
It's an in-world interaction, the tooltip says `"Obtained by throwing planks on a Stone Cutter"`, you literally throw them on top of it

https://user-images.githubusercontent.com/6134440/213568190-a3854fb6-b144-414a-baea-41cc40533f15.mp4
