### ISSUE TITLE
Mystical Agriculture - Proposed removal of some seeds

### ISSUE THREAD

**Issue by BastionNtB** [AllTheMods/ATM-8#717]
Hello, was just looking through all the mystical agriculture seeds and saw that some seeds make essence for items that have no uses, or you can not get the material required to make the seed to then use the essence for anything.

Specifically:
Tungsten
Titanium
Mithril
Chrome
Gaia Spirit

These have no way to craft them nor any uses if you were to craft them. I suggest removing them and quite honestly, unless there is something I'm missing, probably just remove the recipes for the ingots, plates, and bars from JEI as well.

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
