### ISSUE TITLE
Ore duping using mekanism combiner & occultism

### ISSUE THREAD

**Issue by fejp** [AllTheMods/ATM-8#718]
It is possible to dupe ores including allthemodium, vibranium and unobtainium using a combination of the mekansim combiner, occultism ore crusher and apotheosis enchantment system.

You need only 8 dusts to begin with, combine these into an ore block using the combiner, mine these with sufficently high fortune on your pickaxe - getting multiple raw ores per block - and then crush the result using occultism (although looking at the rates even mekansims ore processing could suffice).

Testing this with vibranium, I took 3 stacks of vibranium dust, combined those into 24 vibranium ore, mined with fortune VIII and got 138 raw vibranium ores which after crushing yielded almost 13 stacks of vibranium dust.

Should also be able to automate the process fairly easily.

Honestly not sure what a solution could look like except removing the combiner recipes entirely...

**Comment by enigmaquip** [comment]
> Honestly not sure what a solution could look like except removing the combiner recipes entirely...

Pretty much is the best solution and how we've handled it in the past packs. No good can come from making ores in the combiner ;-)

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
