### ISSUE TITLE
My game keeps crashing when I try to name my world

### ISSUE THREAD

**Issue by Mightyemperor54** [AllTheMods/ATM-8#719]
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_5661_(net.minecraft.network.chat.Component, boolean)" because "net.minecraft.client.Minecraft.m_91087_().f_91074_" is null

**Comment by Mitchell5200** [comment]
Duplicate of #630 and #636
