### ISSUE TITLE
Feeding upgrade filling inventory with glass bottles.

### ISSUE THREAD

**Issue by Alistershade** [AllTheMods/ATM-8#721]
For some reason the feeding upgrade (the tier 1 upgrade) will stop recognizing food (bread in this instance) in my backpack (gold backpack to be specific). The occurrence of this seems to be random as it has only occurred twice and I cant remember any similarity between the two occurences.

Once this happens, whenever my hunger dips below full glass bottles will start spawning in my backpack/inventory. Removing the feeding uprgade caused the bottle generation to cease; however re-equipping the feeding upgrade caused the bottles to resume generation.

Placing the Bread in the top left inventory slot of the backpack resolved this for some reason (previously that slot had the unique spellbook "Phoenix Fire" from Ars Nouveau occupying that slot)

Edit: I remembered that my shield would flicker like i was attempting to block whenever a bottle would generate as well.

Another Edit: Temporary workaround i suppose: Use the backpacks settings to "reserve" the top left (or however many you want) item slot for your food of choice.

PS: I've never submitted a bug report before on github, so forgive me if I've neglected to contain something pertinent.

**Comment by James103** [comment]
What is the contents of your backpack? If you get glass bottles in your inventory through the auto feeding upgrade, you probably have honey bottles or another "edible in a glass bottle" item in your backpack.

**Comment by Alistershade** [comment]
> What is the contents of your backpack? If you get glass bottles in your inventory through the auto feeding upgrade, you probably have honey bottles or another "edible in a glass bottle" item in your backpack.

sorry for the delay in replying. As far as i can remember the only food i had in my inventory at the time was bread. The glitch was filling my inventory completely with bottles. over the course of the two glitch occurrences i had to empty out my backpack of more than 20 stacks of bottles.

although i don't recall having any in my inventory, it is possible that i had some buff potions, but none that provided hunger or saturation.
