### ISSUE TITLE
Bug chunk, help

### ISSUE THREAD

**Issue by FingalYT** [AllTheMods/ATM-8#724]
The chunk broke, it's dark there up to 78 height, after 78 everything is fine. the floor is at a height of 71 and there is a wind generator there, he writes that the sky is not visible, the lighting also behaves strangely in this chunk. What to do? how to fix a chunk. Ver 8 - 1.0.8

**Comment by FingalYT** [comment]
![2023-01-21_21 07 47](https://user-images.githubusercontent.com/68656900/213879647-14cf9ef9-d671-4088-a596-e2f30034250d.png)
![2023-01-21_21 35 27](https://user-images.githubusercontent.com/68656900/213879650-5e646504-70a6-4475-a3d6-2d62f40a7011.png)
![2023-01-21_21 35 30](https://user-images.githubusercontent.com/68656900/213879651-2e5dfdc5-c8a6-4900-846a-909efd06d50c.png)
![2023-01-21_21 37 50](https://user-images.githubusercontent.com/68656900/213879727-df91b102-ca69-45bf-944e-5b9fdb91fa33.png)

**Comment by FingalYT** [comment]
![2023-01-21_21 39 42](https://user-images.githubusercontent.com/68656900/213879801-6da13185-c41d-4eb4-950b-a56bbacacb94.png)
And here, for example, the torch does not shine almost.  The matter is clearly not in the graph, because it is also observed on the maximum graph. I do not understand why the wind generator does not turn

**Comment by brendonsanderson** [comment]
On my server, this was being caused by blocks from Hexerei in the chunk (chests specifically but posts on [reddit](https://www.reddit.com/r/allthemods/comments/zyc9f8/having_this_weird_visual_bug_on_my_atm8_world_how/j25w1hi/) say this is with all the pack's blocks). Breaking the Hexerei blocks and then updating the lighting - place and break a few blocks/torches fixes this.

**Comment by Mitchell5200** [comment]
tracked at https://github.com/JoeFoxe/Hexerei-1.18/issues/79

**Comment by phazejeff** [comment]
I had the same issue, removing Mahogany Chests and reloading the chunk fixed it
