### ISSUE TITLE
Mystical Agriculture Can't plant seeds in farmland

### ISSUE THREAD

**Issue by ViceNoir** [AllTheMods/ATM-8#73]
I currently have a plot of land 5x5 with a water hole with a Pylon on it with different kind of seeds.  The farm land I am using is Prudentium Farmland with slime or spider seeds.   For some reason I can plant some seeds into some of the slots and cant in others.  I am using the current build.  I have looked at the server & the local PC logs and do not see an error event being created.  Any advise on how to get you a logged event for this?  I know you and your team work hard getting though these issues.

**Comment by Mitchell5200** [comment]
Have you illuminated the farmland?, without any pictures, that's my only guess

**Comment by ViceNoir** [comment]
Thank you.  Even though I had glow stones above them must have been too high.  I also was wearing my night vision goggles and didn't think of the light level.
