### ISSUE TITLE
All of my items from the backpack disseper in All The Mods 8 

### ISSUE THREAD

**Issue by TheDarkDruid** [AllTheMods/ATM-8#733]
All of my itemes from my netherite backpacks disseper and i have no ideea what to do...
i tried to swich the sophisticated backpacks to a new version but that didn't do nothing 
what can i do to make my items reaper again?

**Comment by TheDarkDruid** [comment]
i just loaded a backup and all of my stuff showed up so yeah but the bug is still there i guess

**Comment by StrwbryMoon** [comment]
I have created a similar post, please read it as I contacted the mod authors regarding this bug, and they instructed me on how to prevent it from happening again. Hopefully the ATM team sends the patch out ASAP.

**Comment by Mitchell5200** [comment]
Mod updated in 1.0.9
