### ISSUE TITLE
Corail Woodcutter is missing an extension for "Oh The Biomes You'll Go" recipes

### ISSUE THREAD

**Issue by BelkovV** [AllTheMods/ATM-8#734]
![image](https://user-images.githubusercontent.com/71695040/213928107-37677d5d-8247-42ef-a1d5-f3c59ab3d950.png)
This causes the sawmill from the mod to not accept logs and planks from BYG.

**Comment by Motzumoto** [comment]
is there a way to add this missing recipe?
