### ISSUE TITLE
Server crashes while one or more players in the other at Ancient Pyramid

### ISSUE THREAD

**Issue by Agrijag1** [AllTheMods/ATM-8#738]
[message.txt](https://github.com/AllTheMods/ATM-8/files/10475528/message.txt)

Server crash log attached. No additional mods installed, running stock ATM8

**Comment by Bombshock** [comment]
Same here, also exact same stacktrace.
Had to move myself out of this dimension with NBTEdit otherwise I would crash the server as soon as I join.
[crash-2023-01-24_03.48.29-server.txt](https://github.com/AllTheMods/ATM-8/files/10485984/crash-2023-01-24_03.48.29-server.txt)
