### ISSUE TITLE
Changing language to Chinese failed in the game menu ,when i restart , it turned out to be original english. Changing the setting file(default setting),don't work

### ISSUE THREAD

**Issue by KGOne-666** [AllTheMods/ATM-8#749]
Changing language to Chinese failed,when i restart , it turned out to be original english. Changing the setting file(default setting),don't work

**Comment by KGOne-666** [comment]
is zh_cn true? in the default setting file

**Comment by KGOne-666** [comment]
.\config\defaultsettings\Default\options.txt
open this file 
changes as follows

1. forceunicode:false
2. lang:zh_cn

**Comment by James103** [comment]
Alternatively, if you want your settings to always be preserved, you need to disable **both** the DefaultSettings and JCPlugin mods or remove them from your modpack instance. If JCPlugin is installed, it will override most of your settings, including language, FOV, gamma, and sound/music volumes, every time you start up the game.

**Comment by KGOne-666** [comment]
> Alternatively, if you want your settings to always be preserved, you need to disable **both** the DefaultSettings and JCPlugin mods or remove them from your modpack instance. If JCPlugin is installed, it will override most of your settings, including language, FOV, gamma, and sound/music volumes, every time you start up the game.

I already find the solution，
use command in game
# /defaultsettings save forceOverride options
Now I know the defaultsetting mod did it.
Thank you for replying.

**Comment by KGOne-666** [comment]
I am careful to disable some modules
Do you know what mod can hide those potion icons
