### ISSUE TITLE
Crusher ponder causes client crash

### ISSUE THREAD

**Issue by lewnewby** [AllTheMods/ATM-8#75]
So I am new to Create but I am trying to learn it.

When I attempt to view the Ponder for the Crusher Wheel the content pops up and visible for a few seconds then crashes the client to desktop. Doing the same thing for the Waterwheel works just fine as expected.

I have my shaders turned off at the moment, (Tried it both ways.)

I am using a dedicated multi-player server and separate clients.

Attaching the Crash Report
[crash-2022-10-06_18.01.00-client.txt](https://github.com/AllTheMods/ATM-8/files/9728924/crash-2022-10-06_18.01.00-client.txt)

**Comment by InFuRiTy** [comment]
It also happened to me while I was looking up the ponder for the mechanical crafters at the 3rd stage of the demonstration!!

**Comment by fjgreer** [comment]
Happened to me too, pondering a chute.  Attached the crash report.
[crash-2022-10-13_14.06.49-client.txt](https://github.com/AllTheMods/ATM-8/files/9779964/crash-2022-10-13_14.06.49-client.txt)
