### ISSUE TITLE
Crashed, don't know the reason

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-8#752]
[hs_err_pid8916.log](https://github.com/AllTheMods/ATM-8/files/10491721/hs_err_pid8916.log)
[latest.log](https://github.com/AllTheMods/ATM-8/files/10491723/latest.log)

**Comment by Mitchell5200** [comment]
I can't tell what your system total RAM is, but this error looks like an out of memory one, try allocating more RAM if you can

**Comment by Syval0331** [comment]
> I can't tell what your system total RAM is, but this error looks like an out of memory one, try allocating more RAM if you can

Totally 16GB, 6GB allocated
