### ISSUE TITLE
Constant crashing on loading world--wanted to bring attention in case others had this issue

### ISSUE THREAD

**Issue by yescurry** [AllTheMods/ATM-8#753]
Hi,

Just wanted to post my crash logs here, not exactly sure what the issue is and wanted to get some help. I have allocated anywhere from 8-32g of ram out of 64 that I have. I played 12 hours ago without any loading issues. Let me know if any other info is needed, thanks for the help :-) 
https://mclo.gs/msh1L7o
[latest.log](https://github.com/AllTheMods/ATM-8/files/10492543/latest.log)

**Comment by yescurry** [comment]
Just wanted to note that my issue is not due to the dankstorage mod

**Comment by Jcnaylor1998** [comment]
I'm having the same issue... can't even get onto into the world

**Comment by PernDragon** [comment]
Same Here, I just updated the files on the remote server and it won't start.  I will upload my log.
[Crash Log.txt](https://github.com/AllTheMods/ATM-8/files/10505391/Crash.Log.txt)

**Comment by PernDragon** [comment]
Figured out my issue, while updating files I guess something got hosed.  I cleared out the mod folder and placed mods back.  Then Updated Forge as Forge also needed to be updated.
