### ISSUE TITLE
Update broke my game!

### ISSUE THREAD

**Issue by WH1T3B0Y75** [AllTheMods/ATM-8#756]
So I updated to the new version 1.0.9 and this keeps coming 

The game crashed whilst rendering overlay
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing from class net.mehvahdjukaar.modelfix.ModelFix (net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing is in module minecraft@1.19.2 of loader 'TRANSFORMER' @78065fcd; net.mehvahdjukaar.modelfix.ModelFix is in module modelfix@1.8 of loader 'TRANSFORMER' @78065fcd)

HELP!!!
[crash-2023-01-24_13.57.55-client.txt](https://github.com/AllTheMods/ATM-8/files/10493129/crash-2023-01-24_13.57.55-client.txt)

**Comment by Mitchell5200** [comment]
I'll need to see your Latest.log file please via https://mclo.gs/

**Comment by WH1T3B0Y75** [comment]
I did get it all worked out but thank you for even looking at my post. It was I have other mods put in and I forgot to update them but after I did the updates on them all was good.

Thanks for you time and If any thing does come up I will try a bit longer before I post.
