### ISSUE TITLE
Applied Energistics 2 + Thermal: extra conflict

### ISSUE THREAD

**Issue by MrDName** [AllTheMods/ATM-8#768]
Under certain circumstances, taking shellite ingots in or out of the crafting grid crashes the game and softlocks the terminal. 

example:
https://user-images.githubusercontent.com/79543151/214627057-292ac845-1b72-49da-96a3-09ec1bfe4dba.mp4

**Comment by Mitchell5200** [comment]
i'd need to see the logs to be sure, but at a glance at the low res server log overlaid, i'd guess its the Immersive Engineering issue again with some shader recipe or something, i know they have a fix in dev, just nothing released yet

**Comment by MrDName** [comment]
Here are the logs of what appears in the console when a broken terminal is clicked:
[log.txt](https://github.com/AllTheMods/ATM-8/files/10502969/log.txt)

**Comment by Mitchell5200** [comment]
yep, that's the IE issue, breaking that terminal should work short term, we'll have to wait for IE to release their fix

**Comment by James103** [comment]
A similar issue is encountered when attempting to encode patterns containing recipes which cost Dragonsteel Ingots. More specifically, the game crashes whilst encoding the pattern, causing the specific Pattern Terminal to reset (as if the player broke and placed it again) and **void** any patterns that were currently in the terminal (which can be hundreds of quartz and redstone if a full stack was put in).

[crash-2023-01-30_00.06.52-client.txt](https://github.com/AllTheMods/ATM-8/files/10533044/crash-2023-01-30_00.06.52-client.txt)

**Comment by Mitchell5200** [comment]
In theory fixed in 1.0.10, i'll wait for players to report back on this one
