### ISSUE TITLE
[1.0.8] Botania Black Hole Talisman with Construction Wand crashes client

### ISSUE THREAD

**Issue by thylsky** [AllTheMods/ATM-8#773]
When using Black Hole Talisman from Botania and Infinity Wand from Construction Wand it causes to crash the client upon equipping the wand it crashes the game in survival. I tried it first in creative and it's fine.

The game keeps crashing on load. The only solution I found it to use /kill command upon load so it's not in my inventory.

[crash-report](https://gist.github.com/thylsky/8b37a9743408f632711d89be8bd2e374)

**Comment by Kredusch** [comment]
what helped for me with the same problem:

stop the server / exit the game
install the nbteditor
search for the players inventory
search for the wand AND the talisman and delete both
save the file
paste it into the save or on the server
restart the game / the server

maybe youll need to deactivate a running texturepack

**Comment by thylsky** [comment]
But this doesn't fix the problem. I am able to login back to the world if I use the kill command which drops the inventory. But still if somebody else uses it on the server I need to be solving that.

**Comment by Theta-Dev** [comment]
I have fixed the issue with Construction Wand 2.9

See https://github.com/Theta-Dev/ConstructionWand/issues/66

**Comment by thylsky** [comment]
@Theta-Dev Legend 💪
