### ISSUE TITLE
Crash when entering Nether with Scarf of Invisibility ATM 8 [1.0.9]

### ISSUE THREAD

**Issue by nitrotaco444** [AllTheMods/ATM-8#775]
Crash any time I try to go into the nether wearing the scarf of invisibility from the Artifacts mod. The game doesn't crash on an instance of minecraft with only artifacts mod and it's dependencies so it seems to be a mod conflict issue.

- replicated on new world
- crash happens on previous versions of ATM8 as well

[hs_err_pid14576.log](https://github.com/AllTheMods/ATM-8/files/10512370/hs_err_pid14576.log)
[latest.log](https://github.com/AllTheMods/ATM-8/files/10512376/latest.log)

**Comment by Mitchell5200** [comment]
Looks like it might just be an out of memory error, i can see you only have 6GB allocated, if you can please try increasing your RAM allocation to 8GB

**Comment by nitrotaco444** [comment]
> Looks like it might just be an out of memory error, i can see you only have 6GB allocated, if you can please try increasing your RAM allocation to 8GB

Increasing memory allocation to 8GB rasolved the issue.

**Comment by Omegashift** [comment]
> Looks like it might just be an out of memory error, i can see you only have 6GB allocated, if you can please try increasing your RAM allocation to 8GB

I have 14GB allocated and it still crashes. Definitely not the issue.
