### ISSUE TITLE
Can you add this Mod pls

### ISSUE THREAD

**Issue by Hydra-49** [AllTheMods/ATM-8#779]
A few days ago the "Moving Elevator" Mod was released in 1.19.X. Could you add it bc it looks prettier than Openblocks Elevator & is easier to made than pneumaticCraft. 
Hope you get this. thx <3
https://www.minecraftyard.com/moving-elevators-mod/

**Comment by Mitchell5200** [comment]
Please use #3 for mod suggestions, and we only accept curseforge links only
