### ISSUE TITLE
Spatial Comb Centrifuge Recipe Missing

### ISSUE THREAD

**Issue by shawnbyday** [AllTheMods/ATM-8#78]
Not sure if it is intentional or not but the spatial comb can’t be inserted into the centrifuge.

**Comment by StvnWthrsp** [comment]
Based on the JEI description of the spatial bee, I believe this issue is because certus quartz seeds are no longer a part of Applied Energistics 2. The spatial comb centrifuge recipe will probably need to be changed to create certus quartz dust instead of seeds.

**Comment by StvnWthrsp** [comment]
This appears to have been fixed in 0.1.0 as the combs now produce certus quartz crystals instead of seeds.
