### ISSUE TITLE
All the Mods 8 - Crashing on start up 

### ISSUE THREAD

**Issue by KhangHuynh021** [AllTheMods/ATM-8#783]
I have been trying to troubleshoot this problem for the better part of a day. I downloaded All the Mods off of curse forge: version 1.0.9/Minecraft version 1.19.2/forge 43.2.3 it always gives me the error EXIT CODE 1. 

Things I've already tried 

- Reinstalling java (jdk 19)
- reinstalling Minecraft+ CurseForge
- updating drivers 

I eventually switched from forge 43.2.3 to forge 43.2.4, it loads into the game with no exit code error, but it crashes if I join a server or create my own world.

Crash report: [crash-2023-01-27_13.41.42-client.txt](https://github.com/AllTheMods/ATM-8/files/10522651/crash-2023-01-27_13.41.42-client.txt)

Log: https://mclo.gs/qRtpeY8

Any help/advice would be greatly appreciated. I'll try and do some more troubleshooting in the mean time.

**Comment by AfkUserMC** [comment]
Hey! It would be better if you uploaded your crash report to https://mclo.gs because it removes personal info and helps us read it!

**Comment by Kredusch** [comment]
hey there, i have a simillar problem to that.
im playing on a server on 1.0.8 (im not an admin there) and just startet with botania that came into the pack recently..
for some reason my client is allways crashing while i try to connect to the server.. but it says "saving world" before..

my crash log: https://mclo.gs/7mgV6Uc

i hope you can help out D: or find the bug for the occuring problem..

have a nice day :>

**Comment by KhangHuynh021** [comment]
I eventually got the mod pack to work, just not on Curseforge. I've been using the FTB launcher, the problem seems to be unique to the curseforge launcher.

**Comment by Kredusch** [comment]
so i tried ftb launcher too - still the same crash :l

**Comment by Mitchell5200** [comment]
potentially https://github.com/Technici4n/AE2Things-Forge/issues/13, seems fixed
