### ISSUE TITLE
AllTheMods8 Buggy Laggy After A While of Running

### ISSUE THREAD

**Issue by TheGamingMarioD** [AllTheMods/ATM-8#784]
I've Been playing Atm 8 for a few weeks now and whenever I play on my laptop (lowest possible settings for performance, plus fan on max rpm) for more than an hour it starts to get glitchy by freezing randomly and abnormally, until after about 15 minutes it crashes. the weird thing is my laptop isnt bad. This does not happen on my computer because well its got 8 more gigs of ram to work with. But I still find it weird that this happens. I usually play on a multiplayer server my brother set up but yeah I am afraid to try single player on this thing.  I know its something to do with the ram and there not being\ enough but c'mon now 2 chunk render distance on fast graphics? the fps is at around 120 fps (laptop refresh rate).

Intel Core I5-10300H CPU @ 2.50Ghz
NVIDIA GeForce RTX 3060 Laptop Gpu
8 Gb DDR5 Ram

Does anyone have any ideas to what could be going on? or what I could do to mitigate/fix this?

**Comment by GaalFlorian** [comment]
I'm afraid 8 Gb just won't cut it for this modpack. Not sure what operating system you're on, but Win 10 eats 3-4GB of it by itself. Win 11 goes near 6GB from what I've heard. Java may take 2 more Gbs in the background, and then comes the modpack. I personally have 16GB of RAM and allocate 6GB of it for the game. It takes about 1,5-2 hours for it to run out. Then I just restart the game.

Though, in your case, it's likely that not just your game, but your computer runs out of RAM and that can easily cause the operating system to shut down your MC to free up RAM for it to operate.

One solution I don't recommend is using SWAP. It'll eat your SSD alive and if you use an HDD for it, it'll be slow beyond comprehension.

A way to get around it is to restart the game when it starts freezing.

The real solution is getting more RAM, unfortunately. With your CPU and GPU, the size of your RAM is your bottleneck.
