### ISSUE TITLE
Combiner (Mekanism) no longer works

### ISSUE THREAD

**Issue by ICE346** [AllTheMods/ATM-8#785]
1.0.8:
Combiner recipe = [True]
Pressing the recipe button on Ores shows how to do it in a  Combiner = [True]
Using the Combiner to craft Ores = [True]

1.0.9:
Combiner recipe = [True]
Pressing the recipe button on Ores shows how to do it in a  Combiner = [False]
Using the Combiner to craft Ores = [False]
(Extra): You can put Cobblestone in the bottom slot but not Netherrack.

I literally crafted everything needed the day the update was released but did not realize it until the day after, because my friend updated his server the day after the update.

**Comment by Mitchell5200** [comment]
Yes, the ore combination recipes were removed as they usually are in each pack, as they are a direct duping path
