### ISSUE TITLE
ATM 8 Version: 1.0.8: Very Low Single Player TPS

### ISSUE THREAD

**Issue by GregoryG124** [AllTheMods/ATM-8#788]
Bug: Low TPS in single player, hovering around 2-3 at all times
Associated Mods: AE2, Mystical Agradditions
Cause: AE@ Crafting pattern for Insanium Block when placed inside AE2 Pattern provider that is connected to an ae2 network causes huge amounts of tps loss.
Fix: Remove Insanium Block pattern from pattern provider, save and quit, then rejoin world
Additional notes: Recreating the pattern and replacing it did nothing to absolve the issue

**Comment by ViRb3** [comment]
Need logs. https://spark.lucko.me/docs/guides/Finding-lag-spikes
