### ISSUE TITLE
Shulker Shells are considered helmets, causing them to drop with a reforge and become unstackable

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-8#789]
As of pack version 1.0.9, Shulker Shells are considered to be helmets. This causes Apotheosis to reforge the item whenever it is dropped through killing a Shulker. The resulting shells are all unstackable as they are considered different types.

When farming Shulkers the traditional way, this causes most of the resulting Shulker Shells to fill all type slots of an AE2 or basic storage system very quickly, causing a severe reduction in effective capacity. For example, this causes drawers to only hold 1 shell, an ME Item Storage Cell to hold 63 shells, and a vanilla chest to only hold 27 shells (instead of 2K+, 8K+, and 1728 respectively).

A similar problem occurred with Witch Hats and was fixed in version 1.0.5: 336882d1867fff0c5c37ecc91adc2426ffc45b26

**Comment by AfkUserMC** [comment]
I noticed it too and brushed it off as a silly feature. You can actually wear these as a helmet!

**Comment by yutoe** [comment]
Only reason i use Refined Storage cause of the silly 63 slot items

**Comment by James103** [comment]
Workaround: In `config/apotheosis/adventure.cfg` add the line `minecraft:entities.shulker|0` so that the list now looks like this:
```diff
    S:"Affix Convert Loot Rules" <
        .*blocks.*|0
        minecraft:entities.witch|0
+       minecraft:entities.shulker|0
        .*|0.85
     >
```

**Comment by Mitchell5200** [comment]
I've tested this myself after seeing it in the Discord from other players, and while i could not reproduce this, i'll still be implementing that fix @James103.
