### ISSUE TITLE
Immersive engineering rendering bug & fix

### ISSUE THREAD

**Issue by Dainou01** [AllTheMods/ATM-8#79]
Some of the immersive engineering animated models become invisible when using shaders. This occurs because immersive engineering by default uses vertex buffer objects on GPU to have better performance when rendering. This interfere with shaders. 

Fix is to disable VBO in the immersive engineering client-side configs.

config/immersiveengineering-client.toml > enableVBO = false

I do not know to what extent this should be implemented on all clients, as VBO buffering is a lot more efficient than traditional rendering, and on most machines that can't run shaders anyway, one would want VBO to be enabled.

**Comment by leagris** [comment]
> Some of the immersive engineering animated models become invisible when using shaders. This occurs because immersive engineering by default uses vertex buffer objects on GPU to have better performance when rendering. This interfere with shaders.
> I do not know to what extent this should be implemented on all clients, as VBO buffering is a lot more efficient than traditional rendering, and on most machines that can't run shaders anyway, one would want VBO to be enabled.

I bet IE maintainers would consider a shader detection, disable or adapt VBO accordingly if you go to their own reports https://github.com/BluSunrize/ImmersiveEngineering/issues?q=is%3Aissue+VBO to update or open an issue there.
