### ISSUE TITLE
Cursed Chunks

### ISSUE THREAD

**Issue by BoomDoot** [AllTheMods/ATM-8#791]
me and my friends decided to start playing together with ATM8;
all was going great until, one time when I logged onto the server, the chunk where I built my house was shrouded in shadow, like if a platform was built over it, after a bit of testing I found out the following properties:
- using the F7 feature revealed that all blocks in the chunk were at risk of spawning mobs
- torches and other light sources were nullified and needed to be refreshed in some way to allow them to light up the area
- leaves will not decay unless broken by hand
- gravity afflicted blocks will not fall
- blocks like vines and glowberry vines will float in mid air if their anchor point is broken
- monster spawn rates are amplified unless blocked by a mega-torch
These are the issues we encountered so far

**Comment by izzy84075** [comment]
I've also been running into this. Running v1.0.9, so slightly outdated, but it happens regularly when I restart the server. One chunk of my base seems to lose all of it's lighting, and I have to replace the torches to fix it.

It's the chunk that has my RS Controller and my main RS Crafters, not sure if that influences it.

**Comment by Mitchell5200** [comment]
tracked at https://github.com/JoeFoxe/Hexerei-1.18/issues/79

**Comment by LKX66** [comment]
Also having this issue, for my situation, it was Integrated Dynamics causing the issue. It seems like placing down two Omni-Directional-Connector causes the issue. I was able to replicate the issue in a different chunk by placing down ODCs

**Comment by mathias-bevers** [comment]
For me it was also integrated dynamics, I just had fluid-interface and a fluid-exporter for water pumping out of a sink.
