### ISSUE TITLE
direct multiplayer connection kills host internet connection

### ISSUE THREAD

**Issue by BelleTaco** [AllTheMods/ATM-8#798]
1.0.9- my fiance and i are on the same the same lan and whenever i try to connect to him it connects but before i can load the terrain, the modpack somehow nukes his internet connection. he has to unplug his ethernet cord and plus it back in each time weve tried. it happens at the same point in the process each time. ive never encountered anything like this. before this update it just gave me an error but the nuking of his internet is new with this update.

**Comment by camcamhow** [comment]
I'm having a similar issue in 1.0.9 and 1.0.10 once a couple people have joined server randomly breaks the Ethernet driver and the server pc I use needs to be completely restarted to resolve, we currently have to play on 1.0.7 to avoid this issue.
