### ISSUE TITLE
ATM8 randomly crashes after ~30 minutes - 1 hour of playing

### ISSUE THREAD

**Issue by cns05** [AllTheMods/ATM-8#806]
ATM8 randomly crashes after ~30 minutes - 1 hour of playing, this has been going on for a longgg time and its just annoying because it takes a while to load up the game and I have to do that often. Also I have allocated 10G of memory I do not think that is the problem.

Below I will link logs

[latest.log](https://github.com/AllTheMods/ATM-8/files/10531356/latest.log)

[debug.log](https://github.com/AllTheMods/ATM-8/files/10531358/debug.log)

**Comment by James103** [comment]
As a workaround, try removing Journeymap and JourneyMap Integration and adding Xaero's World Map and Xaero's Minimap.

The crash appears to be in JourneyMap code on the client.

**Comment by cns05** [comment]
Will try this thank you very much

**Comment by lanoyo** [comment]
I've been having the same issue and I had a sneaking suspicion that it was journeymap related. I managed to force a crash by rapidly clicking buttons and dragging around on the fullscreeen journeymap, which basically confirmed it for me.

**Comment by cns05** [comment]
yeah the log always includes journey map at the end after my game crashes. But I am now still experiencing my game crash after 30 minutes to an hour due to "not enough memory" even though I have been playing ATM with always ATLEAST 10 gb.

I made another post about this but here are some logs from my most recent crash below
[latest.log](https://github
[debug.log](https://github.com/AllTheMods/ATM-8/files/10562707/debug.log)
.com/AllTheMods/ATM-8/files/10562706/latest.log)
