### ISSUE TITLE
Ethylene should have a (much) lower fuel density

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-8#807]
As of pack version 1.0.9, Hydrogen's energy density was reduced from 80 to 40 FE/mB. However, Ethylene's energy density was only very slightly nerfed, from about 11.48 to 11.24 kFE/mB, which is only a 2% decrease.

The intended change (that I see) is that Ethylene's energy density should have been massively reduced, not just Hydrogen.

Mekanism has a config option "Ethylene Burn Time" to control the amount of time Ethylene burns for.
Decreasing this value increases the amount of Ethylene that must be produced in order to keep up with one Gas Burning Generator and therefore increases the biomass required to keep the same power production.

With the current configuration, 1 bucket of ethylene produces 11.26 MFE, more than any other liquid fuel in the pack (besides fission/fusion). For comparison,
* 1 bucket of syngas in a Gas Turbine produces 1 MFE.
* 1 bucket of Refined Fuel in a Compression Dynamo produces 1.5 MFE.
* 1 bucket of LPG in a Furnace Mycelial Generator produces 7.2 MFE (and other liquid fuels produce less, down to 1.6 MFE per bucket of lava or ethanol).
* 1 bucket of lava in a Magma Mycelial Generator produces 100 kFE (doubled if burnt with 4 Redstone).

If the burn time for Ethylene was reduced from 40 ticks to 10, 1 bucket of Ethylene would produce closer to 2-3 MFE instead of 11.26 and four times as much Ethylene would be required to keep the same power production.

**Comment by Mitchell5200** [comment]
Agreed, in dev

**Comment by James103** [comment]
With this change, one bucket of Ethylene in a Gas Burning Generator produces 2.84 MFE, down from about 11.26 kFE in prior versions.
