### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by Exodus1231** [AllTheMods/ATM-8#81]
Internal Exception: io.netty.handler.codec.DecoderException;java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 12)

This bug is not letting anyone join my server, the server is hosted on Gportal if that helps

Here is the Debug log https://drive.google.com/file/d/1woVVIoCbmXpDeORM-Q0H8KS-ApyzIqww/view?usp=sharing

**Comment by jhall490** [comment]
I am also having this same issue. It sounds like these are usually caused by a particular mod.

**Comment by adamzvolanek** [comment]
Any idea on a fix?

**Comment by Exodus1231** [comment]
Honestly I think it was just gportal

**Comment by Exodus1231** [comment]
I swapped server provider to nodecraft and have not had any issues https://nodecraft.com/

**Comment by adamzvolanek** [comment]
For those running Unraid and running ATM8 as as docker container: I ended up deleting `server\appdata\allthemods8\Server-Files-1.0.XX.zip` and issued a force update. 

Then verified the `server.properties` file and allowed the docker to start fully so it can unpack the `Server-Files-1.0.0X.zip`.

In other words, I believe this error comes from a bad or corrupted unpacking of the Server-Files.zip, be it during unpack or during initial-startup.
