### ISSUE TITLE
Occultism Unopenable Storage Bug

### ISSUE THREAD

**Issue by JesConApk** [AllTheMods/ATM-8#812]
When first building the multi block structure "Dimensional Storage", it worked perfectly fine, but the Storage Accessor couldn't open the storage after 1h anymore, so I made a new one and after about 10 minutes, it didn't work either. A little bit later, there was an problem with the Stable Wormhole, by beeing right clicked nothing happend, 10 minutes ago it opened my storage. A short period later I couldn't even open my Dimensional Storage Actuator and can't get my stuff back, I spend much afford to get their, so please fix it.

**Comment by Mitchell5200** [comment]
likely the IE bug again, should be fixed in pack version 1.0.10, Please update and report back, if it's still not working then Latest log via https://mclo.gs/ please

**Comment by Dunkel32** [comment]
same with familiar rings and their respective summon inside, after a while you can't summon the familiar from the ring.
