### ISSUE TITLE
Garden Cloche Fertilized Essence not working

### ISSUE THREAD

**Issue by Littleghost01** [AllTheMods/ATM-8#813]
Hi, is there a problem with the garden cloche of Immersive Enginerring ? We can only put Bone meal has a fertilizer. Can we expect to be able to put Fertilizer Essence ? Is that a change in the code by you or something ? Because i know its working in the Ragnamod 6 modpack.

Thank you

**Comment by Pultex** [comment]
think it was changed by the Dev of immersive for versions past 1.18.2 of the mod
only bone meal can be used in 1.18.2-1.19.3 of minecraft with immersive
thought you could change it in a config but don't know where

**Comment by Pultex** [comment]
to get it to work they need to add something like this to
kubejs server

` onEvent('recipes',` event => {


event.recipes.immersiveengineering.fertilizer('mysticalagriculture:mystical_fertilizer').growthModifier(1.5)
event.recipes.immersiveengineering.fertilizer('industrialforegoing:fertilizer').growthModifier(1.1)
event.recipes.immersiveengineering.fertilizer('thermal:phytogro').growthModifier(1.3)  `

there is no config in immersive for it

**Comment by Littleghost01** [comment]
Oh ! Interesting... Am I able to modify this somewhere in the code or maybe you will add it in a next update ? If its a .jar, what do I need to do to visualize the code in my VisualCode Studio app ? I tried to read it but I cant.

Really appreciate you're help !

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Littleghost01** [comment]
![image](https://user-images.githubusercontent.com/123947990/216700129-195ed91d-39a4-466c-ae71-7da53ff37470.png)

Ok i found something in the immersive .jar file but i'm not a expert like you guys. Maybe you can do something there ?
