### ISSUE TITLE
Bug(s) Dank/null and botania

### ISSUE THREAD

**Issue by Zandrassen91** [AllTheMods/ATM-8#814]
When using Dank/null players launcher keep crashing.
https://pastebin.com/qbWMaaBc  (bug repport) 
We are playing on a server in version 1.0.9

other mod with a problem is botania, the mana spreader seem to not work.. 
i'm not collection any mana, even when the flower and mana spreader is full.. (they are bound) 
i have not being able to test if this is a bug or not. 
(same server and version)

**Comment by Mitchell5200** [comment]
Dank is sorted for the next update already, botania sounds like you are not pointing the spreader at a nearby mana pool (within 2 or 3 blocks)

**Comment by Mitchell5200** [comment]
Danks Fixed in 1.0.10
