### ISSUE TITLE
Rotating Projector Duping Glitch

### ISSUE THREAD

**Issue by unitivekhan3385** [AllTheMods/ATM-8#817]
Hello there is an issue if you rotate a projector with an item in it it will end up making basically an infinite copy of whatever item is in the projector. It even copies the item that are in that block being able to dupe allthemodium and other blocks and ores that are super rare.

**Comment by Sniperscope1827** [comment]
Can you please elaborate on how to recreate it?

**Comment by unitivekhan3385** [comment]
> 

So grab a wrench (anything that rotates blocks) and when the projector has an item in it, rotate it and you'll see the block you put into the projector fall out, but when you look back into the projector you'll still see the blocks in there with all of its loot meanwhile having a copy of that blocks and all of the loot inside of it as well.

**Comment by Sniperscope1827** [comment]
As in Meka Configurator on Rotate mode? And what mod is the projector from exactly, as there seems to be a couple different ones?

**Comment by GaalFlorian** [comment]
Hi! I managed to recreate this. The projector is from Security Craft. It can only hold placeable blocks. Once a block is in the inventory slot of the projector, and a player right-clicks on it with a Crescent Hammer from Thermal Series, the projector is rotated, with the block in its inventory remaining there. A copy of the block is also dropped beside the projector in the process, as described earlier. The process can be repeated indefinitely. Duplicated objects keep their NBT data, so mass duplication can be done with shulker boxes and such. I managed to recreate this in both 1.0.9 and 1.0.10.

**Comment by unitivekhan3385** [comment]
Yea that's exactly what i did. I ended up also automating it using a rotater block (i don't really remember what mod it's from at this moment). There would be hopper in the bottom that would lead to a receiver from refined storage going directly into the system.

**Comment by tabdelbari** [comment]
I confirm this is still reproduceable in 1.0.11
