### ISSUE TITLE
TELEPORTATION 

### ISSUE THREAD

**Issue by BDOG26202** [AllTheMods/ATM-8#82]
way stones or journey map, /spawn, /home anything that teleports you from distance the who game bugs the interface tweaks out and I am pretty sure its either a rendering bug or journey map bug but once the interface tweaks to home screen is also bugged, last good update was .11 from my experience

**Comment by mjordan67** [comment]
Having the same problem and agree with  .11

**Comment by anigeluk** [comment]
In my case it is crashing the game without recording anything in the log

**Comment by theBeardyDwarf** [comment]
same issue over here , the GUI glitches out since 0.11 when using some kind of tp

**Comment by BioPrince** [comment]
Used waystone; game stops/closes completely no crash log.

**Comment by ViceNoir** [comment]
I've seen that if you are in creative mode and use the teleport function by click the letter N finding the location and clicking Teleport your appear inside the ways stone not next to it.  Not sure if this is part of the issue, but could it be tied to the appearing next to the location and not inside the location?

**Comment by I00I0I** [comment]
I have the same problem when i fly very high

**Comment by Zarkazm** [comment]
I hate to say it, but I feel like this started when Create was added into the pack.  Based on other tickets entered at the time this started, it looks like a Create and Rubidium incompatibility.  I'm guessing Rubidium, like Optifine, is hijacking things in the vanilla Minecraft rendering engine that Create is relying on, and it just can't cope.  Enigmatica 9 recently came out with Create in it as well, but it doesn't have Rubidium and doesn't have these issues that ATM8 is having.  (not trying to advertise another modpack or anything, just citing an example).

**Comment by mstefan21** [comment]
@whatthedrunk can be closed, last change of config in 0.1.3 fixed this problem
