### ISSUE TITLE
Server/Client Mod mismatch [1.0.10]

### ISSUE THREAD

**Issue by SinisterZinn** [AllTheMods/ATM-8#821]
The recent update causes two mod mismatch errors between Client and Server. The first being Silent Gear throwing this error:

![image](https://user-images.githubusercontent.com/111560740/215707576-e57d6293-d2b0-4474-8f44-794d34a1964d.png)

After manually replacing the mod with the proper version, it then spits out a second mod mismatch error this time from Immersive Engineering:

![image](https://user-images.githubusercontent.com/111560740/215709936-7127dd43-b50c-4124-b752-407cd4528144.png)

Manually replacing THAT mod as well, then produces this error:

![image](https://user-images.githubusercontent.com/111560740/215712020-4816349b-881b-4129-b583-848e98a0e20d.png)

**Comment by Mitchell5200** [comment]
Looking at the 1.0.10 server pack that was uploaded to curse, the version numbers match the client mods, looking at your error, it looks like you are using the 1.0.9 server pack.

1.0.10 server pack https://www.curseforge.com/minecraft/modpacks/all-the-mods-8/files/4372519
