### ISSUE TITLE
The angel ring quest does not mention the existence of the Energetic Angel Ring.

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-8#828]
As of pack version 1.0.10, the Angel Ring quest does not mention the existence of the Energetic Angel Ring, despite said ring being part of the Angel Rings 2 mod. Either that ring should be removed or the quest should mention its existence.

Quest preview with description mentioning its existence (the text after the line break is new):
![image](https://user-images.githubusercontent.com/37945304/215970184-811550db-a054-46d8-a96d-7ff4ad6c35f7.png)

**Comment by AfkUserMC** [comment]
There should be a hidden quest after that one.

**Comment by James103** [comment]
> There should be a hidden quest after that one.

That quest mentions some things about the ATM Star, not the Energetic Angel Ring.
