### ISSUE TITLE
Missing recipe: Brass Ingot -> Brass Plate via Multiservo Press

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-8#830]
Title says it all.

Found in pack version 1.0.9; have not tested yet on 1.0.10.

Only way to do it 1:1 is via Create's press, FTBIC roller, or Immersive Engineering metal press, or pay double to hand-craft.

**Comment by iconmaster5326** [comment]
This is also true of plates of several other metals, not just Brass:

* Platinum
* Iridium
* Zinc
* Osmium
* Diamond
* Allthemodium
* Unobtainium
* Vibranium

Hope this gets fixed soon!

**Comment by nmiell** [comment]
There's some KubeJS code that appears to be creating plate recipes for all the metals, I don't understand why it isn't working.
