### ISSUE TITLE
Bug when crafting

### ISSUE THREAD

**Issue by AkaOtaku** [AllTheMods/ATM-8#832]
So when im trying to build the fuild extractor from industrial foregoing mod using the move items from JEI, all the items besides the pity machine frame are consumed and the item is not crafted.

**Comment by Pultex** [comment]
yeah happens to me to have to craft it in the basic crafting table
by hand
the items will dupe as well not sure why that is happening
you might get the frame back with some other parts

also **don't** do it in a refine grid or other automated crafting system
make a recipe for it have it automate or

If you do try to craft it in a refined storage crafting grid manually or with jei
the terminal will freeze and you will not be able to access it
after some time the server will crash an corrupt the world

**Comment by AkaOtaku** [comment]
Okay thanks for letting me know, just wanted to make sure you guys were
aware of the bug.
Cheers :)
