### ISSUE TITLE
Crashing upon startup.

### ISSUE THREAD

**Issue by ANDREWILL06** [AllTheMods/ATM-8#835]
Hello, me and my friends paid for a server about a week and a half ago. It's crashed multiple times but managed to get them all fixed. But this one is different. I found the problem mod and its Cable Tiers and additional enhanced miner. I would like to try and fix this without having to remove the mod entirely cause I use them both a lot.
[Server crash.txt](https://github.com/AllTheMods/ATM-8/files/10561581/Server.crash.txt)

**Comment by hokomili** [comment]
I looked through your log and see the problem : a single server tick took 60.00 seconds
It seems like a problem from refined storage.
I've encounter the same problem when the system is basically full and an automatic machine still trying to dump items in.
If thats the problem, you might need to open it in a single player world and remove them quickly. (for some reason single player can accept a single tick for more than 60 seconds)
Or you can try to increase the max tick time for the server, before you fix the problem.
