### ISSUE TITLE
have been dedicating  10+ GB of ram but game still crash

### ISSUE THREAD

**Issue by cns05** [AllTheMods/ATM-8#836]
have been dedicating  10+ GB of ram but game still crashes, I don't know if there is a minimum amount of ram for ATM8, here are some logs below

[latest.log](https://github.com/AllTheMods/ATM-8/files/10562664/latest.log)
[debug.log](https://github.com/AllTheMods/ATM-8/files/10562665/debug.log)

**Comment by tindolt** [comment]
Please update your java version to java 19 and ensure that this is not the issue.
As well please make a new copy of the modpack in curseforge or where ever you have them launching and managed and reinstall the pack fully. looks like you are also missing a few mods. 

Reason for requests: Running in compatibility mode for java 17, and jei is reported as missing in your logs
