### ISSUE TITLE
ATM 8 Server not shutting down properly. 

### ISSUE THREAD

**Issue by frappim** [AllTheMods/ATM-8#839]
It will get hung up after it's done saving world, and will never fully shut down. I have to end the java process manually. 

Happens on 10.10 and the server update before that. 
Fresh install also has the same problem.

This is an issue because my server restart will not trigger unless the server fully shuts down, which it never does without intervention.

**Comment by frappim** [comment]
Currently it's getting hung up on "Finished Unloading EnderChest Data" 
But the previous version it was something else> (I can't remember)

**Comment by Mitchell5200** [comment]
I have investigated this before, and traced it to Spark, and reported it to them, i'll do some more investigating later, but for now you can remove spark from the server to solve this temporarily

**Comment by frappim** [comment]
When I run my ATM8 Server through AMP it always gets hung up on "Thread Query Listener stopped". 

Would this also be Spark? I will try and remove it shortly
