### ISSUE TITLE
Mining mining gadgets green glow hurts the eyes 

### ISSUE THREAD

**Issue by ViceNoir** [AllTheMods/ATM-8#84]
Version 15 for atm8 - Not sure if this is a ticket for Mining Gadgets or your team.  But I just got my first Mining laser and there is a bright Green glow every time I use it.  I cannot see what I am shooting.  I have tried to adjust a bunch of settings to see if I can get rid of it.  I'm checking to see if anyone else has found a way to make it stop.  Like always Love your mods and apricate your effort.

**Comment by fjgreer** [comment]
Turn off shaders, it's caused by them.

**Comment by ViceNoir** [comment]
Thank you I will try that
