### ISSUE TITLE
Issue regarding Mystical Agriculture's "rubber essence".

### ISSUE THREAD

**Issue by LuisNTC** [AllTheMods/ATM-8#844]
Mystical Agriculture's "rubber essence" does not turn into rubber.

**Comment by AfkUserMC** [comment]
It's missing the forge:rubber tag. If you look in the recipes, you can see that you cannot craft it!

**Comment by cobaltsieg** [comment]
Can we please get the tag updated in Forge to include the present base rubber items? FTB Industrial Contraptions and Thermal Series.

**Comment by Mitchell5200** [comment]
Fixed, closing
