### ISSUE TITLE
AE Export Bus expoting "Flawed Budding Certus Quartz" into ME Interface is converting "Flawed Budding Certus Quartz" into "Mana"

### ISSUE THREAD

**Issue by Jannis636** [AllTheMods/ATM-8#847]
I will just show a setup as it is easier to explain.

## The setup
![image](https://user-images.githubusercontent.com/32140646/216713671-2115f074-02d5-45e4-a1f8-860b818b0c53.png)
Notes:
- The thing by the water is just an annihilation plane picking up the item
- Storage Bus 1 has the default configuration
- Import Bus has the default configuration too
- ME Interface 1 is where the crafted "Flawed Budding Certus Quartz" should go
- There are also two crafing recepies. The first crafts "certus quartz" into "charged certus quartz". The second 1 "certus quartz block" and 3" charged certus quartz" into "Flawed Budding Certus Quartz". They use a charger and dropper respectivly

Export Bus configuration:
![image](https://user-images.githubusercontent.com/32140646/216714185-da0720ec-f145-4c39-9db3-ff5da133f9b1.png)
Storage Bus 2 configuration:
![image](https://user-images.githubusercontent.com/32140646/216714432-d94a7734-bc04-4cb6-b631-29f82e791ce8.png)

## Expected behaviour:
When in the barrel are 3 "certus quartz" and 1 "certus quartz block" the yellow "subnet" will craft a "Flawed Budding Certus Quartz" because of the crafing card in the export bus. Once crafted the "Flawed Budding Certus Quartz" will be exported into the "ME Interface 1".

## Actual behaviour:
The crafing works fine but when exported into "ME Interface 1" a "Mana" "item" appears instead of the "Flawed Budding Certus Quartz". Here a picture of "ME Interface 1":

![image](https://user-images.githubusercontent.com/32140646/216715868-8b88573d-7a8d-4be4-82bb-f8c3343232fe.png)

## Notes
- When a "Flawed Budding Certus Quartz" is put into the barrel directly the item gets exported correctly
- The ATM 8 version is 1.0.10
- I play on a server

**Comment by ramidzkh** [comment]
I'll look into it (appbot dev)

**Comment by ramidzkh** [comment]
Can you update the pack to 1.0.13 (or ensure you're on Applied Botanics 1.4.2)
