### ISSUE TITLE
ATM8 Server with bisect hosting randomly crashing then failing to start/make joinable

### ISSUE THREAD

**Issue by levi2up** [AllTheMods/ATM-8#849]
Title says it all. I'll provide a crash log if I get one, but currently the server just cannot stay started, and gets stuck in an infinite loop
Using 5gb of ram, any way to fix this without allocating more?

**Comment by HijackHornet** [comment]
The pack say minimum ram is 6GB

**Comment by daman31** [comment]
Im running with 12gb on bisect and I'm having issues too
