### ISSUE TITLE
Multiple game crashes

### ISSUE THREAD

**Issue by Epicfailman6** [AllTheMods/ATM-8#85]
So far ive had the game crash many times do to random things:

1. Punching a chest with anything, makes the game instantly crash.
2. Immersive engineering crafting table crashes game and shuts down server if i try to auto craft something into it with JEI
3. Game crashes if i use exp to use waystones, happens 100% the time and wont crash if the tp doesnt use exp
4. this only happened once but, i opened my backpack and then the game suddenly crashed

3 of these are very bad and need to be fixed, on my friends server everyone is experiencing the same crashes, any chest we place we cant remove unless we go into creative and break them. this was all within a 2 hour time span of playing. Sadly i have no crash reports as the game and client fully shut down completely.

**Comment by InFuRiTy** [comment]
Try removing Oculus and Rubidium mods from your clients and check if that removes/reduces the crashes!!

**Comment by NunbearTWITCH** [comment]
I have had to disable those 2 mods to allow chests to be broken

**Comment by whatthedrunk** [comment]
We now ship the pack with the client mod to fix this crash.
