### ISSUE TITLE
Mod addition: Create Plus

### ISSUE THREAD

**Issue by jbagwell27** [AllTheMods/ATM-8#850]
Adding [Create Plus](https://www.curseforge.com/minecraft/mc-mods/create-plus) would be a great addition. I mainly want the goggle curio slot and the mekasuit unit.  
This seems to belong here. Just sayin'

**Comment by AfkUserMC** [comment]
Surprise surprise, it doesn't!
While i'm sure it would make for a great addition, please post it in #3

**Comment by jbagwell27** [comment]
Posted. Thank you :)
