### ISSUE TITLE
Parallax mapping doesnt work with any shaders (Modpack issue - something wrong with the Iris mod port?)

### ISSUE THREAD

**Issue by LiquidLighter** [AllTheMods/ATM-8#852]
Whether using the default iris version or the most updated one which now has parallax functionality (1.5.0+), it doesn't work in-game. 

Parallax mapping does work with a variety of shaderpacks in **other** modpacks which support parallax mapping when using 1.5.0+ version of Iris. I have all the correct settings set for the shader packs which are have identical configs set when using them across multiple modpacks, therefore, i know that the settings used are not the issue. 

I've contacted Iris support and they say that Iris has **potentially** been poorly ported for the pack. 

Current versions for the mods/packs I am using:
All the mods 8 - ATM8 - 1.19.2   Forge-43.2.3
iris-mc1.19.3-1.5.1.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar (Manually placed in the pack to see if it made any difference. Seen it used in other packs which parallax mapping worked and wasn't sure if this was a patch/temp fix)
SEUS PTGI HRR 3 - shaderpack1
AstralLex(BSL Edited)- shaderpack2

**Comment by Mitchell5200** [comment]
> Current versions for the mods/packs I am using:
All the mods 8 - ATM8 - 1.19.2 Forge-43.2.3
iris-mc1.19.3-1.5.1.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar

Considering those mods are Fabric mods, and this is a Forge pack, i'm suprised you didn't crash.
The pack already has Rubidium (forge port of sodium), and Oculus (forge port of iris), and Oculus for 1.19.2 is currently based on iris 1.4, so any iris 1.5 features will not work for obvious reasons.

**Comment by LiquidLighter** [comment]
> 

That makes perfect sense on why the parallax mapping feature doesnt work. 

Appreciate the prompt info :)

**Comment by Mitchell5200** [comment]
The last time i checked in the author's discord, Oculus for 1.19.3 was going to use iris 1.5, but that was not going to be back ported to 1.19.2 or 1.18 (i might be wrong though)

**Comment by LiquidLighter** [comment]
> The last time i checked in the author's discord, Oculus for 1.19.3 was going to use iris 1.5, but that was not going to be back ported to 1.19.2 or 1.18 (i might be wrong though)

Ah okay, will be keeping an eye out on that, thanks.
