### ISSUE TITLE
Server Freezes when killing any mob.

### ISSUE THREAD

**Issue by TheAmazingJeh** [AllTheMods/ATM-8#853]
Version - 1.0.10

Whenever I kill a mob, the server freezes. It doesn't crash my game, and I can move around perfectly fine but when I break blocks or do anything else it just won't work. It also make mobs freeze and float in the air as shown in the image below. I don't have a crash report as the game itself dosn't crash, but the console is filled with errors like this.

`[11:49:36] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Stop: Invalid parameter parameter value. [11:49:38] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value. [11:50:05] [spark-worker-1-4/WARN] [spark/]: Timed out waiting for world statistics [11:51:05] [spark-worker-1-1/WARN] [spark/]: Timed out waiting for world statistics [11:52:05] [spark-worker-1-3/WARN] [spark/]: Timed out waiting for world statistics [11:53:07] [spark-worker-1-5/WARN] [spark/]: Timed out waiting for world statistics [11:54:11] [spark-worker-1-0/WARN] [spark/]: Timed out waiting for world statistics
`

![image](https://user-images.githubusercontent.com/81706323/216766080-bc1cbcae-e2fe-4fe8-8507-299ed83f5b97.png)

**Comment by James103** [comment]
1. What type of sword were you holding? Are you able to reproduce the server hang with other swords?
2. What enchantments does your sword have? More generally, what do you get in the logs as output when you run `/data get entity @s SelectedItem` while holding the sword?

**Comment by TheAmazingJeh** [comment]
1. Supremium sword, it only seems to happen when using this sword. here is an image of it
![image](https://user-images.githubusercontent.com/81706323/216812038-1068a263-4e0d-4eb4-bc8a-2b8718568cab.png)
2. This the result of the data get command 
`{id: "mysticalagriculture:supremium_sword", Count: 1b, tag: {affix_data: {name: '{"color":"rainbow","translate":"%s %s %s","with":[{"translate":"affix.apotheosis:sword/attribute/lacerating"},"",{"translate":"affix.apotheosis:sword/mob_effect/sophisticated.suffix"}]}', affixes: {"apotheosis:sword/attribute/graceful": 0.5041624f, "apotheosis:sword/attribute/lacerating": 0.016564488f, "apotheosis:sword/special/festive": 0.41753155f, "apotheosis:sword/attribute/glacial": 0.05164987f, "apotheosis:sword/attribute/vampiric": 0.4516632f, "apotheosis:sword/attribute/infernal": 0.939117f, "apotheosis:sword/mob_effect/weakening": 0.11232209f, "apotheosis:telepathic": 0.86186564f, "apotheosis:sword/attribute/elongated": 0.809847f, "apotheosis:sword/mob_effect/sophisticated": 0.60059255f, "apotheosis:durable": 0.71f, "apotheosis:socket": 2.0f}, rarity: "ancient"}, AttributeModifiers: [{Amount: 100.0d, Slot: "mainhand", AttributeName: "minecraft:generic.luck", Operation: 2, UUID: [I; 244089667, 1686326675, -1259479447, 1165597359], Name: "cmd-generated-modif"}, {Amount: 100.0d, Slot: "mainhand", AttributeName: "minecraft:generic.luck", Operation: 2, UUID: [I; 130190228, -1247195429, -1519190411, -173762363], Name: "cmd-generated-modif"}, {Amount: 124.0d, Slot: "mainhand", AttributeName: "minecraft:generic.luck", Operation: 2, UUID: [I; 606137939, 18105967, -1591839420, -1616602376], Name: "cmd-generated-modif"}], Enchantments: [{lvl: 8s, id: "minecraft:looting"}, {lvl: 9s, id: "minecraft:sharpness"}]}}`
