### ISSUE TITLE
RSInfinityBooster items not working

### ISSUE THREAD

**Issue by justSatyr** [AllTheMods/ATM-8#854]
The 'Infinity Range Booster' and the 'Dimension Card' from RSInfinityBooster don't seem to be working at all. The 'Infinity Range Booster' does up the range on the 'Advanced Wireless Transmitter' by 500 blocks but other than that they don't appear to be doing anything.

**Comment by James103** [comment]
Try putting the upgrades on a regular old Wireless Transmitter, not the advanced version, to get the full effect.
(Make sure your RS system has enough power first, as the card uses 4 and 8 kFE/t respectively.)

**Comment by maxwoke** [comment]
I can confirm that using the advanced wireless transmitter wont work. You have to use the basic one. I'm not sure if it's related but I'm noticing that when I'm away from my base, all of my inventory is displayed, I can only add to it, not remove. Unless it's something I added while away. Then I'm free to pull it out like normal.

**Comment by justSatyr** [comment]
Switching the transmitter out seems to have gotten it working. With the limited testing I did I don't _seem_ to be having the the inventory issue but time will tell. Thank for the help!

**Comment by christiaangieles** [comment]
This is still a bug, in the version of this mod being used in ATM9 - No Frills. 

the booster doesn't work in the Advanced Wireless transmitter, but does work in the regular one.

**Comment by arghtieqa** [comment]
Thanks for sharring ! It does work with the basic one and not the advanced transmitter. Lifesaveeeerrrr
