### ISSUE TITLE
Dank Crashing Client

### ISSUE THREAD

**Issue by superme123360** [AllTheMods/ATM-8#856]
Yesterday I was playing with a few friends when I made a dank to redstone level. holding it was fine but as soon as I would open my inventory it would crash me out of the game entirely. this happened every time without fail and when handing it to a friend so they could destroy it, they opened their inventory and the same thing then happened to them.

**Comment by ApoIIy0n** [comment]
might want to put the version your playing next time... I bet you are on 1.0.9..

**Comment by superme123360** [comment]
(Yes, sorry haven't written one of these before so will def include next time)
Modpack version is 1.0.9 
if I've left out any other crucial info please let me know so I can include it next time. Thanks!

**Comment by ApoIIy0n** [comment]
> (Yes, sorry haven't written one of these before so will def include next time) Modpack version is 1.0.9 if I've left out any other crucial info please let me know so I can include it next time. Thanks!

you can close this. problem is solved in 1.10

**Comment by superme123360** [comment]
> > (Yes, sorry haven't written one of these before so will def include next time) Modpack version is 1.0.9 if I've left out any other crucial info please let me know so I can include it next time. Thanks!
> 
> you can close this. problem is solved in 1.10

how
