### ISSUE TITLE
Mahou Tsukai crashing client

### ISSUE THREAD

**Issue by NinFluffy** [AllTheMods/ATM-8#857]
Not sure if this was mentioned yet, but whenever I use the Explosive Mana Condensation thing (you know, the staff of explosion) in AOE and Big Explosion mode, it crashes the game after a few uses. Beam mode seems fine for now. 

Here's my crash report.
[crash-2023-02-04_04.36.14-client.txt](https://github.com/AllTheMods/ATM-8/files/10610014/crash-2023-02-04_04.36.14-client.txt)

**Comment by stepsword** [comment]
still broken, huh.. I'll upload another fix in a few minutes and hope it works

**Comment by stepsword** [comment]
ok, just uploaded 1.34.39 of mahou which hopefully fixes it. not that i know what's causing it since it shouldnt even be using the Level's random in the first place anymore
