### ISSUE TITLE
Ars Nouveau spell book server crash

### ISSUE THREAD

**Issue by engdyn** [AllTheMods/ATM-8#859]
Breaking a trash can with the spell book causes the server to crash.
[Crash Log](https://github.com/AllTheMods/ATM-8/files/10610376/crash-2023-02-05_07.38.36-server.txt)

**Comment by CrownJoker** [comment]
I've experienced the same issue, unfortunately I don't have access to crash logs at the moment, I'll try to get them from the server admin. Just joining the thread to get alerted of updates.
