### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by Pedrinhoreidelas** [AllTheMods/ATM-8#86]
I try to open using the original minecraft modpack AllTheMods 8, and it doesn't even show the loading window, I can only see the process through the task manager and then it disappears and nothing happens (does not open).

log with all information.
[hs_err_pid12524.log](https://github.com/AllTheMods/ATM-8/files/9766406/hs_err_pid12524.log)

**Comment by zuccali** [comment]
same for me

**Comment by Mitchell5200** [comment]
Likely insufficient memory allocation, Closing as stale now

**Comment by Pedrinhoreidelas** [comment]
I tried several things, I changed the allocated RAM in various amounts, from 4GB to 12GB, but nothing helped, in the end I updated my video drivers (RX580) and finally managed to open the game and even create a world and play.

this error is definitely something like forge incompatibility with graphics drivers, nothing likely insufficient amount of ram.
