### ISSUE TITLE
[1.0.10] Slimes From Spawner Stuck Mid-Air

### ISSUE THREAD

**Issue by eldonwilliams** [AllTheMods/ATM-8#860]
I have the following Apoth spawner...

<img src="https://user-images.githubusercontent.com/43430084/216813054-d2301f46-ebd8-4d09-905d-f4da1be9d772.png" width="250">

The first slime spawned is fine, however, any other slime spawned by killing the first is always unaffected by gravity. This usually leads to clumps of 4 small slimes floating, which is annoying to deal with. This bug also occurs with Maze Slimes.

<img src="https://user-images.githubusercontent.com/43430084/216813204-42b1e07a-82b3-4bda-9da4-590083680424.png" width="800">

I believe this has something to do with the no-ai modifier?

Also, I have not modified my ATM-8 installation in any way.

**Comment by Mitchell5200** [comment]
No-ai modifier issue
