### ISSUE TITLE
crashing on world loading 

### ISSUE THREAD

**Issue by nethred** [AllTheMods/ATM-8#863]
[crash-2023-02-05_16.53.25-client.txt](https://github.com/AllTheMods/ATM-8/files/10614935/crash-2023-02-05_16.53.25-client.txt)
The game loads until I try and get into a world it either freezes or crashes, yes I have added mods but I've taken them out and still get the same problem with the original ATM-8 mods. 
I do have optifine in there and I removed all the conflicting mods, yet it still crashes even if I remove optifine.
any help is appreciated, Thank you.

**Comment by Mitchell5200** [comment]
change back to forge 43.2.3, and there's no need for opti with the mods we currently have

**Comment by nethred** [comment]
> change back to forge 43.2.3, and there's no need for opti with the mods we currently have

thank you so much that fixed it, have a good day.

**Comment by TinTV1212** [comment]
but how to install forge 42.2.3 into the modpack? im using tlaucher to run the modpack
