### ISSUE TITLE
Solved the problem of memory leaks

### ISSUE THREAD

**Issue by FabioGodo** [AllTheMods/ATM-8#864]
I was having problem on my server of RAM. I started with 9 gb of ram but it crashed in like 1 hour, then i upgraded it at 12 GB and it worked until yesterday, so i did my research and i found a mod called memory leak mod.
I put that mod on my server folder and now the server is standing still at 8.80 GB used, i think i will work for you as well

**Comment by Migno** [comment]
Could you link me the correct version? I can only find the fabric version for 1.19.2

**Comment by HijackHornet** [comment]
Can you send a link ? Its a fabric only mod

**Comment by cauamachado51** [comment]
> 

@ghost Forge, minecraft 1.17-1.20.4: https://modrinth.com/mod/memoryleakfix/versions
