### ISSUE TITLE
Can't apply Space Breathing enchantment to Allthemodium Helmet

### ISSUE THREAD

**Issue by ShaBren** [AllTheMods/ATM-8#865]
I've attempted to apply the Space Breathing enchantment from Ad Astra: Giselle Addon to the Allthemodium Helmet, but am unable to. I'm running version 1.0.10 of the pack.

I've tried applying it from a book with the anvil, as well as via the `/enchant` command; neither works.

I'm able to use the following command to give myself the helmet with the enchantment, but it reflects a level of 0 and is ineffective: `/give @p allthemodium:allthemodium_helmet{Enchantments:[{id:'ad_astra_giselle_addon:space_breathing',level:1}]}`

Thanks!

**Comment by move123456789** [comment]
Got the same issue :)

**Comment by gisellevonbingen** [comment]
It would be fix in 1.12 version
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4392563

**Comment by PeaceIsBliss** [comment]
Same problem, heck tried putting it on a vanilla iron helmet, still nothing.

**Comment by gisellevonbingen** [comment]
> Same problem, heck tried putting it on a vanilla iron helmet, still nothing.

It would be fix in 1.12 version
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/4392563

Try update mod pack or Ad Astra!: Giselle Addon mod.
And have you 'oxygen can' in your inventory?
