### ISSUE TITLE
[1.0.10] Server crashing on startup

### ISSUE THREAD

**Issue by Donutnut1** [AllTheMods/ATM-8#873]
Hello!

While I was offline last night a couple of my friends say they were using the auto-crafter and pattern grid to craft large amounts of mystical agriculture essence and then the server crashed. It's now been crashing as soon as it starts up (every like 3 minutes or so?) since due to a tick taking longer than 60 seconds and I'm not sure how to fix it.

Any help would be much appreciated! Please let me know if I need to provide any more information :)

Initial crash log: https://pastebin.com/GYQNzL3a
One of the repeating crash logs: https://pastebin.com/q7Nmcgbz
One of the logs from the server starting: https://pastebin.com/UYjtrFEh
I can't access the original log from the time it first crashed as multicraft seems to only store 99 logs per calendar day

Friends explanation (I don't really understand as I haven't been using that kind of crafter): "Yeah I think we have a netherite crafter for main essence(infernium) going into a tier 3 crafter and then just the netherite one for all the other essence like the ores and shit that connects to the pattern grid, the pattern grid just lets us craft items basically straight outta the storage network without actually mass clicking I think. Im sure Bailey knows more of the logistics than me since he set it up"

Assuming it's related to the mass crafting of items as that's apparently all they were doing when it went down and they've been crashing the server on a daily basis (when no one else is on) mass crafting in the computer which is why they were trying to automate it instead

**Comment by hokomili** [comment]
I've seen a similar problem before. It was caused by refined storage being crammed by too many items.
We solved it by download the server world to a single player and quickly dump the items out before the game crashes.
