### ISSUE TITLE
[SUGGESTION] Add Time In A Bottle Curio Slot

### ISSUE THREAD

**Issue by AfkUserMC** [AllTheMods/ATM-8#874]

**Comment by Jonz00r** [comment]
Don't create new issues for mod suggestions. use pinned issue #3

**Comment by Yslohr** [comment]
Similar to an idea I had a few years ago you can see on Lumien's randomthings page. I should really finish that mod.

**Comment by AfkUserMC** [comment]
> Don't create new issues for mod suggestions. use pinned issue #3

Sorry, I'm not directly suggesting a mod so I thought it would fit here

**Comment by taj1994** [comment]
> Don't create new issues for mod suggestions. use pinned issue #3

I wouldn't call this a mod suggestion, since they're not asking for a mod to be added. They're asking for an extra curio slot to hold your Time in a Bottle
