### ISSUE TITLE
[1.0.10] Very strange world-specific bug

### ISSUE THREAD

**Issue by reddragon7799** [AllTheMods/ATM-8#875]
I'm experiencing a very weird, game-breaking bug (or multiple bugs) that makes everything see-through and uninteractable, as well as making commands not run (this also extends to, for example, using JEI to give items and teleporting via the Journeymap right click > teleport. Parts of the world (I think naturally-spawned blocks?) also have no collision, and you simply fall into the void - although you don't take any damage, even after falling around 7,000 blocks. Furthermore, I can't access inventories (sophisticated backpacks, the Curios inventory, or my Refined Storage network remote), my armor bar is empty, despite wearing diamond+ gear, and blocks do not drop anything when mined. I could not tell you if I did anything to cause it to get like this - it was working fine until this started happening, and the world remains bugged in spite of repairing the profile and restarting my computer.
It doesn't affect newly-created worlds, only an existing one. I'd like to be able to save/fix that world, though, because I've gotten really far in it. There's no crash report because the game still runs, technically. I posted in the discord but nobody answered and I figured I may as well try here.
Screenshot: https://imgur.com/hHtLEEI
Latest Log: https://mclo.gs/gAEE6Di

**Comment by James103** [comment]
Try running the profiler built into the Spark mod for a couple minutes (`/spark profiler start`, wait a minute, then `/spark profiler stop`), then post the resulting profiler output link here.

**Comment by reddragon7799** [comment]
Here's a link to the Spark output: https://spark.lucko.me/mswiuvgmal

**Comment by reddragon7799** [comment]
Can you parse any of it?

**Comment by reddragon7799** [comment]
Anyone?
