### ISSUE TITLE
The game crashes when the world starts

### ISSUE THREAD

**Issue by bugagagag** [AllTheMods/ATM-8#877]
Out of 5 people, only 3 people were able to enter our server, the rest of the game crashes when the world starts. They have the same mistakes.
[debug (2).log](https://github.com/AllTheMods/ATM-8/files/10700598/debug.2.log)
[latest (4).log](https://github.com/AllTheMods/ATM-8/files/10700602/latest.4.log)
[crash-2023-02-09_22.00.58-client (1).txt](https://github.com/AllTheMods/ATM-8/files/10700608/crash-2023-02-09_22.00.58-client.1.txt)

**Comment by Mitchell5200** [comment]
I think i just spoke to you in Discord, but i'll answer it again, 
It looks like the crashing clients are using the wrong forge version, get them changed to 43.2.3
