### ISSUE TITLE
nether and end portals not working

### ISSUE THREAD

**Issue by tsunam1tv** [AllTheMods/ATM-8#886]
I have a 2 week old server with friends and today we found out we couldn't enter the nether or end anymore. tried to break the portals and remake but couldn't get anything to work. pls help. still can access the other through waystones but cant get back into the nether or the end.

**Comment by dorin6565** [comment]
I had this issue.  What fixed mine was removing everything from your extended inventory slots (backpack, gloves, artifacts, etc).  After the nether/etc. is generated you can put the items back in the slots and the portals will work fine after that.

**Comment by tsunam1tv** [comment]
Tried that and when I sit in the portal it just does the vision blurring animation and doesn't try to tp me to the nether

**Comment by James103** [comment]
What do you get if you try running `execute in the_nether if entity @s`?
If you get the error message "Unknown dimension 'minecraft:the_nether'", that means your Nether and End dimensions are completely inaccessible.

**Comment by tsunam1tv** [comment]
I got that error message, is there any way to recover the dimensions?

**Comment by crippa1337** [comment]
![nether_fix](https://user-images.githubusercontent.com/111508533/221022187-06c9bcab-4d73-4a82-88c5-0b73ad21543c.png)

This worked for me. @tsunam1tv

**Comment by James103** [comment]
> you'll need to open lan with cheats to obtain it

That's actually not required if you are in singleplayer; `/seed` is special-cased to be runnable by a player in a singleplayer world even if cheats are off.

**Comment by crippa1337** [comment]
Doesn't really matter

**Comment by vascorito** [comment]
@crippa1337 that saved my hardcore world!!!! ty so much <3333
i removed a mod from my game and the end dimension was removed from the game. i could not enter any end portal.
that saved me :)
