### ISSUE TITLE
Crashing on World Startup (after "Reading World Data")

### ISSUE THREAD

**Issue by MellowMars** [AllTheMods/ATM-8#888]
I'm quite a bit of ways into my current world and haven't had any issues and when I was mining I had started experiencing some lag spikes so I had saved and exited then when I went to join back into the world, it would not join. Every time I try to join, it says "Reading World Data" then when the text disappears the world never starts and stays on the empty green loading screen and a crash report appears in the files. I tested joining several of my worlds and they all never start up after "Reading World Data."
I've restarted my computer, removed my shaders just incase and even lowered some graphical settings but nothing solved it.

Here is my crash log if anyone can find the issue-
[crash-2023-02-12_10.47.22-server.txt](https://github.com/AllTheMods/ATM-8/files/10716471/crash-2023-02-12_10.47.22-server.txt)

**Comment by James103** [comment]
Try renaming the config file `ars_nouveau/glyph_craft.toml` in your `serverconfig` folder for the world you're trying to join.
If that doesn't work, try renaming the config file in the same path in your `defaultconfigs` folder as well.

**Comment by etg-k** [comment]
i have the same issue that hasnt gone for a week now and have just seen this post. i am new to computer and modded stuff so could you be more specific like what do i rename it too.
Thank you very much i really appreciate it as i am addicted to my world and being unable to play is driving me crazy
