### ISSUE TITLE
Mod Consideration: Just Enough Calculation

### ISSUE THREAD

**Issue by deathhancox** [AllTheMods/ATM-8#889]
I'm genuinely surprised this mod isn't considered by default. It's generally very well balanced and exceptionally helpful, adding in a standard calculator and a calculator for determining what base materials will be needed for any given craft based on the provided recipes. I would be ecstatic if you'd consider adding it to the pack as my friend refuses to install external mods.

https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation

**Comment by OneblockNation** [comment]
im for it

**Comment by James103** [comment]
Firstly, mod suggestions should be posted as a comment in #3.
Secondly, as long as you encode the required patterns, AE2 and Refined Storage is already able to calculate the crafting cost for almost any item on request.
