### ISSUE TITLE
I cant craft RS silicon or smelt it

### ISSUE THREAD

**Issue by Xplodin** [AllTheMods/ATM-8#89]
0.1.0
RS silicon is uncraftable and quartz only makes AE silicon

**Comment by LukeSchmidtler** [comment]
I was about to post the same issue haha. Thx.

**Comment by starixed** [comment]
yup same here

**Comment by aAndrew3030** [comment]
In the config for "almostunified" removing "ae2" fixes the issue

**Comment by starixed** [comment]
i had to do that plus remove silicon from the config in order for it to work

**Comment by whatthedrunk** [comment]
fixed in 0.1.1 that just came out

**Comment by aAndrew3030** [comment]
This is still a issue (maybe just on servers?) as ae2 is still given priority in the unify config file, regardless if RS is properly tagged
