### ISSUE TITLE
FTB Chunks Force Claim not working or bugged?

### ISSUE THREAD

**Issue by IkarosXenano** [AllTheMods/ATM-8#890]
When I had updated the pack to 1.0.10, my claimed forced loaded chunks just no longer to be forcefully loaded? I've tried un-claiming and reclaiming them, then doing the same with the forced loading and it still does not seem to work. I've also tried downgrading to a previous version to see if it was just the update. 
But it still does not work, is there anyway I can fix this problem or any ideas onto why it has stopped working?

**Comment by transbiod** [comment]
I can confirm that chunks do not load properly with ftb claiming

**Comment by transbiod** [comment]
Have you tried shift-righ click?
