### ISSUE TITLE
Floating yellow squares, and i cant break blocks in specific areas. ATM8 

### ISSUE THREAD

**Issue by CuzzoOf740** [AllTheMods/ATM-8#891]
Hello!, Ive found two areas (both in heavy snow areas) where my screen gets these yellow squares and i cant break blocks or do anything in the area. i thought maybe i had to unlock something, until the player i am playing with went to the same area and it was fine. 
![9tt48obxvxha1](https://user-images.githubusercontent.com/125243396/218386167-e5ece38c-5ea5-44b8-b8e3-ca0bf82653ab.jpg)

**Comment by AfkUserMC** [comment]
Hey! This isn't a bug, and you DO have to unlock it. Go to the Twilight Forest Quest Category for help.

**Comment by EndiKM** [comment]
I have this problem too, but in my case I had already defeated other bosses with my friend, such as Hydra, but earlier my world crashed and my friend didn't have yellow squares, and I do and I specially defeated all the bosses again and it still doesn't work.
