### ISSUE TITLE
server startup works on windows but not mac

### ISSUE THREAD

**Issue by choploaf** [AllTheMods/ATM-8#892]
I've been hosting my server on windows with no problems but once I transfer the server files to my mac and try running it, I'm met with two repeating errors:

"[Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /Users/bob/Desktop/Server-Files-1.0.10/config/silentgear-common.toml is not correct. Correcting"
and
"[Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /Users/bob/Desktop/Server-Files-1.0.10/./world/serverconfig/dimstorage-server.toml is not correct. Correcting"

thanks.

**Comment by ericci3** [comment]
I also have the same issue and only see it on Mac. I am able to launch and play on the world, but it is annoying to see the spam in the console. 

I’ve tried deleting the .toml files and their backups and relaunching, but this has not worked. I’ve even tried starting a server from scratch on Mac and these errors still persist.
Any help would be appreciated!

**Comment by scrimmie** [comment]
I am observing the same behavior.

**Comment by choco-green** [comment]
same issue, it is indeed a quality of life bonus, observed for atm5, 6, and 7
