### ISSUE TITLE
Ars Nouveau Bad Interactions (Crashes games sometimes permanent)

### ISSUE THREAD

**Issue by GloomGoozler** [AllTheMods/ATM-8#894]
Shooting a enchanters bow at a chest creates a null exception and will crash the game.

Creating decoys on any Ad-Astra planet will crash the game and require the dimension to be reset to fix.

**Comment by James103** [comment]
Do you have the corresponding crash reports (there should be two)? If so, can you please post them here?

**Comment by Topbobtop** [comment]
I was looking for a fix for the second crash (summon decoy on Ad-Astra planet,) here is my crash log for that issue.
[crash-2023-02-15_00.08.06-server.txt](https://github.com/AllTheMods/ATM-8/files/10739555/crash-2023-02-15_00.08.06-server.txt)

**Comment by Topbobtop** [comment]
For anyone who finds this thread, I was able to "fix" it without resetting the dimension by removing the Ars Nouveau jar, loading the server, and then reinstalling Ars Nouveau. It does, of course, remove or corrupt the Ars Nouveau items loaded in the world while the jar is gone but that was a better tradeoff than resetting the dimension for me.
