### ISSUE TITLE
Game not loading after clicking "play"

### ISSUE THREAD

**Issue by lucasrgolino** [AllTheMods/ATM-8#895]
The game is crashing instantly after I hit "play". The only thing it says is "An expected issue occurred and the game was crashed. We're sorry for the inconvenience".
Already tried:
- updating drivers
- reinstalling the entire modpack
- changing the dedicated RAM
- Downloading other versions of JAVA
Here's the crash report:
[hs_err_pid15956.log](https://github.com/AllTheMods/ATM-8/files/10728498/hs_err_pid15956.log)

Any help is appreciated :)

**Comment by Mitchell5200** [comment]
AMD driver crashes, update
