### ISSUE TITLE
Game crashes while loading chunks

### ISSUE THREAD

**Issue by kingofeverything2** [AllTheMods/ATM-8#897]
I have an issue where the game occasionally just freezes while its loading in chunks, and then will eventually just crash. I opened the log and tried to find the source, I believe its due to not having enough memory, but I have 16GB of ram, is that not enough? It also could be the CPU but I have a fairly good CPU so I'm confused.

**Comment by James103** [comment]
Do you still have the log and/or crash report? If so, can you please post them here?

**Comment by Narkitos** [comment]
> У вас все еще есть журнал и/или отчет о сбое? Если да, то не могли бы вы опубликовать их здесь?

I have exactly the same problem
[latest.log](https://github.com/AllTheMods/ATM-8/files/10768318/latest.log)

**Comment by etg-k** [comment]
even if you have 16G the game may only be using 4G so you have to change the amount of ram the game is allowed to use

**Comment by Narkitos** [comment]
> even if you have 16G the game may only be using 4G so you have to change the amount of ram the game is allowed to use

i have 8 gb for Game on Launcher Settings, is that not enough ?
Some body know how read Log ?

**Comment by gnomuk** [comment]
i have 16gb, but i changed a java version and this bug was fixed

**Comment by Narkitos** [comment]
> i have 16gb, but i changed a java version and this bug was fixed

What version are you using?

**Comment by gnomuk** [comment]
version was 1.8.0_361 (after crash this version is not worked, and i changed version to 18.0.2.1)

**Comment by Narkitos** [comment]
> I have an issue where the game occasionally just freezes while its loading in chunks, and then will eventually just crash. I opened the log and tried to find the source, I believe its due to not having enough memory, but I have 16GB of ram, is that not enough? It also could be the CPU but I have a fairly good CPU so I'm confused.

I bought an additional 16 GB of RAM, the crashes stopped. According to my approximate measurements, you need at least 9 GB, and preferably 12 dedicated RAM with 8 chunks Render Distance
