### ISSUE TITLE
All The Tweaks Crash

### ISSUE THREAD

**Issue by vexica192** [AllTheMods/ATM-8#9]
Mod load error when trying to launch.
Probably helpful to note this is on an apple silicon M1 Max laptop, so I'm aware I might be fresh out of luck for the moment, just hoping there might be some sort of solution going forward
[crash-2022-09-03_08.52.34-fml.txt](https://github.com/AllTheMods/ATM-8/files/9482620/crash-2022-09-03_08.52.34-fml.txt)

**Comment by vexica192** [comment]
It launches with all the tweaks removed so as long as that's just visual background stuff I'm fine to just remove it

**Comment by Mitchell5200** [comment]
This is still an issue that needs to be open

**Comment by vexica192** [comment]
Ok!

**Comment by jimmyjimmy9** [comment]
I am having the same issue on an Intel Mac have tried re-installing etc, unfortunatly I can't remove the mod as am planning to play it on the server network I currently play a different pack on
[crash-2022-09-07_13.12.43.txt](https://github.com/AllTheMods/ATM-8/files/9506120/crash-2022-09-07_13.12.43.txt)

**Comment by jimmyjimmy9** [comment]
I personally am limited to the version used by the server; I'm guessing it's something that the pack makes would try and fix in time?

**Comment by thevortex** [comment]
what version does the server have you are trying to join

**Comment by jimmyjimmy9** [comment]
0.0.3

**Comment by thevortex** [comment]
no sorry what version of all the tweaks is in your mods folder

**Comment by jimmyjimmy9** [comment]
allthetweaks-2.0.0-1.19.2-43.1.3.jar

this is for modpack version 0.0.4

**Comment by thevortex** [comment]
> allthetweaks-2.0.0-1.19.2-43.1.3.jar
> 
> this is for modpack version 0.0.4

please try using this build and let me know if it works https://cdn.discordapp.com/attachments/726213423830007830/1017988815736025098/allthetweaks-2.0.0-1.19.2-43.1.3.jar

**Comment by jimmyjimmy9** [comment]
same issue im afraid

**Comment by majorpayne0055** [comment]
Having the same issue. The build above errored out as well.

**Comment by nskobelevs** [comment]
Also confirming the issue for M1 Mac.

[logs](https://mclo.gs/50U4nyF)

**Comment by thevortex** [comment]
will get you to try this, it has the loading screen fully disabled https://cdn.discordapp.com/attachments/726213423830007830/1017111225613701263/allthetweaks-2.0.0-1.19.2-43.1.3.jar

**Comment by nskobelevs** [comment]
That jar seems to have fixed the issue and the game reaches the main menu via the Curse Launcher.

---

I have come across something interesting since my previous reply:

I use a third-party launcher as a nicer instance manager with better Apple Silicon support.
I think the launcher applies patches and ships versions of lwjgl for this? Not too sure on this details.

Originally I was using ManyMC. Since my reply I realised it was no longer maintained and switched to PolyMC.

While ManyMC isn't maintained anymore and isn't worth supporting, I thought it was interesting that PolyMC didn't run into this issue and the modpack worked out of the box.

The original status of the issue is:
PolyMC: ✅  Main Menu
Curse Launcher: ❌ Fails
ManyMC: ❌  Fails

After the above replacement jar:
PolyMC: ✅ Main Menu
Curse Launcher: ✅ Main Menu
ManyMC: ❌ Fails [[logs if you want em](https://mclo.gs/BmkdgMi)]

**Comment by thevortex** [comment]
good lord that just made this issue all the more confusing... very interesting tho that it works out of the box in PolyMC without needing adjustments. thanks for this extra info!

**Comment by thevortex** [comment]
@majorpayne0055 @jimmyjimmy9  can i get you both to try launching the pack using PolyMC instead and see if it works as expected?

**Comment by nskobelevs** [comment]
> @majorpayne0055 @jimmyjimmy9 can i get you both to try launching the pack using PolyMC instead and see if it works as expected?

In case it affects things, I did follow the instructions on https://github.com/MinecraftMachina/ManyMC to set `https://minecraftmachina.github.io/meta-multimc-arm64/` as the Metadata Server in Settings > APIs

**Comment by mfreeman612** [comment]
not working with curseforge + latest jar posted here on osx + apple silicon

**Comment by 8w-gremlin** [comment]
Yeah I have the same issue,  Mac(intel) osx 
says 
<img width="475" alt="Screen Shot 2022-09-23 at 1 18 58 PM" src="https://user-images.githubusercontent.com/55901363/191876618-91a81012-c142-4a50-87c5-62219f8ac49a.png">

**Comment by thevortex** [comment]
try launching with PolyMC

**Comment by indygwyn** [comment]
Still an issue in 0.0.11 on macOS Intel
my fix is to just remove it from the mods folder on client and server, will update you with next release

**Comment by thevortex** [comment]
try updating allthetweaks to 2.0.1 and let me know if issue remains

**Comment by indygwyn** [comment]
I just updated to 0.0.12 which has 2.0.1, same crash

**Comment by swardhagen** [comment]
Same issue here, crash every time when allthetweaks 2.0.1 is in the mod folder. As soon as I remove it the game loads again. I'm running ATM8 0.0.12 on CurseForge on OSX.

**Comment by thevortex** [comment]
i have at least one confirmation that this build https://cdn.discordapp.com/attachments/1024148493427802153/1024148578542817361/allthetweaks-2.0.1-1.19.2-43.1.3.jar is working, can you all please confirm?

**Comment by indygwyn** [comment]
Just dropped this build in my atm8 0.0.12 curseforge instance and no crash.

Also just updated my instance to 0.0.14 and that also looks to have fixed the crashes on macOS wrt allthetweaks

**Comment by thevortex** [comment]
great! thanks for your patience with this
