### ISSUE TITLE
After update to 0.1.0 all jetpacks are missing !!!!!!

### ISSUE THREAD

**Issue by mstefan21** [AllTheMods/ATM-8#91]
After update to 0.1.0 all jetpacks are missing !!!!!!

**Comment by mstefan21** [comment]
In JEI from jet packs mod, I can see only Leather Strap and 4 typ od Coil. Jetpack in my inventory showing "Undefined Jetpack".

Game is unplayable now!!!!!

**Comment by lmasss** [comment]
Same,no more jetpack will not be able to get unobtainium in the end without it

**Comment by whatthedrunk** [comment]
fixed in 0.1.1 that just came out
