### ISSUE TITLE
Quest Problem

### ISSUE THREAD

**Issue by ShadowRL76** [AllTheMods/ATM-8#910]
Inside the quest getting started and then further into "Basic Ingots" Theres no way to get the exact tin you need without ore dictionary. which is way outdated. I could be wrong but any help would be nice!

**Comment by Mitchell5200** [comment]
The "Basic ingots" quest inside of "Getting started p1" asks for "Iron ingots", "Gold ingots", and "Redstone dust". there's no mention of tin there, at least in 1.0.11, and i cannot see any mention of tin anywhere in the change history of that quest.
![2023-02-19_17 51 14](https://user-images.githubusercontent.com/45913837/219940955-361cc4b2-f516-4362-a108-992ad33390fa.png)

**Comment by ShadowRL76** [comment]
Well could be something I added possibly im in 1.0.10. I did add a few mods but is there any mod that works like ore dic or at least changes it where theres not 3 different tins generation

**Comment by Mitchell5200** [comment]
this might be an install issue, as we remove the different extra metals via KubeJS and the mod "AlmostUnified", ensure when updating that the folders "configs", "kubejs", "mods", and "defaultconfigs" are fresh installed each time if on a server

**Comment by ShadowRL76** [comment]
Judging from the server was made just yesterday ide say all the files are fresh. But even then going through the pain of all that sounds terrible. Thanks for the responses though.

**Comment by ShadowRL76** [comment]
![MedalTVMinecraft20230219055138-tr-edit](https://user-images.githubusercontent.com/17054056/219944287-5d1cdb8e-1e53-4646-8fb7-8f4078ce37c3.jpg)

**Comment by Mitchell5200** [comment]
I stand corrected, there was tin there in pre1.0.11, but it should've been ATO tin, and that should be the only tin available ingame

**Comment by ShadowRL76** [comment]
Also while on the subject I cant make copper gears for some reason from mekanism. I went into a totally separate world out of the server to test if I was crazy.

**Comment by ShadowRL76** [comment]
To be fair I guess the best thing I can do is probably backup the server and update to .11

**Comment by ShadowRL76** [comment]
So I figured out how to get just about everything working I updated the pack and I have the same world. But is there a way to keep all my old sutff me a friend grinded for the past day for?

**Comment by Mitchell5200** [comment]
yes, you keep the world folder from the previous version of the server

**Comment by ShadowRL76** [comment]
YESSS i quite literally went through every individual file and added each data file and etc to get it and got it working i havent slept . I might have fell asleep a few times doing it and I cant even remember 2 mins ago but I have it working with all my stuff thank you for your fast replies.  sorry for bad grammar havent slept lol

**Comment by ShadowRL76** [comment]
Btw found a bug when you shift and pick things up the item is invisble!!!!!
