### ISSUE TITLE
[1.0.11]Game crashing upon joining server(Log mentions Ars Elemental)

### ISSUE THREAD

**Issue by Pokenar** [AllTheMods/ATM-8#920]
I am posting this on a friend's behalf, they are having an issue where they are crashing during the join process of a server, the error log seems to involve Ars Elemental

For what it is worth, I am able to join fine, I also already instructed him to set the ram to the same amount I have, I also instructed him to delete the pack and redownload.

[latest (2).log](https://github.com/AllTheMods/ATM-8/files/10781765/latest.2.log)

**Comment by Mitchell5200** [comment]
Please forward this onto the Ars elemental devs
https://github.com/Alexthw46/Ars-Elemental/issues
