### ISSUE TITLE
Server not connecting to internet / Auth servers

### ISSUE THREAD

**Issue by RealRainbuu** [AllTheMods/ATM-8#929]
This is specifically an issue with the server files in ATM8 and this also happened in ATM7, even though it doesn't happen to any other pack. Every time my friend or I tries to join, its throws an error of "The authentication servers are currently not reachable."
![image](https://user-images.githubusercontent.com/77862418/220212719-f9132fde-6266-4a5d-a04f-d717d6d44e05.png)

**Comment by Migno** [comment]
I guess you have the server saved. We had this issue for a while and found a "workarround".
Simply connect to your sever and you will get that message, go back to the Server list and click "refresh", wait until the
player count shows up and connect again. Worked 100% for our players.

**Comment by fkempf78** [comment]
I encountered the same Problem and was able to fix it by removing the IPv6 Adress of my DynDNS Account.

**Comment by daymondsama** [comment]
i also encountered this problem so i tried restarting the game, reseting the firewall, reinstalling the modpack, reseting my wifi, i also tried the solution told by migno but none worked, what can i do
