### ISSUE TITLE
[1.0.11] Game crashing when joining the server

### ISSUE THREAD

**Issue by jaahaavi** [AllTheMods/ATM-8#930]
Last Sunday my friend had problems with crashing when joining my dedicated All the mods 8 server. He got it working after reinstalling all the mods 8 from the CurseForge.
Yesterday my game crashed after playing it more than hour and now I can't get back to server. When I join the server I can get back to game but the game screen only flashes and then it instantly takes me back to windows screen whith message "Error game crashed... exit code: 1".
I already tried and reinstalled all the mods 8 from CurseForge but it didn't help. 

Server log only has these lines:
[08:58:00] [Netty Epoll Server IO #8/WARN] [co.co.Connectivity/]: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[08:58:00] [Netty Epoll Server IO #8/WARN] [co.co.Connectivity/]: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe

Client error log:
[hs_err_pid3208.log](https://github.com/AllTheMods/ATM-8/files/10790707/hs_err_pid3208.log)

**Comment by drakray** [comment]
I have the same problem on my dedicated server in 1.0.13

**Comment by jaahaavi** [comment]
My issue was caused by the Nvidia drivers. Yesterday they published drivers (GeForce Game Ready 531.18) that fixed the issue.

There was also a way to make ATM8 work by disabling these mods on the client side CurseForge:
model gap fix
oculus
rubidium
rubidium dynamic lights
rubidium extras
