### ISSUE TITLE
[1.0.11] Missing image/model for Mekanism Induction Matrix in quest book

### ISSUE THREAD

**Issue by XDelta** [AllTheMods/ATM-8#931]
Located in the quest book AllThePower>BasicPower>"Need More Storage?"
![image](https://user-images.githubusercontent.com/7883807/220297821-452de3db-28c1-463f-bc0b-74f3ee454432.png)

**Comment by Mitchell5200** [comment]
yes we noticed it after we released 1.0.11, it's fixed for 1.0.12 when we do that update
https://github.com/AllTheMods/ATM-8/pull/925

**Comment by XDelta** [comment]
Oh awesome!
