### ISSUE TITLE
Consistent crash loop 1-2 hours into the gameplay.

### ISSUE THREAD

**Issue by FrancisAinswoth** [AllTheMods/ATM-8#933]
I have an issue where my game is crashing. I don't have any extra mods installed. These crashes are very consistent, as soon as I load into my survival world (I've been playing on it for 1-2h without any issues beforehand), around 12 seconds later it crashes, I timed it with an app too, it crashes at the exact same time every time. What's more is that I had a world before this, I also played on it for a few hours and then it started crashing exactly 3 minutes and 27 seconds from my login. So it's seemingly the same issue. I create a world, play for a few hours, and then get stuck in a crash loop. This survival world is being played by two players via LAN, Hamachi. I was the one who created the world initially, and while trying to fix the issue, I sent the save file to my friend and we tried to play from his host. Oddly enough he was able to stay in the world, while I kept crashing. So it's not an issue with the world save I guess. I attached the crash log. (I am using CurseForge with the most recent version of ATM8, and Windows 11. I tried other launchers as well, same thing).

[message.txt](https://github.com/AllTheMods/ATM-8/files/10793976/message.txt)

**Comment by kealang12** [comment]
YES I have the exact same issue please lmk if you hear anything. Mine crashes after a while then once it crashes it crashes every time I open the world like every 2 min

**Comment by FrancisAinswoth** [comment]
> YES I have the exact same issue please lmk if you hear anything. Mine crashes after a while then once it crashes it crashes every time I open the world like every 2 min

Alright so the best fix I found myself is downgrading the version, downgrading it 2 versions down helped me fix the issue. Try downgrading it one version at a time and see if it fixes itself, my worlds still run fine.

But I'll still keep this open, since I'd still like some help on this issue, because I want to play the newest release.
