### ISSUE TITLE
Black particles and Mekanism exit bug

### ISSUE THREAD

**Issue by gnomuk** [AllTheMods/ATM-8#935]
black particles after pick up a block, how fix this?

after exit spam this strokes:
[Server thread/ERROR] [me.co.Mekanism/]: Different orphan transmitter was already registered at location! [Coord4D: -739, 69, -872, dim=minecraft:overworld]

**Comment by gnomuk** [comment]
game randomly crashed and black particles bug was fixed, wtf

**Comment by transbiod** [comment]
I found out that the culprit is Radon mod

**Comment by transbiod** [comment]
Allegedly

**Comment by Wolfsthrope** [comment]
I'm getting this on my server now, removing the Radon mod did nothing.

**Comment by RoyalReject** [comment]
I have noticed if I launch the game in window mode and then join the server I am playing still in window and then break a block, I am then able to go into full screen and not have issues with black particles
