### ISSUE TITLE
Alkemestry reactor / refined storage

### ISSUE THREAD

**Issue by Noleafclover117** [AllTheMods/ATM-8#936]
![Screenshot (1)](https://user-images.githubusercontent.com/126007326/220423702-c44e6e55-603c-4587-8056-150561223237.png)

**Comment by James103** [comment]
Do you still have the crash report? If so, can you please post the full crash as a text file instead of an image?

**Comment by JushWalker** [comment]
Hey I am on this server and after getting it back up I removed the refined storage part of this equation and tried to plug a Mekanism pipe to the Alkemestry Reactor and crashed the server again.

**Comment by Mitchell5200** [comment]
okay, please use https://mclo.gs/ for the server crash logs, and pass this onto the Alchemistry devs
https://github.com/SmashingMods/Alchemistry/issues

**Comment by callumok2004** [comment]
This issue has been resolved in the latest Alchemistry release which is included in 1.0.12
