### ISSUE TITLE
I removed a trash can and then the whole server crashed

### ISSUE THREAD

**Issue by blackBusterH** [AllTheMods/ATM-8#940]
I made a mob crusher and linked it to a chest which had a item pipe on top with a trash can then i removed the chest and the pipe and when i removed the trash can the server crashed.
This is the crash log, i couldn't paste it because it was too long.

[crash-2023-02-22_17.33.21-server.txt](https://github.com/AllTheMods/ATM-8/files/10806715/crash-2023-02-22_17.33.21-server.txt)

**Comment by James103** [comment]
1. Try changing `max-tick-time` in `server.properties` to `-1` and restart your server.
2. Are you able to reproduce this server hang?

**Comment by blackBusterH** [comment]
Imma try this, but i restarted the server and it is now working normally again.
