### ISSUE TITLE
Crashing after loading into a world

### ISSUE THREAD

**Issue by dillob-tillob** [AllTheMods/ATM-8#943]
When I load into my single player world after updating to 1.0.11, I can load in just fine. Its whenever I to walk to one said of my 9x9 base that my game just crashes. Likewise, my friends server that is also 1.0.11 I keep crashing shortly after joining. Here's the log. any input would be appreciated.

https://mclo.gs/jaMSSNs

**Comment by Nobody931** [comment]
I had the crash a few times as well, after setting particles to "minimal" and render to "fast" it seems to work for now.

**Comment by dillob-tillob** [comment]
> I had the crash a few times as well, after setting particles to "minimal" and graphics to "fast" it seems to work for now.

Unfortuantely, that didn’t workZ I just went back to 1.0.10 for now until they update the pack again

**Comment by BLU13** [comment]
i have been having this issue as well, but weirdly its only when i attempt to leave my underground base and go to the surface
