### ISSUE TITLE
ATM8 Crashing for some reason

### ISSUE THREAD

**Issue by wheredafuq** [AllTheMods/ATM-8#944]
I've been playing on a singleplayer world for a little while now with no issues. Once I got to the "The Other" Teleport pad, it had crashed for the first time. I had assumed it was something I had in my inventory, or had equipped, so I decided to go in with nothing but food. This Worked. So, as time went by and I went back and forth to "The Other" to loot structures and such, I brang with me other kinds of items until it crashed again, to try to narrow it down. Then it also started happening with the Nether. It soon got worse and worse to the point where it would crash ~30sec after loading into the world. Is it a memory problem, or is there some sort of conflict with the one mod I added to the pack. Idk. Please help.
https://mclo.gs/AQHGBqY
Idk if you need any other crash reports, but they all looked the same to me.

**Comment by shadydeath** [comment]
If you're on 8-1.0.11, try 8-1.0.10 instead - This resolved my crashing with the same access violation code and DLL

**Comment by wheredafuq** [comment]
> try 8-1.0.10 instead 
Unfortunately, I'm already on 8-1.0.10.

**Comment by wheredafuq** [comment]
> If you're on 8-1.0.11, try 8-1.0.10 instead - This resolved my crashing with the same access violation code and DLL

Unfortunately, I'm already on 8-1.0.10.
