### ISSUE TITLE
Cobbled Deepslate Block 1x recipe does not work

### ISSUE THREAD

**Issue by HugPhiluu** [AllTheMods/ATM-8#945]
Hello!
The recipe appears to be somewhat bugged?
When attempting to craft Cobbled Deepslate Block 1x, it actually gives me Cobblestone Block 1x as a result.
In the crafter it consequently only gives me cobblestone, and when you pay close attention in the gif linked below, you can even see it become cobblestone for a second before switching to deepslate

https://gfycat.com/ColdLongGoosefish

![image](https://user-images.githubusercontent.com/97440819/220839655-a90267c4-a697-4bf3-b5e8-ff81125f3686.png)

**Comment by HugPhiluu** [comment]
I managed to fix it by restarting the server. But the issue itself is inherently weird :U

**Comment by James103** [comment]
This is likely caused by a recipe conflict. "Cobblestone Block 1x" accepts any items in the `forge:cobblestone` tag, including regular cobblestone and deepslate, while deepslate is also used in crafting "Cobbled Deepslate Block 1x".
