### ISSUE TITLE
Advanced Peripherals Mod needs update

### ISSUE THREAD

**Issue by Saratoubi** [AllTheMods/ATM-8#947]
Several of the "peripherals" in advanced peripherals have issues with their implementation. The ME and RS bridges do not correctly transfer over items with NBT data, neither does the Inventory Manager. The Mod author has fixed these bugs in their latest release, so all that is needed is a mod update I believe.

**Comment by Mitchell5200** [comment]
The newer versions of that mod are not available for 1.19.2, and are instead for 1.19.3, so No, we cannot update to the newer versions

**Comment by JoaoRodrigoGoncalves** [comment]
There have been updates to the 1.19.2 branch of the mod since this issue was closed, backporting some features and bugfixes from the 1.19.3 and 1.18 branches.

Will the mod be updated on the pack with the next release @Mitchell5200? What would be the requirements for updating this mod if not?
