### ISSUE TITLE
im getting stuck at loading the server, am i doing something wrong? 

### ISSUE THREAD

**Issue by grandluaxe** [AllTheMods/ATM-8#95]
![image](https://user-images.githubusercontent.com/31015576/195639991-c67d75bc-3dbf-4871-b290-c2539e4d023f.png)

**Comment by guffelman** [comment]
Do you have more logs than this? Are you trying to update from 1.1.6 to 1.1.7? 
I was able to successfully update my server from old 1.1.6 to 1.1.7 and login. I would try removing your world and restarting the server.
