### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by CaptainAlekse** [AllTheMods/ATM-8#953]
Prism Launcher version: 6.3

Launched instance in offline mode

Minecraft folder is:
C:/Users/atrea/AppData/Roaming/PrismLauncher/instances/All the Mods 8 - ATM8/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/atrea/AppData/Roaming/PrismLauncher/instances/All the Mods 8 - ATM8/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech-natives-windows/1.13.9/text2speech-natives-windows-1.13.9.jar
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/mmc2/ForgeWrapper-mmc2.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarSelector/0.3.16/JarJarSelector-0.3.16.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarMetadata/0.3.16/JarJarMetadata-0.3.16.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/fmlloader/1.19.2-43.2.3/fmlloader-1.19.2-43.2.3.jar (missing)
  C:/Users/atrea/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:

Mods:
  [✔] [1.19.2] SecurityCraft v1.9.4
  [✔] absentbydesign-1.19-1.7.0
  [✔] ad_astra-forge-1.19.2-1.12.3
  [✔] Ad-Astra-Giselle-Addon-forge-1.19.2-1.12
  [✔] additional_lights-1.19-2.1.5
  [✔] AdditionalEnchantedMiner-1.19.2-19.10.6
  [✔] additionallanterns-1.0.3-forge-mc1.19
  [✔] AdvancedPeripherals-0.7.22b
  [✔] AdvancementPlaques-1.19.2-1.4.7
  [✔] advgenerators-1.4.0.5-mc1.19.2
  [✔] AE2-Things-1.1.1
  [✔] AE2WTLib-12.8.5
  [✔] AEAdditions-1.19.2-4.0.3
  [✔] AEInfinityBooster-1.19.2-1.2.0+11
  [✔] AIOTBotania-1.19.2-3.0.0
  [✔] alchemistry-1.19.2-2.2.3
  [✔] alchemylib-1.19.2-1.0.19
  [✔] AllTheCompressed-1.19.2-2.0.0
  [✔] allthemodium-2.1.6-1.19.2-43.1.1
  [✔] alltheores-2.0.2-1.19.2-43.1.3
  [✔] allthetweaks-2.0.4-1.19.2-43.1.3
  [✔] almostunified-forge-1.19.2-0.3.5
  [✔] AngelRing2-1.19.2-2.1.5
  [✔] antighost-1.19.1-forge42.0.1-1.1.3
  [✔] Apotheosis-1.19.2-6.0.3
  [✔] appleskin-forge-mc1.19-2.4.2
  [✔] Applied-Botanics-1.4.2
  [✔] appliedcooking-2.0.3
  [✔] appliedenergistics2-forge-12.9.2
  [✔] Applied-Mekanistics-1.3.4
  [✔] Aquaculture-1.19.2-2.4.8
  [✔] architectury-6.5.69-forge
  [✔] ars_creo-1.19.2-3.1.3
  [✔] ars_elemental-1.19.2-0.5.8.0
  [✔] ars_nouveau-1.19.2-3.12.1
  [✔] artifacts-1.19.2-5.0.1
  [✔] AttributeFix-Forge-1.19.2-17.1.3
  [✔] AutoRegLib-1.8.2-55
  [✔] balm-4.5.3
  [✔] BambooEverything-forge-2.2.4-build.33+mc1.19.2
  [✔] baubley-heart-canisters-1.19.2-1.2.3
  [✔] bdlib-1.25.0.5-mc1.19.2
  [✔] BetterAdvancements-1.19.2-0.2.2.142
  [✔] BetterF3-4.0.0-Forge-1.19.2
  [✔] biggerreactors-1.19.2-0.6.0-beta.6
  [✔] blockui-1.19-0.0.64-ALPHA
  [✔] blue_skies-1.19.2-1.3.20
  [✔] blueflame-1.19.2-0.1.0.2
  [✔] Bookshelf-Forge-1.19.2-16.2.17
  [✔] Botania-1.19.2-437-FORGE
  [✔] BotanyPots-Forge-1.19.2-9.0.27
  [✔] BotanyTrees-Forge-1.19.2-5.0.4
  [✔] botarium-forge-1.19.2-1.8.2
  [✔] buildinggadgets-3.16.1-build.15+mc1.19.2
  [✔] bwncr-forge-1.19.2-3.14.1
  [✔] cabletiers-1.19.2-0.5471
  [✔] caelus-forge-1.19.2-3.0.0.6
  [✔] cc-tweaked-1.19.2-1.101.2
  [✔] cfm-7.0.0-pre35-1.19.2
  [✔] charginggadgets-1.9.0
  [✔] charmofundying-forge-6.1.1+1.19.2
  [✔] chemlib-1.19.2-2.0.16
  [✔] clickadv-1.19.2-3.0
  [✔] cloth-config-8.2.88-forge
  [✔] Clumps-forge-1.19.2-9.0.0+14
  [✔] cofh_core-1.19.2-10.2.1.40
  [✔] comforts-forge-6.0.3+1.19.2
  [✔] CommonCapabilities-1.19.2-2.9.0
  [✔] compactmachines-5.1.0
  [✔] configured-2.0.1-1.19.2
  [✔] connectedglass-1.1.6-forge-mc1.19
  [✔] connectivity-1.19.2-3.4
  [✔] constructionwand-1.19.2-2.9
  [✔] Controlling-forge-1.19.2-10.0+7
  [✔] cookingforblockheads-forge-1.19.2-13.3.0
  [✔] corail_woodcutter-1.19.2-2.5.1
  [✔] CosmeticArmorReworked-1.19.2-v1a
  [✔] crafting-on-a-stick-1.19.2-1.0.3
  [✔] craftingtweaks-forge-1.19-15.1.0
  [✔] crashutilities-6.2
  [✔] create-1.19.2-0.5.0.i
  [✔] createaddition-1.19.2-20230202b
  [✔] creeperoverhaul-2.0.6-forge
  [✔] Croptopia-1.19.2-FORGE-2.2.2
  [✔] ctov-3.1.4
  [✔] Cucumber-1.19.2-6.0.6
  [✔] curios-forge-1.19.2-5.1.2.2
  [✔] CyclopsCore-1.19.2-1.17.5
  [✔] dankstorage-1.19.2-5.1.6
  [✔] DarkModeEverywhere-1.19.1-1.0.3
  [✔] DarkUtilities-Forge-1.19.2-13.1.7
  [✔] deeperdarker-forge-1.1.6-forge
  [✔] deepresonance-1.19-4.1.2
  [✔] DefaultSettings-1.19.x-2.8.7
  [✔] Delightful-1.19.2-3.2.2
  [✔] DimStorage-1.19.2-7.2.0
  [✔] domum_ornamentum-1.19-1.0.76-ALPHA-universal
  [✔] dpanvil-1.19.2-4.3.1
  [✔] dummmmmmy-1.19.2-1.7.0
  [✔] DungeonCrawl-1.19-2.3.11
  [✔] DungeonsArise-1.19.2-2.1.54-release
  [✔] dynamiclightsreforged-1.19.2_v1.4.0
  [✔] eccentrictome-1.19.2-1.9.1
  [✔] EdivadLib-1.19.2-1.2.0
  [✔] elementalcraft-1.19.2-5.5.10
  [✔] elevatorid-1.19.2-1.8.9
  [✔] elytraslot-forge-6.1.0+1.19.2
  [✔] enderchests-1.19-1.10.1b
  [✔] endertanks-1.19-1.12.1b
  [✔] energymeter-1.19.2-1.0.0
  [✔] engineersdecor-1.19.2-forge-1.3.28
  [✔] ensorcellation-1.19.2-4.2.0.14
  [✔] entangled-1.3.13-forge-mc1.19
  [✔] Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0
  [✔] entityculling-forge-1.5.2-mc1.19.1
  [✔] EvilCraft-1.19.2-1.2.15
  [✔] ExperienceBugFix-1.19-1.41.2.3
  [✔] ExtraDisks-1.19.2-2.2.0
  [✔] ExtraStorage-1.19.2-3.0.1
  [✔] extremesoundmuffler-3.35-forge-1.19.2
  [✔] FarmersDelight-1.19-1.2.0
  [✔] farmingforblockheads-forge-1.19-11.1.0
  [✔] farsight-1.19.2-2.1
  [✔] FastFurnace-1.19.2-7.0.0
  [✔] FastLeafDecay-30
  [✔] FastSuite-1.19.2-4.0.0
  [✔] FastWorkbench-1.19.2-7.0.1
  [✔] ferritecore-5.0.3-forge
  [✔] findme-3.1.0-forge
  [✔] flickerfix-1.19.1-3.1.0
  [✔] FluxNetworks-1.19.2-7.1.3.12
  [✔] FramedBlocks-6.7.0
  [✔] ftb-chunks-forge-1902.3.15-build.233
  [✔] ftb-essentials-1902.1.10-build.47
  [✔] ftb-industrial-contraptions-1900.1.7-build.212
  [✔] ftb-library-forge-1902.3.13-build.175
  [✔] ftb-quests-forge-1902.4.8-build.190
  [✔] ftb-ranks-forge-1902.1.14-build.70
  [✔] ftb-teams-forge-1902.2.12-build.95
  [✔] ftb-ultimine-forge-1902.3.5-build.65
  [✔] fuelgoeshere-1.19.2-0.1.0.0
  [✔] functionalstorage-1.19.2-1.1.3
  [✔] GameMenuModOption-1.19-1.18
  [✔] GatewaysToEternity-1.19.2-3.1.1
  [✔] geckolib-forge-1.19-3.1.39
  [✔] getittogetherdrops-forge-1.19.2-1.3
  [✔] glassential-forge-1.19-1.2.4
  [✔] GravitationalModulatingAdditionalUnit-1.19.2-2.8
  [✔] guardvillagers-1.19.2-1.5.2
  [✔] handcrafted-forge-1.19.2-2.0.2
  [✔] harvestwithease-1.19.2-4.0.0.3-forge
  [✔] HealthOverlay-1.19.2-7.2.1
  [✔] hexcasting-forge-1.19.2-0.10.3
  [✔] hexerei-0.2.5
  [✔] HostileNeuralNetworks-1.19.2-4.0.2
  [✔] Iceberg-1.19.2-forge-1.1.4
  [✔] ImmersiveEngineering-1.19.2-9.1.2-159
  [✔] industrial-foregoing-1.19.2-3.3.2.2-4
  [✔] IntegratedCrafting-1.19.2-1.1.0
  [✔] IntegratedDynamics-1.19.2-1.15.1
  [✔] integratednbt-1.19.2-1.6.0
  [✔] IntegratedTerminals-1.19.2-1.4.4
  [✔] IntegratedTunnels-1.19.2-1.8.18
  [✔] inventoryessentials-forge-1.19-5.0.0
  [✔] InventoryProfilesNext-forge-1.19-1.9.2
  [✔] ironfurnaces-1.19.2-3.6.5
  [✔] IronJetpacks-1.19.2-6.0.3
  [✔] itemcollectors-1.1.7-forge-mc1.19
  [✔] item-filters-forge-1902.2.9-build.46
  [✔] JCPlugin-1.18.x-1.19.x-2.8.7
  [✔] jei-1.19.2-forge-11.6.0.1010
  [✔] jmi-forge-1.19.2-0.13-30
  [✔] journeymap-1.19.2-5.9.3-forge
  [✔] jumpboat-1.19-0.1.0.5
  [✔] JustEnoughProfessions-forge-1.19-2.0.1
  [✔] JustEnoughResources-1.19.2-1.2.1.193
  [✔] kotlinforforge-3.10.0-all
  [✔] kubejs-forge-1902.6.0-build.142
  [✔] laserio-1.5.2
  [✔] LegendaryTooltips-1.19.2-forge-1.4.0
  [✔] letmedespawn-1.18.x-1.19.x-forge-1.0.3
  [✔] libIPN-forge-1.19-2.0.2
  [✔] LibX-1.19.2-4.2.8
  [✔] littlecontraptions-forge-1.19.2.0
  [✔] littlelogistics-mc1.19.2-v1.3.1
  [✔] lootr-1.19-0.3.22.59
  [✔] mahoutsukai-1.19.2-v1.34.39
  [✔] mcjtylib-1.19-7.1.5
  [✔] mcw-bridges-2.0.6-mc1.19.2forge
  [✔] mcw-doors-1.0.8forge-mc1.19.2
  [✔] mcw-fences-1.0.7-mc1.19.2forge
  [✔] mcw-lights-1.0.5-mc1.19.2forge
  [✔] mcw-roofs-2.2.2-mc1.19.2forge
  [✔] mcw-trapdoors-1.0.8-mc1.19.2forge
  [✔] megacells-forge-2.0.0-beta.7-1.19.2
  [✔] Mekanism-1.19.2-10.3.8.477
  [✔] MekanismGenerators-1.19.2-10.3.8.477
  [✔] MekanismTools-1.19.2-10.3.8.477
  [✔] merequester-1.19.2-1.0.3
  [✔] minecolonies-1.19.2-1.0.1247-BETA
  [✔] mininggadgets-1.13.0
  [✔] mob_grinding_utils-1.19.2-0.4.47
  [✔] modelfix-1.8
  [✔] modnametooltip-1.19-1.19.0
  [✔] modonomicon-1.19.2-1.25.0
  [✔] modular-routers-1.19.2-10.2.0-3
  [✔] moonlight-1.19.2-2.2.7-forge
  [✔] moredragoneggs-3.2
  [✔] moreoverlays-1.21.5-mc1.19.2
  [✔] Morph-o-Tool-1.6-34
  [✔] MouseTweaks-forge-mc1.19-2.23
  [✔] multipiston-1.19.2-1.2.21-ALPHA
  [✔] myrtrees-forge-1.2.0-build.31
  [✔] MyServerIsCompatible-1.19-1.0
  [✔] MysticalAgradditions-1.19.2-6.0.2
  [✔] MysticalAgriculture-1.19.2-6.0.8
  [✔] MysticalCustomization-1.19.2-4.0.1
  [✔] naturalist-forge-2.1.1-1.19.2
  [✔] NaturesAura-37.7
  [✔] NaturesCompass-1.19.2-1.10.0-forge
  [✔] netherportalfix-forge-1.19-10.0.0
  [✔] NoChatReports-FORGE-1.19.2-v1.5.1
  [✔] nomowanderer-1.19.2_1.3.6
  [✔] observable-3.3.1
  [✔] occultism-1.19.2-1.70.0
  [✔] oculus-mc1.19.2-1.2.8a
  [✔] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13
  [✔] PackMenu-1.19.2-5.1.0
  [✔] Patchouli-1.19.2-77
  [✔] paucal-forge-1.19.2-0.5.0
  [✔] phosphophyllite-1.19.2-0.6.0-beta.6.4
  [✔] PigPen-Forge-1.19.2-11.1.2
  [✔] pipez-1.19.2-1.0.1
  [✔] Placebo-1.19.2-7.1.2
  [✔] platforms-1.19-1.10.2
  [✔] pneumaticcraft-repressurized-1.19.2-4.3.1-20
  [✔] polymorph-forge-0.46.1+1.19.2
  [✔] potionsmaster-0.6.0-1.19.2-43.1.1
  [✔] Powah-4.0.6
  [✔] Prism-1.19.1-1.0.2
  [✔] productivebees-1.19.2-0.10.4.0
  [✔] pylons-1.19.2-3.1.0
  [✔] Quark-3.4-389
  [✔] quartz-1.19.2-0.1.0-beta.1
  [✔] radon-0.8.2
  [✔] rangedpumps-1.0.0
  [✔] rebornstorage-1.19.2-5.0.3
  [✔] rechiseled-1.0.12a-forge-mc1.19
  [✔] redstone_arsenal-1.19.2-7.2.0.15
  [✔] refinedcooking-3.0.3
  [✔] refinedstorage-1.11.5
  [✔] refinedstorageaddons-0.9.0
  [✔] reliquary-1.19.2-2.0.20.1166
  [✔] repurposed_structures_forge-6.3.11+1.19.2
  [✔] resourcefulconfig-forge-1.19.2-1.0.19
  [✔] resourcefullib-forge-1.19.2-1.1.22
  [✔] rftoolsbase-1.19.1-4.1.4
  [✔] rftoolsbuilder-1.19.1-5.2.3
  [✔] rftoolscontrol-1.19-6.1.2
  [✔] rftoolspower-1.19-5.1.1
  [✔] rftoolsstorage-1.19-4.1.0
  [✔] rftoolsutility-1.19-5.1.4
  [✔] rhino-forge-1902.2.2-build.264
  [✔] RootsClassic-1.19.2-1.1.34
  [✔] RSInfinityBooster-1.19.2-3.0+27
  [✔] rsrequestify-2.3.0
  [✔] rubidium_extras-1.19.2_v1.3.2
  [✔] rubidium-0.6.2
  [✔] Runelic-Forge-1.19.2-14.1.4
  [✔] saturn-mc1.19.2-0.0.1
  [✔] ScalableCatsForce-2.13.10-build-10-with-library
  [✔] sebastrnlib-2.0.1
  [✔] shetiphiancore-1.19-3.11.3
  [✔] Shrink-1.19-1.3.4
  [✔] silent-gear-1.19.2-3.2.5
  [✔] silent-lib-1.19.2-7.0.3
  [✔] SimpleBackups-1.19.1-2.1.8
  [✔] simplemagnets-1.1.9-forge-mc1.19
  [✔] simplylight-1.19.2-1.4.5-build.42
  [✔] smallships-1.19.2-2.0.0-Alpha-0.4
  [✔] SmartBrainLib-forge-1.19.2-1.8
  [✔] smoothboot(reloaded)-mc1.19.2-0.0.2
  [✔] SoL-Carrot-1.19.2-1.14.0
  [✔] sophisticatedbackpacks-1.19.2-3.18.40.779
  [✔] sophisticatedcore-1.19.2-0.5.38.203
  [✔] sophisticatedstorage-1.19.2-0.6.16.276
  [✔] spark-1.10.29-forge
  [✔] spirit-forge-1.19.2-2.2.3
  [✔] structure_gel-1.19.2-2.7.1
  [✔] StructureCompass-1.19.2-1.3.5
  [✔] structurize-1.19.2-1.0.472-BETA
  [✔] SuperFactoryManager-1.19.2-4.4.4
  [✔] supermartijn642configlib-1.1.6b-forge-mc1.19
  [✔] supermartijn642corelib-1.1.2-forge-mc1.19
  [✔] supplementaries-1.19.2-2.2.50
  [✔] systeams-1.2.1
  [✔] tempad-forge-1.19.2-1.4.4
  [✔] TerraBlender-forge-1.19.2-2.0.1.136
  [✔] tesseract-1.0.28a-forge-mc1.19
  [✔] theoneprobe-1.19-6.2.2
  [✔] thermal_cultivation-1.19.2-10.2.0.17
  [✔] thermal_dynamics-1.19.2-10.2.1b.14
  [✔] thermal_expansion-1.19.2-10.2.0.21
  [✔] thermal_foundation-1.19.2-10.2.0.47
  [✔] thermal_innovation-1.19.2-10.2.0.18
  [✔] thermal_integration-1.19.2-10.2.0.17
  [✔] thermal_locomotion-1.19.2-10.2.0.14
  [✔] ThermalExtra 1.19.2-3.0.1
  [✔] theurgy-1.19.2-1.3.0
  [✔] time-in-a-bottle-3.0.1-mc1.19
  [✔] titanium-1.19.2-3.7.2-26
  [✔] ToastControl-1.19.2-7.0.0
  [✔] tombstone-8.2.5-1.19.2
  [✔] ToolBelt-1.19.2-1.19.7
  [✔] torchmaster-19.2.0
  [✔] trashcans-1.0.17-forge-mc1.19
  [✔] trashslot-forge-1.19-12.0.0
  [✔] TravelAnchors-1.19.2-4.1.2
  [✔] twilightforest-1.19.2-4.2.1518-universal
  [✔] universalgrid-1.19.2-1.033
  [✔] UtilitiX-1.19.2-0.7.6
  [✔] villagertools-1.19-1.0.3
  [✔] vitalize-forge-1.19.2-1.1.1
  [✔] voidtotem-forge-1.19.2-2.1.0
  [✔] waystones-forge-1.19-11.1.0
  [✔] wirelesschargers-1.0.8-forge-mc1.19
  [✔] WitherSkeletonTweaks-1.19.2-8.0.0
  [✔] xnet-1.19-5.1.2
  [✔] XNetGases-1.19.1-4.0.0
  [✔] XyCraft Core-0.5.17
  [✔] XyCraft Override-0.5.17
  [✔] XyCraft World-0.5.17
  [✔] yeetusexperimentus-1.0.1-build.2+mc1.19.1
  [✔] YungsApi-1.19.2-Forge-3.8.6
  [✔] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔] YungsBetterMineshafts-1.19.2-Forge-3.2.0
  [✔] YungsBetterOceanMonuments-1.19.2-Forge-2.1.0
  [✔] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Forge-2.1.0

Params:
  --username  --version 1.19.2 --gameDir C:/Users/atrea/AppData/Roaming/PrismLauncher/instances/All the Mods 8 - ATM8/minecraft --assetsDir C:/Users/atrea/AppData/Roaming/PrismLauncher/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 43.2.3 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Window size: 1280 x 720

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx5800m, -Duser.language=en]

Minecraft process ID: 14780

Exception caught from launcher
java.lang.ClassNotFoundException: io.github.zekerzhayard.forgewrapper.installer.Main
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:151)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
Process exited with code 2.
Clipboard copy at: 24 Feb 2023 10:11:49 -0500

**Comment by Razmath** [comment]
I'm having the same issue with StoneBlock 3 on the same version of PrismLauncher.

**Comment by Floryster** [comment]
I had the exact same problem. I was running the game offline, but I just had to run it with the Internet.

**Comment by Razmath** [comment]
two years dude.
