### ISSUE TITLE
[AE Additions] ME wireless Transceiver bug?

### ISSUE THREAD

**Issue by Dragonex97** [AllTheMods/ATM-8#958]
whenever i try to interact with the ME wireless Transceiver block after placing it on an empty ME controller Face it instantly kicks me out of my server/world and back into the ATM8 menu.. not sure if its a bug or not..

![Skärmbild 2023-02-25 192834](https://user-images.githubusercontent.com/125225151/221373664-0a7ff4d8-bb47-411a-9ef6-3be66301b918.png)
^
and gives me this result everytime :/

**Comment by XDelta** [comment]
I was able to open it once in the server, now trying to open it again disconnects me from the server. not sure why but same error.

On 1.0.11 myself

**Comment by XDelta** [comment]
In the mean time for connecting up ME systems at range, use the ME Quantum Link Chamber.

**Comment by Mitchell5200** [comment]
Duplicate of #550
