### ISSUE TITLE
Exit Code: 1 Crash

### ISSUE THREAD

**Issue by Obed-Hernandez** [AllTheMods/ATM-8#959]
Every time I try to join my localhost server, my client crashes, gives me an Exit Code 1, and the crash report states, 
"EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb1d756010, pid=14020, tid=36608"
Send Help Please.

**Comment by jellllo** [comment]
I solved this problem by disabling rain, for me at the very least it only crashed every time it rained

**Comment by zxaber** [comment]
Rain seems to be the key, I can trigger the crash on-demand by making a creative world and clicking the weather button in the creative menu. What's really strange is that not everyone is affected by the issue, and don't know what causes the discrepancy.

**Comment by zxaber** [comment]
By happenstance, I found that enabling `ComplementaryShaders_v4.6.zip` (Options > Video Settings > Shader Packs) has seemingly fixed rain causing my client to crash. So I suppose that's a workaround if your computer can handle it.

I haven't tested the other shaders, they may also mitigate the crash.
