### ISSUE TITLE
Refined storage not displaying items

### ISSUE THREAD

**Issue by JanisChambers** [AllTheMods/ATM-8#961]
For some reason items will not display unless I break the grid block and put it back.  I have to do this every time I use it.  I set my chunk to force load, connected the blocks with cables.  Nothing seems to help.

**Comment by James103** [comment]
Do you get a similar issue with the Refined Storage wireless terminals? If so, it may be a problem with Refined Storage, one of its addons, or (not as likely) another mod in the pack.
1. Try reducing the total amount of **types** of items you have in your system. The more types of items you have, the greater the data required and the more likely you are to have problems like this. Remember that items with the same item ID but different NBT (such as spawners, equipment and gems from Apotheosis) count as different types.
2. If you are still having this issue, try migrating your storage to AE2.

**Comment by JanisChambers** [comment]
I'll definitely move onto AE2 when I have it all set up.  Perhaps I should export some things into barrels in the meantime.

**Comment by JanisChambers** [comment]
I appreciate the response!
