### ISSUE TITLE
Both the Wireless Crafting Terminal and my Crafting Terminal completely stopped working after crafting mob slaughtering factory

### ISSUE THREAD

**Issue by Jsgraz** [AllTheMods/ATM-8#964]
it says my me system is online and it is being supplied the correct amount of power. This has literally been working without fail for the longest time, and the split second i decided to craft this very specific item it just stops working. I don't see how it can be anything besides a bug

**Comment by Mitchell5200** [comment]
Immersive Engineering bug, fixed and closing
