### ISSUE TITLE
ATM 8 Peacock Feather Fan (Twilight Forest)

### ISSUE THREAD

**Issue by toxikak** [AllTheMods/ATM-8#965]
I have been playing for over 24 hours decimating every Large/Medium Hollow Hill and Labyrinth I find in the Twilight Forest dimension for this item and can't find it... is it possible it doesn't exist? It shows up in the JEI... so I was wondering if it is disabled in the modpack and if so, how to find out...

**Comment by Mitchell5200** [comment]
They exist, and according to the TF wiki, are in lich towers or large/medium hollow hills, they just appear to be Rare
http://benimatic.com/tfwiki/index.php?title=Peacock_Feather_Fan
