### ISSUE TITLE
Server kicks everyone if disk is removed from the Disk Drive.

### ISSUE THREAD

**Issue by Hiattech** [AllTheMods/ATM-8#966]
As I have been upgrading my disk drives in refined storage, I decided I would pull the tiny ones, dump the items in the disk manipulator, and put the larger drive (now an infinite) back in. However, As soon as I pull a drive out, the server kicks everyone. ~~The server does not crash but it also doesn't let us log back in for about five minutes.~~ The logs are in my other comments, including some additional logs from 3/1 where the server hangs while starting. It doesn't show that anyone was kicked or disconnected. As such, I cannot provide crash logs. However, I can provide what was in the disk drives. This isn't the first time this has happened but I thought the first time was a fluke. Once I crafted the infinite drive, I was going to dump everything into it and remove the small disks. As soon as I pulled the 64k, everyone got kicked. When I logged back in, the 64k drive was still in the system... 
Drives in my system from left to right, top to bottom
slot 1 - 64k storage drive         slot 2 - 256k storage drive
slot 3 - 16384k storage drive   slot 4 - 16384k fluid storage drive
slot 5 - Infinite Fluid storage drive

**Comment by James103** [comment]
What do you get in the logs (client and server) when the kick occurs? What message do you get on the "connection lost" screen?

**Comment by Hiattech** [comment]
Ok, I started my server, logged in, immediately popped the drive out, got kicked, and shutdown the server to pull the logs. the shutdown was manual. Posting server logs on this post and my client logs on the next one
[startup.txt](https://github.com/AllTheMods/ATM-8/files/10846389/startup.txt)
[client.txt](https://github.com/AllTheMods/ATM-8/files/10846390/client.txt)
[server.txt](https://github.com/AllTheMods/ATM-8/files/10846391/server.txt)
[debug.log](https://github.com/AllTheMods/ATM-8/files/10846392/debug.log)
[latest.log](https://github.com/AllTheMods/ATM-8/files/10846393/latest.log)

**Comment by Hiattech** [comment]
And my client logs here
[latest.log](https://github.com/AllTheMods/ATM-8/files/10846395/latest.log)
[client.txt](https://github.com/AllTheMods/ATM-8/files/10846396/client.txt)
[server.txt](https://github.com/AllTheMods/ATM-8/files/10846397/server.txt)
[startup.txt](https://github.com/AllTheMods/ATM-8/files/10846398/startup.txt)

**Comment by ricdk** [comment]
Refined Storage does not play well with large amounts of items stored. It seems to take a lot of server power to update the storage larger drives and especially creative infinity drives. My personal recommendation... Only use RS as a starter storage, and switch to AE2's ME system as soon as possible.

**Comment by Hiattech** [comment]
> Refined Storage does not play well with large amounts of items stored. It seems to take a lot of server power to update the storage larger drives and especially creative infinity drives. My personal recommendation... Only use RS as a starter storage, and switch to AE2's ME system as soon as possible.

Normally, I would have since I also prefer the AE2 system but, I decided this time that I wanted to get all of the achievements for it. I guess with that done now, I should begin the AE system.

**Comment by Hiattech** [comment]
An additional note. It seems to have an effect on more than just Minecraft. The first couple times it just disconnected everyone and left the drive in. This time I actually had the drive on me. I tried to drop it back in tonight and not only did it disconnect everyone from the server, my son, who was playing League of Legends, got disconnected briefly.

**Comment by Hiattech** [comment]
I discovered the problem. The system/server wasn't speeding up at all even even though I dumped a couple million items. We finally dumped the quivers (we had a skeleton farm running) and the system went back to normal speed. I'm guessing thousands of quivers each with a few arrows really messed with the system.
