### ISSUE TITLE
1.0.12 - Error when connecting to server

### ISSUE THREAD

**Issue by fkempf78** [AllTheMods/ATM-8#973]
![grafik](https://user-images.githubusercontent.com/54644233/221807656-8df39bb3-8be6-4f4c-a4d8-861985f9a7da.png)
Any idea? Reinstall of Client has not changed Error

**Comment by Mitchell5200** [comment]
Currently under investigation, was not caught during testing

**Comment by Mitchell5200** [comment]
Issue solved 1.0.13 is now pending Curse approval for release

**Comment by Mitchell5200** [comment]
CF approved, Closing
