### ISSUE TITLE
Productive Bees don't work after the latest update 1.0.13

### ISSUE THREAD

**Issue by DmitryScaletta** [AllTheMods/ATM-8#977]
I just created a completely new world and added a few Advanced Beehives + Simulation Upgrade and used Time in a bottle to these beehives.
And it doesn't work.

The only ones that works in my main word are Salty Bee and Oily Bee (they use water and oil instead of a Feeding Slab)

![image](https://user-images.githubusercontent.com/5096735/221936517-78ecb0d0-2d27-4864-bd49-3c19031cc532.png)

![image](https://user-images.githubusercontent.com/5096735/221936638-18279887-c741-4fdc-bd01-5f710b1b15ee.png)

**Comment by Dragonex97** [comment]
got same issue xd, simulator bee's don't work after latest update (normal entering/exiting bee's still does tho)

**Comment by DmitryScaletta** [comment]
Fixed in `productivebees-1.19.2-0.10.5.3.jar`

**Comment by pgudge** [comment]
Not sure if this is the same issue, but Advanced Beehives + Feeding Slab is only working for the item that is in the far right slot on the Feeding Slab.

I was on:
 ATM8 1.0.8 (productivebees-1.19.2-0.10.4.0) and all three slots feed the various bees in the hives, and all combs produced.
Now on:
 ATM8 1.0.13 (productivebees-1.19.2-0.10.5.2) and all bees have stopped producing combs expect for the bees who's flowering items is in the far right slot of each Feeding Slab

In the image below, only gold combs are produced.
<img width="443" alt="javaw_Vgo1ylvJA7" src="https://user-images.githubusercontent.com/1702829/223598965-329bd55c-f274-4dae-b84d-98333bea881f.png">

If I move the copper block to the right slot, only copper combs are produced.

If this is not linked, let me know and I can create a new issue.

Thanks

**Comment by Dragonex97** [comment]
> Not sure if this is the same issue, but Advanced Beehives + Feeding Slab is only working for the item that is in the far right slot on the Feeding Slab.
> 
> I was on: ATM8 1.0.8 (productivebees-1.19.2-0.10.4.0) and all three slots feed the various bees in the hives, and all combs produced. Now on: ATM8 1.0.13 (productivebees-1.19.2-0.10.5.2) and all bees have stopped producing combs expect for the bees who's flowering items is in the far right slot of each Feeding Slab
> 
> In the image below, only gold combs are produced. <img alt="javaw_Vgo1ylvJA7" width="443" src="https://user-images.githubusercontent.com/1702829/223598965-329bd55c-f274-4dae-b84d-98333bea881f.png">
> 
> If I move the copper block to the right slot, only copper combs are produced.
> 
> If this is not linked, let me know and I can create a new issue.
> 
> Thanks

Hadn't tried different positions in the feeding slabs but after having tried it, i'd say it's more or less the same issue(i think) as i also only get combs from the rightmost slot instead of every slot.

**Comment by DaveeyMey87** [comment]
Confirmed the Feeding slab issue in my world (ATM8 1.0.13). I thought it completely wasn't working but as the previous comments  mention it was because only the far right slot of the feeding slab works. I moved the Items to the right and all of them started working again. Granted that only works if you're setup has one bee type per hive.
