### ISSUE TITLE
Hud/Gui Trouble

### ISSUE THREAD

**Issue by TheColonel7602** [AllTheMods/ATM-8#979]
These two things appeared on my screen one day (text box and power bar looking thing) and i can't seem to get rid of them no matter what i do, i was hoping someone would know what mods they're from and how to disable them. I've included images to show what I'm talking about. (I'm sorry if this isn't the place to ask this I couldn't find anywhere else to troubleshoot)
![IMG_0294](https://user-images.githubusercontent.com/126623541/222000699-028fc7f6-9103-4153-b23f-07c62528a1e7.jpg)
![2023-02-28_14 50 21](https://user-images.githubusercontent.com/126623541/222000720-c600da4a-050c-4484-ad2a-98ce8ac3a286.png)

**Comment by enigmaquip** [comment]
Those are pinned quests from ftb quests.

**Comment by TheColonel7602** [comment]
Thanks a lot I must've hit pin on them by accident and didn't realize, but one more thing do you know what that bar is in the bottom right?
