### ISSUE TITLE
silicon still not fixed with build 1.1

### ISSUE THREAD

**Issue by starixed** [AllTheMods/ATM-8#98]
still cannot make refined storage silicon. deleted ae2 and silicon from the almostunify config and it worked again

**Comment by aAndrew3030** [comment]
https://github.com/AllTheMods/ATM-8/issues/89

**Comment by starixed** [comment]
im on sp not server and is still an issue

**Comment by DAmNRelentless** [comment]
You don't need Refined Storage silicon. Unification means the silicon from AE and RS becomes one. You can just craft everything from RS with the AE2 silicon so there doesn't need to be a way to obtain RS silicon. All recipes got transferred over to the AE equivalent.

![](https://i.imgur.com/WxSKS8A.png)

**Comment by aAndrew3030** [comment]
Except it is not working that way

**Comment by aAndrew3030** [comment]
Most of us are getting this, with no way to craft rs silicon, and I just did a fresh update for a second time to double check
![2022-10-13_16 10 32](https://user-images.githubusercontent.com/84727133/195699760-263c56cd-bdbe-4bbb-810f-cacaa68a6d01.png)

**Comment by aAndrew3030** [comment]
Simply doing a /reload gets the above recipe to load with ae silicon, but with kubejs errors, so it looks like there is a conflict somewhere between the unify mod config and kubejs silicon fix?

**Comment by DAmNRelentless** [comment]
The KubeJS v6 alpha which they use in this pack is probably not very consistent yet when it comes to recipe replacements and tags.

**Comment by aAndrew3030** [comment]
the kubejs error
`Error occurred while handling event 'ServerEvents.recipes': Wrapped java.lang.NullPointerException (server_scripts:mods/refinedstorage/refinedstorage.js#7)`

**Comment by Xplodin** [comment]
I believe the server files fail to include kubejs and rhino.
Upon downloading the server files to my panel, I noticed its missing the kubejs mod and rhino mod but kept architecture mod
