### ISSUE TITLE
atm8 end code 1

### ISSUE THREAD

**Issue by jinmuk99** [AllTheMods/ATM-8#980]
After creating the world, he played the game for about three hours without any problems. However, the game ended shortly after the end code 1 was displayed. Even if you enter the world again, if you play the game for about five minutes, it ends again with the end code 1.

**Comment by Nicon4454** [comment]
is there a crash report or the latest log to look at?

**Comment by RangedAce** [comment]
I have the same problem, Here are the logs
[2023-03-01-1.log.gz](https://github.com/AllTheMods
[latest.log](https://github.com/AllTheMods/ATM-8/files/10861272/latest.log)
/ATM-8/files/10861271/2023-03-01-1.log.gz)
