### ISSUE TITLE
[1.0.13] Starts to crash after a while

### ISSUE THREAD

**Issue by Grausamkeeit** [AllTheMods/ATM-8#985]
I played for a while in the newly created world and started building my house. After 10-20 minutes the game crashed and this continues every time after the restart. I did not add any other mods, except for those in the modpack.

[log.txt](https://github.com/AllTheMods/ATM-8/files/10861892/log.txt)

**Comment by Mitchell5200** [comment]
a Hss_err_pid, it's likely the particle crash we are chasing and others have already reported, some users have reported enabling shaders as fixing the crash, or you can turn off your particles

**Comment by Grausamkeeit** [comment]
Disabling shaders helped, but not disabling particles. Can something be done to not enable shaders? I just don't like playing with them.

**Comment by wcmanik** [comment]
This is helped me:

1. Particles to minimum
2. Enable shaders
3. Execute ars-light off
4. Disable shaders
5. Particles to All
