### ISSUE TITLE
[1.0.13] Crash upon starting server

### ISSUE THREAD

**Issue by mzx987** [AllTheMods/ATM-8#986]
Recently updated a server to this version of ATM 8, and noticed that the server will shut down shortly after with the following [crash report](https://pastebin.com/j9hY4Qz4).

I suspect it has something to do with Computercraft (and possibly AlchemyLib), but I'm not too sure. Any help would be greatly appreciated.

**Comment by mzx987** [comment]
To anyone else that may run into this issue: It was definitely caused by two adjacent objects: An Alchemistry Atomizer, and a CC:Tweaked computer. Before I updated (from 1.0.11), it was working fine. I guess an update with one of these mods introduced a new issue.

**Comment by Mitchell5200** [comment]
Tracked at https://github.com/SmashingMods/Alchemistry/issues/305
