### ISSUE TITLE
[1.0.13] Ender chests, ender tanks and flux points without colors

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-8#987]
After the update, ender chests, ender tanks and flux points are all white, even though they have color codes on them. It is just a visual bug, because the ender chests continue being connected to the inventory the color is set but in the world textures you see them all white.

**Comment by XFactHD** [comment]
Try disabling Biome Blending in the video settings, I have a feeling that this is connected to a bug in Rubidium Extra.

**Comment by M4RC0Sx** [comment]
> Try disabling Biome Blending in the video settings, I have a feeling that this is connected to a bug in Rubidium Extra.

Worked! Thank you!
