### ISSUE TITLE
Mekanism Pipes(All types) not showing configured colors and FluxNetworks Flux point not turning blue when connected after update

### ISSUE THREAD

**Issue by VoidFyre** [AllTheMods/ATM-8#991]
After updating from 1.0.11 to 1.0.13, I noticed that when using the configurator on any of the item/fluid/power pipes from mekanism to change their channel color does not correctly visually update the pipe. There is an overlay but it's not colored properly, so I'm assuming this is some sort of rendering issue. Also, the flux points from FluxNetworks are not visually updating to have their corners blue after connecting to a network.

**Comment by XFactHD** [comment]
This is very likely the same issue as #987, see that for the suggested fix.
