### ISSUE TITLE
Inustrial Foregoing Wither Builder Bug

### ISSUE THREAD

**Issue by toast-psb** [AllTheMods/ATM-8#994]
I am finding that the wither builder doesn't work when a chunk is loaded or claimed, but works when I am in the room with an unclaimed/unloaded chunk.
When chunk is loaded the blocks are in the machine and don't get placed at all.

**Comment by TheDarkFlame** [comment]
I'd wager that there's a fake player that industrial foregoing uses to create the wither... 

I'd expect that you'd need to add that fake player to whitelisted players for your chunk...

I'd try the following and see if that solves the problem:


1. open inventory
2. click the button on top left that looks like 3 players ("My Team")
3. click the settings gear in the top right of the window that opens
4. click on "allied fake player names/ids
5. click "add+" to add a new fake player
6. add player name [IF] 
7. confirm in the list of fake players, you now see "[IF]"


If that doesn't work, try also adding just IF without the square braces.


Worth noting that if you're using mine colonies, you'll likely need to add the fake player to your colony too.
