### ISSUE TITLE
Single-Player World Crashes on Load-Up

### ISSUE THREAD

**Issue by Parakus** [AllTheMods/ATM-8#998]
So I've been playing for a month now, and I'm suddenly crashing as of yesterday. I was exploring to find an ocean monument for a while.
Eventually my game froze. I jumped back in and teleported home, but I started crashing. Couldn't get back in until I tried disabling shaders and I could play again. Thinking that would work, I tried exploring again and crashed again. Now I'm crashing every time I try entering my save. I tried allocating more RAM, reinstalling the modpack and minecraft. I've also moved my save out of the modpack, but I still can't even get into a new world. Any help?

[crash.log](https://github.com/AllTheMods/ATM-8/files/10879393/crash.log)

**Comment by Mitchell5200** [comment]
That crash looks like a system out of memory error, while allocating 8GB to the game is fine on a 16GB pc, some of your other programs are taking up the rest of your system memory and the system is then crashing, try closing a few programs while MC is running to avoid this in the future.
I also advise ensuring your GPU drivers are up to date.
