### ISSUE TITLE
crash while teleport to waypoint

### ISSUE THREAD

**Issue by eqorfox** [AllTheMods/ATM-8#999]
[hs_err_pid7284.log](https://github.com/AllTheMods/ATM-8/files/10880926/hs_err_pid7284.log)

**Comment by Mitchell5200** [comment]
Particle Render crash, either turn off particles, Or check and Update your GPU drivers

**Comment by eqorfox** [comment]
disabling the particles helped for 20-30 minutes, I was able to teleport and play a little, but after crash again

**Comment by Mitchell5200** [comment]
Check your GPU drivers for updates and update them

**Comment by eqorfox** [comment]
now it just doesn't let you enter the world, it immediately paints

**Comment by eqorfox** [comment]
immediately updated when you said about it

**Comment by eqorfox** [comment]
it always crush differently, then it does not let you enter the world, then after 5 minutes of the game, then after 30

**Comment by eqorfox** [comment]
also crashes when I go to hell, first they fall to -2500 height and crashes, looked through f3 ram, it's enough
